SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_NOTA_DEBITO]
@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_NOT_DEB_FEC datetime
,@CO_NOT_DEB_EST bit
,@CO_NOT_DEB_CON nvarchar(150)
,@PROF_COD char(10)
,@CO_NOT_DEB_COM nvarchar(50)
,@CO_NOT_DEB_USU_ALI nvarchar(14)
,@CO_NOT_DEB_SUB FLOAT
,@CO_NOT_DEB_DES FLOAT
,@CO_NOT_DEB_TOT FLOAT
,@CO_COM_NUM INT
,@CO_TIP_COM_COD INT
,@CO_NOT_DEB_FOR_PAG NVARCHAR(15)
,@CO_NOT_DEB_EFE BIT
,@CO_NOT_DEB_EFE_VAL FLOAT
,@CO_NOT_DEB_CHE BIT
,@CO_NOT_DEB_CHE_VAL FLOAT
,@CO_NOT_DEB_CHE_NUM NVARCHAR(15)
,@CO_NOT_DEB_CUE_NUM NVARCHAR(20)
,@CO_NOT_DEB_NUM_PAG INT
AS
INSERT INTO [dbo].[CO_NOTA_DEBITO]
([CO_EMP_RUC]
,[CO_NOT_DEB_NUM]
,[CO_NOT_DEB_FEC]
,[CO_NOT_DEB_EST]
,[CO_NOT_DEB_CON]
,[PROF_COD]
,[CO_NOT_DEB_COM]
,[CO_NOT_DEB_USU_ALI]
,CO_NOT_DEB_SUB
,CO_NOT_DEB_DES
,CO_NOT_DEB_TOT
,CO_COM_NUM
,CO_TIP_COM_COD
,CO_NOT_DEB_FOR_PAG
,CO_NOT_DEB_EFE
,CO_NOT_DEB_EFE_VAL
,CO_NOT_DEB_CHE
,CO_NOT_DEB_CHE_VAL
,CO_NOT_DEB_CHE_NUM
,CO_NOT_DEB_CUE_NUM
,CO_NOT_DEB_NUM_PAG)
VALUES
(@CO_EMP_RUC
,@CO_NOT_DEB_NUM
,@CO_NOT_DEB_FEC
,@CO_NOT_DEB_EST
,@CO_NOT_DEB_CON
,@PROF_COD
,@CO_NOT_DEB_COM
,@CO_NOT_DEB_USU_ALI
,@CO_NOT_DEB_SUB
,@CO_NOT_DEB_DES
,@CO_NOT_DEB_TOT
,@CO_COM_NUM
,@CO_TIP_COM_COD
,@CO_NOT_DEB_FOR_PAG
,@CO_NOT_DEB_EFE
,@CO_NOT_DEB_EFE_VAL
,@CO_NOT_DEB_CHE
,@CO_NOT_DEB_CHE_VAL
,@CO_NOT_DEB_CHE_NUM
,@CO_NOT_DEB_CUE_NUM
,@CO_NOT_DEB_NUM_PAG)
GO
