SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TEMP_ASIENTO]
@CO_EMP_RUC char(13)
,@CO_CUE_COD varchar(40)
,@CO_TEMP_ASI_FEC datetime
,@CO_TEMP_ASI_DES varchar(150)
,@CO_TEMP_ASI_DEB float
,@CO_TEMP_ASI_HAB float
,@CO_CEN_COS_COD varchar(30)
,@CO_TEMP_ASI_COD INT
as
UPDATE [dbo].[CO_TEMP_ASIENTO]
SET
CO_TEMP_ASI_FEC=@CO_TEMP_ASI_FEC
,CO_TEMP_ASI_DES=@CO_TEMP_ASI_DES
,CO_TEMP_ASI_DEB=@CO_TEMP_ASI_DEB
,CO_TEMP_ASI_HAB=@CO_TEMP_ASI_HAB
,CO_CEN_COS_COD=@CO_CEN_COS_COD
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_TEMP_ASI_COD=@CO_TEMP_ASI_COD
and CO_CUE_COD=@CO_CUE_COD
GO
