SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CADUCIDAD]
(@CO_EMP_RUC char(13)
,@CO_DOC_COM_NUM int)
AS
SELECT * FROM [dbo].[CO_CADUCIDAD]
WHERE ([CO_EMP_RUC]=@CO_EMP_RUC and CO_DOC_COM_NUM=@CO_DOC_COM_NUM)
GO
