SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DETALLE_DOCUMENTO_COMPRA]
@CO_DOC_COM_ID UNIQUEIDENTIFIER
AS
SELECT * FROM CO_DETALLE_DOCUMENTO_COMPRA
WHERE CO_DOC_COM_ID=@CO_DOC_COM_ID
GO
