SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TARJETA_CREDITO]
	(@CO_TAR_CRE_COD INT
			,@CO_EMP_RUC char(13)
           ,@CO_TAR_CRE_NOM nvarchar(250)
           ,@CO_TAR_CRE_CUE varchar(40))
AS
UPDATE [dbo].[CO_TARJETA_CREDITO] SET [CO_TAR_CRE_NOM]=@CO_TAR_CRE_NOM
           ,[CO_TAR_CRE_CUE]=@CO_TAR_CRE_CUE
     WHERE [CO_EMP_RUC]=@CO_EMP_RUC
           AND CO_TAR_CRE_COD=@CO_TAR_CRE_COD
GO
