SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_COMPROBANTE_COBRO_EMPLEADO]
@CO_COM_COB_NUM int,
@CO_EMP_RUC char(13)
AS
SELECT * FROM CO_VW_SELECT_REPORTE_COBRO_EMPLEADO
WHERE CO_COM_COB_NUM=@CO_COM_COB_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
