SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_DETALLE_PROFORMA]
(@CO_PRO_COD int
,@CO_EMP_RUC char(13)
,@CO_DET_PRO_ART_COD nvarchar(20)
,@CO_DET_PRO_ART_NOM nvarchar(50)
,@CO_DET_PRO_CAN int
,@CO_DET_PRO_PRE float
,@CO_DET_PRO_DES float
,@CO_DET_PRO_TOT float
,@CO_DET_PRO_TIP_ART bit
,@CO_DET_PRO_IVA float
,@CO_DET_PRO_CAN_EXI int
,@CO_DET_PRO_TIP_PRE nvarchar(50)
,@CO_DET_PRO_ART_BAR NVARCHAR(20))
AS
INSERT INTO [dbo].[CO_DETALLE_PROFORMA]
([CO_PRO_COD]
,[CO_EMP_RUC]
,[CO_DET_PRO_ART_COD]
,[CO_DET_PRO_ART_NOM]
,[CO_DET_PRO_CAN]
,[CO_DET_PRO_PRE]
,[CO_DET_PRO_DES]
,[CO_DET_PRO_TOT]
,[CO_DET_PRO_TIP_ART]
,[CO_DET_PRO_IVA]
,[CO_DET_PRO_CAN_EXI]
,[CO_DET_PRO_TIP_PRE]
,CO_DET_PRO_ART_BAR
,CANTIDAD_PROCESADA
,ESTADO
,CANTIDAD_FACTURAR)
VALUES
(@CO_PRO_COD
,@CO_EMP_RUC
,@CO_DET_PRO_ART_COD
,@CO_DET_PRO_ART_NOM
,@CO_DET_PRO_CAN
,@CO_DET_PRO_PRE
,@CO_DET_PRO_DES
,@CO_DET_PRO_TOT
,@CO_DET_PRO_TIP_ART
,@CO_DET_PRO_IVA
,@CO_DET_PRO_CAN_EXI
,@CO_DET_PRO_TIP_PRE
,@CO_DET_PRO_ART_BAR
,0
,'PENDIENTE'
,0)
GO
