SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_DOCUMENTO_VENTA_RETENCION]
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
,@CO_COM_NUM_RET INT
AS
UPDATE CO_DOCUMENTO_VENTA SET CO_COM_NUM_RET=@CO_COM_NUM_RET
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID
GO
