SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CADUCIDAD_CANTIDAD]
@CO_CAD_COD int
,@CO_CAD_OPE CHAR(1)
,@CO_CAD_CAN INT
AS
IF(@CO_CAD_OPE='+')
	UPDATE CO_CADUCIDAD SET CO_CAD_CAN=CO_CAD_CAN+@CO_CAD_CAN
	WHERE CO_CAD_CAN=@CO_CAD_COD
ELSE
	UPDATE CO_CADUCIDAD SET CO_CAD_CAN=CO_CAD_CAN-@CO_CAD_CAN
	WHERE CO_CAD_CAN=@CO_CAD_COD
GO
