SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_PRESUPUESTO_CONSOLIDADO]
@CO_EMP_RUC CHAR(13)
,@CO_PRE_ANO INT
,@CO_ITE_PRE_TIP NVARCHAR(10)
AS
SELECT * FROM CO_VW_SELECT_PRESUPUESTO_CONSOLIDADO
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_PRE_ANO=@CO_PRE_ANO 
AND CO_ITE_PRE_TIP=case @CO_ITE_PRE_TIP when '' then CO_ITE_PRE_TIP else @CO_ITE_PRE_TIP end
order by co_ite_pre_cod
GO
