SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PARAMETRO_RENTA]
@CO_PAR_REN_COD int
,@CO_PAR_REN_LIM_INF float
,@CO_PAR_REN_LIM_SUP float
,@CO_PAR_REN_VAL_BAS float
,@CO_PAR_REN_POR_DIF float
AS
UPDATE [dbo].[CO_PARAMETRO_RENTA] SET
[CO_PAR_REN_LIM_INF]=@CO_PAR_REN_LIM_INF
,[CO_PAR_REN_LIM_SUP]=@CO_PAR_REN_LIM_SUP
,[CO_PAR_REN_VAL_BAS]=@CO_PAR_REN_VAL_BAS
,[CO_PAR_REN_POR_DIF]=@CO_PAR_REN_POR_DIF
WHERE 
CO_PAR_REN_COD=@CO_PAR_REN_COD
GO
