SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CADUCIDAD_ESTADO]
@CO_CAD_COD int
,@CO_CAD_EST bit
AS
UPDATE CO_CADUCIDAD SET CO_CAD_EST=@CO_CAD_EST
WHERE CO_CAD_COD=@CO_CAD_COD
GO
