SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_RUBROS_ROL_MENSUAL1]
@CO_EMP_RUC CHAR(13)
,@CO_INT_OPC INT
,@CO_UBI_COD INT
AS
IF @CO_INT_OPC=1
BEGIN
SELECT dbo.CO_EMPRESA.CO_EMP_NOM, dbo.PROFESOR.PROF_COD, dbo.CO_UBICACION_AF.CO_UBI_COD, dbo.CO_UBICACION_AF.CO_UBI_NOM, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS EMPLEADO
FROM dbo.PROFESOR INNER JOIN
dbo.CO_UBICACION_AF ON dbo.PROFESOR.CO_EMP_RUC = dbo.CO_UBICACION_AF.CO_EMP_RUC AND 
dbo.PROFESOR.CO_UBI_COD = dbo.CO_UBICACION_AF.CO_UBI_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_UBICACION_AF.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC
END
ELSE
BEGIN
SELECT dbo.CO_EMPRESA.CO_EMP_NOM, dbo.PROFESOR.PROF_COD, dbo.CO_UBICACION_AF.CO_UBI_COD, dbo.CO_UBICACION_AF.CO_UBI_NOM, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS EMPLEADO
FROM dbo.PROFESOR INNER JOIN
dbo.CO_UBICACION_AF ON dbo.PROFESOR.CO_EMP_RUC = dbo.CO_UBICACION_AF.CO_EMP_RUC AND 
dbo.PROFESOR.CO_UBI_COD = dbo.CO_UBICACION_AF.CO_UBI_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_UBICACION_AF.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_UBICACION_AF.CO_UBI_COD=@CO_UBI_COD
END
GO
