SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CONCILIACION_BANCOS_PLUS]
@CODIGO_LIBRO_BANCO int
,@PAGADO_PENDIENTE_LIBRO_BANCO bit
AS
UPDATE [dbo].[CO_LIBRO_BANCO]set
[PAGADO_PENDIENTE_LIBRO_BANCO]=@PAGADO_PENDIENTE_LIBRO_BANCO
WHERE
[CODIGO_LIBRO_BANCO]=@CODIGO_LIBRO_BANCO AND ESTADO_TRANSACCION_LIBRO_BANCO='ACTIVA' AND TIPO_TRANSACCION_LIBRO_BANCO='CH'
GO
