SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_COMPROBANTES_MAYORIZACION]
@CO_EMP_RUC CHAR(13),
@CO_COM_FEC_INI DATETIME,
@CO_COM_FEC_FIN DATETIME,
@CO_COM_MAY BIT
AS
SELECT dbo.CO_COMPROBANTE.CO_COM_NUM, dbo.CO_TIPO_COMPROBANTE.CO_TIP_COM_NOM, Convert(varchar(10),dbo.CO_COMPROBANTE.CO_COM_FEC,103) AS FECHA, 
dbo.CO_COMPROBANTE.CO_COM_NOM_EMP, dbo.CO_COMPROBANTE.CO_COM_MAY, dbo.CO_COMPROBANTE.CO_TIP_COM_COD
FROM dbo.CO_COMPROBANTE INNER JOIN
dbo.CO_TIPO_COMPROBANTE ON dbo.CO_COMPROBANTE.CO_EMP_RUC = dbo.CO_TIPO_COMPROBANTE.CO_EMP_RUC AND 
dbo.CO_COMPROBANTE.CO_TIP_COM_COD = dbo.CO_TIPO_COMPROBANTE.CO_TIP_COM_COD
WHERE dbo.CO_COMPROBANTE.CO_EMP_RUC=@CO_EMP_RUC AND
Convert(varchar(10),dbo.CO_COMPROBANTE.CO_COM_FEC,103)>=Convert(varchar(10),@CO_COM_FEC_INI,103) AND
Convert(varchar(10),dbo.CO_COMPROBANTE.CO_COM_FEC,103)<=Convert(varchar(10),@CO_COM_FEC_FIN,103) AND
dbo.CO_COMPROBANTE.CO_COM_MAY=@CO_COM_MAY
GO
