SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_INSERT_DETALLE_DOCUMENTO_PAGO_PLUS]
@CODIGO_DETALLE_DOCUMENTO_PAGO int
,@CODIGO_DOCUMENTO_PAGO int
,@CO_DOC_COM_NUM int
,@VALOR_FACTURA_COMPRA decimal(18,2)
,@NUMERO_FACTURA_COMPRA nvarchar(15)
,@CO_EMP_RUC char(13)
,@CO_PRO_COD nvarchar(10)
AS
INSERT INTO dbo.CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES(
CODIGO_DETALLE_DOCUMENTO_PAGO
,CODIGO_DOCUMENTO_PAGO
,CO_DOC_COM_NUM
,VALOR_FACTURA_COMPRA
,NUMERO_FACTURA_COMPRA
,CO_EMP_RUC
,CO_PRO_COD)
VALUES(
@CODIGO_DETALLE_DOCUMENTO_PAGO
,@CODIGO_DOCUMENTO_PAGO
,@CO_DOC_COM_NUM
,@VALOR_FACTURA_COMPRA
,@NUMERO_FACTURA_COMPRA
,@CO_EMP_RUC
,@CO_PRO_COD)
GO
