SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_IDENTIFICACION]
@CO_TIP_IDE_COD_SRI nvarchar(5)
,@CO_TIP_IDE_NOM nvarchar(50)
AS
INSERT INTO [dbo].[CO_TIPO_IDENTIFICACION]
([CO_TIP_IDE_NOM], [CO_TIP_IDE_COD_SRI])
VALUES
(@CO_TIP_IDE_NOM, @CO_TIP_IDE_COD_SRI)
GO
