SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_AUTORIZACION_CONTADOR]
@CO_TIP_DOC_VEN_NUM INT,
@CO_ALM_COD INT,
@CO_EMP_RUC CHAR(13),
@FECHA_FACTURACION DATETIME
AS
SELECT count(*) 
FROM dbo.CO_AUTORIZACION AUT
WHERE CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM AND CO_ALM_COD=@CO_ALM_COD AND CO_EMP_RUC=@CO_EMP_RUC AND Activo=1
and @FECHA_FACTURACION BETWEEN AUT.ValidoDesde AND AUT.ValidoHasta
GO
