SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_DOCUMENTOS_VENTAS]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_DOC_VEN_NUM INT
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
,@CO_DOC_VEN_FOR_PAG NVARCHAR(15)
,@CO_DOC_VEN_EST NVARCHAR(50)
,@CO_TIP_DOC_VEN_NOM NVARCHAR(100)
,@CO_TIP_CLI_COD NVARCHAR(10)
,@CO_CLI_COD NVARCHAR(50)
,@CO_VEN_CED NCHAR(10)
,@CO_ALM_COD NVARCHAR(20)
AS
SELECT CO_EMP_NOM,CO_EMP_CIU,CO_DOC_VEN_NUM,CO_VEN_CED,CO_DOC_VEN_FEC,CO_CLI_NOM,CO_CLI_COD,
--CO_DOC_VEN_TOT_NET,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN CO_DOC_VEN_TOT_NET+CO_DOC_VEN_DES ELSE CO_DOC_VEN_TOT_NET END AS CO_DOC_VEN_TOT_NET,
CO_DOC_VEN_DES,CO_DOC_VEN_IVA,CO_DOC_VEN_TOT_PAG,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA,
@CO_TIP_DOC_VEN_NOM AS TIPO_DOCUMENTO, CO_VALOR_NOTA_CREDITO
FROM CO_VW_SELECT_LISTADO_FACTURAS
WHERE 
CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM AND
CO_EMP_RUC=@CO_EMP_RUC AND
(CO_DOC_VEN_EST=@CO_DOC_VEN_EST or CO_DOC_VEN_EST=CASE WHEN @CO_DOC_VEN_EST='ACTIVA' THEN 'PROCESADO' ELSE 'ANULADA' END)  AND
(CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND
CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2) AND 
CO_DOC_VEN_FOR_PAG=case @CO_DOC_VEN_FOR_PAG when '' then CO_DOC_VEN_FOR_PAG else @CO_DOC_VEN_FOR_PAG end  AND
CO_TIP_CLI_COD=case @CO_TIP_CLI_COD when '' then CO_TIP_CLI_COD else @CO_TIP_CLI_COD end  AND
CO_CLI_COD=case @CO_CLI_COD when '' then CO_CLI_COD else @CO_CLI_COD end  AND
CO_VEN_CED=case @CO_VEN_CED when '' then CO_VEN_CED else @CO_VEN_CED end  
order by CO_DOC_VEN_FEC

GO
