SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_KARDEX]

@CO_EMP_RUC char(13),
@CO_ART_COD nvarchar(20),
@CO_COM_FEC_INI datetime,
@CO_COM_FEC_FIN DATETIME,
@CO_BOD_COD int
AS

--SELECT CO_KAR_TOT_COD, CO_EMP_RUC, CO_ART_COD, CO_KAR_TOT_FEC, CO_KAR_TOT_DOC, CO_KAR_TOT_TIP_DOC, CO_KAR_TOT_ENT_CANT, 
--CO_KAR_TOT_ENT_VAL_UNI, CO_KAR_TOT_ENT_VAL_TOT, CO_KAR_TOT_SAL_CANT, CO_KAR_TOT_SAL_VAL_UNI, CO_KAR_TOT_SAL_VAL_TOT, 
--CO_KAR_TOT_EXI_CANT, CO_KAR_TOT_EXI_VAL_UNI, CO_KAR_TOT_EXI_VAL_TOT,CO_KAR_TOT_EST,CO_KAR_TOT_DET
--FROM CO_KARDEX_TOTAL
SELECT CO_KAR_TOT_COD, KT.CO_EMP_RUC, KT.CO_ART_COD, CO_KAR_TOT_FEC, CO_KAR_TOT_DOC, CO_KAR_TOT_TIP_DOC, 
CAST(CASE WHEN ISNULL(A.UNIDAD_X_EMPAQUE,0)!=0 THEN CAST(CO_KAR_TOT_ENT_CANT AS float) / CAST(A.UNIDAD_X_EMPAQUE AS FLOAT) ELSE 0 END AS float) as CO_KAR_TOT_ENT_CANT_PAQ, 
CAST(CASE WHEN ISNULL(A.UNIDAD_X_EMPAQUE,0)!=0 THEN CAST(CO_KAR_TOT_ENT_CANT AS float) / CAST(A.UNIDAD_X_EMPAQUE AS FLOAT) ELSE CO_KAR_TOT_ENT_CANT END AS float) as CO_KAR_TOT_ENT_CANT, 
CO_KAR_TOT_ENT_VAL_UNI, CO_KAR_TOT_ENT_VAL_TOT, 
CAST(CASE WHEN ISNULL(A.UNIDAD_X_EMPAQUE,0)!=0 THEN CAST(CO_KAR_TOT_SAL_CANT AS float) / CAST(A.UNIDAD_X_EMPAQUE AS FLOAT) ELSE 0 END AS float) as CO_KAR_TOT_SAL_CANT_PAQ,
CAST(CASE WHEN ISNULL(A.UNIDAD_X_EMPAQUE,0)!=0 THEN CAST(CO_KAR_TOT_SAL_CANT AS float) / CAST(A.UNIDAD_X_EMPAQUE AS FLOAT) ELSE CO_KAR_TOT_SAL_CANT END AS float) as CO_KAR_TOT_SAL_CANT, CO_KAR_TOT_SAL_VAL_UNI, CO_KAR_TOT_SAL_VAL_TOT, 
CAST(CASE WHEN ISNULL(A.UNIDAD_X_EMPAQUE,0)!=0 THEN CAST(CO_KAR_TOT_EXI_CANT AS float) / CAST(A.UNIDAD_X_EMPAQUE AS FLOAT) ELSE 0 END AS float) as CO_KAR_TOT_EXI_CANT_PAQ, 
CAST(CASE WHEN ISNULL(A.UNIDAD_X_EMPAQUE,0)!=0 THEN CAST(CO_KAR_TOT_EXI_CANT AS float) / CAST(A.UNIDAD_X_EMPAQUE AS FLOAT) ELSE CO_KAR_TOT_EXI_CANT END AS float) as CO_KAR_TOT_EXI_CANT 
,CO_KAR_TOT_EXI_VAL_UNI, CO_KAR_TOT_EXI_VAL_TOT,CO_KAR_TOT_EST,CO_KAR_TOT_DET
FROM CO_KARDEX_TOTAL KT INNER JOIN CO_ARTICULO A ON KT.CO_ART_COD=A.CO_ART_COD AND KT.CO_EMP_RUC=A.CO_EMP_RUC
WHERE (KT.CO_EMP_RUC = @CO_EMP_RUC) AND (KT.CO_KAR_TOT_FEC >= @CO_COM_FEC_INI AND KT.CO_KAR_TOT_FEC <= @CO_COM_FEC_FIN)
and KT.CO_ART_COD=case when @CO_ART_COD='' then KT.CO_ART_COD else @CO_ART_COD end
AND KT.CO_BOD_COD=@CO_BOD_COD
ORDER BY CO_KAR_TOT_FEC






GO
