SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_RUBROS_MANUALES_MES]
@CO_UBI_COD INT
,@CO_EMP_RUC CHAR(13)
,@CO_MES INT
,@CO_ANIO INT
AS
SELECT CO_EMP_RUC,PROF_COD,CO_RUB_ROL_COD,SUM(CO_TRA_VAL),MES,ANIO,CO_RUB_ROL_VAL,CO_UBI_COD
FROM CO_VW_SELECT_RUBROS_MANUALES_MES
WHERE CO_UBI_COD=@CO_UBI_COD AND MES=@CO_MES AND ANIO=@CO_ANIO AND CO_EMP_RUC=@CO_EMP_RUC
GROUP BY CO_EMP_RUC,PROF_COD,CO_RUB_ROL_COD,MES,ANIO,CO_RUB_ROL_VAL,CO_UBI_COD
GO
