SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BODEGA_POR_ALMACEN_ALMACEN]
@CO_EMP_RUC CHAR(13),
@CO_ALM_COD INT
AS
SELECT dbo.CO_ALMACEN.CO_ALM_COD, dbo.CO_ALMACEN.CO_ALM_NOM, dbo.CO_BODEGA.CO_BOD_NOM AS BODEGA
FROM dbo.CO_ALMACEN INNER JOIN
dbo.CO_BODEGA ON dbo.CO_ALMACEN.CO_ALM_COD = dbo.CO_BODEGA.CO_ALM_COD AND 
dbo.CO_ALMACEN.CO_EMP_RUC = dbo.CO_BODEGA.CO_EMP_RUC
WHERE CO_ALMACEN.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_ALMACEN.CO_ALM_COD=@CO_ALM_COD
GO
