SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_DOCUMENTO_RESERVA]
@CO_EMP_RUC char(13)
,@CO_DOC_VEN_ID uniqueidentifier
AS
UPDATE CO_DOCUMENTO_RESERVA SET
CO_DOC_VEN_EST='ANULADO'
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID AND
CO_EMP_RUC=@CO_EMP_RUC
GO
