SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PROYECTO_INGRESOS]
@CO_EMP_RUC char(13)
,@CO_ING_COD INT
AS
DELETE [dbo].[CO_PROYECTO_INGRESOS] 
WHERE
           (CO_ING_COD=@CO_ING_COD
           AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
