SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE proc [dbo].[CO_SP_SELECT_REPORTE_MOVIMIENTOS_ARTICULOS]
@CO_EMP_RUC CHAR(13),
@CO_ART_COD NVARCHAR(20),
@CO_FEC_FIN DATETIME
AS
DECLARE @FECHA_INICIAL DATETIME
DECLARE @SALDO_ANTERIOR FLOAT
--OBTENER LA FECHA MAXIMA
--SELECT @FECHA_INICIAL=MAX(CO_KAR_TOT_FEC) FROM CO_VW_SELECT_REPORTE_MOVIMIENTOS_ENTRADAS
--WHERE CO_ART_COD=@CO_ART_COD AND CO_KAR_TOT_FEC<=@CO_FEC_FIN

--OBTENER EL SALDO ANTERIOR A LA FECHA DE LA ENTRADA DE LA ULTIMA ENTRADA
--SELECT @SALDO_ANTERIOR=CO_KAR_TOT_EXI_CANT
--FROM dbo.CO_KARDEX_TOTAL
--WHERE CO_ART_COD=@CO_ART_COD 
--AND CO_KAR_TOT_FEC=(SELECT MAX(CO_KAR_TOT_FEC) FROM dbo.CO_KARDEX_TOTAL
--WHERE CO_ART_COD=@CO_ART_COD AND CO_KAR_TOT_FEC<@FECHA_INICIAL)

SELECT *, 0 as SaldoAnterior FROM CO_VW_SELECT_REPORTE_MOVIMIENTOS_FINAL
WHERE CO_ART_COD=@CO_ART_COD
AND CO_EMP_RUC=@CO_EMP_RUC
AND  CO_KAR_TOT_FEC<=@CO_FEC_FIN
ORDER BY CO_KAR_TOT_FEC

GO
