SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIPO_COMPROBANTE_COMPRA_OPERACION]
@CO_TIP_COM_COM_COD INT
AS
SELECT [CO_TIP_COM_COM_INV] FROM [dbo].[CO_TIPO_COMPROBANTE_COMPRA]
WHERE CO_TIP_COM_COM_COD=@CO_TIP_COM_COM_COD
GO
