SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_COMPROBANTE_COBRO]
@CO_COM_COB_NUM int
,@CO_EMP_RUC char(13)
,@PROF_COD char(10)
,@CO_COM_COB_FEC datetime
,@CO_COM_COB_CON nvarchar(100)
,@CO_COM_COB_VAL float
,@CO_COM_COB_EST BIT
,@CO_COM_COB_COM nvarchar(50)
,@CO_COM_COB_USU_ALI NVARCHAR(14)
,@CO_COM_COB_FOR_COB nvarchar(15)
,@CO_COM_COB_EFE bit
,@CO_COM_COB_EFE_VAL float
,@CO_COM_COB_CHE bit
,@CO_COM_COB_CHE_VAL float
,@CO_COM_COB_CHE_NUM nvarchar(15)
,@CO_COM_COB_CHE_BAN nvarchar(20)
,@CO_COM_COB_ROL bit
,@CO_COM_COB_ROL_VAL float
,@CO_COM_COB_ROL_DOC_NUM int
,@CO_COM_NUM int
,@CO_TIP_COM_COD int
AS
INSERT INTO [dbo].[CO_COMPROBANTE_COBRO]
([CO_COM_COB_NUM]
,[CO_EMP_RUC]
,[PROF_COD]
,[CO_COM_COB_FEC]
,[CO_COM_COB_CON]
,[CO_COM_COB_VAL]
,CO_COM_COB_EST
,CO_COM_COB_COM
,CO_COM_COB_USU_ALI
,CO_COM_COB_FOR_COB
,CO_COM_COB_EFE
,CO_COM_COB_EFE_VAL
,CO_COM_COB_CHE
,CO_COM_COB_CHE_VAL
,CO_COM_COB_CHE_NUM
,CO_COM_COB_CHE_BAN
,CO_COM_COB_ROL
,CO_COM_COB_ROL_VAL
,CO_COM_COB_ROL_DOC_NUM
,CO_COM_NUM
,CO_TIP_COM_COD)
VALUES
(@CO_COM_COB_NUM
,@CO_EMP_RUC
,@PROF_COD
,@CO_COM_COB_FEC
,@CO_COM_COB_CON
,@CO_COM_COB_VAL
,@CO_COM_COB_EST
,@CO_COM_COB_COM
,@CO_COM_COB_USU_ALI
,@CO_COM_COB_FOR_COB
,@CO_COM_COB_EFE
,@CO_COM_COB_EFE_VAL
,@CO_COM_COB_CHE
,@CO_COM_COB_CHE_VAL
,@CO_COM_COB_CHE_NUM
,@CO_COM_COB_CHE_BAN
,@CO_COM_COB_ROL
,@CO_COM_COB_ROL_VAL
,@CO_COM_COB_ROL_DOC_NUM
,@CO_COM_NUM
,@CO_TIP_COM_COD)
GO
