SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ROL_TEMP]
@CO_EMP_RUC char(13)
,@PROF_COD CHAR(10)
AS
DELETE [dbo].[CO_ROL_TEMP]
WHERE [CO_EMP_RUC]=@CO_EMP_RUC AND PROF_COD=@PROF_COD
GO
