SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_SUSTENTO]
@CO_TIP_SUS_COD nvarchar(5),
@CO_TIP_SUS_NOM NVARCHAR(150),
@CO_TIP_OPC CHAR(1)
AS
IF(@CO_TIP_OPC='N')
BEGIN
DECLARE @LIKE AS VARCHAR(152)
SET @LIKE='%'+@CO_TIP_SUS_NOM+'%'
SELECT *
FROM CO_TIPO_SUSTENTO     
WHERE CO_TIP_SUS_NOM LIKE @LIKE 
END
ELSE
SELECT *
FROM CO_TIPO_SUSTENTO     
WHERE CO_TIP_SUS_COD=@CO_TIP_SUS_COD
GO
