SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_ASIENTO_AUX]
@CO_EMP_RUC char(13)
,@CO_TIP_COM_COD int
,@CO_COM_NUM int
AS
DELETE [dbo].[CO_ASIENTO_AUX] 
WHERE @CO_EMP_RUC=CO_EMP_RUC AND
CO_TIP_COM_COD=@CO_TIP_COM_COD AND
CO_COM_NUM=@CO_COM_NUM
GO
