SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_INSERT_CUENTA_CONTABLE_ESTANDAR]
@CO_EMP_RUC char(13)
as
INSERT INTO [dbo].[CO_CUENTA]
([CO_EMP_RUC]
,[CO_CUE_COD]
,[CO_CUE_NOM]
,[CO_CUE_TIP]
,[CO_CUE_USU_ALI]
,[CO_CUE_NIV]
,[CO_CUE_COD_ANT]
,[CO_CUE_CAS_IMP])
SELECT 
@CO_EMP_RUC,
CO_CUE_COD,
CO_CUE_NOM,
CO_CUE_TIP,
CO_CUE_USU_ALI,
CO_CUE_NIV,
CO_CUE_COD_ANT,
CO_CUE_CAS_IMP_REN
FROM CO_ESTANDAR_CUENTA
GO
