SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_ASIENTO_AUX]
@CO_EMP_RUC char(13)
,@CO_CUE_COD varchar(40)
,@CO_ASI_COD int
,@CO_ASI_AUX_FEC datetime
,@CO_ASI_AUX_DES nvarchar(150)
,@CO_ASI_AUX_DEB float
,@CO_ASI_AUX_HAB float
,@CO_ASI_AUX_COD_REF nvarchar(10)
,@CO_ASI_AUX_CLI nvarchar(50)
,@CO_TIP_COM_COD int
,@CO_COM_NUM int
AS
UPDATE [dbo].[CO_ASIENTO_AUX] SET
[CO_ASI_AUX_FEC]=@CO_ASI_AUX_FEC
,[CO_ASI_AUX_DES]=@CO_ASI_AUX_DES
,[CO_ASI_AUX_DEB]=@CO_ASI_AUX_DEB
,[CO_ASI_AUX_HAB]=@CO_ASI_AUX_HAB
,[CO_ASI_AUX_COD_REF]=@CO_ASI_AUX_COD_REF
,[CO_ASI_AUX_CLI]=@CO_ASI_AUX_CLI
,[CO_CUE_COD]=@CO_CUE_COD
,[CO_ASI_COD]=@CO_ASI_COD
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_TIP_COM_COD=@CO_TIP_COM_COD
AND CO_COM_NUM=@CO_COM_NUM
GO
