SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TRANSACCIONES]
@CO_EMP_RUC char(13)
,@CO_RUB_ROL_COD int
,@CO_TRA_MES INT 
,@CO_TRA_ANO INT 
AS
DELETE [dbo].[CO_TRANSACCION] 
WHERE 
[CO_EMP_RUC]=@CO_EMP_RUC AND
[CO_RUB_ROL_COD]=@CO_RUB_ROL_COD AND
[CO_TRA_MES]=@CO_TRA_MES AND
[CO_TRA_ANO]=@CO_TRA_ANO
GO
