SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PROYECTO]
@CO_PRO_COD int
,@CO_EMP_RUC char(13)
,@CO_PRO_NOM nvarchar(150)
,@CO_PRO_DES nvarchar(150)
,@CO_PRO_TIP nvarchar(10)
AS
UPDATE [dbo].[CO_PROYECTO] SET
[CO_PRO_NOM]=@CO_PRO_NOM
,[CO_PRO_DES]=@CO_PRO_DES
,CO_PRO_TIP=@CO_PRO_TIP
WHERE
([CO_PRO_COD]=@CO_PRO_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
