SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PARAMETRO_COMPRAS_PORID]
@ParametroCompraID INT
AS
SELECT * FROM CO_PARAMETRO_COMPRAS
WHERE ParametroCompraID=@ParametroCompraID
GO
