SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_ACTIVO_FIJO_ESTADO]
@CO_ACT_FIJ_COD int
,@CO_EMP_RUC char(13)
,@CO_ACT_FIJ_EST bit
AS
UPDATE [dbo].[CO_ACTIVO_FIJO] SET
[CO_ACT_FIJ_EST]=@CO_ACT_FIJ_EST
WHERE 
CO_ACT_FIJ_COD=@CO_ACT_FIJ_COD AND
CO_EMP_RUC=@CO_EMP_RUC
GO
