SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_ASIENTO]
@CO_EMP_RUC char(13)
,@CO_CUE_COD varchar(40)
,@CO_ASI_COD INT
,@CO_TIP_COM_COD inT
,@CO_COM_NUM int
,@CO_ASI_FEC datetime
,@CO_ASI_DES varchar(150)
,@CO_ASI_DEB float
,@CO_ASI_HAB float
,@CO_ASI_TIP CHAR(1)
,@CO_ASI_COD_ALI int
,@CO_CEN_COS_COD varchar(30)
AS
INSERT INTO [dbo].[CO_ASIENTO]
          
     VALUES
           (@CO_EMP_RUC
,@CO_CUE_COD
,@CO_ASI_COD
,@CO_TIP_COM_COD
,@CO_COM_NUM
,@CO_ASI_FEC
,@CO_ASI_DES
,@CO_ASI_DEB
,@CO_ASI_HAB
,@CO_ASI_TIP
,@CO_ASI_COD_ALI
,@CO_CEN_COS_COD)
GO
