SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_PAGO_CUOTA_EMPLEADO]
@CO_EMP_RUC CHAR(13)
,@PROF_COD CHAR(10)
AS
SELECT * FROM CO_VW_SELECT_BUSCAR_PAGO_CUOTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND PROF_COD=@PROF_COD
GO
