SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CABECERA_TEMP]
@CO_EMP_RUC char(13)
,@CO_CAB_TEM_MES int
,@CO_CAB_TEM_ANO int
,@CO_CAB_TEM_EST bit
AS
UPDATE [dbo].[CO_CABECERA_TEMP] SET
[CO_CAB_TEM_MES]=@CO_CAB_TEM_MES
,[CO_CAB_TEM_ANO]=@CO_CAB_TEM_ANO
,[CO_CAB_TEM_EST]=@CO_CAB_TEM_EST
WHERE [CO_EMP_RUC]=@CO_EMP_RUC
GO
