SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_COMPROBANTE_NOTA_DEBITO]
@CO_NOT_DEB_NUM int,
@CO_EMP_RUC char(13)
AS
SELECT * FROM CO_VW_SELECT_REPORTE_NOTAS_DEBITO
WHERE CO_NOT_DEB_NUM=@CO_NOT_DEB_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
