SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_DOCUMENTO_COMPRA]
@CO_EMP_RUC CHAR(13)
,@CO_PRO_NOM NVARCHAR(100)
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
,@CO_DOC_COM_SEC NVARCHAR(20)
,@CO_ALM_COD INT
AS
if(@CO_DOC_VEN_FEC1 is null)
SELECT dbo.CO_PROVEEDOR.CO_PRO_NOM, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM, 
dbo.CO_DOCUMENTO_COMPRA.CO_PRO_COD, dbo.CO_DOCUMENTO_COMPRA.CO_EMP_RUC, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_CAD, dbo.CO_DOCUMENTO_COMPRA.CO_TIP_SUS_COD, 
dbo.CO_DOCUMENTO_COMPRA.CO_TIP_COM_COM_COD, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_ETA, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_PUN_EMI, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_SEC, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_DET, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM_AUT, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_EMI, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_REG, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_EST, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TOT_NET, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_POR_DES, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_DES, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_POR_IVA, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_IVA, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TOT_PAG, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FOR_PAG, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_EFE, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_EFE_VAL, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_VAL, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_NUM, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_NUM_CUE, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM_PAG, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_USU_ALI, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TOT_LET, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_VAL_ICE, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_VAL_IVA0, dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD AS CO_TIP_IDE_PRO_COD, 
dbo.CO_PROVEEDOR.CO_PRO_CED,dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_NOM, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_PAGO,dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_DIAS_PLA,
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR_VAL,
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR_NUM, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR_VAU, CO_DOC_COM_ID,
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_FEC, CO_DOC_COM_TRA, CO_DOC_COM_TRA_VAL, CO_DOC_COM_TRA_DOC_NUM,
(SELECT top 1 CO_RET_COD FROM CO_RETENCION WHERE CO_RETENCION.CO_DOC_COM_ID=dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_ID) as CO_RET_COD
FROM dbo.CO_PROVEEDOR INNER JOIN
dbo.CO_DOCUMENTO_COMPRA ON dbo.CO_PROVEEDOR.CO_PRO_COD = dbo.CO_DOCUMENTO_COMPRA.CO_PRO_COD INNER JOIN
dbo.CO_TIPO_IDENTIFICACION ON 
dbo.CO_PROVEEDOR.CO_TIP_IDE_COD = dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD INNER JOIN
dbo.CO_TIPO_COMPROBANTE_COMPRA ON dbo.CO_DOCUMENTO_COMPRA.CO_TIP_COM_COM_COD = dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_COD
WHERE dbo.CO_PROVEEDOR.CO_PRO_NOM like '%'+@CO_PRO_NOM+'%'
--AND dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_EMI between @CO_DOC_VEN_FEC1 and @CO_DOC_VEN_FEC2
AND dbo.CO_DOCUMENTO_COMPRA.CO_EMP_RUC=@CO_EMP_RUC
--and dbo.CO_DOCUMENTO_COMPRA.co_doc_com_sec like '%'+@CO_DOC_COM_SEC+'%'
and CO_DOC_COM_NUM like '%'+@CO_DOC_COM_SEC+'%'
--AND (SELECT CO_ALM_COD FROM dbo.CO_BODEGA WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_BOD_COD IN (
--		(SELECT TOP 1 CO_BOD_COD FROM dbo.CO_DETALLE_DOCUMENTO_COMPRA WHERE CO_DOC_COM_ID=dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_ID)))=@CO_ALM_COD
else
SELECT dbo.CO_PROVEEDOR.CO_PRO_NOM, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM, 
dbo.CO_DOCUMENTO_COMPRA.CO_PRO_COD, dbo.CO_DOCUMENTO_COMPRA.CO_EMP_RUC, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_CAD, dbo.CO_DOCUMENTO_COMPRA.CO_TIP_SUS_COD, 
dbo.CO_DOCUMENTO_COMPRA.CO_TIP_COM_COM_COD, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_ETA, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_PUN_EMI, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_SEC, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_DET, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM_AUT, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_EMI, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_REG, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_EST, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TOT_NET, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_POR_DES, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_DES, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_POR_IVA, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_IVA, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TOT_PAG, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FOR_PAG, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_EFE, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_EFE_VAL, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_VAL, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_NUM, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_NUM_CUE, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM_PAG, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_USU_ALI, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TOT_LET, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_VAL_ICE, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_VAL_IVA0, dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD AS CO_TIP_IDE_PRO_COD, 
dbo.CO_PROVEEDOR.CO_PRO_CED,dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_NOM, 
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_PAGO,dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_DIAS_PLA,
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR_VAL,
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR_NUM, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_TAR_VAU, CO_DOC_COM_ID,
dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_FEC, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_CHE_FEC, CO_DOC_COM_TRA, CO_DOC_COM_TRA_VAL, CO_DOC_COM_TRA_DOC_NUM,
(SELECT top 1 CO_RET_COD FROM CO_RETENCION WHERE CO_RETENCION.CO_DOC_COM_ID=dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_ID) as CO_RET_COD
FROM dbo.CO_PROVEEDOR INNER JOIN
dbo.CO_DOCUMENTO_COMPRA ON dbo.CO_PROVEEDOR.CO_PRO_COD = dbo.CO_DOCUMENTO_COMPRA.CO_PRO_COD INNER JOIN
dbo.CO_TIPO_IDENTIFICACION ON 
dbo.CO_PROVEEDOR.CO_TIP_IDE_COD = dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD INNER JOIN
dbo.CO_TIPO_COMPROBANTE_COMPRA ON dbo.CO_DOCUMENTO_COMPRA.CO_TIP_COM_COM_COD = dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_COD
WHERE dbo.CO_PROVEEDOR.CO_PRO_NOM like '%'+@CO_PRO_NOM+'%'
AND dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_EMI between @CO_DOC_VEN_FEC1 and @CO_DOC_VEN_FEC2
AND dbo.CO_DOCUMENTO_COMPRA.CO_EMP_RUC=@CO_EMP_RUC
and CO_DOC_COM_NUM like '%'+@CO_DOC_COM_SEC+'%'
--AND (SELECT CO_ALM_COD FROM dbo.CO_BODEGA WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_BOD_COD IN (
--		(SELECT TOP 1 CO_BOD_COD FROM dbo.CO_DETALLE_DOCUMENTO_COMPRA WHERE CO_DOC_COM_ID=dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_ID)))=@CO_ALM_COD

















GO
