SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TRANSACCION]
(@CO_EMP_RUC char(13)
,@CO_RUB_ROL_COD int
,@PROF_COD char(10)
,@CO_TRA_MES int
,@CO_TRA_ANO int
,@CO_TRA_VAL float
,@CO_TRA_USU_ALI varchar(13))
AS
INSERT INTO [dbo].[CO_TRANSACCION]
([CO_EMP_RUC]
,[CO_RUB_ROL_COD]
,[PROF_COD]
,[CO_TRA_MES]
,[CO_TRA_ANO]
,[CO_TRA_VAL]
,[CO_TRA_USU_ALI])
VALUES
(@CO_EMP_RUC
,@CO_RUB_ROL_COD
,@PROF_COD
,@CO_TRA_MES
,@CO_TRA_ANO
,@CO_TRA_VAL
,@CO_TRA_USU_ALI)
GO
