SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TABLA_PRECIO]
@CO_EMP_RUC char(13)
,@CO_ART_COD nvarchar(40)
AS
SELECT [CO_TABLA_PRECIO].*, dbo.CO_LISTA_PRECIO.Nombre, dbo.CO_LISTA_PRECIO.ListaDePrecioID
FROM [dbo].[CO_TABLA_PRECIO] INNER JOIN dbo.CO_LISTA_PRECIO ON dbo.CO_TABLA_PRECIO.ListaDePrecioID = dbo.CO_LISTA_PRECIO.ListaDePrecioID
WHERE [CO_TABLA_PRECIO].[CO_EMP_RUC]=@CO_EMP_RUC AND CO_ART_COD=@CO_ART_COD
GO
