SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_ARTICULO_ULTIMO_STOCK]
@CO_EMP_RUC CHAR(13),
@CO_BOD_COD INT,
@CO_ART_COD VARCHAR(20)
AS
WITH S
		as
		(
		SELECT RANK() OVER (PARTITION BY CO_ARTICULO.CO_ART_COD, dbo.CO_KARDEX_TOTAL.CO_BOD_COD ORDER BY dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_FEC DESC) AS 'RowNumber',		
						dbo.CO_ARTICULO.CO_ART_COD, dbo.CO_ARTICULO.CO_EMP_RUC, dbo.CO_BODEGA.CO_BOD_COD,
						dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_ARTICULO.CO_ART_COD_FAB, dbo.CO_ARTICULO.CO_ART_MAR, CO_ART_COL,
						CO_ART_EXI_MIN, CO_ART_EXI_MAX, CO_ART_UNI, CO_ART_POR_IVA,
						CO_ART_TIP, CO_ICE_COD, ISNULL((SELECT TOP 1 CO_TAB_PRE FROM dbo.CO_TABLA_PRECIO INNER JOIN dbo.CO_LISTA_PRECIO ON dbo.CO_TABLA_PRECIO.ListaDePrecioID = dbo.CO_LISTA_PRECIO.ListaDePrecioID
													WHERE CO_ART_COD=dbo.CO_ARTICULO.CO_ART_COD AND dbo.CO_LISTA_PRECIO.Nombre='PVP'),0) AS PVP, 
						dbo.CO_BODEGA.CO_BOD_NOM, CO_ART_PES, CO_ART_BAR, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT, 
						dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_UNI
		FROM dbo.CO_ARTICULO INNER JOIN
             dbo.CO_UBICACIONARTICULO ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_UBICACIONARTICULO.CO_ART_COD AND 
             dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_UBICACIONARTICULO.CO_EMP_RUC INNER JOIN
             dbo.CO_BODEGA ON dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_BODEGA.CO_BOD_COD LEFT OUTER JOIN
             dbo.CO_KARDEX_TOTAL ON dbo.CO_UBICACIONARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
             dbo.CO_UBICACIONARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC AND 
             dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_KARDEX_TOTAL.CO_BOD_COD
		where dbo.CO_ARTICULO.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_KARDEX_TOTAL.CO_BOD_COD=@CO_BOD_COD and dbo.CO_KARDEX_TOTAL.CO_ART_COD=@CO_ART_COD)

		SELECT CO_ART_COD, CO_ART_NOM, 
				ROUND( PVP/1.12,2) AS PVP, PVP AS  PVPIVA, CO_KAR_TOT_EXI_CANT AS STOCK, CO_KAR_TOT_EXI_VAL_UNI AS COSTO_PROMEDIO
		FROM S
		WHERE RowNumber=1
GO
