SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PROVEEDOR]
(@CO_PRO_COD nvarchar(20)
,@CO_EMP_RUC char(13)
,@CO_TIP_PRO_COD nvarchar(10)
,@CO_TIP_IDE_PRO_COD nvarchar(50)
,@CO_PRO_CED nvarchar(20)
,@CO_PRO_NOM nvarchar(100)
,@CO_PRO_CON nvarchar(50)
,@CO_PRO_PAI nvarchar(50)
,@CO_PRO_CIU nvarchar(50)
,@CO_PRO_DIR nvarchar(200)
,@CO_PRO_TEL1 nvarchar(20)
,@CO_PRO_TEL2 nvarchar(20)
,@CO_PRO_FAX nvarchar(20)
,@CO_PRO_CEL nvarchar(20)
,@CO_PRO_MAI nvarchar(150)
,@CO_PRO_EST nvarchar(10)
,@CO_PRO_CUE nvarchar(40)
,@CO_PRO_CON_ESP bit
,@CO_PRO_CRE bit
,@CO_PRO_LIM_CRE float
,@CO_PRO_USU_ALI nvarchar(15)
,@CO_PRO_FAC_FEC_CAD datetime
,@CO_PRO_FAC_SER1 nchar(3)
,@CO_PRO_FAC_SER2 nchar(3)
,@CO_PRO_FAC_SEC nchar(7)
,@CO_PRO_FAC_NUM_ACT nchar(10)
,@CO_PRO_MAI2 nvarchar(100)
,@CO_PRO_MAI3 nvarchar(100))
AS
INSERT INTO [dbo].[CO_PROVEEDOR]
([CO_PRO_COD]
,[CO_EMP_RUC]
,[CO_TIP_PRO_COD]
,[CO_TIP_IDE_COD]
,[CO_PRO_CED]
,[CO_PRO_NOM]
,[CO_PRO_CON]
,[CO_PRO_PAI]
,[CO_PRO_CIU]
,[CO_PRO_DIR]
,[CO_PRO_TEL1]
,[CO_PRO_TEL2]
,[CO_PRO_FAX]
,[CO_PRO_CEL]
,[CO_PRO_MAI]
,[CO_PRO_EST]
,[CO_PRO_CUE]
,[CO_PRO_CON_ESP]
,[CO_PRO_CRE]
,[CO_PRO_LIM_CRE]
,[CO_PRO_USU_ALI]
,[CO_PRO_FAC_FEC_CAD]
,[CO_PRO_FAC_SER1]
,[CO_PRO_FAC_SER2]
,[CO_PRO_FAC_SEC]
,[CO_PRO_FAC_NUM_ACT]
,CO_PRO_MAI2
,CO_PRO_MAI3)
VALUES
(@CO_PRO_COD
,@CO_EMP_RUC
,@CO_TIP_PRO_COD
,@CO_TIP_IDE_PRO_COD
,@CO_PRO_CED
,@CO_PRO_NOM
,@CO_PRO_CON
,@CO_PRO_PAI
,@CO_PRO_CIU
,@CO_PRO_DIR
,@CO_PRO_TEL1
,@CO_PRO_TEL2
,@CO_PRO_FAX
,@CO_PRO_CEL
,@CO_PRO_MAI
,@CO_PRO_EST
,@CO_PRO_CUE
,@CO_PRO_CON_ESP
,@CO_PRO_CRE
,@CO_PRO_LIM_CRE
,@CO_PRO_USU_ALI
,@CO_PRO_FAC_FEC_CAD
,@CO_PRO_FAC_SER1
,@CO_PRO_FAC_SER2
,@CO_PRO_FAC_SEC
,@CO_PRO_FAC_NUM_ACT
,@CO_PRO_MAI2
,@CO_PRO_MAI3)
GO
