SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PAGO_CUOTA_MES]
@CO_EMP_RUC CHAR(13),
@CO_PAG_MES INT,
@CO_PAG_ANO INT,
@CO_UBI_COD int
AS
SELECT dbo.PROFESOR.PROF_COD, dbo.CO_PAGO_CUOTA.CO_PAG_FEC, dbo.CO_PAGO_CUOTA.CO_PAG_VAL, 
dbo.CO_PAGO_CUOTA.CO_RUB_ROL_COD
FROM dbo.CO_PAGO_CUOTA INNER JOIN
dbo.CO_NOTA_DEBITO ON dbo.CO_PAGO_CUOTA.CO_EMP_RUC = dbo.CO_NOTA_DEBITO.CO_EMP_RUC AND 
dbo.CO_PAGO_CUOTA.CO_NOT_DEB_NUM = dbo.CO_NOTA_DEBITO.CO_NOT_DEB_NUM AND 
dbo.CO_PAGO_CUOTA.PROF_COD = dbo.CO_NOTA_DEBITO.PROF_COD INNER JOIN
dbo.PROFESOR ON dbo.CO_NOTA_DEBITO.PROF_COD = dbo.PROFESOR.PROF_COD
WHERE MONTH(dbo.CO_PAGO_CUOTA.CO_PAG_FEC)=@CO_PAG_MES AND YEAR(dbo.CO_PAGO_CUOTA.CO_PAG_FEC)=@CO_PAG_ANO AND
dbo.CO_NOTA_DEBITO.CO_EMP_RUC=@CO_EMP_RUC and  dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD
GO
