SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_RETENCION_DIARIO]
(@CO_DOC_VEN_ID UNIQUEIDENTIFIER)
AS
DELETE [dbo].[CO_RETENCION] 
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID
GO
