SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_SERVICIOS]
@CO_EMP_RUC CHAR(13)
,@CO_SER_OPC CHAR(1)
,@CO_TIP_SER_COD INT
AS
IF (@CO_SER_OPC='T')
SELECT dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_SERVICIO.CO_SER_COD, 
dbo.CO_SERVICIO.CO_SER_NOM, dbo.CO_SERVICIO.CO_SER_PRE, dbo.CO_SERVICIO.CO_SER_POR_IVA, 
dbo.CO_TIPO_SERVICIO.CO_TIP_SER_NOM
FROM dbo.CO_EMPRESA INNER JOIN
dbo.CO_TIPO_SERVICIO ON dbo.CO_EMPRESA.CO_EMP_RUC = dbo.CO_TIPO_SERVICIO.CO_EMP_RUC INNER JOIN
dbo.CO_SERVICIO ON dbo.CO_TIPO_SERVICIO.CO_TIP_SER_COD = dbo.CO_SERVICIO.CO_TIP_SER_COD AND 
dbo.CO_TIPO_SERVICIO.CO_EMP_RUC = dbo.CO_SERVICIO.CO_EMP_RUC
WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC
ELSE IF (@CO_SER_OPC='C')
SELECT dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_SERVICIO.CO_SER_COD, 
dbo.CO_SERVICIO.CO_SER_NOM, dbo.CO_SERVICIO.CO_SER_PRE, dbo.CO_SERVICIO.CO_SER_POR_IVA, 
dbo.CO_TIPO_SERVICIO.CO_TIP_SER_NOM
FROM dbo.CO_EMPRESA INNER JOIN
dbo.CO_TIPO_SERVICIO ON dbo.CO_EMPRESA.CO_EMP_RUC = dbo.CO_TIPO_SERVICIO.CO_EMP_RUC INNER JOIN
dbo.CO_SERVICIO ON dbo.CO_TIPO_SERVICIO.CO_TIP_SER_COD = dbo.CO_SERVICIO.CO_TIP_SER_COD AND 
dbo.CO_TIPO_SERVICIO.CO_EMP_RUC = dbo.CO_SERVICIO.CO_EMP_RUC
WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_TIPO_SERVICIO.CO_TIP_SER_COD=@CO_TIP_SER_COD
GO
