SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CRUCE_SUSTENTO]
@CO_TIP_SUS_COD nvarchar(5)
AS
SELECT * FROM CO_CRUCE_SUSTENTO
WHERE CO_TIP_SUS_COD=@CO_TIP_SUS_COD
GO
