SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ACTIVO_DEPRECIABLES]
@CO_EMP_RUC CHAR(13),
@CO_TIP_ACT_COD INT,
@CO_FEC_DEP DATETIME
AS
SELECT CO_ACT_FIJ_COD,CO_TIP_ACT_POR,CO_ACT_FIJ_VAL_ACT,CO_ACT_FIJ_CAN,CO_TIP_ACT_TIE,CO_CUE_COD,CO_CUE_COD_DEP
FROM CO_VW_SELECT_ACTIVO_DEPRECIACION
WHERE CO_TIP_ACT_COD=@CO_TIP_ACT_COD  AND CO_EMP_RUC=@CO_EMP_RUC
AND (MONTH(@CO_FEC_DEP)>=MONTH(CO_ACT_FIJ_FEC_INI)+1 AND YEAR(@CO_FEC_DEP)>=YEAR(CO_ACT_FIJ_FEC_INI))
--AND (CONVERT(VARCHAR(10),'03/31/2006 00:00',101)<=CONVERT(VARCHAR(10),CO_ACT_FIJ_FEC_FIN,101))
GO
