SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_ASIENTO]
@CO_EMP_RUC char(13)
,@CO_CUE_COD varchar(40)
,@CO_TIP_COM_COD inT
,@CO_COM_NUM int
,@CO_ASI_FEC datetime
,@CO_ASI_DES varchar(150)
,@CO_ASI_DEB float
,@CO_ASI_HAB float
,@CO_ASI_TIP CHAR(1)
AS
UPDATE [dbo].[CO_ASIENTO] SET
CO_CUE_COD=@CO_CUE_COD
,CO_ASI_FEC=@CO_ASI_FEC
,CO_ASI_DES=@CO_ASI_DES
,CO_ASI_DEB=@CO_ASI_DEB
,CO_ASI_HAB=@CO_ASI_HAB
,CO_ASI_TIP=@CO_ASI_TIP
WHERE
CO_EMP_RUC=@CO_EMP_RUC AND
CO_COM_NUM=@CO_COM_NUM AND
CO_TIP_COM_COD=@CO_TIP_COM_COD
GO
