SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_SERVICIO]
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_SERVICIO.CO_TIP_SER_COD, dbo.CO_SERVICIO.CO_SER_COD, dbo.CO_SERVICIO.CO_SER_NOM, dbo.CO_SERVICIO.CO_SER_PRE, 
dbo.CO_SERVICIO.CO_SER_POR_IVA, dbo.CO_TIPO_SERVICIO.CO_TIP_SER_NOM, dbo.CO_SERVICIO.CO_ICE_COD, 
dbo.CO_SERVICIO.CO_CUE_COD
FROM dbo.CO_TIPO_SERVICIO INNER JOIN
dbo.CO_SERVICIO ON dbo.CO_TIPO_SERVICIO.CO_TIP_SER_COD = dbo.CO_SERVICIO.CO_TIP_SER_COD
WHERE dbo.CO_TIPO_SERVICIO.CO_EMP_RUC=@CO_EMP_RUC
AND CO_ESTADO=1

GO
