SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_ACTIVO_FIJO_DESTINO]
@CO_ACT_FIJ_COD INT,
@CO_ACT_FIJ_ARE VARCHAR(30),
@CO_UBI_COD INT,
@CO_ACT_FIJ_FUN_NOM NVARCHAR(50)
AS
UPDATE CO_ACTIVO_FIJO SET
CO_ACT_FIJ_ARE=@CO_ACT_FIJ_ARE,
CO_UBI_COD=@CO_UBI_COD,
CO_ACT_FIJ_FUN_NOM=@CO_ACT_FIJ_FUN_NOM
WHERE CO_ACT_FIJ_COD=@CO_ACT_FIJ_COD
GO
