SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_PROVEEDOR]
@CO_EMP_RUC CHAR(13)
,@CO_PRO_EST NVARCHAR(10)
,@CO_TIP_PRO_COD NVARCHAR(10)
,@CO_PRO_OPC CHAR(1)
AS
IF(@CO_PRO_OPC='T')
SELECT     dbo.CO_PROVEEDOR.*, dbo.CO_TIPO_PROVEEDOR.CO_TIP_PRO_NOM, dbo.CO_EMPRESA.CO_EMP_NOM
FROM         dbo.CO_PROVEEDOR INNER JOIN
                      dbo.CO_TIPO_PROVEEDOR ON dbo.CO_PROVEEDOR.CO_TIP_PRO_COD = dbo.CO_TIPO_PROVEEDOR.CO_TIP_PRO_COD AND 
                      dbo.CO_PROVEEDOR.CO_EMP_RUC = dbo.CO_TIPO_PROVEEDOR.CO_EMP_RUC INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_TIPO_PROVEEDOR.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_PROVEEDOR.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_PROVEEDOR.CO_PRO_EST=@CO_PRO_EST
ELSE IF(@CO_PRO_OPC='C')
SELECT     dbo.CO_PROVEEDOR.*, dbo.CO_TIPO_PROVEEDOR.CO_TIP_PRO_NOM, dbo.CO_EMPRESA.CO_EMP_NOM
FROM         dbo.CO_PROVEEDOR INNER JOIN
                      dbo.CO_TIPO_PROVEEDOR ON dbo.CO_PROVEEDOR.CO_TIP_PRO_COD = dbo.CO_TIPO_PROVEEDOR.CO_TIP_PRO_COD AND 
                      dbo.CO_PROVEEDOR.CO_EMP_RUC = dbo.CO_TIPO_PROVEEDOR.CO_EMP_RUC INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_TIPO_PROVEEDOR.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_PROVEEDOR.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_PROVEEDOR.CO_PRO_EST=@CO_PRO_EST 
AND dbo.CO_PROVEEDOR.CO_TIP_PRO_COD=@CO_TIP_PRO_COD
GO
