SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create PROC [dbo].[CO_SELECT_CUENTA_POR_PAGAR_DETALLE]
@CO_EMP_RUC CHAR(13),
@CO_CUE_PAG_COD INT
AS
SELECT dbo.CO_CUENTA_POR_PAGAR_DETALLE.*, dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_FEC_EMI
FROM dbo.CO_CUENTA_POR_PAGAR_DETALLE INNER JOIN
dbo.CO_DOCUMENTO_COMPRA ON dbo.CO_CUENTA_POR_PAGAR_DETALLE.CO_DOC_COM_NUM = dbo.CO_DOCUMENTO_COMPRA.CO_DOC_COM_NUM AND 
dbo.CO_CUENTA_POR_PAGAR_DETALLE.CO_EMP_RUC = dbo.CO_DOCUMENTO_COMPRA.CO_EMP_RUC
WHERE dbo.CO_CUENTA_POR_PAGAR_DETALLE.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_CUENTA_POR_PAGAR_DETALLE.CO_CUE_PAG_COD=@CO_CUE_PAG_COD
GO
