SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_CLIENTE]
@CO_TIP_CLI_COD nvarchar(50)
,@CO_EMP_RUC char(13)
,@CO_TIP_CLI_NOM nvarchar(50)
,@CO_TIP_CLI_CUE nvarchar(40)
AS
UPDATE [dbo].[CO_TIPO_CLIENTE] SET
[CO_TIP_CLI_NOM]=@CO_TIP_CLI_NOM
,[CO_TIP_CLI_CUE]=@CO_TIP_CLI_CUE
WHERE
([CO_TIP_CLI_COD]=@CO_TIP_CLI_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
