SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_PROFORMA_DETALLADO]
@CO_EMP_RUC CHAR(13)
,@CO_VEN_CED NCHAR(10)
,@CO_PRO_OPC CHAR(1)
,@CO_PRO_FEC1 DATETIME
,@CO_PRO_FEC2 DATETIME
AS
IF (@CO_PRO_OPC='T')
SELECT * FROM CO_VW_SELECT_REPORTE_PROFORMAS
WHERE (CO_PRO_EST = N'ACTIVA') AND CO_EMP_RUC=@CO_EMP_RUC AND
CO_PRO_FEC>=@CO_PRO_FEC1 AND
CO_PRO_FEC<=@CO_PRO_FEC2
ELSE IF (@CO_PRO_OPC='O')
SELECT * FROM CO_VW_SELECT_REPORTE_PROFORMAS
WHERE (CO_PRO_EST = N'ACTIVA') AND CO_EMP_RUC=@CO_EMP_RUC AND
CO_PRO_FEC>=@CO_PRO_FEC1 AND
CO_PRO_FEC<=@CO_PRO_FEC2
ELSE IF (@CO_PRO_OPC='V')
SELECT * FROM CO_VW_SELECT_REPORTE_PROFORMAS
WHERE (CO_PRO_EST = N'ACTIVA') AND CO_EMP_RUC=@CO_EMP_RUC AND CO_VEN_CED=@CO_VEN_CED AND
CO_PRO_FEC>=@CO_PRO_FEC1 AND
CO_PRO_FEC<=@CO_PRO_FEC2
GO
