SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CARGO]
@CO_EMP_RUC CHAR(13)
,@CO_CAR_COD INT
,@CO_CAR_NOM NVARCHAR(50)
,@CO_CAR_SUE FLOAT
AS
UPDATE [dbo].[CO_CARGO] SET
[CO_CAR_NOM]=@CO_CAR_NOM,
[CO_CAR_SUE]=@CO_CAR_SUE
WHERE 
CO_EMP_RUC=@CO_EMP_RUC AND CO_CAR_COD=@CO_CAR_COD
GO
