SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_RUBRO_EMPLEADO_ROL]
@CO_EMP_RUC CHAR(13)
,@CO_UBI_COD INT
AS
SELECT dbo.CO_RUBRO_EMPLEADO.CO_EMP_RUC, dbo.CO_RUBRO_EMPLEADO.PROF_COD, dbo.CO_RUBRO_EMPLEADO.CO_RUB_ROL_COD, 
dbo.CO_RUBRO_EMPLEADO.CO_RUB_EMP_VAL, dbo.CO_RUBROS_ROL.CO_RUB_ROL_VAL, dbo.PROFESOR.CO_UBI_COD
FROM dbo.CO_RUBRO_EMPLEADO INNER JOIN
dbo.CO_RUBROS_ROL ON dbo.CO_RUBRO_EMPLEADO.CO_RUB_ROL_COD = dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD AND 
dbo.CO_RUBRO_EMPLEADO.CO_EMP_RUC = dbo.CO_RUBROS_ROL.CO_EMP_RUC INNER JOIN
dbo.PROFESOR ON dbo.CO_RUBRO_EMPLEADO.PROF_COD = dbo.PROFESOR.PROF_COD
WHERE dbo.CO_RUBRO_EMPLEADO.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD
GO
