SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_CHEQUES_POSFECHADOS]
@CO_EMP_RUC CHAR(13),
@CO_DOC_VEN_CHE_FEC1 DATETIME,
@CO_DOC_VEN_CHE_FEC2 DATETIME,
@CO_CLI_COD NVARCHAR(50)
AS
SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM, 
dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE_VAL, 
dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE_NUM, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE_BAN, 
dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE_FEC
FROM dbo.CO_CLIENTE INNER JOIN
dbo.CO_DOCUMENTO_VENTA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD AND 
dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC AND 
dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_TIP_CLI_COD
WHERE dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC AND
dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE_FEC>=@CO_DOC_VEN_CHE_FEC1 AND dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_CHE_FEC<=@CO_DOC_VEN_CHE_FEC2 
AND dbo.CO_CLIENTE.CO_CLI_COD=CASE @CO_CLI_COD WHEN '' THEN dbo.CO_CLIENTE.CO_CLI_COD ELSE @CO_CLI_COD END
GO
