SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_DOCUMENTO_RESERVA]
@CO_EMP_RUC CHAR(13)
,@CO_DOC_VEN_NUM uniqueidentifier 

AS
	SELECT [CO_CLI_NOM]
		  ,[CO_CLI_COD]
		  ,[CO_CLI_CED]
		  ,[CO_CLI_TEL]
		  ,[CO_CLI_DIR]
		  ,[CO_CLI_CIU]
		  ,[CO_DOC_VEN_FEC]
		  ,[CO_DOC_VEN_TOT_LET]
		  ,[CO_DOC_VEN_TOT_NET]
		  ,[CO_DOC_VEN_POR_DES]
		  ,[CO_DOC_VEN_DES]
		  ,[CO_DOC_VEN_POR_IVA]
		  ,[CO_DOC_VEN_IVA]
		  ,[CO_DOC_VEN_TOT_PAG]
		  ,[CO_EMP_RUC]
		  ,[CO_DOC_VEN_NUM]
		  ,[CO_DET_DOC_VEN_ART_COD]
		  ,[CO_DET_DOC_VEN_ART_NOM]
		  ,[CO_DET_DOC_VEN_CAN]
		  ,[CO_DET_DOC_VEN_PRE]
		  ,[CO_DET_DOC_VEN_TOT]
		  ,[CO_EMP_NOM]
		  ,[CO_EMP_CIU]
		  ,[CO_EMP_DIR]
		  ,[CO_DOC_VEN_VAL_IVA0]
		  ,[CO_VEN_NOM]
		  ,[CO_DET_DOC_VEN_ART_BAR]
		  ,[CO_DOC_VEN_OTR]
		  ,[CO_DOC_VEN_DET]
		  ,[CO_CANTIDAD_EMPAQUE]
	FROM CO_VW_SELECT_REPORTE_DOCUMENTO_RESERVA
	WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_DOC_VEN_ID=@CO_DOC_VEN_NUM
GO
