SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_LISTAPRECIOS_ARTICULO]
@CO_EMP_RUC CHAR(13)
,@CO_ART_COD NVARCHAR(20)
AS
SELECT     dbo.CO_LISTA_PRECIO.Nombre, dbo.CO_TABLA_PRECIO.ListaDePrecioID, dbo.CO_TABLA_PRECIO.CO_EMP_RUC, 
                      dbo.CO_TABLA_PRECIO.CO_ART_COD, dbo.CO_TABLA_PRECIO.CO_TAB_PRE, CO_TAB_PRE_POR_ART, 'A' AS CO_ESTADO
					  , dbo.CO_TABLA_PRECIO.CO_TAB_PRE_MIN
FROM         dbo.CO_LISTA_PRECIO INNER JOIN
                      dbo.CO_TABLA_PRECIO ON dbo.CO_LISTA_PRECIO.ListaDePrecioID = dbo.CO_TABLA_PRECIO.ListaDePrecioID
where dbo.CO_TABLA_PRECIO.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_TABLA_PRECIO.CO_ART_COD=@CO_ART_COD
GO
