SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_UBICACION_GEOGRAFICA]
@CO_UBI_GEO_COD nvarchar(10)
,@CO_EMP_RUC char(13)
,@CO_UBI_GEO_DIV nvarchar(50)
,@CO_UBI_GEO_NOM nvarchar(50)
AS
INSERT INTO [dbo].[CO_UBICACION_GEOGRAFICA]
([CO_UBI_GEO_COD]
,[CO_EMP_RUC]
,[CO_UBI_GEO_DIV]
,[CO_UBI_GEO_NOM])
VALUES
(@CO_UBI_GEO_COD
,@CO_EMP_RUC
,@CO_UBI_GEO_DIV
,@CO_UBI_GEO_NOM)
GO
