SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CORRECION_HORARIO_CONTADOR]
@CO_COR_HOR_MES INT
,@CO_COR_HOR_ANO INT
,@CO_EMP_RUC CHAR(13)
AS
SELECT COUNT(*) FROM CO_CORRECION_HORARIO
WHERE CO_COR_HOR_MES=@CO_COR_HOR_MES  AND CO_COR_HOR_ANO=@CO_COR_HOR_ANO AND CO_EMP_RUC=@CO_EMP_RUC
GO
