SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_COMPROBANTE_BANCOS]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_COM_COD INT
,@CO_COM_NUM INT
,@CO_COMPRA_DOC_COM_NUM INT
,@CO_COMPRA_CUE_PAG_COD INT
AS
if(@CO_COM_NUM<>0)
SELECT CO_CON_BAN_NOM_BEN,CO_CON_BAN_FEC, CO_CON_BAN_VAL, CO_CON_BAN_VAL_LET
FROM dbo.CO_CONCILIACION
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_CONTABILIDAD_TIP_COM_COD=@CO_TIP_COM_COD
AND CO_CONTABILIDAD_COM_NUM=@CO_COM_NUM
else if(@CO_COMPRA_DOC_COM_NUM<>0)
SELECT CO_CON_BAN_NOM_BEN,CO_CON_BAN_FEC, CO_CON_BAN_VAL, CO_CON_BAN_VAL_LET
FROM dbo.CO_CONCILIACION
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_COMPRA_DOC_COM_NUM=@CO_COMPRA_DOC_COM_NUM
else
SELECT CO_CON_BAN_NOM_BEN,CO_CON_BAN_FEC, CO_CON_BAN_VAL, CO_CON_BAN_VAL_LET
FROM dbo.CO_CONCILIACION
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_COMPRA_CUE_PAG_COD=@CO_COMPRA_CUE_PAG_COD
GO
