SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_GRUPO_OCUPACIONAL]
@CO_GRU_OCU_COD int
,@CO_EMP_RUC char(13)
,@CO_GRU_OCU_NOM nvarchar(20)
AS
UPDATE [dbo].[CO_GRUPO_OCUPACIONAL] SET
[CO_GRU_OCU_NOM]=@CO_GRU_OCU_NOM
WHERE 
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_GRU_OCU_COD]=@CO_GRU_OCU_COD)
GO
