SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_COMPROBANTE_COMPRA]
@CO_TIP_COM_COM_COD int
,@CO_TIP_COM_COM_NOM nvarchar(150)
,@CO_TIP_COM_COM_FEC_VIG datetime
,@CO_TIP_COM_COM_INV char(1)
AS
UPDATE [dbo].[CO_TIPO_COMPROBANTE_COMPRA] SET
[CO_TIP_COM_COM_NOM]=@CO_TIP_COM_COM_NOM
,[CO_TIP_COM_COM_FEC_VIG]=@CO_TIP_COM_COM_FEC_VIG
,[CO_TIP_COM_COM_INV]=@CO_TIP_COM_COM_INV
WHERE
[CO_TIP_COM_COM_COD]=@CO_TIP_COM_COM_COD
GO
