SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CUENTASPORPAGAR_DETALLE_CHEQUES]
@CO_CUE_PAG_COD INT
AS
select *,'' as CO_CHE_BEN from dbo.CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE
where CO_CUE_PAG_COD=@CO_CUE_PAG_COD
GO
