SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_SELECT_BUSQUEDA_USUARIO_GRUPO]
@CO_GRU_COD CHAR(15)
AS
SELECT     dbo.USUARIO.USUA_COD, dbo.USUARIO.USUA_NOM, dbo.USUARIO.USUA_CLA, dbo.USUARIO.USUA_ALI, dbo.USUARIO.USUA_EST
FROM         dbo.CO_GRUPO INNER JOIN
                      dbo.CO_PERTENECE ON dbo.CO_GRUPO.CO_GRU_COD = dbo.CO_PERTENECE.CO_GRU_COD INNER JOIN
                      dbo.USUARIO ON dbo.CO_PERTENECE.USUA_COD = dbo.USUARIO.USUA_COD INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_GRUPO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE CO_GRUPO.CO_GRU_COD=@CO_GRU_COD
GO
