SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_DOCUMENTOS_PAGO_PENDIENTE_PAGADOS_PLUS]
@ESTADO_DOCUMENTO_PAGO nvarchar(9)
,@PAGADO_PENDIENTE_FORMA_PAGO nvarchar(50)
AS
SELECT     dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.CODIGO_DOCUMENTO_PAGO, 
                      dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.FECHA_DOCUMENTO_PAGO, 
                      dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.VALOR_TOTAL_DOCUMENTO_PAGO, 
                      dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.ESTADO_DOCUMENTO_PAGO, 
                      dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.PAGADO_PENDIENTE_FORMA_PAGO, dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.CO_PRO_COD, 
                      dbo.CO_PROVEEDOR.CO_PRO_NOM
FROM         dbo.CO_DOCUMENTO_PAGO_PROVEEDORES INNER JOIN
                      dbo.CO_PROVEEDOR ON dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.CO_PRO_COD = dbo.CO_PROVEEDOR.CO_PRO_COD
WHERE     (dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.ESTADO_DOCUMENTO_PAGO = @ESTADO_DOCUMENTO_PAGO) AND 
                      (dbo.CO_DOCUMENTO_PAGO_PROVEEDORES.PAGADO_PENDIENTE_FORMA_PAGO = @PAGADO_PENDIENTE_FORMA_PAGO)
GO
