SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_SERVICIOS_VARIOS_RESUMIDO]
@CO_EMP_RUC CHAR(13)
,@CO_SER_OPC CHAR(1)
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
,@CO_TIP_SER_COD INT
,@CO_VEN_CED NCHAR(10)
AS
IF (@CO_SER_OPC='N') 
SELECT CO_EMP_NOM,CO_EMP_CIU,CO_DET_DOC_VEN_ART_COD,CO_DET_DOC_VEN_ART_NOM,CO_TIP_SER_COD,CO_TIP_SER_NOM,
SUM(CO_DET_DOC_VEN_CAN) AS CANTIDAD,SUM(CO_DET_DOC_VEN_PRE * CO_DET_DOC_VEN_CAN) AS VALOR
,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_REPORET_SERVICIOS_VARIOS
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
GROUP BY CO_EMP_NOM, CO_EMP_CIU,CO_DET_DOC_VEN_ART_COD, 
CO_DET_DOC_VEN_ART_NOM, CO_TIP_SER_COD,CO_TIP_SER_NOM
ELSE IF (@CO_SER_OPC='T') 
SELECT CO_EMP_NOM,CO_EMP_CIU,CO_DET_DOC_VEN_ART_COD,CO_DET_DOC_VEN_ART_NOM,CO_TIP_SER_COD,CO_TIP_SER_NOM,
SUM(CO_DET_DOC_VEN_CAN) AS CANTIDAD,SUM(CO_DET_DOC_VEN_PRE*CO_DET_DOC_VEN_CAN) AS VALOR
,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_REPORET_SERVICIOS_VARIOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_TIP_SER_COD=@CO_TIP_SER_COD
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
GROUP BY CO_EMP_NOM, CO_EMP_CIU,CO_DET_DOC_VEN_ART_COD, 
CO_DET_DOC_VEN_ART_NOM, CO_TIP_SER_COD,CO_TIP_SER_NOM
ELSE IF (@CO_SER_OPC='V') 
SELECT CO_EMP_NOM,CO_EMP_CIU,CO_DET_DOC_VEN_ART_COD,CO_DET_DOC_VEN_ART_NOM,CO_TIP_SER_COD,CO_TIP_SER_NOM,
SUM(CO_DET_DOC_VEN_CAN) AS CANTIDAD,SUM(CO_DET_DOC_VEN_PRE*CO_DET_DOC_VEN_CAN) AS VALOR
,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_REPORET_SERVICIOS_VARIOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_VEN_CED=@CO_VEN_CED
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
GROUP BY CO_EMP_NOM, CO_EMP_CIU,CO_DET_DOC_VEN_ART_COD, 
CO_DET_DOC_VEN_ART_NOM, CO_TIP_SER_COD,CO_TIP_SER_NOM
GO
