SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIPO_DOCUMENTO_VENTA_PORID]
@CO_TIP_DOC_VEN_NUM int
AS
SELECT * FROM [dbo].[CO_TIPO_DOCUMENTO_VENTA] 
WHERE CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM
GO
