SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_COMPROBANTE_COMPRA]
@CO_TIP_COM_COM_COD INT,
@CO_TIP_COM_COM_NOM NVARCHAR(150),
@CO_TIP_OPC CHAR(1)
AS
IF(@CO_TIP_OPC='N')
BEGIN
DECLARE @LIKE AS VARCHAR(152)
SET @LIKE='%'+@CO_TIP_COM_COM_NOM+'%'
SELECT *
FROM CO_TIPO_COMPROBANTE_COMPRA     
WHERE CO_TIP_COM_COM_NOM LIKE @LIKE 
END
ELSE
SELECT *
FROM CO_TIPO_COMPROBANTE_COMPRA     
WHERE CO_TIP_COM_COM_COD=@CO_TIP_COM_COM_COD
GO
