SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PRESUPUESTO]
@CO_EMP_RUC char(13)
,@CO_ITE_PRE_COD int
,@CO_PRE_ANO int
,@CO_PRE_VAL_ACT float
,@CO_PRE_VAL_NUE float
AS
INSERT INTO [dbo].[CO_PRESUPUESTO]
([CO_EMP_RUC]
,[CO_ITE_PRE_COD]
,[CO_PRE_ANO]
,[CO_PRE_VAL_ACT]
,[CO_PRE_VAL_NUE])
VALUES
(@CO_EMP_RUC
,@CO_ITE_PRE_COD
,@CO_PRE_ANO
,@CO_PRE_VAL_ACT
,@CO_PRE_VAL_NUE)
GO
