SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CUENTA_CORRIENTE_CHEQUE]
@CO_EMP_RUC CHAR(13)
,@CO_CC_NUM VARCHAR(10)
AS
SELECT cast(isnull(dbo.CO_CUENTA_CORRIENTE.CO_CC_NUM_CHE,0) as int) as CO_CC_NUM_CHE
FROM dbo.CO_CUENTA_CORRIENTE
WHERE dbo.CO_CUENTA_CORRIENTE.CO_EMP_RUC=@CO_EMP_RUC AND
CO_CC_NUM=@CO_CC_NUM
GO
