SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_SELECT_VERICAR_GRUPO]
@CO_GRU_NOM VARCHAR(20),
@CO_EMP_RUC CHAR(13)
AS
SELECT COUNT(*) FROM CO_GRUPO
WHERE UPPER(CO_GRU_NOM)=UPPER(@CO_GRU_NOM) AND CO_EMP_RUC=@CO_EMP_RUC
GO
