SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PAGO_CUOTA]
@CO_FOR_PAG_COD int
,@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_PAG_COD int
,@CO_PAG_VAL int
,@CO_PAG_FEC datetime
,@CO_PAG_EST bit
,@CO_RUB_ROL_COD int
AS
UPDATE [dbo].[CO_PAGO_CUOTA] SET
[CO_PAG_VAL]=@CO_PAG_VAL
,[CO_PAG_FEC]=@CO_PAG_FEC
,[CO_PAG_EST]=@CO_PAG_EST
,CO_RUB_ROL_COD=@CO_RUB_ROL_COD
WHERE 
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_NOT_DEB_NUM]=@CO_NOT_DEB_NUM 
AND [CO_PAG_COD]=@CO_PAG_COD)
GO
