SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PRESUPUESTO]
@CO_PRE_ANO INT
,@CO_EMP_RUC CHAR(13)
AS
if @CO_PRE_ANO=0
SELECT * FROM CO_VW_SELECT_PRESUPUESTO
WHERE CO_ITE_PRE_CUE=1 
AND CO_EMP_RUC=@CO_EMP_RUC
else
SELECT * FROM CO_VW_SELECT_PRESUPUESTO
WHERE CO_ITE_PRE_CUE=1 
AND CO_PRE_ANO=@CO_PRE_ANO
AND CO_EMP_RUC=@CO_EMP_RUC
GO
