SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_DOCUMENTO_VENTA_ESTADO]
@CO_DOC_VEN_EST NVARCHAR(50),
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
AS
UPDATE CO_DOCUMENTO_VENTA SET CO_DOC_VEN_EST=@CO_DOC_VEN_EST
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID
GO
