SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_ALMACEN]
(@CO_EMP_RUC char(13)
,@CO_ALM_NOM nvarchar(100))
AS
INSERT INTO [dbo].[CO_ALMACEN]
([CO_EMP_RUC]
,[CO_ALM_NOM])
VALUES
(@CO_EMP_RUC
,@CO_ALM_NOM)
GO
