SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DOCUMENTO_VENTA_CONTADOR_PROFORMAS]
@CO_PROFORMA_ID INT
AS
select count(*) as facturadas from CO_DOCUMENTO_VENTA where CO_PROFORMA_ID=@CO_PROFORMA_ID
GO
