SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_PERMISO_CONTROL]
@CO_GRU_COD INT,
@PERM_NOM VARCHAR(80)
AS
SELECT   CONT_COD
FROM         PERMISO
WHERE CO_GRU_COD=@CO_GRU_COD AND PERM_NOM=@PERM_NOM
GO
