SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE PROC [dbo].[CO_SP_INSERT_DETALLE_DOCUMENTO_VENTA]
(@CO_DET_DOC_VEN_COD UNIQUEIDENTIFIER
,@CO_DOC_VEN_ID UNIQUEIDENTIFIER
,@CO_DET_DOC_VEN_ART_COD nvarchar(50)
,@CO_DET_DOC_VEN_ART_NOM nvarchar(50)
,@CO_DET_DOC_VEN_CAN float
,@CO_DET_DOC_VEN_PRE float
,@CO_DET_DOC_VEN_DES float
,@CO_DET_DOC_VEN_TOT float
,@CO_DET_DOC_VEN_TIP_ART bit
,@CO_DET_DOC_VEN_VAL_ICE float
,@CO_DET_DOC_VEN_POR_ICE float
,@CO_DET_DOC_VEN_IVA float
,@CO_DET_DOC_VEN_POR_IVA float
,@CO_DET_DOC_VEN_TIP_PRE nvarchar(50)
,@CO_DET_DOC_VEN_ART_BAR nvarchar(50)
,@CO_DET_DOC_VEN_ART_PRE_COS FLOAT
,@CO_BOD_COD INT
,@CO_CANTIDAD_EMPAQUE float)
AS
INSERT INTO [dbo].[CO_DETALLE_DOCUMENTO_VENTA]
(CO_DET_DOC_VEN_COD
,CO_DOC_VEN_ID
,[CO_DET_DOC_VEN_ART_COD]
,[CO_DET_DOC_VEN_ART_NOM]
,[CO_DET_DOC_VEN_CAN]
,[CO_DET_DOC_VEN_PRE]
,[CO_DET_DOC_VEN_DES]
,[CO_DET_DOC_VEN_TOT]
,[CO_DET_DOC_VEN_TIP_ART]
,[CO_DET_DOC_VEN_VAL_ICE]
,[CO_DET_DOC_VEN_POR_ICE]
,[CO_DET_DOC_VEN_IVA]
,[CO_DET_DOC_VEN_POR_IVA]
,[CO_DET_DOC_VEN_TIP_PRE]
,[CO_DET_DOC_VEN_ART_BAR]
,[CO_DET_DOC_VEN_ART_PRE_COS]
,CO_BOD_COD
,CO_CANTIDAD_EMPAQUE)
VALUES
(@CO_DET_DOC_VEN_COD
,@CO_DOC_VEN_ID
,@CO_DET_DOC_VEN_ART_COD
,@CO_DET_DOC_VEN_ART_NOM
,@CO_DET_DOC_VEN_CAN
,@CO_DET_DOC_VEN_PRE
,@CO_DET_DOC_VEN_DES
,@CO_DET_DOC_VEN_TOT
,@CO_DET_DOC_VEN_TIP_ART
,@CO_DET_DOC_VEN_VAL_ICE
,@CO_DET_DOC_VEN_POR_ICE
,@CO_DET_DOC_VEN_IVA
,@CO_DET_DOC_VEN_POR_IVA
,@CO_DET_DOC_VEN_TIP_PRE
,@CO_DET_DOC_VEN_ART_BAR
,@CO_DET_DOC_VEN_ART_PRE_COS
,@CO_BOD_COD
,@CO_CANTIDAD_EMPAQUE)













GO
