SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PAGO_CUOTA_SALDO]
@CO_EMP_RUC CHAR(13)
,@PROF_COD CHAR(10)
,@CO_PAG_MES INT
,@CO_PAG_ANO INT
AS
UPDATE CO_PAGO_CUOTA
SET CO_PAG_VAL=0
WHERE CO_EMP_RUC=@CO_EMP_RUC AND PROF_COD=@PROF_COD
AND MONTH(CO_PAG_FEC)=@CO_PAG_MES AND YEAR(CO_PAG_FEC)=@CO_PAG_ANO
GO
