SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_CADUCIDAD]
@CO_EMP_RUC CHAR(13)
,@CO_ART_COD nvarchar(40)
,@CO_ALM_COD nvarchar(20)
,@CO_TIP_ART_COD nvarchar(40)
,@CO_FAM_ART_COD int
AS
SELECT * FROM CO_VW_SELECT_REPORTE_CADUCIDAD
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
CO_ART_COD=case @CO_ART_COD when '' then CO_ART_COD else @CO_ART_COD end  AND
CO_ALM_COD=case @CO_ALM_COD when 0 then CO_ALM_COD else CO_ALM_COD end  AND
CO_TIP_ART_COD=case @CO_TIP_ART_COD when '' then CO_TIP_ART_COD else @CO_TIP_ART_COD end  AND
CO_FAM_ART_COD=case @CO_FAM_ART_COD when 0 then CO_FAM_ART_COD else @CO_FAM_ART_COD end
GO
