SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FORMULARIO_1041]
@CO_IMP_ANO INT
,@CO_IMP_MES INT
,@CO_EMP_RUC CHAR(13)
AS
SELECT 
(SELECT COUNT(CO_DOC_COM_NUM) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS NUM_FACTURAS,
(SELECT COUNT(CO_DOC_COM_NUM) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=2 AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS NUM_NOTASVENTA,
(SELECT COUNT(CO_DOC_COM_NUM) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=4 AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS NUM_NOTASCREDITO,
(SELECT COUNT(CO_DOC_COM_NUM) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=5 AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS NUM_NOTASDEBITO,
(SELECT SUM(CO_DOC_COM_TOT_NET) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND (CO_TIP_SUS_COD='06' OR CO_TIP_SUS_COD='07') AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS IVABIENES12,
(SELECT SUM(CO_DOC_COM_VAL_IVA0) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND (CO_TIP_SUS_COD='06' OR CO_TIP_SUS_COD='07') AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS IVABIENES0,
(SELECT SUM(CO_DOC_COM_TOT_NET) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND (CO_TIP_SUS_COD='01' OR CO_TIP_SUS_COD='02') AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS IVASERVICIOS12,
(SELECT SUM(CO_DOC_COM_VAL_IVA0) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND (CO_TIP_SUS_COD='01' OR CO_TIP_SUS_COD='02') AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS IVASERVICIOS0,
(SELECT SUM(CO_DOC_COM_TOT_NET) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND (CO_TIP_SUS_COD='04' OR CO_TIP_SUS_COD='05') AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS IVAACTIVOS12,
(SELECT SUM(CO_DOC_COM_VAL_IVA0) FROM dbo.CO_DOCUMENTO_COMPRA WHERE CO_TIP_COM_COM_COD=1 AND (CO_TIP_SUS_COD='04' OR CO_TIP_SUS_COD='05') AND CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_DOC_COM_EST='ACTIVA') AS IVAACTIVOS0
FROM dbo.CO_DOCUMENTO_COMPRA
where MONTH(CO_DOC_COM_FEC_REG)=@CO_IMP_MES AND YEAR(CO_DOC_COM_FEC_REG)=@CO_IMP_ANO AND CO_EMP_RUC=@CO_EMP_RUC
GO
