SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_ACTIVOS_FIJOS]
@CO_EMP_RUC CHAR(13),
@CO_TIP_ACT_COD INT,
@CO_UBI_COD INT,
@CO_ACT_FIJ_OPC CHAR(1),
@CO_ACT_FIJ_EST BIT
AS
IF @CO_ACT_FIJ_OPC='U'
	begin
		SELECT CO_ACT_FIJ_COD,CO_CUE_COD,CO_ACT_FIJ_NOM,CO_ACT_FIJ_FEC_COM,CO_ACT_FIJ_NUM_FAC,CO_TIP_ACT_NOM,CO_UBI_NOM,CO_ACT_FIJ_VAL_ADQ,CO_ACT_FIJ_CAN,CO_ACT_FIJ_NOM_PRO,CO_EMP_NOM,CO_ACT_FIJ_DEP_ACU,CO_ACT_FIJ_VAL_ACT
		FROM CO_VW_SELECT_REPORTE_ACTIVOS_FIJOS
		WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_UBI_COD=@CO_UBI_COD AND CO_ACT_FIJ_EST=@CO_ACT_FIJ_EST
	end
else
	begin
		if @CO_ACT_FIJ_OPC='T'
			begin
				SELECT CO_ACT_FIJ_COD,CO_CUE_COD,CO_ACT_FIJ_NOM,CO_ACT_FIJ_FEC_COM,CO_ACT_FIJ_NUM_FAC,CO_TIP_ACT_NOM,CO_UBI_NOM,CO_ACT_FIJ_VAL_ADQ,CO_ACT_FIJ_CAN,CO_ACT_FIJ_NOM_PRO,CO_EMP_NOM,CO_ACT_FIJ_DEP_ACU,CO_ACT_FIJ_VAL_ACT
				FROM CO_VW_SELECT_REPORTE_ACTIVOS_FIJOS
				WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_TIP_ACT_COD=@CO_TIP_ACT_COD AND CO_ACT_FIJ_EST=@CO_ACT_FIJ_EST
			end
		else
			begin
				if @CO_ACT_FIJ_OPC='D'
					begin
						SELECT CO_ACT_FIJ_COD,CO_CUE_COD,CO_ACT_FIJ_NOM,CO_ACT_FIJ_FEC_COM,CO_ACT_FIJ_NUM_FAC,CO_TIP_ACT_NOM,CO_UBI_NOM,CO_ACT_FIJ_VAL_ADQ,CO_ACT_FIJ_CAN,CO_ACT_FIJ_NOM_PRO,CO_EMP_NOM,CO_ACT_FIJ_DEP_ACU,CO_ACT_FIJ_VAL_ACT
						FROM CO_VW_SELECT_REPORTE_ACTIVOS_FIJOS
						WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_ACT_FIJ_EST=@CO_ACT_FIJ_EST
					end
			end
	end
GO
