SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TRANSACCION_FECHA]
@CO_EMP_RUC CHAR(13),
@CO_TRA_ANO INT,
@CO_TRA_MES INT,
@CO_RUB_ROL_COD INT,
@CO_UBI_COD INT
AS
SELECT dbo.CO_TRANSACCION.CO_EMP_RUC, dbo.CO_TRANSACCION.CO_RUB_ROL_COD, dbo.CO_TRANSACCION.PROF_COD, 
dbo.CO_TRANSACCION.CO_TRA_VAL, dbo.CO_TRANSACCION.CO_TRA_USU_ALI,dbo.CO_TRANSACCION.CO_TRA_MES,dbo.CO_TRANSACCION.CO_TRA_ANO
FROM dbo.CO_TRANSACCION INNER JOIN
dbo.PROFESOR ON dbo.CO_TRANSACCION.PROF_COD = dbo.PROFESOR.PROF_COD
WHERE dbo.CO_TRANSACCION.CO_EMP_RUC=@CO_EMP_RUC AND
dbo.CO_TRANSACCION.CO_TRA_MES=@CO_TRA_MES AND
dbo.CO_TRANSACCION.CO_TRA_ANO=@CO_TRA_ANO AND
dbo.CO_TRANSACCION.CO_RUB_ROL_COD=@CO_RUB_ROL_COD AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD
GO
