SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_DETALLE_PROFORMA]
(@CO_DET_PRO_COD int)
AS
DELETE [dbo].[CO_DETALLE_PROFORMA] 
WHERE
([CO_DET_PRO_COD]=@CO_DET_PRO_COD)
GO
