SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_PROFESOR]
@CO_EMP_RUC CHAR(13)
AS
SELECT PROF_COD AS CODIGO,PROF_APE+' '+PROF_NOM AS NOMBRE
FROM PROFESOR
where CO_EMP_RUC=@CO_EMP_RUC and PROF_EST='Activo'
GO
