SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_SALDO_ANTERIOR_EMPLEADO]
@co_emp_ruc CHAR(13),
@CO_SAL_FEC DATETIME
AS
declare @pagos float
declare @cobro float
SELECT @pagos=sUM(dbo.CO_PAGO_CUOTA.CO_PAG_VAL_IMP)
FROM dbo.CO_PAGO_CUOTA INNER JOIN
dbo.CO_NOTA_DEBITO ON dbo.CO_PAGO_CUOTA.CO_EMP_RUC = dbo.CO_NOTA_DEBITO.CO_EMP_RUC AND 
dbo.CO_PAGO_CUOTA.CO_NOT_DEB_NUM = dbo.CO_NOTA_DEBITO.CO_NOT_DEB_NUM
where dbo.CO_NOTA_DEBITO.CO_EMP_RUC=@co_emp_ruc and 
dbo.CO_NOTA_DEBITO.CO_NOT_DEB_FEC<=@CO_SAL_FEC
SELECT @cobro=SUM(dbo.CO_DETALLE_COBRO.CO_DET_COB_VAL) 
FROM dbo.CO_DETALLE_COBRO INNER JOIN
dbo.CO_COMPROBANTE_COBRO ON dbo.CO_DETALLE_COBRO.CO_COM_COB_NUM = dbo.CO_COMPROBANTE_COBRO.CO_COM_COB_NUM AND 
dbo.CO_DETALLE_COBRO.CO_EMP_RUC = dbo.CO_COMPROBANTE_COBRO.CO_EMP_RUC
where dbo.CO_COMPROBANTE_COBRO.CO_EMP_RUC=@co_emp_ruc and 
dbo.CO_COMPROBANTE_COBRO.CO_COM_COB_FEC<=@CO_SAL_FEC

select @pagos-@cobro as saldo_anterior,prof_cod from profesor
GO
