SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CONCEPTO_AIR]
@CO_CON_AIR_COD int
,@CO_CON_AIR_NOM nvarchar(100)
,@CO_CON_AIR_POR FLOAT
,@CO_CON_AIR_CUE_COM nvarchar(40)
,@CO_CON_AIR_CUE_VEN nvarchar(40)
,@CO_EMP_RUC char(13)
,@CO_CON_AIR_COD_SRI nvarchar(20)
AS
UPDATE [dbo].[CO_CONCEPTO_AIR] SET
[CO_CON_AIR_NOM]=@CO_CON_AIR_NOM
,[CO_CON_AIR_POR]=@CO_CON_AIR_POR
,CO_CON_AIR_CUE_COM=@CO_CON_AIR_CUE_COM
,CO_CON_AIR_CUE_VEN=@CO_CON_AIR_CUE_VEN
,CO_CON_AIR_COD_SRI=@CO_CON_AIR_COD_SRI
WHERE [CO_CON_AIR_COD]=@CO_CON_AIR_COD and @CO_EMP_RUC=@CO_EMP_RUC
GO
