SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_UPDATE_CUENTA_CONTABLE]
@CO_EMP_RUC char(13),
@CO_CUE_COD varchar(40),
@CO_CUE_NOM varchar(60),
@CO_CUE_USU_ALI varchar(15)
as
UPDATE CO_CUENTA SET CO_CUE_NOM=@CO_CUE_NOM,CO_CUE_USU_ALI=@CO_CUE_USU_ALI
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CUE_COD=@CO_CUE_COD
GO
