SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_MES_SALDO]
@CO_EMP_RUC char(13)
,@CO_CUE_COD varchar(40)
,@CO_MES_NUM int
,@CO_ANIO_NUM int
AS
DELETE [dbo].[CO_MES_SALDO] 
     WHERE
           CO_EMP_RUC=@CO_EMP_RUC
			AND CO_CUE_COD=@CO_CUE_COD
			AND CO_MES_NUM=@CO_MES_NUM AND CO_ANIO_NUM=@CO_ANIO_NUM
GO
