SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_RECURSO]
        (@CO_TIP_REC_COD int
           ,@CO_EMP_RUC char(13))
AS
DELETE [dbo].[CO_TIPO_RECURSO]
     WHERE
           [CO_TIP_REC_COD]=@CO_TIP_REC_COD
           AND [CO_EMP_RUC]=@CO_EMP_RUC
GO
