SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_MES_LIQUIDACION_ESTADO]
@CO_MES_LIQ_NUM int
,@CO_ANIO_LIQ_NUM int
,@CO_EMP_RUC char(13)
AS
UPDATE [dbo].[CO_MES_LIQUIDACION] SET
CO_MES_LIQ_CON_EST=1
WHERE 
(CO_MES_LIQ_NUM=@CO_MES_LIQ_NUM
AND CO_ANIO_LIQ_NUM=@CO_ANIO_LIQ_NUM
AND CO_EMP_RUC=@CO_EMP_RUC)
GO
