SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_ARTICULO]
			@CO_ART_COD nvarchar(20)
           ,@CO_EMP_RUC char(13)
AS


--DELETE dbo.CO_UBICACIONARTICULO
--WHERE CO_ART_COD=@CO_ART_COD AND CO_EMP_RUC=@CO_EMP_RUC

--DELETE dbo.CO_TABLA_PRECIO
--WHERE CO_ART_COD=@CO_ART_COD AND CO_EMP_RUC=@CO_EMP_RUC


--DELETE [dbo].[CO_ARTICULO] 
--     WHERE ([CO_ART_COD]=@CO_ART_COD
--           AND [CO_EMP_RUC]=@CO_EMP_RUC)
UPDATE dbo.CO_ARTICULO SET co_art_est='ANULADO' WHERE ([CO_ART_COD]=@CO_ART_COD AND [CO_EMP_RUC]=@CO_EMP_RUC)

GO
