SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_CLIENTES]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_CLI_COD NVARCHAR(10)
,@CO_CLI_CIU NVARCHAR(20)
,@CO_CLI_EST NVARCHAR(10)
AS
SELECT dbo.CO_CLIENTE.CO_CLI_COD, dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_CLIENTE.CO_CLI_TEL, dbo.CO_CLIENTE.CO_CLI_CON, 
dbo.CO_CLIENTE.CO_CLI_DIR, dbo.CO_CLIENTE.CO_CLI_CED, dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_NOM, dbo.CO_EMPRESA.CO_EMP_NOM, 
dbo.CO_EMPRESA.CO_EMP_CIU, dbo.CO_EMPRESA.CO_EMP_DIR,dbo.CO_CLIENTE.CO_CLI_CIU
FROM dbo.CO_CLIENTE INNER JOIN
dbo.CO_TIPO_CLIENTE ON dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_COD AND 
dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_TIPO_CLIENTE.CO_EMP_RUC INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_TIPO_CLIENTE.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_TIPO_CLIENTE.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_CLIENTE.CO_CLI_EST=@CO_CLI_EST AND
dbo.CO_CLIENTE.CO_TIP_CLI_COD=CASE @CO_TIP_CLI_COD WHEN '' THEN dbo.CO_CLIENTE.CO_TIP_CLI_COD ELSE @CO_TIP_CLI_COD END AND
dbo.CO_CLIENTE.CO_CLI_CIU=CASE @CO_CLI_CIU WHEN '' THEN dbo.CO_CLIENTE.CO_CLI_CIU ELSE @CO_CLI_CIU END
GO
