SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_PROVEEDOR]
@CO_TIP_PRO_COD nvarchar(10)
,@CO_EMP_RUC char(13)
,@CO_TIP_PRO_NOM nvarchar(50)
,@CO_TIP_PRO_CUE_CON varchar(40)
AS
UPDATE [dbo].[CO_TIPO_PROVEEDOR] SET
[CO_TIP_PRO_NOM]=@CO_TIP_PRO_NOM,
[CO_TIP_PRO_CUE_CON]=@CO_TIP_PRO_CUE_CON
WHERE [CO_TIP_PRO_COD]=@CO_TIP_PRO_COD AND [CO_EMP_RUC]=@CO_EMP_RUC
GO
