SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CORRECCION_HORAS]
@CO_UBI_COD INT,
@CO_EMP_RUC CHAR(13),
@CO_MES INT,
@CO_ANIO INT
AS
begin
declare @contador int
declare @contador2 int
SELECT @contador=count(*) FROM CO_VW_SELECT_CORRECCION_HORARIA WHERE CO_UBI_COD=@CO_UBI_COD AND CO_EMP_RUC=@CO_EMP_RUC and MES=@CO_MES AND ANIO=@CO_ANIO
SELECT @contador2=COUNT(*) FROM dbo.PROFESOR LEFT OUTER JOIN dbo.CO_REGISTRO_DIARIO ON dbo.PROFESOR.PROF_COD = dbo.CO_REGISTRO_DIARIO.PROF_COD WHERE dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD AND MONTH(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_FEC)=@CO_MES and YEAR(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_FEC)=@CO_ANIO 
if @contador>0
SELECT PROF_COD, EMPLEADO, Horas_Laboradas, Horas_Extras, Horas_Suplementarias,MES,ANIO,CO_EMP_RUC FROM CO_VW_SELECT_CORRECCION_HORARIA 
WHERE CO_UBI_COD=@CO_UBI_COD AND CO_EMP_RUC=@CO_EMP_RUC and MES=@CO_MES AND ANIO=@CO_ANIO
else IF @contador2>0
SELECT dbo.PROFESOR.PROF_COD, dbo.PROFESOR.PROF_APE+' '+dbo.PROFESOR.PROF_NOM AS EMPLEADO, SUM(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_HOR_LAB) AS Horas_Laboradas, SUM(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_HOR_EXT) AS Horas_Extras, SUM(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_HOR_SUP) AS Horas_Suplementarias,cast('0' as int) AS MES,cast('0' as int) AS ANIO,dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC
FROM dbo.PROFESOR LEFT OUTER JOIN dbo.CO_REGISTRO_DIARIO ON dbo.PROFESOR.PROF_COD = dbo.CO_REGISTRO_DIARIO.PROF_COD
WHERE dbo.PROFESOR.PROF_EST='Activo' and dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD AND MONTH(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_FEC)=@CO_MES and YEAR(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_FEC)=@CO_ANIO 
GROUP BY dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC,dbo.PROFESOR.PROF_COD, dbo.PROFESOR.PROF_APE, dbo.PROFESOR.PROF_NOM
ELSE
SELECT PROF_COD,EMPLEADO, Horas_Laboradas, Horas_Extras, Horas_Suplementarias,MES,ANIO,CO_EMP_RUC
FROM CO_VW_SELECT_HORAS_VACIAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_UBI_COD=@CO_UBI_COD 
end
GO
