SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_REPORTE_CHEQUES_PLUS]
@CODIGO_DOCUMENTO_PAGO int
AS
SELECT     dbo.CO_PAGO_PROVEEDORES_PLUS.CODIGO_DOCUMENTO_PAGO, dbo.CO_PAGO_PROVEEDORES_PLUS.VALOR_PAGO_PROVEEDOR, 
                      dbo.CO_PAGO_PROVEEDORES_PLUS.FECHA_PAGO_PROVEEDOR, dbo.CO_PAGO_PROVEEDORES_PLUS.VALOR_PAGADO_EN_NUMEROS, 
                      dbo.CO_PROVEEDOR.CO_PRO_NOM, dbo.CO_PAGO_PROVEEDORES_PLUS.NUMERO_PAGO_PROVEEDOR
FROM         dbo.CO_PAGO_PROVEEDORES_PLUS INNER JOIN
                      dbo.CO_PROVEEDOR ON dbo.CO_PAGO_PROVEEDORES_PLUS.CO_PRO_COD = dbo.CO_PROVEEDOR.CO_PRO_COD
WHERE     (dbo.CO_PAGO_PROVEEDORES_PLUS.CODIGO_DOCUMENTO_PAGO = @CODIGO_DOCUMENTO_PAGO) AND 
                      (dbo.CO_PAGO_PROVEEDORES_PLUS.ESTADO_PAGO_PROVEEDOR = 'PENDIENTE')
GO
