SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_DETALLE_RETENCION]
@CO_DET_RET_ID UNIQUEIDENTIFIER
,@CO_TIP_RET_NOM nvarchar(150)
,@CO_TIP_RET_COD_SRI varchar(20)
,@CO_RET_BAS float
,@CO_RET_DET_COD nvarchar(50)
,@CO_RET_POR float
,@CO_RET_VAL float
,@CO_RET_DET_CUE nvarchar(40)
,@CO_RET_DET_IMP NVARCHAR(20)
,@CO_TIP_RET_COD int
AS
UPDATE [dbo].[CO_DETALLE_RETENCION] SET
[CO_TIP_RET_NOM]=@CO_TIP_RET_NOM
,[CO_TIP_RET_COD_SRI]=@CO_TIP_RET_COD_SRI
,[CO_RET_BAS]=@CO_RET_BAS
,[CO_RET_DET_COD]=@CO_RET_DET_COD
,[CO_RET_POR]=@CO_RET_POR
,[CO_RET_VAL]=@CO_RET_VAL
,[CO_RET_DET_CUE]=@CO_RET_DET_CUE
,[CO_RET_DET_IMP]=@CO_RET_DET_IMP
,[CO_TIP_RET_COD]=@CO_TIP_RET_COD
WHERE
CO_DET_RET_ID=@CO_DET_RET_ID

GO
