SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CUENTA_POR_PAGAR_DETALLE]
@CO_DOC_COM_NUM int,
@CO_EMP_RUC char(13),
@CO_CUE_PAG_COD int,
@CO_CUE_PAG_DET_VAL float
as
insert into dbo.CO_CUENTA_POR_PAGAR_DETALLE values(
@CO_DOC_COM_NUM,
@CO_EMP_RUC,
@CO_CUE_PAG_COD,
@CO_CUE_PAG_DET_VAL)
GO
