SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_COMPROBANTE_EMPRESA]
@CO_EMP_RUC CHAR(13)
AS
SELECT COUNT(CO_COM_NUM) AS CONTADOR
FROM CO_COMPROBANTE
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
