SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_LIBRO_BANCO_PLUS]
@FECHAINICIO datetime
,@FECHAFIN datetime
,@CO_CC_NUM varchar(10)
AS
SELECT     CODIGO_LIBRO_BANCO, CO_CC_NUM, NUMERO_RESIBO_LIBRO_BANCO, TIPO_TRANSACCION_LIBRO_BANCO, 
                      DETALLE_TRANSACCION_LIBRO_BANCO, VALOR_INGRESO_LIBRO_BANCO, VALOR_EGRESO_LIBRO_BANCO, FECHA_TRANSACCION_LIBRO_BANCO,
                       AGENCIA_LIBRO_BANCO, PAGADO_PENDIENTE_LIBRO_BANCO
FROM         dbo.CO_LIBRO_BANCO
WHERE     (FECHA_TRANSACCION_LIBRO_BANCO >= @FECHAINICIO) AND (FECHA_TRANSACCION_LIBRO_BANCO <= @FECHAFIN) AND 
                      (CO_CC_NUM = @CO_CC_NUM) AND (ESTADO_TRANSACCION_LIBRO_BANCO = 'ACTIVA') AND (TIPO_TRANSACCION_LIBRO_BANCO = 'CH') AND 
                      (PAGADO_PENDIENTE_LIBRO_BANCO = 'FALSE')
GO
