SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CONCILIACION_BANCARIA]
@CO_CC_NUM VARCHAR(10),
@CO_EMP_RUC CHAR(13),
@CO_CON_BAN_FEC DATETIME
AS
SELECT Convert(varchar(10),CO_CON_BAN_FEC,103) AS FECHA,
CO_TIP_TRA_COD AS TRANSACCION,
CO_CON_BAN_TRA_NUM AS DOCUMENTO,
CO_CONTABILIDAD_TIP_COM_COD AS COMPROBANTE,
CONVERT(VARCHAR(20),CO_CONTABILIDAD_COM_NUM,10) AS NUMERO,
CO_COMPRA_DOC_COM_NUM AS NUMERO_COMPRA,
CO_COMPRA_CUE_PAG_COD AS NUMERO_CUENTAS_POR_PAGAR,
CO_CON_BAN_VAL AS VALOR,CO_CON_BAN_CON AS ESTADO,
CO_CON_BAN_COD AS CODIGO,
CO_TIP_TRA_OPE AS OPERACION
FROM CO_VW_SELECT_CONCILIACION_DIARIO
WHERE CO_CC_NUM=@CO_CC_NUM AND CO_EMP_RUC=@CO_EMP_RUC AND 
Convert(varchar(10),CO_CON_BAN_FEC,102)<=Convert(varchar(10),@CO_CON_BAN_FEC,102) AND CO_CON_BAN_CON=0
UNION 
SELECT Convert(varchar(10),FECHA,103) AS FECHA,
TRANSACCION,
DOCUMENTO,
COMPROBANTE,NUMERO,
CAST('0' AS INT) AS NUMERO_COMPRA,
CAST('0' AS INT) AS NUMERO_CUENTAS_POR_PAGAR
,VALOR,ESTADO,CODIGO,OPERACION
FROM CO_VW_SELECT_MOVIMIENTO_NOCONCILIADO
WHERE CO_CC_NUM=@CO_CC_NUM AND CO_EMP_RUC=@CO_EMP_RUC AND 
Convert(varchar(10),FECHA,103)
<=Convert(varchar(10),@CO_CON_BAN_FEC,103) AND ESTADO=0
GO
