SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_DETALLE_RETENCION_COMPRA]
@CO_DOC_COM_NUM int
,@CO_DOC_COM_TIP nvarchar(50)
,@CO_EMP_RUC char(13)
,@CO_TIP_RET_COD varchar(10)
AS
DELETE [dbo].[CO_DETALLE_RETENCION_COMPRA]
WHERE
([CO_DOC_COM_NUM]=@CO_DOC_COM_NUM
AND [CO_DOC_COM_TIP]=@CO_DOC_COM_TIP
AND [CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_TIP_RET_COD]=@CO_TIP_RET_COD)
GO
