SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_ROL_TEMP]
@CO_EMP_RUC char(13)
,@PROF_COD CHAR(10)
,@CO_RUB_ROL_VAL FLOAT
AS
UPDATE [dbo].[CO_ROL_TEMP] SET
CO_RUB_ROL_VAL=@CO_RUB_ROL_VAL
WHERE [CO_EMP_RUC]=@CO_EMP_RUC AND PROF_COD=@PROF_COD
GO
