SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PAGOS_DOCUMENTO_COMPRA]
@CO_EMP_RUC CHAR(13),
@CO_PRO_COD NVARCHAR(20)
AS
SELECT CO_PAG_PRO_COD,CO_PAG_PRO_CON,CONVERT(NVARCHAR(10),CO_PAG_PRO_FEC,101) AS CO_PAG_PRO_FEC,CO_DOC_COM_NUM,CO_PAG_PRO_VAL,CO_PAG_PRO_VAL_IMP
FROM CO_VW_SELECT_PAGOS_DOCUMENTO_COMPRA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PAG_PRO_EST=0 AND CO_PRO_COD=@CO_PRO_COD
GO
