SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_ESTADO_CUENTA_PROVEEDOR_RESUMEN]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_PRO_COD NVARCHAR(10)
,@CO_PRO_COD NVARCHAR(10)
,@CO_DOC_COM_FEC1 DATETIME
,@CO_DOC_COM_FEC2 DATETIME
AS
SELECT CO_PRO_COD, CO_PRO_NOM, SUM(CO_PAG_PRO_VAL) AS ABONOS, SUM(CO_FACTURAS) AS COMPRAS, CO_EMP_NOM
,@CO_DOC_COM_FEC1 AS DESDE,@CO_DOC_COM_FEC2 AS HASTA
FROM dbo.CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR
WHERE 
CO_EMP_RUC=@CO_EMP_RUC AND
CO_FEC_DOC>=@CO_DOC_COM_FEC1 AND
CO_FEC_DOC<=@CO_DOC_COM_FEC2 AND 
CO_TIP_PRO_COD=case @CO_TIP_PRO_COD when '' then CO_TIP_PRO_COD else @CO_TIP_PRO_COD end  AND
CO_PRO_COD=case @CO_PRO_COD when '' then CO_PRO_COD else @CO_PRO_COD end 
GROUP BY CO_PRO_NOM, CO_PRO_COD, CO_EMP_NOM,CO_PRO_CUE
GO
