SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_DATOS_PROFESOR]
@PROF_COD CHAR(10)
AS
DECLARE 
@PARA_NOM_COL AS VARCHAR(100),
@PARA_ANO_LEC AS VARCHAR(10),
@PARA_NOM_REC AS VARCHAR(60),
@PARA_NOM_SEC AS VARCHAR(60),
@PARA_NOM_CIU AS VARCHAR(50)
SELECT @PARA_NOM_COL=nom_insti,@PARA_ANO_LEC=año_lecti,@PARA_NOM_REC=nom_recto,@PARA_NOM_SEC=nom_secre,@PARA_NOM_CIU=nom_ciu
FROM funcion_prueba()

SELECT * ,
@PARA_NOM_COL AS COLEGIO,@PARA_NOM_CIU AS CIUDAD 
FROM PROFESOR
WHERE PROF_COD=@PROF_COD
GO
