SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_MOVIMIENTO_NOCONCILIADO]
@CO_TIP_TRA_COD char(2),
@CO_EMP_RUC char(13),
@CO_CC_NUM varchar(10),
@CO_MOV_NOC_BEN varchar(50),
@CO_MOV_NOC_FEC_PAG datetime,
@CO_MOV_NOC_NUM_DOC varchar(10),
@CO_MOV_NOC_MON float,
@CO_COM_NUM char(3),
@CO_MOV_NOC_EST bit,
@CO_TIP_COM_NOM varchar(20),
@CO_MOV_NOC_OPE char(1),
@CO_MOV_NOC_COD INT
AS
UPDATE [dbo].[CO_MOVIENTO_NOCONCILIADO]
SET 
CO_TIP_TRA_COD=@CO_TIP_TRA_COD,
CO_MOV_NOC_BEN=@CO_MOV_NOC_BEN,
CO_MOV_NOC_FEC_PAG=@CO_MOV_NOC_FEC_PAG,
CO_MOV_NOC_NUM_DOC=@CO_MOV_NOC_NUM_DOC,
CO_MOV_NOC_MON=@CO_MOV_NOC_MON,
CO_COM_NUM=@CO_COM_NUM,
@CO_MOV_NOC_EST=@CO_MOV_NOC_EST,
CO_TIP_COM_NOM=@CO_TIP_COM_NOM,
CO_MOV_NOC_OPE=@CO_MOV_NOC_OPE
WHERE 
CO_EMP_RUC=@CO_EMP_RUC AND
CO_CC_NUM=@CO_CC_NUM AND
CO_MOV_NOC_COD=@CO_MOV_NOC_COD
GO
