SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_DETALLE_DOCUMENTO_PAGO_PLUS]
@CODIGO_DOCUMENTO_PAGO int
AS
SELECT     CODIGO_DETALLE_DOCUMENTO_PAGO, CODIGO_DOCUMENTO_PAGO, CO_DOC_COM_NUM, VALOR_FACTURA_COMPRA, 
                      NUMERO_FACTURA_COMPRA
FROM         dbo.CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES
WHERE     (CODIGO_DOCUMENTO_PAGO = @CODIGO_DOCUMENTO_PAGO)
GO
