SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_SEGURIDADES_EMPRESA]
@CO_EMP_RUC char(13)
as
delete from PERMISO where CO_GRU_COD in (select CO_GRU_COD from CO_GRUPO where CO_EMP_RUC=@CO_EMP_RUC)
delete from CO_PERTENECE where CO_GRU_COD in (select CO_GRU_COD from CO_GRUPO where CO_EMP_RUC=@CO_EMP_RUC)
delete CO_GRUPO where CO_EMP_RUC=@CO_EMP_RUC

GO
