SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create PROC [dbo].[CO_SP_SELECT_REPORTE_SALDOS_FECHA_CLIENTE]
@CO_DOC_COM_FEC_EMI DATETIME
,@CO_EMP_RUC CHAR(13)
,@CO_TIP_CLI_COD NVARCHAR(10)
,@CO_CLI_COD NVARCHAR(10)
AS
SELECT CO_EMP_NOM, CO_TIP_CLI_COD, CO_CLI_COD, 
CO_CLI_NOM, SUM(CO_FACTURAS) AS Saldo_Ventas, 
CO_TIP_CLI_NOM,
(SELECT SUM(CO_COBROS) 
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO
WHERE CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_EMP_RUC=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC AND 
CO_FEC_DOC<=@CO_DOC_COM_FEC_EMI AND CO_CLI_COD!='CL700' AND
CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_CLI_COD=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_CLI_COD
GROUP BY CO_CLI_COD, CO_EMP_RUC) AS Saldo_Cobros
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CLI_COD!='CL700' AND
CO_FEC_DOC<=@CO_DOC_COM_FEC_EMI AND
CO_CLI_COD=case @CO_CLI_COD when '' then CO_CLI_COD else @CO_CLI_COD end  AND
CO_TIP_CLI_COD=case @CO_TIP_CLI_COD when '' then CO_TIP_CLI_COD else @CO_TIP_CLI_COD end
GROUP BY CO_CLI_NOM, CO_CLI_COD, CO_TIP_CLI_COD, CO_EMP_NOM, CO_TIP_CLI_NOM, CO_EMP_RUC
GO
