SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_ROL_TEMP]
(@CO_EMP_RUC char(13)
,@PROF_COD char(10)
,@CO_RUB_ROL_COD int
,@CO_RUB_ROL_VAL float
,@CO_MES int
,@CO_ANIO int
,@CO_RUB_ROL_TIP nvarchar(15))
AS
INSERT INTO [dbo].[CO_ROL_TEMP]
([CO_EMP_RUC]
,[PROF_COD]
,[CO_RUB_ROL_COD]
,[CO_RUB_ROL_VAL]
,[CO_MES]
,[CO_ANIO]
,[CO_RUB_ROL_TIP])
VALUES
(@CO_EMP_RUC
,@PROF_COD
,@CO_RUB_ROL_COD
,@CO_RUB_ROL_VAL
,@CO_MES
,@CO_ANIO
,@CO_RUB_ROL_TIP)
GO
