SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_SALDO_CUENTA]
@CO_EMP_RUC CHAR(13)
,@CO_CUE_COD NVARCHAR(40)
,@CO_ASI_FEC1 DATETIME
,@CO_ASI_FEC2 DATETIME
,@CO_PRO_TIP NVARCHAR(10)
AS
IF @CO_PRO_TIP='Ingresos'
SELECT     SUM(CO_ASI_DEB) AS DEBE
FROM         dbo.CO_ASIENTO
WHERE Convert(varchar(10),CO_ASI_FEC,103)>=Convert(varchar(10),@CO_ASI_FEC1,103)
AND Convert(varchar(10),CO_ASI_FEC,103)<=Convert(varchar(10),@CO_ASI_FEC2,103)
AND CO_CUE_COD=@CO_CUE_COD AND CO_EMP_RUC=@CO_EMP_RUC
else
SELECT SUM(CO_ASI_HAB) AS HABER
FROM         dbo.CO_ASIENTO
WHERE Convert(varchar(10),CO_ASI_FEC,103)>=Convert(varchar(10),@CO_ASI_FEC1,103)
AND Convert(varchar(10),CO_ASI_FEC,103)<=Convert(varchar(10),@CO_ASI_FEC2,103)
AND CO_CUE_COD=@CO_CUE_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
