SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Fredy M. Aguirre
-- Create date: 11/12/2006
-- Description:	Registra un entrada del Kardex en la tabla CO_KARDEX_TOTAL
-- =============================================
CREATE PROCEDURE [dbo].[CO_SP_INSERT_KARDEX_TOTAL] 
@CO_KAR_TOT_COD UNIQUEIDENTIFIER,
@CO_EMP_RUC char(13),
@CO_ART_COD nvarchar(40),
@CO_BOD_COD INT,
@CO_KAR_TOT_FEC datetime,
@CO_KAR_TOT_DOC NVARCHAR(50),
@CO_KAR_TOT_TIP_DOC int,
@CO_KAR_TOT_ENT_CANT float,
@CO_KAR_TOT_ENT_VAL_UNI float,
@CO_KAR_TOT_ENT_VAL_TOT float,
@CO_KAR_TOT_SAL_CANT float,
@CO_KAR_TOT_SAL_VAL_UNI float,
@CO_KAR_TOT_SAL_VAL_TOT float,
@CO_KAR_TOT_EXI_CANT float,
@CO_KAR_TOT_EXI_VAL_UNI float,
@CO_KAR_TOT_EXI_VAL_TOT float,
@CO_KAR_TOT_EST nvarchar(10),
@CO_KAR_TOT_DET nvarchar(70)
AS
BEGIN
INSERT INTO CO_KARDEX_TOTAL
(CO_KAR_TOT_COD,
CO_EMP_RUC,
CO_ART_COD,
CO_BOD_COD,
CO_KAR_TOT_FEC,
CO_KAR_TOT_DOC,
CO_KAR_TOT_TIP_DOC,
CO_KAR_TOT_ENT_CANT, 
CO_KAR_TOT_ENT_VAL_UNI,
CO_KAR_TOT_ENT_VAL_TOT,
CO_KAR_TOT_SAL_CANT,
CO_KAR_TOT_SAL_VAL_UNI, 
CO_KAR_TOT_SAL_VAL_TOT,
CO_KAR_TOT_EXI_CANT,
CO_KAR_TOT_EXI_VAL_UNI,
CO_KAR_TOT_EXI_VAL_TOT,
CO_KAR_TOT_EST,
CO_KAR_TOT_DET)
VALUES
(@CO_KAR_TOT_COD,
@CO_EMP_RUC,
@CO_ART_COD,
@CO_BOD_COD,
@CO_KAR_TOT_FEC,
@CO_KAR_TOT_DOC,
@CO_KAR_TOT_TIP_DOC,
@CO_KAR_TOT_ENT_CANT,
@CO_KAR_TOT_ENT_VAL_UNI,
@CO_KAR_TOT_ENT_VAL_TOT,
@CO_KAR_TOT_SAL_CANT,
@CO_KAR_TOT_SAL_VAL_UNI,
@CO_KAR_TOT_SAL_VAL_TOT,
@CO_KAR_TOT_EXI_CANT,
@CO_KAR_TOT_EXI_VAL_UNI,
@CO_KAR_TOT_EXI_VAL_TOT,
@CO_KAR_TOT_EST,
@CO_KAR_TOT_DET)
END
GO
