SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_RETENCION]
(@CO_RET_COD UNIQUEIDENTIFIER
,@CO_EMP_RUC char(13)
,@CO_RET_SER1 nchar(3)
,@CO_RET_SER2 nchar(3)
,@CO_RET_NUM_REF varchar(10)
,@CO_RET_AUT nvarchar(50)
,@CO_RET_BEN_NOM varchar(50)
,@CO_RET_BEN_NUM_RUC char(13)
,@CO_RET_BEN_DIR nvarchar(50)
,@CO_RET_BEN_FEC_EMI datetime
,@CO_RET_USU_ALI varchar(15)
,@CO_RET_TIP nvarchar(10)
,@CO_DOC_VEN_ID UNIQUEIDENTIFIER
,@CO_DOC_COM_ID UNIQUEIDENTIFIER
,@CO_RET_EJE_FIS nvarchar(10))
AS
INSERT INTO [dbo].[CO_RETENCION]
([CO_RET_COD]
,[CO_EMP_RUC]
,[CO_RET_SER1]
,[CO_RET_SER2]
,[CO_RET_NUM_REF]
,[CO_RET_AUT]
,[CO_RET_BEN_NOM]
,[CO_RET_BEN_NUM_RUC]
,[CO_RET_BEN_DIR]
,[CO_RET_BEN_FEC_EMI]
,[CO_RET_USU_ALI]
,[CO_RET_TIP]
,[CO_DOC_VEN_ID]
,[CO_DOC_COM_ID]
,CO_RET_EJE_FIS
,CO_ESTADO)
VALUES
(@CO_RET_COD
,@CO_EMP_RUC
,@CO_RET_SER1
,@CO_RET_SER2
,@CO_RET_NUM_REF
,@CO_RET_AUT
,@CO_RET_BEN_NOM
,@CO_RET_BEN_NUM_RUC
,@CO_RET_BEN_DIR
,@CO_RET_BEN_FEC_EMI
,@CO_RET_USU_ALI
,@CO_RET_TIP
,@CO_DOC_VEN_ID
,@CO_DOC_COM_ID
,@CO_RET_EJE_FIS
,1)
GO
