SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PAGO_CUOTA]
@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_PAG_VAL int
,@CO_PAG_FEC datetime
,@CO_PAG_EST bit
,@CO_PAG_CON nvarchar(100)
,@PROF_COD CHAR(10)
,@CO_RUB_ROL_COD int
AS
INSERT INTO [dbo].[CO_PAGO_CUOTA]
([CO_EMP_RUC]
,[CO_NOT_DEB_NUM]
,[CO_PAG_VAL]
,[CO_PAG_FEC]
,[CO_PAG_EST]
,[CO_PAG_CON]
,[CO_PAG_VAL_IMP]
,[PROF_COD]
,CO_RUB_ROL_COD)
VALUES
(@CO_EMP_RUC
,@CO_NOT_DEB_NUM
,@CO_PAG_VAL
,@CO_PAG_FEC
,@CO_PAG_EST
,@CO_PAG_CON
,@CO_PAG_VAL
,@PROF_COD
,@CO_RUB_ROL_COD)
GO
