SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_PRESUPUESTO_RECURSOS]
@CO_EMP_RUC CHAR(13),
@CO_PRE_ANO INT,
@CO_TIP_REC_COD INT,
@CO_PRO_COD INT,
@CO_PRO_TIP NVARCHAR(10)
AS
SELECT * FROM CO_VW_SELECT_REPORTE_PRESUPUESTOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
CO_PRE_ANO=@CO_PRE_ANO AND
CO_TIP_REC_COD=case @CO_TIP_REC_COD when 0 then CO_TIP_REC_COD else @CO_TIP_REC_COD end  AND
CO_PRO_COD=case @CO_PRO_COD when 0 then CO_PRO_COD else @CO_PRO_COD end  AND
CO_PRO_TIP=case @CO_PRO_TIP when '' then CO_PRO_TIP else @CO_PRO_TIP end
GO
