SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_IDENTIFICACION]
@CO_TIP_IDE_COD nvarchar(50)
,@CO_TIP_IDE_NOM nvarchar(50)
,@CO_TIP_IDE_COD_SRI nvarchar(5)
AS
UPDATE [dbo].[CO_TIPO_IDENTIFICACION] SET
[CO_TIP_IDE_NOM]=@CO_TIP_IDE_NOM,
CO_TIP_IDE_COD_SRI=@CO_TIP_IDE_COD_SRI
WHERE [CO_TIP_IDE_COD]=@CO_TIP_IDE_COD
GO
