SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_ESTADO_CUENTA_PROVEEDOR]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_PRO_COD NVARCHAR(10)
,@CO_PRO_COD NVARCHAR(10)
,@CO_DOC_COM_FEC1 DATETIME
,@CO_DOC_COM_FEC2 DATETIME
AS
SELECT *,@CO_DOC_COM_FEC1 AS DESDE,@CO_DOC_COM_FEC2 AS HASTA 
FROM CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
(CO_FEC_DOC>=@CO_DOC_COM_FEC1 AND CO_FEC_DOC<=@CO_DOC_COM_FEC2) AND
CO_TIP_PRO_COD=case @CO_TIP_PRO_COD when '' then CO_TIP_PRO_COD else @CO_TIP_PRO_COD end  AND 
CO_PRO_COD=case @CO_PRO_COD when '' then CO_PRO_COD else @CO_PRO_COD end 
UNION
SELECT *,@CO_DOC_COM_FEC1 AS DESDE,@CO_DOC_COM_FEC2 AS HASTA 
FROM CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR_PAGOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
(CO_FEC_DOC>=@CO_DOC_COM_FEC1 AND CO_FEC_DOC<=@CO_DOC_COM_FEC2) AND
CO_TIP_PRO_COD=case @CO_TIP_PRO_COD when '' then CO_TIP_PRO_COD else @CO_TIP_PRO_COD end  AND 
CO_PRO_COD=case @CO_PRO_COD when '' then CO_PRO_COD else @CO_PRO_COD end
GO
