SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PRESUPUESTO_CONTADOR]
@CO_EMP_RUC CHAR(13),
@CO_ITE_PRE_COD INT,
@CO_PRE_ANO INT
AS
SELECT COUNT(*) FROM CO_PRESUPUESTO
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_ITE_PRE_COD=@CO_ITE_PRE_COD
AND CO_PRE_ANO=@CO_PRE_ANO
GO
