SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_PLANILLA_TOTAL]
@CO_EMP_RUC CHAR(13)
,@MES INT
,@ANIO INT
,@CO_UBI_COD INT
AS
SELECT CO_RUB_ROL_NOM,CO_UBI_NOM,SUM(CO_TRA_VAL) AS TOTAL,CO_EMP_NOM,CO_EMP_DIR,CO_EMP_CIU,MES,ANIO,CO_EMP_RUC,CO_RUB_ROL_VAL
FROM CO_VW_SELECT_PLANILLA_ROL
WHERE CO_EMP_RUC=@CO_EMP_RUC AND MES=@MES AND ANIO=@ANIO AND CO_UBI_COD=@CO_UBI_COD
GROUP BY CO_RUB_ROL_NOM,CO_UBI_NOM,CO_EMP_NOM,CO_EMP_DIR,CO_EMP_CIU,MES,ANIO,CO_EMP_RUC,CO_RUB_ROL_VAL
GO
