SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_DOCUMENTOS_VENTAS_DETALLADO]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_DOC_VEN_NUM INT
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
,@CO_DOC_VEN_FOR_PAG NVARCHAR(15)
,@CO_DOC_VEN_EST NVARCHAR(50)
,@CO_TIP_DOC_VEN_NOM NVARCHAR(100)
,@CO_TIP_CLI_COD NVARCHAR(10)
,@CO_CLI_COD NVARCHAR(50)
,@CO_VEN_CED NCHAR(10)
,@CO_ALM_COD NVARCHAR(20)
AS
SELECT * ,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA,@CO_TIP_DOC_VEN_NOM AS TIPO_DOCUMENTO
FROM CO_VW_SELECT_LISTADO_DOCUMENTOS_VENTA
WHERE 
CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM AND
CO_EMP_RUC=@CO_EMP_RUC AND
CO_DOC_VEN_EST=@CO_DOC_VEN_EST AND
CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND
CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2 AND 
CO_DOC_VEN_FOR_PAG=case @CO_DOC_VEN_FOR_PAG when '' then CO_DOC_VEN_FOR_PAG else @CO_DOC_VEN_FOR_PAG end  AND
CO_TIP_CLI_COD=case @CO_TIP_CLI_COD when '' then CO_TIP_CLI_COD else @CO_TIP_CLI_COD end  AND
CO_CLI_COD=case @CO_CLI_COD when '' then CO_CLI_COD else @CO_CLI_COD end  AND
CO_VEN_CED=case @CO_VEN_CED when '' then CO_VEN_CED else @CO_VEN_CED end  AND
CO_ALM_COD=case @CO_ALM_COD when '' then CO_ALM_COD else @CO_ALM_COD end
GO
