SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_RUBRO_EMPLEADO]
@PROF_COD char(10)
,@CO_RUB_ROL_COD int
,@CO_EMP_RUC char(13)
,@CO_RUB_EMP_VAL float
AS
UPDATE [dbo].[CO_RUBRO_EMPLEADO] SET
[CO_RUB_EMP_VAL]=@CO_RUB_EMP_VAL
WHERE PROF_COD=@PROF_COD
AND CO_RUB_ROL_COD=@CO_RUB_ROL_COD
AND CO_EMP_RUC=@CO_EMP_RUC
GO
