SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--UPDATE dbo.CO_DOCUMENTO_VENTA
--SET CO_DOC_VEN_NUM='001-001-'+REPLICATE('0',7-len(CO_DOC_VEN_NUM))+CO_DOC_VEN_NUM 
CREATE PROC [dbo].[CO_SP_SELECT_DOCUMENTO_NUMERO]
@CO_TIP_DOC_VEN_NUM INT,
@CO_ALM_COD INT,
@CO_EMP_RUC CHAR(13)
AS
DECLARE @MAYOR INT, @SERIE1 NVARCHAR(3), @SERIE2 NVARCHAR(3), @SECUENCIAINICIO INT, @SECUENCIAFINAL INT

IF(@CO_TIP_DOC_VEN_NUM=18) --FACTURA
	SELECT @MAYOR=ISNULL(MAX(CAST(SUBSTRING(CO_DOC_VEN_NUM,9,len(CO_DOC_VEN_NUM)) AS INT)),0) + 1 FROM dbo.CO_DOCUMENTO_VENTA
			WHERE CO_TIP_DOC_VEN_NUM=18 AND CO_EMP_RUC=@CO_EMP_RUC
ELSE IF(@CO_TIP_DOC_VEN_NUM=20) --NOTA DE VENTA
	SELECT @MAYOR=ISNULL(MAX(CAST(SUBSTRING(CO_DOC_VEN_NUM,9,len(CO_DOC_VEN_NUM)) AS INT)),0) + 1 FROM dbo.CO_DOCUMENTO_VENTA
			WHERE CO_TIP_DOC_VEN_NUM=20 AND CO_EMP_RUC=@CO_EMP_RUC
ELSE IF(@CO_TIP_DOC_VEN_NUM=4) --NOTA DE CREDITO
	SELECT @MAYOR=ISNULL(MAX(CAST(SUBSTRING(CO_DOC_VEN_NUM,9,len(CO_DOC_VEN_NUM)) AS INT)),0) + 1 FROM dbo.CO_DOCUMENTO_VENTA
			WHERE CO_TIP_DOC_VEN_NUM=4 AND CO_EMP_RUC=@CO_EMP_RUC
ELSE IF (@CO_TIP_DOC_VEN_NUM=99) --EGRESO
	SELECT @MAYOR=ISNULL(MAX(CAST(SUBSTRING(Numero,9,len(Numero)) AS INT)),0) + 1 FROM dbo.CO_EGRESO WHERE CO_EMP_RUC=@CO_EMP_RUC
ELSE IF(@CO_TIP_DOC_VEN_NUM=98) --INGRESO
	SELECT @MAYOR=ISNULL(MAX(CAST(SUBSTRING(Numero,9,len(Numero)) AS INT)),0) + 1 FROM dbo.CO_INGRESO WHERE CO_EMP_RUC=@CO_EMP_RUC
ELSE IF(@CO_TIP_DOC_VEN_NUM=100) --DOCUMENTO DE RESERVA
	SELECT @MAYOR=ISNULL(MAX(CAST(SUBSTRING(CO_DOC_VEN_NUM,9,len(CO_DOC_VEN_NUM)) AS INT)),0) + 1 FROM dbo.CO_DOCUMENTO_RESERVA WHERE CO_EMP_RUC=@CO_EMP_RUC
ELSE IF(@CO_TIP_DOC_VEN_NUM=101) --RETENCION
	SELECT @MAYOR=iSNULL(MAX(CAST(SUBSTRING(CO_RET_SER1+'-'+CO_RET_SER2+'-'+CO_RET_NUM_REF,9,len(CO_RET_SER1+'-'+CO_RET_SER2+'-'+CO_RET_NUM_REF)) AS INT)),0) + 1 FROM dbo.CO_RETENCION WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_RET_TIP='Compras' and cast(CO_RET_BEN_FEC_EMI as date)>=cast('2018/07/01' as date)
ELSE IF(@CO_TIP_DOC_VEN_NUM=102) --GUIA DE REMISION
	SELECT @MAYOR=iSNULL(MAX(CAST(SUBSTRING(CO_DOC_VEN_GUI_NUM,9,len(CO_DOC_VEN_GUI_NUM)) AS INT)),0) + 1 FROM dbo.CO_GUIA_REMISION WHERE CO_EMP_RUC=@CO_EMP_RUC

PRINT @MAYOR


SELECT @SERIE1=Serie1, @SERIE2=Sere2, @SECUENCIAINICIO=SecuenciaInicio, @SECUENCIAFINAL=SecuenciaFinal 
FROM dbo.CO_AUTORIZACION
WHERE CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM AND CO_ALM_COD=@CO_ALM_COD AND CO_EMP_RUC=@CO_EMP_RUC AND Activo=1

PRINT @SECUENCIAINICIO
PRINT @SECUENCIAFINAL

IF(@MAYOR BETWEEN @SECUENCIAINICIO AND @SECUENCIAFINAL)
BEGIN
	SELECT @SERIE1 + '-' + @SERIE2 + '-' + REPLICATE('0',9-len(@MAYOR)) + CAST(@MAYOR AS NVARCHAR(9))
END
ELSE
BEGIN
	SELECT @SERIE1 + '-' + @SERIE2 + '-' + REPLICATE('0',9-len(@SECUENCIAINICIO)) + CAST(@SECUENCIAINICIO AS NVARCHAR(9))
END

GO
