SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_DOCUMENTOS_ELECTRONICOS]
@CO_DOC_VEN_FEC_DESDE DATETIME,
@CO_DOC_VEN_FEC_HASTA DATETIME,
@CO_TIP_DOC INT
AS
SELECT * FROM CO_VW_SELECT_REPORTE_DOCUMENTOS_ELECTRONICOS
WHERE CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC_DESDE AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC_HASTA
AND CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC
GO
