SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_COMPROBANTE_FECHA]
@CO_EMP_RUC CHAR(13),
@CO_MES_NUM INT,
@CO_ANIO_NUM INT
AS
SELECT COUNT(CO_COM_NUM) AS CONTADOR
FROM CO_COMPROBANTE
WHERE CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_COM_FEC)=@CO_MES_NUM
AND YEAR(CO_COM_FEC)=@CO_ANIO_NUM
GO
