SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CADUCIDAD_MINIMA]
@CO_EMP_RUC CHAR(13)
,@CO_ART_COD nvarchar(40)
AS
SELECT MIN(CO_CAD_FEC_FIN) AS PROXIMO_CADUCAR,CO_CAD_CAN,CO_CAD_COD
FROM CO_CADUCIDAD
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CAD_EST=1 AND CO_ART_COD=@CO_ART_COD
GROUP BY CO_CAD_COD,CO_CAD_CAN
GO
