SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_DETALLE_DOCUMENTO_COMPRA]
           @CO_DET_DOC_COM_COD UNIQUEIDENTIFIER
           ,@CO_DET_DOC_COM_CAN float
           ,@CO_DET_DOC_COM_PRE float
           ,@CO_DET_DOC_COM_DES float
           ,@CO_DET_DOC_COM_TOT float
           ,@CO_DET_DOC_COM_TIP_ART bit
			,@CO_DET_DOC_COM_VAL_ICE float
			,@CO_DET_DOC_COM_POR_ICE float
			,@CO_DET_DOC_COM_IVA float
			,@CO_DET_DOC_COM_POR_IVA float
			,@CO_DET_DOC_COM_ART_BAR nvarchar(20)
			,@CO_BOD_COD INT
			,@CO_BOD_NOM NVARCHAR(100)
			,@CO_CANTIDAD_EMPAQUE float
AS
UPDATE [dbo].[CO_DETALLE_DOCUMENTO_COMPRA] SET
           [CO_DET_DOC_COM_CAN]=@CO_DET_DOC_COM_CAN
           ,[CO_DET_DOC_COM_PRE]=@CO_DET_DOC_COM_PRE
           ,[CO_DET_DOC_COM_DES]=@CO_DET_DOC_COM_DES
           ,[CO_DET_DOC_COM_TOT]=@CO_DET_DOC_COM_TOT
           ,[CO_DET_DOC_COM_TIP_ART]=@CO_DET_DOC_COM_TIP_ART
			,CO_DET_DOC_COM_VAL_ICE=@CO_DET_DOC_COM_VAL_ICE
			,CO_DET_DOC_COM_POR_ICE=@CO_DET_DOC_COM_POR_ICE
			,CO_DET_DOC_COM_IVA=@CO_DET_DOC_COM_IVA
			,CO_DET_DOC_COM_POR_IVA=@CO_DET_DOC_COM_POR_IVA
			,CO_DET_DOC_COM_ART_BAR=@CO_DET_DOC_COM_ART_BAR
			,CO_BOD_COD=@CO_BOD_COD
			,CO_BOD_NOM=@CO_BOD_NOM
			,CO_CANTIDAD_EMPAQUE=@CO_CANTIDAD_EMPAQUE
WHERE [CO_DET_DOC_COM_COD]=@CO_DET_DOC_COM_COD
GO
