SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_NOMBRE_CUENTA_CONTABLE]
@CO_EMP_RUC CHAR(13),
@CO_CUE_NOM VARCHAR(20)
AS
DECLARE @LIKE AS VARCHAR(50)
SET @LIKE='%'+@CO_CUE_NOM+'%'
SELECT CO_EMP_RUC, CO_CUE_COD, CO_CUE_NOM, CO_CUE_TIP,
		CO_CUE_USU_ALI, CO_CUE_CAS_IMP, CO_CUE_COD_ANT
FROM CO_CUENTA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CUE_NOM LIKE @LIKE AND CO_CUE_TIP='Movimiento'
GO
