SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PARAMETRO_RENTA]
@CO_PAR_REN_LIM_INF float
,@CO_PAR_REN_LIM_SUP float
,@CO_PAR_REN_VAL_BAS float
,@CO_PAR_REN_POR_DIF float
AS
INSERT INTO [dbo].[CO_PARAMETRO_RENTA]
([CO_PAR_REN_LIM_INF]
,[CO_PAR_REN_LIM_SUP]
,[CO_PAR_REN_VAL_BAS]
,[CO_PAR_REN_POR_DIF])
VALUES
(@CO_PAR_REN_LIM_INF
,@CO_PAR_REN_LIM_SUP
,@CO_PAR_REN_VAL_BAS
,@CO_PAR_REN_POR_DIF)
GO
