SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CONCILIACION_ESTADO]
@CO_CON_BAN_COD int
AS
UPDATE [dbo].[CO_CONCILIACION] SET
CO_CON_BAN_CON=0
WHERE CO_CON_BAN_COD=@CO_CON_BAN_COD
GO
