SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BODEGA_ARTICULO]
@CO_EMP_RUC CHAR(13)
,@CO_ART_COD NVARCHAR(20)
AS
SELECT     dbo.CO_BODEGA.CO_BOD_NOM, dbo.CO_ALMACEN.CO_ALM_NOM, dbo.CO_UBICACIONARTICULO.CO_BOD_COD, 
				dbo.CO_UBICACIONARTICULO.CO_ART_COD, dbo.CO_UBICACIONARTICULO.CO_EMP_RUC, 'A' AS CO_ESTADO_BODEGA
FROM         dbo.CO_BODEGA INNER JOIN
                      dbo.CO_UBICACIONARTICULO ON dbo.CO_BODEGA.CO_BOD_COD = dbo.CO_UBICACIONARTICULO.CO_BOD_COD INNER JOIN
                      dbo.CO_ALMACEN ON dbo.CO_BODEGA.CO_ALM_COD = dbo.CO_ALMACEN.CO_ALM_COD AND dbo.CO_BODEGA.CO_EMP_RUC = dbo.CO_ALMACEN.CO_EMP_RUC
where dbo.CO_BODEGA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_UBICACIONARTICULO.CO_ART_COD=@CO_ART_COD
GO
