SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ESTADO_MES]
@CO_MES_NUM int
,@CO_ANIO_NUM int
,@CO_EMP_RUC char(13)
AS
SELECT CO_MES_EST FROM CO_MES
WHERE CO_MES_NUM=@CO_MES_NUM 
AND CO_ANIO_NUM=@CO_ANIO_NUM
AND CO_EMP_RUC=@CO_EMP_RUC
GO
