SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_TRANSACCIONES_BANCO_AFECTA_PLUS]
@CO_TIP_TRA_COD char(2)
AS
SELECT     CO_TIP_TRA_COD AS CODIGO,CO_TIP_TRA_OPE AS AFECTA
FROM       dbo.CO_TIPO_TRANSACCION
WHERE CO_TIP_TRA_COD=@CO_TIP_TRA_COD
GO
