SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_TRANSACCION]
@CO_TIP_TRA_COD CHAR(2),
@CO_EMP_RUC CHAR(13),
@CO_TIP_TRA_NOM VARCHAR(20),
@CO_TIP_TRA_OPE CHAR(1)
AS
INSERT INTO CO_TIPO_TRANSACCION VALUES
(@CO_TIP_TRA_COD,
@CO_EMP_RUC,
@CO_TIP_TRA_NOM,
@CO_TIP_TRA_OPE)
GO
