SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DELETE_ELIMINAR_SALDOS_MES]
@CO_EMP_RUC char(13)
,@CO_COM_MES int
,@CO_COM_ANIO int
AS
DELETE CO_MES_SALDO
WHERE CO_MES_NUM=@CO_COM_MES AND CO_ANIO_NUM=@CO_COM_ANIO AND CO_EMP_RUC=@CO_EMP_RUC
GO
