SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DETALLE_COBRO_CLIENTE_DOCUMENTO_VENTA]
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
AS
select distinct CO_COM_COD_CLI_ID from CO_COBRO_CLIENTE
WHERE CO_COM_COD_CLI_ID IN (select CO_COM_COD_CLI_ID from [dbo].[CO_DETALLE_COBRO_CLIENTE]
where CO_DOC_VEN_ID=@CO_DOC_VEN_ID)
AND CO_COM_COB_CLI_EST='ACTIVA'
GO
