SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TABLA_PRECIO]
@ListaDePrecioID int
,@CO_EMP_RUC char(13)
,@CO_ART_COD nvarchar(20)
,@CO_TAB_PRE FLOAT
,@CO_TAB_PRE_POR_ART FLOAT
,@CO_TAB_PRE_MIN float
AS
UPDATE [dbo].[CO_TABLA_PRECIO] SET
CO_TAB_PRE=@CO_TAB_PRE,
CO_TAB_PRE_POR_ART=@CO_TAB_PRE_POR_ART
,CO_TAB_PRE_MIN=@CO_TAB_PRE_MIN
WHERE 
ListaDePrecioID=@ListaDePrecioID and
CO_ART_COD=@CO_ART_COD AND 
CO_EMP_RUC=@CO_EMP_RUC
GO
