SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_EMPRESA]
@CO_EMP_RUC CHAR(13),
@CO_EMP_NOM VARCHAR(50),
@CO_EMP_NOM_REP VARCHAR(50),
@CO_EMP_NOM_CON VARCHAR(50),
@CO_EMP_REG_CON VARCHAR(10),
@CO_EMP_DIR VARCHAR(100),
@CO_EMP_CIU VARCHAR(20),
@CO_EMP_TEL VARCHAR(11),
@CO_EMP_FAX VARCHAR(11),
@CO_EMP_TIP_IDE NVARCHAR(50),
@CO_EMP_REP_IDE NVARCHAR(20),
@CO_EMP_RUC_CON NCHAR(13),
@CO_EMP_MAI NVARCHAR(100),
@CO_EMP_RAZ_SOC NVARCHAR(100),
@CO_CONTRIBUYENTE_ESPECIAL bit,
@CO_CONTRIBUYENTE_NUMERO nvarchar(10),
@CO_OBLIGADO_CONTABILIDAD bit,
@CO_EMPRESA_LOGO varbinary(MAX),
@CO_EMPRESA_LOGO_FILE VARCHAR(150)
AS
INSERT INTO CO_EMPRESA VALUES(
@CO_EMP_RUC,
@CO_EMP_NOM,
@CO_EMP_NOM_REP,
@CO_EMP_NOM_CON,
@CO_EMP_REG_CON,
@CO_EMP_DIR,
@CO_EMP_CIU,
@CO_EMP_TEL,
@CO_EMP_FAX,
@CO_EMP_TIP_IDE,
@CO_EMP_REP_IDE,
@CO_EMP_RUC_CON,
@CO_EMP_MAI,
@CO_EMP_RAZ_SOC,
@CO_CONTRIBUYENTE_ESPECIAL,
@CO_CONTRIBUYENTE_NUMERO,
@CO_OBLIGADO_CONTABILIDAD,
@CO_EMPRESA_LOGO,
@CO_EMPRESA_LOGO_FILE)



GO
