SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_INSERT_PAGO_PROVEEDORES_PLUS]
@CODIGO_PAGO_PROVEEDOR int
,@CODIGO_DOCUMENTO_PAGO int
,@FORMA_PAGO_PROVEEDOR nvarchar(50)
,@NUMERO_PAGO_PROVEEDOR nvarchar(30)
,@CO_CC_NUM varchar(10)
,@VALOR_PAGO_PROVEEDOR decimal(18,2)
,@FECHA_PAGO_PROVEEDOR datetime
,@ESTADO_PAGO_PROVEEDOR nvarchar(50)
,@USUARIO_NOMBRE nvarchar(50)
,@CO_EMP_RUC char(13)
,@CO_PRO_COD nvarchar(10)
,@VALOR_PAGADO_EN_NUMEROS nvarchar(max)
AS
INSERT INTO dbo.CO_PAGO_PROVEEDORES_PLUS(
CODIGO_PAGO_PROVEEDOR
,CODIGO_DOCUMENTO_PAGO
,FORMA_PAGO_PROVEEDOR
,NUMERO_PAGO_PROVEEDOR
,CO_CC_NUM
,VALOR_PAGO_PROVEEDOR
,FECHA_PAGO_PROVEEDOR
,ESTADO_PAGO_PROVEEDOR
,USUARIO_NOMBRE
,CO_EMP_RUC
,CO_PRO_COD
,VALOR_PAGADO_EN_NUMEROS)
VALUES(
@CODIGO_PAGO_PROVEEDOR
,@CODIGO_DOCUMENTO_PAGO
,@FORMA_PAGO_PROVEEDOR
,@NUMERO_PAGO_PROVEEDOR
,@CO_CC_NUM
,@VALOR_PAGO_PROVEEDOR
,@FECHA_PAGO_PROVEEDOR
,@ESTADO_PAGO_PROVEEDOR
,@USUARIO_NOMBRE
,@CO_EMP_RUC
,@CO_PRO_COD
,@VALOR_PAGADO_EN_NUMEROS)
GO
