SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIPO_RUBROS_MES]
@CO_EMP_RUC CHAR(13)
,@CO_MES INT
,@CO_ANIO INT
AS
SELECT CO_TIP_RUB_COD_CUE,CO_TIP_RUB_NOM,VALOR,CO_RUB_ROL_AFE
FROM CO_VW_SELECT_TIPO_RUBROS
WHERE MES=@CO_MES AND ANIO=@CO_ANIO AND CO_EMP_RUC=@CO_EMP_RUC
GO
