SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_UBICACION_AF]
@CO_EMP_RUC char(13)
,@CO_UBI_COD INT
,@CO_UBI_NOM varchar(30)
,@CO_UBI_DIR nvarchar(100)
,@CO_UBI_TEL nchar(10)
,@CO_UBI_REP nvarchar(100)
,@CO_UBI_REP_CED nchar(10)
AS
UPDATE [dbo].[CO_UBICACION_AF] SET      
CO_UBI_NOM=@CO_UBI_NOM
,CO_UBI_DIR=@CO_UBI_DIR
,CO_UBI_TEL=@CO_UBI_TEL
,CO_UBI_REP=@CO_UBI_REP
,CO_UBI_REP_CED=@CO_UBI_REP_CED
WHERE
CO_EMP_RUC=@CO_EMP_RUC
AND CO_UBI_COD=@CO_UBI_COD
GO
