SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_DOCUMENTO_COMPRA]
@CO_EMP_RUC char(13)
,@CO_DOC_COM_ID uniqueidentifier
AS
UPDATE CO_DOCUMENTO_COMPRA SET
CO_DOC_COM_EST='ANULADO'
WHERE CO_DOC_COM_ID=@CO_DOC_COM_ID AND
CO_EMP_RUC=@CO_EMP_RUC
GO
