SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_NOTA_DEBITO_FECHA]
@CO_NOT_DEB_FEC_INI DATETIME
,@CO_NOT_DEB_FEC_FIN DATETIME
,@CO_EMP_RUC CHAR(13)
AS
SELECT * FROM CO_VW_SELECT_NOTAS_DEBITO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
CO_NOT_DEB_FEC>=@CO_NOT_DEB_FEC_INI
AND CO_NOT_DEB_FEC<=@CO_NOT_DEB_FEC_FIN
GO
