SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_NOTA_DEBITO_ESTADO]
@CO_EMP_RUC CHAR(13)
,@CO_NOT_DEB_NUM INT
,@CO_NOT_DEB_EST BIT
AS
UPDATE CO_NOTA_DEBITO SET
CO_NOT_DEB_EST=@CO_NOT_DEB_EST
WHERE CO_EMP_RUC=@CO_EMP_RUC
AND CO_NOT_DEB_NUM=@CO_NOT_DEB_NUM
GO
