SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_SERVICIO]
@CO_SER_NOM NVARCHAR(50),
@CO_EMP_RUC CHAR(13)
AS
DECLARE @LIKE AS VARCHAR(50)
SET @LIKE='%'+@CO_SER_NOM+'%'
SELECT dbo.CO_SERVICIO.CO_SER_COD, dbo.CO_SERVICIO.CO_SER_NOM, dbo.CO_SERVICIO.CO_SER_PRE, 
dbo.CO_SERVICIO.CO_SER_POR_IVA, dbo.CO_SERVICIO.CO_EMP_RUC, dbo.CO_TABLA_ICE.CO_ICE_POR
FROM dbo.CO_SERVICIO INNER JOIN
dbo.CO_TABLA_ICE ON dbo.CO_SERVICIO.CO_ICE_COD = dbo.CO_TABLA_ICE.CO_ICE_COD
WHERE CO_SER_NOM LIKE @LIKE AND
CO_EMP_RUC=@CO_EMP_RUC
AND CO_ESTADO=1
GO
