SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE proc [dbo].[CO_RETENCION_AIR_REOC]
@CO_DOC_COM_ID UNIQUEIDENTIFIER
AS
SELECT CA.CO_CON_AIR_COD as codRetAir, R.CO_RET_POR as porcentaje, cast(0 as float) as base0,
		R.CO_RET_VAL as valRetAir, cast(0 as float) as baseNoGrav, R.CO_RET_BAS as baseGrav
FROM CO_RETENCION R INNER JOIN dbo.CO_CONCEPTO_AIR CA ON R.CO_TIP_RET_COD=CA.CO_CON_AIR_COD
WHERE CO_DOC_COM_ID=@CO_DOC_COM_ID
GO
