SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TABAL_ICE]
@CO_ICE_COD INT,
@CO_ICE_NOM NVARCHAR(50),
@CO_ICE_POR FLOAT
AS
UPDATE [dbo].[CO_TABLA_ICE] SET
@CO_ICE_NOM=CO_ICE_NOM,
@CO_ICE_POR=CO_ICE_POR
WHERE  @CO_ICE_COD=CO_ICE_COD
GO
