SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_BODEGA]
@CO_ALM_COD nvarchar(20)
,@CO_EMP_RUC char(13)
,@CO_BOD_NOM nvarchar(100)
AS
INSERT INTO [dbo].[CO_BODEGA]
([CO_ALM_COD]
,[CO_EMP_RUC]
,[CO_BOD_NOM])
VALUES
(@CO_ALM_COD
,@CO_EMP_RUC
,@CO_BOD_NOM)
GO
