SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_VENTA_EMPLEADO]
@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_SER_COD nvarchar(10)
,@CO_VEN_EMP_CAN int
,@CO_VEN_EMP_PRE float
,@CO_VEN_EMP_DES float
,@CO_VEN_EMP_TOT float
,@CO_VEN_EMP_USU_ALI nvarchar(14)
AS
UPDATE [dbo].[CO_VENTA_EMPLEADO] SET
[CO_VEN_EMP_CAN]=@CO_VEN_EMP_CAN
,[CO_VEN_EMP_PRE]=@CO_VEN_EMP_PRE
,[CO_VEN_EMP_DES]=@CO_VEN_EMP_DES
,[CO_VEN_EMP_TOT]=@CO_VEN_EMP_TOT
,[CO_VEN_EMP_USU_ALI]=@CO_VEN_EMP_USU_ALI
WHERE
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_NOT_DEB_NUM]=@CO_NOT_DEB_NUM
AND [CO_SER_COD]=@CO_SER_COD)
GO
