SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CIERRE_ASIENTO_INICIAL]
@CO_MES INT,
@CO_ANIO INT,
@CO_EMP_RUC CHAR(13)
AS
SELECT CO_CUE_COD,CO_CUE_NOM,DEBE,HABER,CO_CUE_COD_ANT 
FROM CO_VW_SELECT_SALDO_ASIENTO
WHERE MES=@CO_MES AND ANIO=@CO_ANIO AND CO_EMP_RUC=@CO_EMP_RUC
GO
