SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[CO_SP_UPDATE_DOCUMENTO_RESERVA]
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
,@CO_DOC_VEN_DET nvarchar(100)
,@CO_DOC_VEN_TOT_NET float
,@CO_DOC_VEN_POR_DES float
,@CO_DOC_VEN_DES float
,@CO_DOC_VEN_POR_IVA int
,@CO_DOC_VEN_IVA float
,@CO_DOC_VEN_TOT_PAG float
,@CO_DOC_VEN_USU_ALI nvarchar(15)
,@CO_DOC_VEN_TOT_LET nvarchar(150)
,@CO_DOC_VEN_VAL_IVA0 FLOAT
,@CO_DOC_VEN_OTR NVARCHAR(100)
,@AlmacenID int
,@CO_DOC_VEN_SAL float
AS
UPDATE [dbo].[CO_DOCUMENTO_RESERVA] SET
[CO_DOC_VEN_DET]=@CO_DOC_VEN_DET
,[CO_DOC_VEN_TOT_NET]=@CO_DOC_VEN_TOT_NET
,[CO_DOC_VEN_POR_DES]=@CO_DOC_VEN_POR_DES
,[CO_DOC_VEN_DES]=@CO_DOC_VEN_DES
,[CO_DOC_VEN_POR_IVA]=@CO_DOC_VEN_POR_IVA
,[CO_DOC_VEN_IVA]=@CO_DOC_VEN_IVA
,[CO_DOC_VEN_TOT_PAG]=@CO_DOC_VEN_TOT_PAG
,[CO_DOC_VEN_USU_ALI]=@CO_DOC_VEN_USU_ALI
,[CO_DOC_VEN_TOT_LET]=@CO_DOC_VEN_TOT_LET
,CO_DOC_VEN_VAL_IVA0=@CO_DOC_VEN_VAL_IVA0
,CO_DOC_VEN_OTR=@CO_DOC_VEN_OTR
,CO_DOC_VEN_SAL=@CO_DOC_VEN_SAL
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID

















GO
