SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_USUARIO_EMPRESA]
@EMP_RUC CHAR(13)
AS
SELECT     dbo.USUARIO.USUA_COD, dbo.USUARIO.USUA_ALI
FROM         dbo.CO_GRUPO INNER JOIN
                      dbo.CO_PERTENECE ON dbo.CO_GRUPO.CO_GRU_COD = dbo.CO_PERTENECE.CO_GRU_COD INNER JOIN
                      dbo.USUARIO ON dbo.CO_PERTENECE.USUA_COD = dbo.USUARIO.USUA_COD
WHERE CO_GRUPO.CO_EMP_RUC=@EMP_RUC
GO
