SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_HORAINGRESO_REGISTRO_DIARIO]
@CO_EMP_RUC CHAR(13),
@PROF_COD CHAR(10),
@CO_REG_DIA_FEC DATETIME
AS
SELECT CO_REG_DIA_HOR_ING
FROM CO_REGISTRO_DIARIO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PROF_COD=@PROF_COD AND
Convert(varchar(10),CO_REG_DIA_FEC,103)=Convert(varchar(10),@CO_REG_DIA_FEC,103)
GO
