SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_TRANSACCIONES]
@CO_EMP_RUC CHAR(13),
@CO_CC_NUM VARCHAR(10),
@CO_CON_BAN_FEC_INI DATETIME,
@CO_CON_BAN_FEC_FIN DATETIME,
@CO_TRA_OPC CHAR(1),
@CO_TIP_TRA_COD CHAR(2)
AS
IF(@CO_TRA_OPC='N')
	BEGIN
		SELECT CO_EMP_NOM,CO_CC_NUM,CO_CC_NOM,convert(nvarchar(10),CO_CON_BAN_FEC,101) as CO_CON_BAN_FEC,CO_TIP_TRA_COD,CO_TIP_COM_COD,
		CO_COM_NUM,CO_CON_BAN_VAL,CO_CON_BAN_DOC_NUM,CO_CON_BAN_NOM_BEN,CO_CON_BAN_AFE,CO_CC_SAL_INI,@CO_CON_BAN_FEC_INI AS INICIO,@CO_CON_BAN_FEC_FIN AS FIN,CO_CEN_COS_COD
		FROM CO_VW_SELECT_CONCILIACION_REPORTE
		WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
		(CO_CON_BAN_FEC>=@CO_CON_BAN_FEC_INI
		AND CO_CON_BAN_FEC<=@CO_CON_BAN_FEC_FIN) 
		AND CO_CC_NUM=@CO_CC_NUM
	END
ELSE
	BEGIN
		if(@CO_TRA_OPC='C')
		BEGIN
			SELECT CO_EMP_NOM,CO_CC_NUM,CO_CC_NOM,convert(nvarchar(10),CO_CON_BAN_FEC,101) as CO_CON_BAN_FEC,CO_TIP_TRA_COD,CO_TIP_COM_COD,
			CO_COM_NUM,CO_CON_BAN_VAL,CO_CON_BAN_DOC_NUM,CO_CON_BAN_NOM_BEN,CO_CON_BAN_AFE,CO_CC_SAL_INI,@CO_CON_BAN_FEC_INI AS INICIO,@CO_CON_BAN_FEC_FIN AS FIN,CO_CEN_COS_COD
			FROM CO_VW_SELECT_CONCILIACION_REPORTE
			WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
			(CO_CON_BAN_FEC>=@CO_CON_BAN_FEC_INI
			AND CO_CON_BAN_FEC<=@CO_CON_BAN_FEC_FIN) 
		END
		ELSE
		BEGIN
			if(@CO_TRA_OPC='T')
			BEGIN
			SELECT CO_EMP_NOM,CO_CC_NUM,CO_CC_NOM,convert(nvarchar(10),CO_CON_BAN_FEC,101) as CO_CON_BAN_FEC,CO_TIP_TRA_COD,CO_TIP_COM_COD,
			CO_COM_NUM,CO_CON_BAN_VAL,CO_CON_BAN_DOC_NUM,CO_CON_BAN_NOM_BEN,CO_CON_BAN_AFE,CO_CC_SAL_INI,@CO_CON_BAN_FEC_INI AS INICIO,@CO_CON_BAN_FEC_FIN AS FIN,CO_CEN_COS_COD
			FROM CO_VW_SELECT_CONCILIACION_REPORTE
			WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
			(CO_CON_BAN_FEC>=@CO_CON_BAN_FEC_INI
			AND CO_CON_BAN_FEC<=@CO_CON_BAN_FEC_FIN) 
			AND CO_CC_NUM=@CO_CC_NUM AND CO_TIP_TRA_COD=@CO_TIP_TRA_COD
			END
			ELSE
			BEGIN
			SELECT CO_EMP_NOM,CO_CC_NUM,CO_CC_NOM,convert(nvarchar(10),CO_CON_BAN_FEC,101) as CO_CON_BAN_FEC,CO_TIP_TRA_COD,CO_TIP_COM_COD,
			CO_COM_NUM,CO_CON_BAN_VAL,CO_CON_BAN_DOC_NUM,CO_CON_BAN_NOM_BEN,CO_CON_BAN_AFE,CO_CC_SAL_INI,@CO_CON_BAN_FEC_INI AS INICIO,@CO_CON_BAN_FEC_FIN AS FIN,CO_CEN_COS_COD
			FROM CO_VW_SELECT_CONCILIACION_REPORTE
			WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
			(CO_CON_BAN_FEC>=@CO_CON_BAN_FEC_INI
			AND CO_CON_BAN_FEC<=@CO_CON_BAN_FEC_FIN) 
			AND CO_CC_NUM=@CO_CC_NUM AND CO_TIP_TRA_COD=@CO_TIP_TRA_COD
			END
			
		END

	END
GO
