SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_SELECT_FORMATO_CUENTAS]
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_CONFIG_NIVEL.CO_CON_NUM, dbo.CO_CONFIG_NIVEL.CO_CON_NUM_DIG, dbo.CO_CONFIG_FPC.CO_CON_SEP
FROM dbo.CO_CONFIG_FPC INNER JOIN
dbo.CO_CONFIG_NIVEL ON 
dbo.CO_CONFIG_FPC.CO_CON_COD = dbo.CO_CONFIG_NIVEL.CO_CON_COD
WHERE dbo.CO_CONFIG_FPC.CO_EMP_RUC=@CO_EMP_RUC
ORDER BY dbo.CO_CONFIG_NIVEL.CO_CON_NUM
GO
