SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_IDENTIFICACION_PROVEEDOR]
@CO_TIP_IDE_PRO_COD nvarchar(10)
AS
DELETE [dbo].[CO_TIPO_IDENTIFICACION_PROVEEDOR]
WHERE 
[CO_TIP_IDE_PRO_COD]=@CO_TIP_IDE_PRO_COD
GO
