SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DETALLE_DOCUMENTO_VENTA]
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
AS
SELECT * FROM CO_DETALLE_DOCUMENTO_VENTA
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID
GO
