SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_RETENCION_COMPRA]
@CO_DOC_COM_ID UNIQUEIDENTIFIER
AS
SELECT * FROM [dbo].[CO_RETENCION]
WHERE CO_DOC_COM_ID=@CO_DOC_COM_ID
GO
