SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PARAMETRO_RENTA_RANGO]
@CO_PAR_REN_CAN DECIMAL
AS
SELECT CO_PAR_REN_LIM_INF,CO_PAR_REN_VAL_BAS,CO_PAR_REN_POR_DIF FROM CO_PARAMETRO_RENTA
WHERE @CO_PAR_REN_CAN between co_par_ren_lim_inf and co_par_ren_lim_sup
GO
