SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_EMPLEADOS]
@CO_UBI_COD INT
,@CO_EMP_RUC CHAR(13)
,@PROF_NAC_FEC INT
,@PROF_OPC INT
AS
IF @PROF_OPC=1
	SELECT dbo.PROFESOR.*, dbo.CO_CARGO.CO_CAR_NOM,dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_CARGO ON dbo.PROFESOR.CO_CAR_COD = dbo.CO_CARGO.CO_CAR_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_CARGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC	
	WHERE dbo.PROFESOR.CO_EMP_RUC=@CO_EMP_RUC
IF @PROF_OPC=2
	SELECT dbo.PROFESOR.*, dbo.CO_CARGO.CO_CAR_NOM,dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_CARGO ON dbo.PROFESOR.CO_CAR_COD = dbo.CO_CARGO.CO_CAR_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_CARGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
	WHERE dbo.PROFESOR.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.PROF_EST='Activo'
IF @PROF_OPC=3
	SELECT dbo.PROFESOR.*, dbo.CO_CARGO.CO_CAR_NOM,dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_CARGO ON dbo.PROFESOR.CO_CAR_COD = dbo.CO_CARGO.CO_CAR_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_CARGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
	WHERE dbo.PROFESOR.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD
IF @PROF_OPC=4
	SELECT dbo.PROFESOR.*, dbo.CO_CARGO.CO_CAR_NOM,dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_CARGO ON dbo.PROFESOR.CO_CAR_COD = dbo.CO_CARGO.CO_CAR_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_CARGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
	WHERE dbo.PROFESOR.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD AND dbo.PROFESOR.PROF_EST='Activo'
IF @PROF_OPC=5
	SELECT dbo.PROFESOR.*, dbo.CO_CARGO.CO_CAR_NOM,dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_CARGO ON dbo.PROFESOR.CO_CAR_COD = dbo.CO_CARGO.CO_CAR_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_CARGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
	WHERE dbo.PROFESOR.CO_EMP_RUC=@CO_EMP_RUC AND MONTH(dbo.PROFESOR.PROF_NAC_FEC)=@PROF_NAC_FEC
IF @PROF_OPC=6
	SELECT dbo.PROFESOR.*, dbo.CO_CARGO.CO_CAR_NOM,dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_CARGO ON dbo.PROFESOR.CO_CAR_COD = dbo.CO_CARGO.CO_CAR_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_CARGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
	WHERE dbo.PROFESOR.CO_EMP_RUC=@CO_EMP_RUC AND MONTH(dbo.PROFESOR.PROF_NAC_FEC)=@PROF_NAC_FEC AND dbo.PROFESOR.PROF_EST='Activo'
GO
