SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ASIENTOS_PERIODO]
@CO_FEC_INI DATETIME,
@CO_FEC_FIN DATETIME,
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_CUENTA.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, ROUND(SUM(dbo.CO_ASIENTO.CO_ASI_DEB), 2) AS CO_ASI_DEB, 
ROUND(SUM(dbo.CO_ASIENTO.CO_ASI_HAB), 2) AS CO_ASI_HAB, dbo.CO_CUENTA.CO_CUE_COD_ANT
FROM dbo.CO_CUENTA INNER JOIN
dbo.CO_ASIENTO ON dbo.CO_CUENTA.CO_EMP_RUC = dbo.CO_ASIENTO.CO_EMP_RUC AND 
dbo.CO_CUENTA.CO_CUE_COD = dbo.CO_ASIENTO.CO_CUE_COD INNER JOIN
dbo.CO_COMPROBANTE ON dbo.CO_ASIENTO.CO_EMP_RUC = dbo.CO_COMPROBANTE.CO_EMP_RUC AND 
dbo.CO_ASIENTO.CO_TIP_COM_COD = dbo.CO_COMPROBANTE.CO_TIP_COM_COD AND 
dbo.CO_ASIENTO.CO_COM_NUM = dbo.CO_COMPROBANTE.CO_COM_NUM
WHERE dbo.CO_CUENTA.CO_EMP_RUC=@CO_EMP_RUC AND 
(CO_COM_FEC>=@CO_FEC_INI
AND CO_COM_FEC<=@CO_FEC_FIN)
GROUP BY dbo.CO_CUENTA.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, dbo.CO_CUENTA.CO_CUE_COD_ANT, dbo.CO_CUENTA.CO_EMP_RUC, 
dbo.CO_COMPROBANTE.CO_COM_EST
HAVING (dbo.CO_COMPROBANTE.CO_COM_EST = 'ACTIVO')

GO
