SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_UPDATE_PAGO_PROVEEDOR]
@CO_PAG_PRO_COD int
,@CO_PAG_PRO_VAL float
,@CO_PAG_PRO_FEC datetime
,@CO_PAG_PRO_EST bit
,@CO_PAG_PRO_CON nvarchar(50)
,@CO_PAG_PRO_VAL_IMP float
AS
UPDATE [dbo].[CO_PAGO_PROVEEDOR] SET
[CO_PAG_PRO_VAL]=@CO_PAG_PRO_VAL
,[CO_PAG_PRO_FEC]=@CO_PAG_PRO_FEC
,[CO_PAG_PRO_EST]=@CO_PAG_PRO_EST
,[CO_PAG_PRO_CON]=@CO_PAG_PRO_CON
,[CO_PAG_PRO_VAL_IMP]=@CO_PAG_PRO_VAL_IMP
WHERE CO_PAG_PRO_COD=@CO_PAG_PRO_COD
GO
