SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_COMPROBANTE]
@CO_EMP_RUC CHAR(13),
@CO_TIP_COM_COD int,
@CO_TIP_COM_NOM VARCHAR(20),
@CO_TIP_COM_INI INT
AS
INSERT INTO CO_TIPO_COMPROBANTE VALUES(
@CO_EMP_RUC,
@CO_TIP_COM_COD,
@CO_TIP_COM_NOM,
@CO_TIP_COM_INI)
GO
