SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PARAMETRO_COMPRAS]
@CO_EMP_RUC char(13)
AS
SELECT * FROM [dbo].[CO_PARAMETRO_COMPRA]
WHERE
([CO_EMP_RUC]=@CO_EMP_RUC)
GO
