SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PROYECTO]
@CO_PRO_COD int
,@CO_EMP_RUC char(13)
,@CO_PRO_NOM nvarchar(150)
,@CO_PRO_DES nvarchar(150)
,@CO_PRO_TIP nvarchar(10)
AS
INSERT INTO [dbo].[CO_PROYECTO]
([CO_PRO_COD]
,[CO_EMP_RUC]
,[CO_PRO_NOM]
,[CO_PRO_DES]
,[CO_PRO_TIP])
VALUES
(@CO_PRO_COD
,@CO_EMP_RUC
,@CO_PRO_NOM
,@CO_PRO_DES
,@CO_PRO_TIP)
GO
