SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_DETALLE_PROFORMA_BAJA_PROCESADO]
@CO_PRO_COD INT
,@CO_EMP_RUC CHAR(13)
,@CO_ART_COD VARCHAR(50)
,@CANTIDAD INT
AS
UPDATE [dbo].[CO_DETALLE_PROFORMA] SET [CANTIDAD_PROCESADA]=CANTIDAD_PROCESADA-@CANTIDAD
, [ESTADO]=CASE WHEN CANTIDAD_PROCESADA-@CANTIDAD>=[CO_DET_PRO_CAN] THEN 'PROCESADO' ELSE 'PENDIENTE' END
WHERE CO_EMP_RUC=@CO_EMP_RUC AND [CO_PRO_COD]=@CO_PRO_COD AND [CO_DET_PRO_ART_COD]=@CO_ART_COD


DECLARE @CONTADOR_PROCESADOS INT 
DECLARE @CONTADOR_PENDIENTES INT

SELECT @CONTADOR_PROCESADOS=COUNT(*) FROM [dbo].[CO_DETALLE_PROFORMA] WHERE CO_EMP_RUC=@CO_EMP_RUC AND [CO_PRO_COD]=@CO_PRO_COD AND ESTADO='PROCESADO' OR ESTADO='ANULADO'
SELECT @CONTADOR_PENDIENTES=COUNT(*) FROM [dbo].[CO_DETALLE_PROFORMA] WHERE CO_EMP_RUC=@CO_EMP_RUC AND [CO_PRO_COD]=@CO_PRO_COD AND ESTADO='PENDIENTE'

IF @CONTADOR_PROCESADOS=@CONTADOR_PENDIENTES
BEGIN
	UPDATE [dbo].[CO_PROFORMA] SET CO_PRO_EST='PROCESADO'
	WHERE CO_EMP_RUC=@CO_EMP_RUC AND [CO_PRO_COD]=@CO_PRO_COD
END
ELSE
BEGIN
	UPDATE [dbo].[CO_PROFORMA] SET CO_PRO_EST='ACTIVA'
	WHERE CO_EMP_RUC=@CO_EMP_RUC AND [CO_PRO_COD]=@CO_PRO_COD
END
GO
