SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_PROFORMA]
@CO_PRO_COD int,
@CO_EMP_RUC char(13)
AS
SELECT * FROM CO_VW_SELECT_REPORTE_PROFORMA
WHERE CO_PRO_COD=@CO_PRO_COD AND CO_EMP_RUC=@CO_EMP_RUC
order by CO_DET_PRO_ART_COD
GO
