SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_COBRO_CLIENTE]
@CO_EMP_RUC CHAR(13)
AS
SELECT ISNULL(MAX(CO_COM_COB_CLI_NUM),0) AS CO_COB_CLI_MAX
FROM CO_COBRO_CLIENTE
WHERE CO_EMP_RUC=@CO_EMP_RUC 
GO
