SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_PROFORMA]
@CO_EMP_RUC char(13)
AS
SELECT MAX(CO_PRO_COD) AS CONTADOR FROM CO_PROFORMA
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
