SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PARAMETRO_NOMINA]
@CO_EMP_RUC char(13)
,@CO_PAR_NOM_NOT_DEB_TIP_COM nvarchar(50)
,@CO_PAR_NOM_NOT_DEB_TIP_COM_COD int
,@CO_PAR_NOM_NOT_DEB_MOD_FEC bit
,@CO_PAR_NOM_NOT_DEB_MOD_NUM bit
,@CO_PAR_NOM_REG_HOR_ING nchar(5)
,@CO_PAR_NOM_REG_HOR_SAL nchar(5)
,@CO_PAR_NOM_REG_MIN_DES nchar(5)
,@CO_PAR_NOM_REG_TIE_LUN nchar(5)
,@CO_PAR_NOM_ROL_RUB_SUE int
,@CO_PAR_NOM_NOT_DEB_CUE_DEB varchar(40)
,@CO_PAR_NOM_NOT_DEB_CUE_HAB_EFE varchar(40)
,@CO_PAR_NOM_ROL_TIP_COM_COD INT
,@CO_PAR_NOM_ROL_CUE_HAB_EFE varchar(40)
,@CO_PAR_NOM_ROL_CUE_SUE_PAG varchar(40)
,@CO_PAR_NOM_NOT_DEB_ASI_AUT bit
,@CO_PAR_NOM_ROL_ASI_AUT bit
AS
INSERT INTO [dbo].[CO_PARAMETRO_NOMINA]
([CO_EMP_RUC]
,[CO_PAR_NOM_NOT_DEB_TIP_COM]
,[CO_PAR_NOM_NOT_DEB_TIP_COM_COD]
,[CO_PAR_NOM_NOT_DEB_MOD_FEC]
,[CO_PAR_NOM_NOT_DEB_MOD_NUM]
,CO_PAR_NOM_REG_HOR_ING
,CO_PAR_NOM_REG_HOR_SAL
,CO_PAR_NOM_REG_MIN_DES
,CO_PAR_NOM_REG_TIE_LUN
,CO_PAR_NOM_ROL_RUB_SUE
,CO_PAR_NOM_NOT_DEB_CUE_DEB
,CO_PAR_NOM_NOT_DEB_CUE_HAB_EFE
,CO_PAR_NOM_ROL_TIP_COM_COD
,CO_PAR_NOM_ROL_CUE_HAB_EFE
,CO_PAR_NOM_ROL_CUE_SUE_PAG
,CO_PAR_NOM_NOT_DEB_ASI_AUT
,CO_PAR_NOM_ROL_ASI_AUT)
VALUES
(@CO_EMP_RUC
,@CO_PAR_NOM_NOT_DEB_TIP_COM
,@CO_PAR_NOM_NOT_DEB_TIP_COM_COD
,@CO_PAR_NOM_NOT_DEB_MOD_FEC
,@CO_PAR_NOM_NOT_DEB_MOD_NUM
,@CO_PAR_NOM_REG_HOR_ING
,@CO_PAR_NOM_REG_HOR_SAL
,@CO_PAR_NOM_REG_MIN_DES
,@CO_PAR_NOM_REG_TIE_LUN
,@CO_PAR_NOM_ROL_RUB_SUE
,@CO_PAR_NOM_NOT_DEB_CUE_DEB
,@CO_PAR_NOM_NOT_DEB_CUE_HAB_EFE
,@CO_PAR_NOM_ROL_TIP_COM_COD
,@CO_PAR_NOM_ROL_CUE_HAB_EFE
,@CO_PAR_NOM_ROL_CUE_SUE_PAG
,@CO_PAR_NOM_NOT_DEB_ASI_AUT
,@CO_PAR_NOM_ROL_ASI_AUT)
GO
