SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PROFORMA_CONTADOR]
@CO_PRO_COD INT,
@CO_EMP_RUC CHAR(13)
AS
SELECT COUNT(*) FROM CO_PROFORMA WHERE CO_PRO_COD=@CO_PRO_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
