SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ANEXOS_VENTAS]
@CO_ANE_MES int,
@CO_ANE_ANIO int,
@CO_EMP_RUC char(13)
AS
SELECT *, 
CAST(ISNULL(dbo.CO_FN_RENTA_VENTAS(CO_EMP_RUC,idCliente,@CO_ANE_MES,@CO_ANE_ANIO),0) AS FLOAT) as valorRetRenta
FROM CO_VW_SELECT_ANEXOS_VENTAS
WHERE CO_DOC_VEN_EST<>'ANULADA' AND MES=@CO_ANE_MES AND
ANIO=@CO_ANE_ANIO AND CO_EMP_RUC=@CO_EMP_RUC
GO
