SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_PAGO_PROVEEDOR]
@CO_EMP_RUC CHAR(13)
,@CO_COM_PAG_FEC1 DATETIME
,@CO_COM_PAG_FEC2 DATETIME
,@CO_PRO_COD NVARCHAR(50)
,@CO_COM_PAG_OPC CHAR(1)
AS
IF (@CO_COM_PAG_OPC='F')
SELECT * FROM CO_VW_SELECT_BUCAR_PAGOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
CO_COM_PAG_FEC>=@CO_COM_PAG_FEC1
AND CO_COM_PAG_FEC<=@CO_COM_PAG_FEC2
ELSE IF (@CO_COM_PAG_OPC='C')
SELECT * FROM CO_VW_SELECT_BUCAR_PAGOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
CO_COM_PAG_FEC>=@CO_COM_PAG_FEC1
AND CO_COM_PAG_FEC<=@CO_COM_PAG_FEC2
AND CO_PRO_COD=@CO_PRO_COD
GO
