SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_DOCUMENTO_RESERVA]
@CO_EMP_RUC CHAR(13)
,@CO_CLI_NOM NVARCHAR(100)
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
AS
DECLARE @LIKE AS VARCHAR(50)
SET @LIKE='%'+@CO_CLI_NOM+'%'
SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_DOCUMENTO_RESERVA.*, dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_NOM, 
	   dbo.CO_CLIENTE.CO_CLI_CED, dbo.CO_CLIENTE.CO_CLI_CIU, dbo.CO_CLIENTE.CO_CLI_DIR
FROM dbo.CO_CLIENTE INNER JOIN
dbo.CO_DOCUMENTO_RESERVA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_DOCUMENTO_RESERVA.CO_CLI_COD AND 
dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_DOCUMENTO_RESERVA.CO_EMP_RUC AND 
dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_DOCUMENTO_RESERVA.CO_TIP_CLI_COD INNER JOIN
dbo.CO_TIPO_IDENTIFICACION ON dbo.CO_CLIENTE.CO_TIP_IDE_COD = dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD
WHERE dbo.CO_CLIENTE.CO_CLI_NOM like @LIKE AND dbo.CO_DOCUMENTO_RESERVA.CO_EMP_RUC=@CO_EMP_RUC 
AND (dbo.CO_DOCUMENTO_RESERVA.CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND dbo.CO_DOCUMENTO_RESERVA.CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2)
AND dbo.CO_DOCUMENTO_RESERVA.CO_EMP_RUC=@CO_EMP_RUC
--AND (SELECT CO_ALM_COD FROM dbo.CO_BODEGA WHERE CO_BOD_COD=dbo.CO_DOCUMENTO_VENTA.CO_BOD_COD)=@CO_ALM_COD
ORDER BY dbo.CO_DOCUMENTO_RESERVA.CO_DOC_VEN_NUM





GO
