SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_COMPROBANTE_COBRO]
@CO_EMP_RUC CHAR(13)
AS
SELECT MAX(CO_COM_COB_NUM) AS CO_COM_COB_MAX
FROM CO_COMPROBANTE_COBRO
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
