SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ASIENTOS_MES_RESULTADOS]
@CO_ASI_FEC_INI DATETIME,
@CO_ASI_FEC_FIN DATETIME,
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_CUENTA.CO_CUE_COD,
dbo.CO_CUENTA.CO_CUE_NOM,
ROUND(SUM(dbo.CO_ASIENTO.CO_ASI_DEB), 2) AS CO_ASI_DEB, 
ROUND(SUM(dbo.CO_ASIENTO.CO_ASI_HAB), 2) AS CO_ASI_HAB, 
 dbo.CO_CUENTA.CO_CUE_COD_ANT
FROM dbo.CO_CUENTA INNER JOIN
dbo.CO_ASIENTO ON dbo.CO_CUENTA.CO_EMP_RUC = dbo.CO_ASIENTO.CO_EMP_RUC AND 
dbo.CO_CUENTA.CO_CUE_COD = dbo.CO_ASIENTO.CO_CUE_COD
WHERE (dbo.CO_CUENTA.CO_CUE_COD LIKE '4.%' OR  dbo.CO_CUENTA.CO_CUE_COD LIKE '5.%')
--AND dbo.CO_CUENTA.CO_EMP_RUC=@CO_EMP_RUC
--(CONVERT(NVARCHAR(10),dbo.CO_ASIENTO.CO_ASI_FEC,101) >= CONVERT(NVARCHAR(10),@CO_ASI_FEC_INI,101) 
--AND CONVERT(NVARCHAR(10),dbo.CO_ASIENTO.CO_ASI_FEC,101) <= CONVERT(NVARCHAR(10),@CO_ASI_FEC_FIN,101) )
GROUP BY dbo.CO_CUENTA.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, dbo.CO_CUENTA.CO_CUE_COD_ANT, dbo.CO_CUENTA.CO_EMP_RUC
GO
