SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_NOCONCILIADO_ESTADO]
@CO_MOV_NOC_COD INT,
@CO_EMP_RUC CHAR(13)
AS
UPDATE CO_MOVIENTO_NOCONCILIADO SET
CO_MOV_NOC_EST=1
WHERE CO_MOV_NOC_COD=@CO_MOV_NOC_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
