SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PROFORMA]
(@CO_PRO_COD int
,@CO_EMP_RUC char(13))
AS
UPDATE [dbo].[CO_PROFORMA]  SET CO_PRO_EST='ANULADA'
WHERE
([CO_PRO_COD]=@CO_PRO_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
