SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PROYECTO_INGRESOS]
@CO_EMP_RUC char(13)
AS
SELECT     dbo.CO_PROYECTO.CO_PRO_NOM, dbo.CO_TIPO_RECURSO.CO_TIP_REC_NOM, dbo.CO_PROYECTO_INGRESOS.CO_ING_NOM, 
                      dbo.CO_PROYECTO_INGRESOS.CO_ING_MAN, dbo.CO_PROYECTO_INGRESOS.CO_ING_CUE, dbo.CO_PROYECTO_INGRESOS.CO_ING_COD, 
                      dbo.CO_PROYECTO_INGRESOS.CO_TIP_REC_COD, dbo.CO_PROYECTO_INGRESOS.CO_PRO_COD
FROM         dbo.CO_PROYECTO INNER JOIN
                      dbo.CO_PROYECTO_INGRESOS ON dbo.CO_PROYECTO.CO_PRO_COD = dbo.CO_PROYECTO_INGRESOS.CO_PRO_COD AND 
                      dbo.CO_PROYECTO.CO_EMP_RUC = dbo.CO_PROYECTO_INGRESOS.CO_EMP_RUC INNER JOIN
                      dbo.CO_TIPO_RECURSO ON dbo.CO_PROYECTO_INGRESOS.CO_TIP_REC_COD = dbo.CO_TIPO_RECURSO.CO_TIP_REC_COD AND 
                      dbo.CO_PROYECTO_INGRESOS.CO_EMP_RUC = dbo.CO_TIPO_RECURSO.CO_EMP_RUC
WHERE dbo.CO_PROYECTO.[CO_EMP_RUC]=@CO_EMP_RUC
GO
