SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_GRUPO_OCUPACIONAL]
@CO_GRU_OCU_COD int
,@CO_EMP_RUC char(13)
AS
DELETE [dbo].[CO_GRUPO_OCUPACIONAL]
WHERE 
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_GRU_OCU_COD]=@CO_GRU_OCU_COD)
GO
