SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CLIENTE_IDENTIFICACION]
@CO_EMP_RUC char(13)
,@CO_CLI_COD NVARCHAR(13)
AS
SELECT * FROM [dbo].[CO_CLIENTE] 
WHERE [CO_EMP_RUC]=@CO_EMP_RUC AND CO_CLI_COD=@CO_CLI_COD


GO
