SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FORMULARIO_104]
@CO_IMP_ANO INT
,@CO_IMP_MES INT
,@CO_EMP_RUC CHAR(13)
AS
SELECT   (select COUNT(CO_DOC_VEN_NUM) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=18 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO)  AS NUM_FACTURAS,
(select SUM(CO_DOC_VEN_TOT_NET-CO_DOC_VEN_DES) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=18 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO) AS FAC_IVA12,(select SUM(CO_DOC_VEN_TOT_NET) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=4 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO)  AS NCIVA12,
(select SUM(CO_DOC_VEN_VAL_IVA0) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=18 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO)AS FAC_IVA0,(select SUM(CO_DOC_VEN_VAL_IVA0) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=4 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO)  AS NCIVA0,
(select COUNT(CO_DOC_VEN_NUM) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=5 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO)  AS NUM_NOTASD,
(select COUNT(CO_DOC_VEN_NUM) from CO_DOCUMENTO_VENTA where CO_DOC_VEN_EST='ACTIVA' AND CO_TIP_DOC_VEN_NUM=4 and CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO)  AS NUM_NOTASC
FROM dbo.CO_DOCUMENTO_VENTA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND MONTH(CO_DOC_VEN_FEC)=@CO_IMP_MES AND YEAR(CO_DOC_VEN_FEC)=@CO_IMP_ANO
GO
