SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DOCUMENTO_VENTA_CONTADOR]
@CO_EMP_RUC CHAR(13),
@CO_DOC_VEN_NUM NVARCHAR(20),
@CO_TIP_DOC_VEN_NUM int
AS
SELECT ISNULL(COUNT(*),0) FROM dbo.CO_DOCUMENTO_VENTA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_DOC_VEN_NUM=@CO_DOC_VEN_NUM AND CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM
GO
