SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_CRUCE_SUSTENTO]
@CO_TIP_SUS_COD nvarchar(5)
,@CO_TIP_COM_COM_COD int
AS
DELETE [dbo].[CO_CRUCE_SUSTENTO]
WHERE
[CO_TIP_COM_COM_COD]=@CO_TIP_COM_COM_COD AND
[CO_TIP_SUS_COD]=@CO_TIP_SUS_COD
GO
