SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_PAGO_PROVEEDOR_PLUS]
@CODIGO_PAGO_PROVEEDOR int
AS
SELECT     CODIGO_PAGO_PROVEEDOR, CODIGO_DOCUMENTO_PAGO, FORMA_PAGO_PROVEEDOR, NUMERO_PAGO_PROVEEDOR, CO_CC_NUM, 
                      VALOR_PAGO_PROVEEDOR, FECHA_PAGO_PROVEEDOR, ESTADO_PAGO_PROVEEDOR, USUARIO_NOMBRE, CO_EMP_RUC, CO_PRO_COD
FROM         dbo.CO_PAGO_PROVEEDORES_PLUS
WHERE     (CODIGO_PAGO_PROVEEDOR = @CODIGO_PAGO_PROVEEDOR)
GO
