SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PAGO_DOCUMENTO_VENTA_ANULA]
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
AS
DELETE CO_PAGO_DOCUMENTO_VENTA
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID
GO
