SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CRUCE_SUSTENTO]
@CO_TIP_SUS_COD nvarchar(5),
@CO_TIP_COM_COM_COD int,
@CO_CRUCE_SUSTENTO_CI bit,
@CO_CRUCE_SUSTENTO_RUC bit,
@CO_CRUCE_SUSTENTO_PASAPORTE bit
AS
INSERT INTO CO_CRUCE_SUSTENTO
		(CO_TIP_SUS_COD, CO_TIP_COM_COM_COD, CO_CRUCE_SUSTENTO_CI, CO_CRUCE_SUSTENTO_RUC, CO_CRUCE_SUSTENTO_PASAPORTE)
VALUES	(@CO_TIP_SUS_COD,@CO_TIP_COM_COM_COD,@CO_CRUCE_SUSTENTO_CI,@CO_CRUCE_SUSTENTO_RUC,@CO_CRUCE_SUSTENTO_PASAPORTE)
GO
