SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ARTICULO_KARDEX_ANTERIOR]
@CO_EMP_RUC CHAR(13)
,@CO_ART_COD NVARCHAR(20)
,@CO_BOD_COD INT
AS
SELECT TOP 1 dbo.CO_KARDEX_TOTAL.CO_ART_COD, dbo.CO_KARDEX_TOTAL.CO_EMP_RUC, dbo.CO_KARDEX_TOTAL.CO_BOD_COD,
					dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_ARTICULO.CO_ART_COD_FAB, dbo.CO_ARTICULO.CO_ART_MAR, CO_ART_COL,
					CO_ART_EXI_MIN, CO_ART_EXI_MAX, CO_ART_UNI, CO_ART_POR_IVA,
					CO_ART_TIP, CO_ICE_COD, 0 AS PVP, dbo.CO_BODEGA.CO_BOD_NOM,
					CO_ART_PES, CO_ART_BAR, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT, 
				    dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_UNI, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_TOT
	FROM	dbo.CO_ARTICULO INNER JOIN
			dbo.CO_UBICACIONARTICULO ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_UBICACIONARTICULO.CO_ART_COD AND 
			dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_UBICACIONARTICULO.CO_EMP_RUC INNER JOIN
			dbo.CO_KARDEX_TOTAL ON dbo.CO_UBICACIONARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
			dbo.CO_UBICACIONARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC AND 
			dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_KARDEX_TOTAL.CO_BOD_COD INNER JOIN
			 dbo.CO_BODEGA ON dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_BODEGA.CO_BOD_COD
	where dbo.CO_KARDEX_TOTAL.CO_EMP_RUC=@CO_EMP_RUC
			AND dbo.CO_KARDEX_TOTAL.CO_BOD_COD=@CO_BOD_COD 
			AND dbo.CO_KARDEX_TOTAL.CO_ART_COD=@CO_ART_COD
	ORDER BY CO_KAR_TOT_FEC DESC
GO
