SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_CLAVE]
@CO_EMP_RUC VARCHAR(15),
@USUA_ALI VARCHAR(15),
@USUA_CLA VARCHAR(100)
AS
SELECT dbo.USUARIO.USUA_COD, dbo.USUARIO.USUA_EST, dbo.USUARIO.USUA_FEC_FIN, dbo.USUARIO.USUA_CLA, 
dbo.CO_EMPRESA.CO_EMP_NOM, dbo.USUARIO.USUA_NOM, dbo.CO_GRUPO.CO_EMP_ESCONTADOR
FROM dbo.CO_GRUPO INNER JOIN
dbo.CO_PERTENECE ON dbo.CO_GRUPO.CO_GRU_COD = dbo.CO_PERTENECE.CO_GRU_COD INNER JOIN
dbo.USUARIO ON dbo.CO_PERTENECE.USUA_COD = dbo.USUARIO.USUA_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_GRUPO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE USUA_CLA=@USUA_CLA AND USUA_ALI=@USUA_ALI AND dbo.CO_GRUPO.CO_EMP_RUC=@CO_EMP_RUC
GO
