SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_RUBROS_ROL_MENSUAL2]
@CO_EMP_RUC CHAR(13),
@CO_ROL_CAB_MES1 int,
@CO_ROL_CAB_ANO1 INT,
@CO_ROL_CAB_MES2 int,
@CO_ROL_CAB_ANO2 INT

AS
SELECT PROF_COD,CO_ROL_CAB_VAL,cast(CO_ROL_CAB_ANO as varchar(10))+'-'+cast(CO_ROL_CAB_MES as varchar(10)) as mes FROM CO_CABECERA_ROL
WHERE CO_EMP_RUC=@CO_EMP_RUC and (co_rol_cab_mes>=@CO_ROL_CAB_MES1 and CO_ROL_CAB_ANO>=@CO_ROL_CAB_ANO1) and
(co_rol_cab_mes<=@CO_ROL_CAB_MES2 and CO_ROL_CAB_ANO<=@CO_ROL_CAB_ANO2)
GO
