SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_CLIENTE]
@CO_TIP_CLI_COD nvarchar(50)
,@CO_EMP_RUC char(13)
,@CO_TIP_CLI_NOM nvarchar(50)
,@CO_TIP_CLI_CUE nvarchar(40)
AS
INSERT INTO [dbo].[CO_TIPO_CLIENTE]
([CO_TIP_CLI_COD]
,[CO_EMP_RUC]
,[CO_TIP_CLI_NOM]
,[CO_TIP_CLI_CUE])
VALUES
(@CO_TIP_CLI_COD
,@CO_EMP_RUC
,@CO_TIP_CLI_NOM
,@CO_TIP_CLI_CUE)
GO
