SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ANEXO_COMPRAS]
@CO_ANE_MES int,
@CO_ANE_ANIO int,
@CO_EMP_RUC char(13)
AS
SELECT *
FROM CO_VW_SELECT_REOC
WHERE month(fechaEmision)=@CO_ANE_MES AND
year(fechaEmision)=@CO_ANE_ANIO AND EmpresaRuc=@CO_EMP_RUC
GO
