SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PARAMETRO_VENTA]
(@CO_EMP_RUC char(13)
,@CO_PAR_VEN_COB_TIP_COM nvarchar(50)
,@CO_PAR_VEN_COB_TIP_COM_COD int
,@CO_PAR_VEN_COB_CUE_DEB varchar(40)
,@CO_PAR_VEN_COB_CUE_HAB varchar(40)
,@CO_PAR_VEN_COB_MOD_NUM bit
,@CO_PAR_VEN_COB_MOD_FEC bit
,@CO_PAR_VEN_COB_MOD_VAL_CUO bit
,@CO_PAR_VEN_COB_NUM_INI int
,@CO_PAR_VEN_COB_ASI_AUT bit
,@CO_PAR_VEN_PRO_TIP_PRE nchar(1)
,@CO_PAR_VEN_PRO_NUM_INI int
,@CO_PAR_VEN_PRO_NUM_FIL int)
AS
INSERT INTO [dbo].[CO_PARAMETRO_VENTA]
([CO_EMP_RUC]
,[CO_PAR_VEN_COB_TIP_COM]
,[CO_PAR_VEN_COB_TIP_COM_COD]
,[CO_PAR_VEN_COB_CUE_DEB]
,[CO_PAR_VEN_COB_CUE_HAB]
,[CO_PAR_VEN_COB_MOD_NUM]
,[CO_PAR_VEN_COB_MOD_FEC]
,[CO_PAR_VEN_COB_MOD_VAL_CUO]
,[CO_PAR_VEN_COB_NUM_INI]
,[CO_PAR_VEN_COB_ASI_AUT]
,[CO_PAR_VEN_PRO_TIP_PRE]
,[CO_PAR_VEN_PRO_NUM_INI]
,[CO_PAR_VEN_PRO_NUM_FIL])
VALUES
(@CO_EMP_RUC
,@CO_PAR_VEN_COB_TIP_COM
,@CO_PAR_VEN_COB_TIP_COM_COD
,@CO_PAR_VEN_COB_CUE_DEB
,@CO_PAR_VEN_COB_CUE_HAB
,@CO_PAR_VEN_COB_MOD_NUM
,@CO_PAR_VEN_COB_MOD_FEC
,@CO_PAR_VEN_COB_MOD_VAL_CUO
,@CO_PAR_VEN_COB_NUM_INI
,@CO_PAR_VEN_COB_ASI_AUT
,@CO_PAR_VEN_PRO_TIP_PRE
,@CO_PAR_VEN_PRO_NUM_INI
,@CO_PAR_VEN_PRO_NUM_FIL)
GO
