SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_RETENCION]
@CO_EMP_RUC CHAR(13),
@CO_CUE_COD_COM VARCHAR(40),
@CO_CUE_COD_VEN VARCHAR(40),
@CO_TIP_RET_NOM VARCHAR(50),
@CO_TIP_RET_POR FLOAT,
@CO_TIP_USU_ALI VARCHAR(15),
@CO_TIP_RET_COD_SRI VARCHAR(20)
AS
INSERT INTO CO_TIPO_RETENCION VALUES(
@CO_EMP_RUC,
@CO_CUE_COD_COM,
@CO_TIP_RET_NOM,
@CO_TIP_RET_POR,
@CO_TIP_USU_ALI,
@CO_CUE_COD_VEN,
@CO_TIP_RET_COD_SRI)

GO
