SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_USUARIOS]
@CO_EMP_RUC CHAR(13)
AS
SELECT     dbo.USUARIO.USUA_NOM, dbo.USUARIO.USUA_ALI, dbo.USUARIO.USUA_EST, dbo.USUARIO.USUA_CLA, dbo.CO_GRUPO.CO_GRU_NOM, 
                      dbo.CO_EMPRESA.CO_EMP_NOM
FROM         dbo.USUARIO INNER JOIN
                      dbo.CO_PERTENECE ON dbo.USUARIO.USUA_COD = dbo.CO_PERTENECE.USUA_COD INNER JOIN
                      dbo.CO_GRUPO ON dbo.CO_PERTENECE.CO_GRU_COD = dbo.CO_GRUPO.CO_GRU_COD INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_GRUPO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_GRUPO.CO_EMP_RUC=@CO_EMP_RUC
GO
