SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_RESUMEN_VENTAS_TOTALES]
@CO_EMP_RUC CHAR(13)
,@CO_RES_OPC CHAR(1)
,@CO_CLI_COD NVARCHAR(50)
,@CO_VEN_CED NCHAR(10)
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
AS
IF(@CO_RES_OPC='N')
SELECT CO_EMP_NOM,CO_EMP_CIU,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_NET) * -1 ELSE SUM(CO_DOC_VEN_TOT_NET) END AS TOTAL_NETO,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_DES) * -1 ELSE SUM(CO_DOC_VEN_DES) END AS DESCUENTOS,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_IVA) * -1 ELSE SUM(CO_DOC_VEN_IVA) END AS IVA,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_PAG) * -1 ELSE SUM(CO_DOC_VEN_TOT_PAG) END AS TOTAL,
COUNT(CO_TIP_DOC_VEN_NUM) AS CONTADOR,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_RESUMEN_VENTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
AND CO_TIP_DOC_VEN_NUM IN (4,18)
GROUP BY CO_TIP_DOC_VEN_NUM,CO_EMP_NOM,CO_EMP_CIU
ELSE IF(@CO_RES_OPC='C')
SELECT CO_EMP_NOM,CO_EMP_CIU,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_NET) * -1 ELSE SUM(CO_DOC_VEN_TOT_NET) END AS TOTAL_NETO,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_DES) * -1 ELSE SUM(CO_DOC_VEN_DES) END AS DESCUENTOS,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_IVA) * -1 ELSE SUM(CO_DOC_VEN_IVA) END AS IVA,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_PAG) * -1 ELSE SUM(CO_DOC_VEN_TOT_PAG) END AS TOTAL,
COUNT(CO_TIP_DOC_VEN_NUM) AS CONTADOR,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_RESUMEN_VENTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CLI_COD=@CO_CLI_COD
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
AND CO_TIP_DOC_VEN_NUM IN (4,18)
GROUP BY CO_TIP_DOC_VEN_NUM,CO_EMP_NOM,CO_EMP_CIU
ELSE IF(@CO_RES_OPC='V')
SELECT CO_EMP_NOM,CO_EMP_CIU,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_NET) * -1 ELSE SUM(CO_DOC_VEN_TOT_NET) END AS TOTAL_NETO,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_DES) * -1 ELSE SUM(CO_DOC_VEN_DES) END AS DESCUENTOS,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_IVA) * -1 ELSE SUM(CO_DOC_VEN_IVA) END AS IVA,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_PAG) * -1 ELSE SUM(CO_DOC_VEN_TOT_PAG) END AS TOTAL,
COUNT(CO_TIP_DOC_VEN_NUM) AS CONTADOR,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_RESUMEN_VENTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_VEN_CED=@CO_VEN_CED
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
AND CO_TIP_DOC_VEN_NUM IN (4,18)
GROUP BY CO_TIP_DOC_VEN_NUM,CO_EMP_NOM,CO_EMP_CIU
IF(@CO_RES_OPC='P')
SELECT CO_EMP_NOM,CO_EMP_CIU,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_NET) * -1 ELSE SUM(CO_DOC_VEN_TOT_NET) END AS TOTAL_NETO,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_DES) * -1 ELSE SUM(CO_DOC_VEN_DES) END AS DESCUENTOS,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_IVA) * -1 ELSE SUM(CO_DOC_VEN_IVA) END AS IVA,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_PAG) * -1 ELSE SUM(CO_DOC_VEN_TOT_PAG) END AS TOTAL,
COUNT(CO_TIP_DOC_VEN_NUM) AS CONTADOR,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_RESUMEN_VENTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
AND CO_TIP_DOC_VEN_NUM IN (20)
GROUP BY CO_TIP_DOC_VEN_NUM,CO_EMP_NOM,CO_EMP_CIU
ELSE IF(@CO_RES_OPC='Q')
SELECT CO_EMP_NOM,CO_EMP_CIU,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_NET) * -1 ELSE SUM(CO_DOC_VEN_TOT_NET) END AS TOTAL_NETO,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_DES) * -1 ELSE SUM(CO_DOC_VEN_DES) END AS DESCUENTOS,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_IVA) * -1 ELSE SUM(CO_DOC_VEN_IVA) END AS IVA,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_PAG) * -1 ELSE SUM(CO_DOC_VEN_TOT_PAG) END AS TOTAL,
COUNT(CO_TIP_DOC_VEN_NUM) AS CONTADOR,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_RESUMEN_VENTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CLI_COD=@CO_CLI_COD
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
AND CO_TIP_DOC_VEN_NUM IN (20)
GROUP BY CO_TIP_DOC_VEN_NUM,CO_EMP_NOM,CO_EMP_CIU
ELSE IF(@CO_RES_OPC='R')
SELECT CO_EMP_NOM,CO_EMP_CIU,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_NET) * -1 ELSE SUM(CO_DOC_VEN_TOT_NET) END AS TOTAL_NETO,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_DES) * -1 ELSE SUM(CO_DOC_VEN_DES) END AS DESCUENTOS,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_IVA) * -1 ELSE SUM(CO_DOC_VEN_IVA) END AS IVA,
CASE WHEN CO_TIP_DOC_VEN_NUM=4 THEN SUM(CO_DOC_VEN_TOT_PAG) * -1 ELSE SUM(CO_DOC_VEN_TOT_PAG) END AS TOTAL,
COUNT(CO_TIP_DOC_VEN_NUM) AS CONTADOR,CO_TIP_DOC_VEN_NUM,@CO_DOC_VEN_FEC1 AS DESDE,@CO_DOC_VEN_FEC2 AS HASTA 
FROM CO_VW_SELECT_RESUMEN_VENTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_VEN_CED=@CO_VEN_CED
AND CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1
AND CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
AND CO_TIP_DOC_VEN_NUM IN (20)
GROUP BY CO_TIP_DOC_VEN_NUM,CO_EMP_NOM,CO_EMP_CIU
GO
