SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PARAMETROS_COMPRAS]
@CO_EMP_RUC CHAR(13)
AS
select A.CO_ALM_NOM, TS.CO_TIP_SUS_NOM, TC.CO_TIP_COM_COM_NOM, PC.ParametroCompraID
from CO_PARAMETRO_COMPRAS PC inner join CO_ALMACEN A on PC.AlmacenID=A.CO_ALM_COD
INNER JOIN CO_TIPO_SUSTENTO TS ON PC.CO_TIP_SUS_COD=TS.CO_TIP_SUS_COD
INNER JOIN CO_TIPO_COMPROBANTE_COMPRA TC ON PC.CO_TIP_COM_COM_COD=TC.CO_TIP_COM_COM_COD
where PC.CO_EMP_RUC=@CO_EMP_RUC
GO
