SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_SERVICIO]
@CO_SER_COD VARCHAR(10)
,@CO_EMP_RUC CHAR(13)
AS
UPDATE [dbo].[CO_SERVICIO]
SET CO_ESTADO=0
WHERE 
CO_SER_COD=@CO_SER_COD AND
CO_EMP_RUC=@CO_EMP_RUC
GO
