SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_COMPROBANTE_DIARIO]
@CO_COM_NUM INT,
@CO_EMP_RUC CHAR(13),
@CO_TIP_COM_COD INT
AS
SELECT * FROM CO_VW_SELECT_REPORTE_COMPROBANTE_DIARIO
WHERE CO_COM_NUM=@CO_COM_NUM AND CO_EMP_RUC=@CO_EMP_RUC AND CO_TIP_COM_COD=@CO_TIP_COM_COD
ORDER BY CO_ASI_COD
GO
