SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIPO_RETENCION_PORID]
@CO_EMP_RUC CHAR(13),
@CO_TIP_RET_COD int
AS
SELECT * FROM CO_TIPO_RETENCION
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_TIP_RET_COD=@CO_TIP_RET_COD
GO
