SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIPO_RETENCION]
@CO_EMP_RUC CHAR(13)
AS
SELECT [CO_TIP_RET_COD]
      ,[CO_EMP_RUC]
	  ,[CO_TIP_RET_NOM]
	  ,[CO_TIP_RET_POR]
      ,[CO_TIP_RET_COD_SRI]           
      ,[CO_CUE_COD_VEN]
	  ,[CO_CUE_COD_COM]
	  ,[CO_TIP_USU_ALI]
  FROM [dbo].[CO_TIPO_RETENCION]
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
