SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_CONCILIACION]
@CO_EMP_RUC CHAR(13)
,@CO_CON_BAN_FEC DATETIME
,@CO_CC_NUM varchar(10)
AS
SELECT CO_EMP_RUC,CO_EMP_NOM,CO_CC_NUM,CO_CC_NOM,convert(nvarchar(10),CO_CON_BAN_FEC,101) as CO_CON_BAN_FEC,CO_TIP_TRA_COD,
CO_CON_BAN_VAL,CO_CON_BAN_DOC_NUM,CO_CON_BAN_NOM_BEN,CO_CON_BAN_AFE,CO_CC_SAL_INI,CO_CC_SAL_LIB
FROM CO_VW_SELECT_CONCILIACION_REPORTE
WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
CO_CON_BAN_FEC<=@CO_CON_BAN_FEC
and CO_CC_NUM=@CO_CC_NUM AND CO_CON_BAN_CON = 0
GO
