SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CUENTA_CORRIENTE]
@CO_CC_NUM VARCHAR(10),
@CO_BAN_COD INT,
@CO_EMP_RUC CHAR(13),
@CO_CUE_COD VARCHAR(40),
@CO_CC_NOM VARCHAR(30),
@CO_CC_FEC DATETIME,
@CO_CC_SAL_INI FLOAT,
@CO_CC_NUM_CHE int
AS
UPDATE CO_CUENTA_CORRIENTE SET
CO_BAN_COD=@CO_BAN_COD,
CO_CUE_COD=@CO_CUE_COD,
CO_CC_NOM=@CO_CC_NOM,
CO_CC_FEC=@CO_CC_FEC,
CO_CC_SAL_INI=@CO_CC_SAL_INI,
CO_CC_NUM_CHE=@CO_CC_NUM_CHE
WHERE CO_CC_NUM=@CO_CC_NUM and CO_EMP_RUC=@CO_EMP_RUC
GO
