SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DETALLE_RETENCION_COMPRA]
@CO_DOC_COM_NUM int
,@CO_DOC_COM_TIP nvarchar(50)
,@CO_EMP_RUC char(13)
AS
SELECT dbo.CO_TIPO_RETENCION.CO_TIP_RET_NOM, dbo.CO_DETALLE_RETENCION_COMPRA.*
FROM dbo.CO_DETALLE_RETENCION_COMPRA INNER JOIN
dbo.CO_TIPO_RETENCION ON dbo.CO_DETALLE_RETENCION_COMPRA.CO_TIP_RET_COD = dbo.CO_TIPO_RETENCION.CO_TIP_RET_COD
WHERE [CO_DOC_COM_NUM]=@CO_DOC_COM_NUM 
AND [CO_DOC_COM_TIP]=@CO_DOC_COM_TIP 
AND dbo.CO_DETALLE_RETENCION_COMPRA.CO_EMP_RUC=@CO_EMP_RUC
GO
