SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FAMILIA_ARTICULO]
@CO_EMP_RUC char(13)
AS
SELECT TA.CO_TIP_ART_NOM, FA.* FROM [dbo].[CO_FAMILIA_ARTICULO] FA
INNER JOIN [dbo].[CO_TIPO_ARTICULO] TA ON TA.CO_TIP_ART_COD=FA.CO_TIP_ART_COD
WHERE FA.[CO_EMP_RUC]=@CO_EMP_RUC
GO
