SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CONTADOR_RETENCIONES]
@CO_EMP_RUC CHAR(13)
AS
SELECT MAX(CO_RET_NUM_REF) AS MAXIMO FROM CO_RETENCION
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
