SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_COBRO_CLIENTE_ESTADO]
@CO_COM_COD_CLI_ID uniqueidentifier
,@CO_EMP_RUC CHAR(13)
,@CO_COM_COB_CLI_EST varchar(10)
AS
UPDATE CO_COBRO_CLIENTE SET
CO_COM_COB_CLI_EST=@CO_COM_COB_CLI_EST
WHERE CO_COM_COD_CLI_ID=@CO_COM_COD_CLI_ID AND CO_EMP_RUC=@CO_EMP_RUC

GO
