SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_RETENCION]
@CO_TIP_RET_COD int,
@CO_EMP_RUC CHAR(13),
@CO_CUE_COD_COM VARCHAR(40),
@CO_CUE_COD_VEN VARCHAR(40),
@CO_TIP_RET_NOM VARCHAR(50),
@CO_TIP_RET_POR FLOAT,
@CO_TIP_RET_COD_SRI VARCHAR(20)
AS
UPDATE CO_TIPO_RETENCION SET
CO_CUE_COD_COM=@CO_CUE_COD_COM,
CO_CUE_COD_VEN=@CO_CUE_COD_VEN,
CO_TIP_RET_NOM=@CO_TIP_RET_NOM,
CO_TIP_RET_POR=@CO_TIP_RET_POR,
CO_TIP_RET_COD_SRI=@CO_TIP_RET_COD_SRI
WHERE CO_TIP_RET_COD=@CO_TIP_RET_COD AND CO_EMP_RUC=@CO_EMP_RUC

GO
