SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CENTRO_COSTOS]
@CO_CEN_COS_COD VARCHAR(10),
@CO_EMP_RUC CHAR(13),
@CO_CEN_COS_DES VARCHAR(50)
AS
INSERT INTO CO_CENTRO_COSTO
VALUES (@CO_CEN_COS_COD,
@CO_EMP_RUC,
@CO_CEN_COS_DES)
GO
