SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIEMPO_TIPO_ACTIVO]
@CO_TIP_ACT_COD INT
AS
SELECT CO_TIP_ACT_TIE FROM CO_TIPO_ACTIVO
WHERE CO_TIP_ACT_COD=@CO_TIP_ACT_COD
GO
