SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CORRECCION_HORAS2]
@CO_UBI_COD INT,
@CO_EMP_RUC CHAR(13),
@CO_MES INT,
@CO_ANIO INT
AS
SELECT dbo.PROFESOR.PROF_COD, dbo.PROFESOR.PROF_APE+' '+dbo.PROFESOR.PROF_NOM AS EMPLEADO, SUM(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_HOR_LAB) AS Horas_Laboradas, SUM(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_HOR_EXT) AS Horas_Extras, SUM(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_HOR_SUP) AS Horas_Suplementarias,cast('0' as int) AS MES,cast('0' as int) AS ANIO,dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC
FROM dbo.PROFESOR LEFT OUTER JOIN dbo.CO_REGISTRO_DIARIO ON dbo.PROFESOR.PROF_COD = dbo.CO_REGISTRO_DIARIO.PROF_COD
WHERE dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC=@CO_EMP_RUC AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD AND MONTH(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_FEC)=@CO_MES and YEAR(dbo.CO_REGISTRO_DIARIO.CO_REG_DIA_FEC)=@CO_ANIO 
GROUP BY dbo.CO_REGISTRO_DIARIO.CO_EMP_RUC,dbo.PROFESOR.PROF_COD, dbo.PROFESOR.PROF_APE, dbo.PROFESOR.PROF_NOM
GO
