SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_ASIENTO]
@CO_EMP_RUC char(13)
,@CO_TIP_COM_COD inT
,@CO_COM_NUM int
AS
DELETE [dbo].[CO_ASIENTO] 
WHERE
CO_EMP_RUC=@CO_EMP_RUC AND
CO_COM_NUM=@CO_COM_NUM AND
CO_TIP_COM_COD=@CO_TIP_COM_COD
GO
