SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_DETALLE_COBRO]
@CO_COM_COB_NUM int
,@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_DET_COB_TIP nchar(10)
,@CO_DET_COB_CON nvarchar(50)
,@CO_DET_COB_VAL float
,@CO_DET_COB_FEC datetime
,@CO_PAG_COD int
AS
INSERT INTO [dbo].[CO_DETALLE_COBRO]
([CO_COM_COB_NUM]
,[CO_EMP_RUC]
,[CO_NOT_DEB_NUM]
,[CO_DET_COB_TIP]
,[CO_DET_COB_CON]
,[CO_DET_COB_VAL]
,[CO_DET_COB_FEC]
,[CO_PAG_COD])
VALUES
(@CO_COM_COB_NUM
,@CO_EMP_RUC
,@CO_NOT_DEB_NUM
,@CO_DET_COB_TIP
,@CO_DET_COB_CON
,@CO_DET_COB_VAL
,@CO_DET_COB_FEC
,@CO_PAG_COD)
GO
