SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_COMPROBANTE_COMPRA]
@CO_TIP_COM_COM_COD int
AS
DELETE [dbo].[CO_TIPO_COMPROBANTE_COMPRA]
WHERE
[CO_TIP_COM_COM_COD]=@CO_TIP_COM_COM_COD
GO
