SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CABECERA_TEMP]
@CO_EMP_RUC char(13)
,@CO_CAB_TEM_MES int
,@CO_CAB_TEM_ANO int
,@CO_CAB_TEM_EST bit
AS
INSERT INTO [dbo].[CO_CABECERA_TEMP]
([CO_EMP_RUC]
,[CO_CAB_TEM_MES]
,[CO_CAB_TEM_ANO]
,[CO_CAB_TEM_EST])
VALUES
(@CO_EMP_RUC
,@CO_CAB_TEM_MES
,@CO_CAB_TEM_ANO
,@CO_CAB_TEM_EST)
GO
