SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_GRUPO_OCUPACIONAL]
@CO_EMP_RUC char(13)
AS
SELECT * FROM [dbo].[CO_GRUPO_OCUPACIONAL]
WHERE 
[CO_EMP_RUC]=@CO_EMP_RUC
GO
