SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FORMULARIO_102A_INGRESOS]
@CO_EMP_RUC CHAR(13)
,@CO_RET_ANIO INT
AS
SELECT SUM(CO_DOC_VEN_TOT_NET) AS INGRESOS FROM CO_DOCUMENTO_VENTA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND YEAR(CO_DOC_VEN_FEC)=@CO_RET_ANIO AND CO_DOC_VEN_EST='ACTIVA'
GO
