SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_RUBRO]
@CO_EMP_RUC char(13)
,@CO_TIP_RUB_NOM nvarchar(50)
,@CO_TIP_RUB_COD_CUE varchar(40)
,@CO_TIP_RUB_COD int
AS
UPDATE [dbo].[CO_TIPO_RUBRO] set
[CO_TIP_RUB_NOM]=@CO_TIP_RUB_NOM
,[CO_TIP_RUB_COD_CUE]=@CO_TIP_RUB_COD_CUE
where
[CO_EMP_RUC]=@CO_EMP_RUC
AND CO_TIP_RUB_COD=@CO_TIP_RUB_COD
GO
