SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CABECERA_TEMP_DIARIO]
@CO_EMP_RUC char(13),
@CO_CAB_TEM_MES INT,
@CO_CAB_TEM_ANO INT
AS
SELECT COUNT(*) AS NUMERO_FILAS 
FROM [dbo].[CO_CABECERA_TEMP]
WHERE [CO_EMP_RUC]=@CO_EMP_RUC
AND CO_CAB_TEM_MES=@CO_CAB_TEM_MES
AND CO_CAB_TEM_ANO=@CO_CAB_TEM_ANO
AND CO_CAB_TEM_EST=0
GO
