SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FORMULARIO_102_CABECERA]
@CO_EMP_RUC CHAR(13)
AS
SELECT CO_EMP_RUC,CO_EMP_NOM,CO_EMP_CIU,CO_EMP_DIR,CO_EMP_NOM_REP,CO_EMP_REP_IDE FROM CO_EMPRESA
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
