SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_SERVICIOS]
(@CO_EMP_RUC char(13)
,@CO_TIP_SER_NOM nvarchar(50)
,@CO_TIP_SER_CTA_VEN varchar(40)
,@CO_TIP_SER_CTA_COM varchar(40)
,@CO_TIP_SER_CTA_IMP varchar(40)
,@CO_TIP_SER_CTA_PRO varchar(40))
AS
INSERT INTO [dbo].[CO_TIPO_SERVICIO]
([CO_EMP_RUC]
,[CO_TIP_SER_NOM]
,[CO_TIP_SER_CTA_VEN]
,[CO_TIP_SER_CTA_COM]
,[CO_TIP_SER_CTA_IMP]
,[CO_TIP_SER_CTA_PRO])
VALUES
(@CO_EMP_RUC
,@CO_TIP_SER_NOM
,@CO_TIP_SER_CTA_VEN
,@CO_TIP_SER_CTA_COM
,@CO_TIP_SER_CTA_IMP
,@CO_TIP_SER_CTA_PRO)
GO
