SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CUENTA_POR_PAGAR_DETALLE_CHEQUE]
@CO_CUE_PAG_COD int,
@CO_CC_NUM varchar(50),
@CO_CUE_PAG_DET_CHE_NUM int,
@CO_CUE_PAG_DET_CHE_VAL float,
@CO_CUE_PAG_DET_CHE_FEC datetime
as
insert into dbo.CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE
values(
@CO_CUE_PAG_COD,
@CO_CC_NUM,
@CO_CUE_PAG_DET_CHE_NUM,
@CO_CUE_PAG_DET_CHE_VAL,
@CO_CUE_PAG_DET_CHE_FEC
)
GO
