SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_INSERT_USUARIO]
@USUA_COD INT,
@USUA_NOM VARCHAR(50),
@USUA_CLA VARCHAR(100),
@USUA_ALI VARCHAR(15),
@USUA_FEC_INI DATETIME,
@USUA_FEC_FIN DATETIME,
@USUA_EST BIT
AS
INSERT INTO USUARIO VALUES(
@USUA_COD,
@USUA_NOM,
@USUA_CLA,
@USUA_ALI,
@USUA_FEC_INI,
@USUA_FEC_FIN,
@USUA_EST)
GO
