SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_SALDO_ANTERIOR_CLIENTE_SIN_MOVIMIENTOS]
@CO_EMP_RUC CHAR(13)
,@CO_DOC_COM_FEC_REG DATETIME
,@CO_DOC_COM_FEC_REG2 DATETIME
,@CO_TIP_CLI_COD NVARCHAR(10)
,@CO_CLI_COD NVARCHAR(20)
AS
SELECT CO_EMP_NOM,CO_TIP_CLI_COD,CO_CLI_COD,CO_CLI_NOM,
SUM(CO_FACTURAS) AS SALDO_ANTERIOR, CO_TIP_CLI_NOM,
(SELECT SUM(CO_COBROS) 
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO
WHERE CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_EMP_RUC=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC AND 
CO_FEC_DOC<@CO_DOC_COM_FEC_REG AND
CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_CLI_COD=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_CLI_COD
GROUP BY CO_CLI_COD, CO_EMP_RUC) AS VALOR_COBRADO
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE
WHERE CO_FEC_DOC<@CO_DOC_COM_FEC_REG and 
(CO_CLI_COD!='CL400' and CO_CLI_COD!='CL500' and CO_CLI_COD!='CL600' and CO_CLI_COD!='CL700' and CO_CLI_COD!='CL800' and CO_CLI_COD!='CL900')
AND CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC=@CO_EMP_RUC AND
CO_TIP_CLI_COD=case @CO_TIP_CLI_COD when '' then CO_TIP_CLI_COD else @CO_TIP_CLI_COD end  AND 
CO_CLI_COD=case @CO_CLI_COD when '' then CO_CLI_COD else @CO_CLI_COD end
and (CO_CLI_COD not in (select CO_CLI_COD from co_documento_venta
where (CO_DOC_VEN_FEC>=@CO_DOC_COM_FEC_REG AND CO_DOC_VEN_FEC<=@CO_DOC_COM_FEC_REG2))
and CO_CLI_COD not in (select CO_CLI_COD from co_cobro_cliente
where (CO_COM_COB_CLI_FEC>=@CO_DOC_COM_FEC_REG AND CO_COM_COB_CLI_FEC<=@CO_DOC_COM_FEC_REG2)))
GROUP BY CO_CLI_COD, CO_CLI_NOM,CO_TIP_CLI_COD,CO_TIP_CLI_NOM,CO_EMP_NOM,CO_EMP_RUC
GO
