SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_BUSQUEDA_USUARIOS]
@BUSCAR NVARCHAR(30),
@CO_EMP_RUC CHAR(13)
AS
DECLARE @LIKE NVARCHAR(50)
SET @LIKE='%'+@BUSCAR+'%'
SELECT dbo.USUARIO.USUA_COD, dbo.USUARIO.USUA_NOM, dbo.USUARIO.USUA_CLA, dbo.USUARIO.USUA_ALI, dbo.USUARIO.USUA_EST
FROM dbo.CO_GRUPO INNER JOIN
dbo.CO_PERTENECE ON dbo.CO_GRUPO.CO_GRU_COD = dbo.CO_PERTENECE.CO_GRU_COD INNER JOIN
dbo.USUARIO ON dbo.CO_PERTENECE.USUA_COD = dbo.USUARIO.USUA_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_GRUPO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.USUARIO.USUA_NOM LIKE @LIKE
AND dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.USUARIO.USUA_NOM!='Developer'
GO
