SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TARJETA_CREDITO_PORID]
@CO_EMP_RUC CHAR(13),
@CO_TAR_CRE_COD INT
AS
SELECT * FROM dbo.CO_TARJETA_CREDITO
WHERE CO_TAR_CRE_COD=@CO_TAR_CRE_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
