SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_COMPROBANTE]
@CO_EMP_RUC CHAR(13),
@CO_TIP_COM_COD INT
AS
SELECT ISNULL(MAX(CO_COM_NUM),0) AS CO_COM_NUM_MAX
FROM CO_COMPROBANTE
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_TIP_COM_COD=@CO_TIP_COM_COD
GO
