SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CUENTA_CORRIENTE]
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_CUENTA_CORRIENTE.CO_CC_NUM, dbo.CO_BANCO.CO_BAN_NOM, dbo.CO_CUENTA_CORRIENTE.CO_CUE_COD, 
dbo.CO_CUENTA_CORRIENTE.CO_CC_NOM, dbo.CO_CUENTA_CORRIENTE.CO_BAN_COD, dbo.CO_CUENTA_CORRIENTE.CO_EMP_RUC, 
dbo.CO_CUENTA_CORRIENTE.CO_CC_FEC, dbo.CO_CUENTA_CORRIENTE.CO_CC_SAL_INI, dbo.CO_CUENTA_CORRIENTE.CO_CC_NUM_CHE
FROM dbo.CO_BANCO INNER JOIN
dbo.CO_CUENTA_CORRIENTE ON dbo.CO_BANCO.CO_BAN_COD = dbo.CO_CUENTA_CORRIENTE.CO_BAN_COD
WHERE dbo.CO_CUENTA_CORRIENTE.CO_EMP_RUC=@CO_EMP_RUC
GO
