SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PROFORMA]
@CO_PRO_COD int
,@CO_EMP_RUC char(13)
,@CO_CLI_COD nvarchar(50)
,@CO_VEN_CED nchar(10)
,@CO_ALM_COD int
,@CO_PRO_FEC datetime
,@CO_PRO_EST nvarchar(50)
,@CO_PRO_DET nvarchar(100)
,@CO_PRO_TOT_NET float
,@CO_PRO_POR_DES float
,@CO_PRO_DES float
,@CO_PRO_POR_IVA int
,@CO_PRO_IVA float
,@CO_PRO_TOT_PAG float
,@CO_PRO_FOR_PAG nvarchar(15)
,@CO_PRO_EFE bit
,@CO_PRO_EFE_VAL float
,@CO_PRO_CHE bit
,@CO_PRO_CHE_VAL float
,@CO_PRO_CHE_NUM nvarchar(20)
,@CO_PRO_CHE_BAN nvarchar(40)
,@CO_PRO_TAR bit
,@CO_PRO_TAR_VAL float
,@CO_PRO_TAR_NUM nvarchar(30)
,@CO_PRO_TAR_VAU nvarchar(50)
,@CO_PRO_NUM_PAG int
,@CO_PRO_USU_ALI nvarchar(15)
,@CO_PRO_TOT_LET nvarchar(150)
,@CO_PEDIDO_VENDEDOR varchar(10)
AS
UPDATE [dbo].[CO_PROFORMA] SET
[CO_CLI_COD]=@CO_CLI_COD
,[CO_VEN_CED]=@CO_VEN_CED
,[CO_ALM_COD]=@CO_ALM_COD
,[CO_PRO_FEC]=@CO_PRO_FEC
,[CO_PRO_EST]=@CO_PRO_EST
,[CO_PRO_DET]=@CO_PRO_DET
,[CO_PRO_TOT_NET]=@CO_PRO_TOT_NET
,[CO_PRO_POR_DES]=@CO_PRO_POR_DES
,[CO_PRO_DES]=@CO_PRO_DES
,[CO_PRO_POR_IVA]=@CO_PRO_POR_IVA
,[CO_PRO_IVA]=@CO_PRO_IVA
,[CO_PRO_TOT_PAG]=@CO_PRO_TOT_PAG
,[CO_PRO_FOR_PAG]=@CO_PRO_FOR_PAG
,[CO_PRO_EFE]=@CO_PRO_EFE
,[CO_PRO_EFE_VAL]=@CO_PRO_EFE_VAL
,[CO_PRO_CHE]=@CO_PRO_CHE
,[CO_PRO_CHE_VAL]=@CO_PRO_CHE_VAL
,[CO_PRO_CHE_NUM]=@CO_PRO_CHE_NUM
,[CO_PRO_CHE_BAN]=@CO_PRO_CHE_BAN
,[CO_PRO_TAR]=@CO_PRO_TAR
,[CO_PRO_TAR_VAL]=@CO_PRO_TAR_VAL
,[CO_PRO_TAR_NUM]=@CO_PRO_TAR_NUM
,[CO_PRO_TAR_VAU]=@CO_PRO_TAR_VAU
,[CO_PRO_NUM_PAG]=@CO_PRO_NUM_PAG
,[CO_PRO_USU_ALI]=@CO_PRO_USU_ALI
,[CO_PRO_TOT_LET]=@CO_PRO_TOT_LET
,[CO_PEDIDO_VENDEDOR]=@CO_PEDIDO_VENDEDOR
WHERE [CO_PRO_COD]=@CO_PRO_COD AND
[CO_EMP_RUC]=@CO_EMP_RUC

GO
