SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_DOCUMENTO_VENTA]
@CO_EMP_RUC CHAR(13)
,@CO_TIP_DOC_VEN_NUM INT
,@CO_CLI_NOM NVARCHAR(100)
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
,@CO_DOC_VEN_OPC CHAR(1)
,@CO_ALM_COD INT
,@CO_TIP_DOC_VEN_NUM2 INT
AS
if(@CO_DOC_VEN_OPC='N')
BEGIN
	SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_DOCUMENTO_VENTA.*, dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_NOM, 
		   dbo.CO_CLIENTE.CO_CLI_CED, dbo.CO_CLIENTE.CO_CLI_CIU, dbo.CO_CLIENTE.CO_CLI_DIR
	FROM dbo.CO_CLIENTE INNER JOIN
	dbo.CO_DOCUMENTO_VENTA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD AND 
	dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC 
	--AND dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_TIP_CLI_COD 
	INNER JOIN
	dbo.CO_TIPO_IDENTIFICACION ON dbo.CO_CLIENTE.CO_TIP_IDE_COD = dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD
	WHERE dbo.CO_CLIENTE.CO_CLI_NOM like '%' + @CO_CLI_NOM + '%' AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC 
	AND (dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2)
	AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC
	AND dbo.CO_DOCUMENTO_VENTA.AlmacenID=@CO_ALM_COD
	AND dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM=CASE WHEN @CO_TIP_DOC_VEN_NUM<>0 THEN @CO_TIP_DOC_VEN_NUM ELSE dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM END
	ORDER BY dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM
END
ELSE if(@CO_DOC_VEN_OPC='U')
BEGIN
	SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_DOCUMENTO_VENTA.*, dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_NOM, 
		   dbo.CO_CLIENTE.CO_CLI_CED, dbo.CO_CLIENTE.CO_CLI_CIU, dbo.CO_CLIENTE.CO_CLI_DIR
	FROM dbo.CO_CLIENTE INNER JOIN
	dbo.CO_DOCUMENTO_VENTA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD AND 
	dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC 
	--AND dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_TIP_CLI_COD 
	INNER JOIN
	dbo.CO_TIPO_IDENTIFICACION ON dbo.CO_CLIENTE.CO_TIP_IDE_COD = dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD
	WHERE dbo.CO_CLIENTE.CO_CLI_NOM like '%' + @CO_CLI_NOM + '%' AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC 
	AND (dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2)
	AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC
	AND dbo.CO_DOCUMENTO_VENTA.AlmacenID=@CO_ALM_COD
	AND dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM=CASE WHEN @CO_TIP_DOC_VEN_NUM<>0 THEN @CO_TIP_DOC_VEN_NUM ELSE dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM END
	AND dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM=@CO_TIP_DOC_VEN_NUM2
	ORDER BY dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM
END
ELSE
BEGIN
	SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_DOCUMENTO_VENTA.*, dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_NOM, 
		   dbo.CO_CLIENTE.CO_CLI_CED, dbo.CO_CLIENTE.CO_CLI_CIU, dbo.CO_CLIENTE.CO_CLI_DIR
	FROM dbo.CO_CLIENTE INNER JOIN
	dbo.CO_DOCUMENTO_VENTA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD AND 
	dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC 
	--AND dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_TIP_CLI_COD 
	INNER JOIN
	dbo.CO_TIPO_IDENTIFICACION ON dbo.CO_CLIENTE.CO_TIP_IDE_COD = dbo.CO_TIPO_IDENTIFICACION.CO_TIP_IDE_COD
	WHERE dbo.CO_CLIENTE.CO_CLI_NOM like '%' + @CO_CLI_NOM + '%' AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC 
	AND (dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2)
	AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@CO_EMP_RUC
	AND dbo.CO_DOCUMENTO_VENTA.AlmacenID=@CO_ALM_COD
	AND dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM=CASE WHEN @CO_TIP_DOC_VEN_NUM<>0 THEN @CO_TIP_DOC_VEN_NUM ELSE dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM END
	AND dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM<>@CO_TIP_DOC_VEN_NUM2
	ORDER BY dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM
END





GO
