SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_CUENTAS_CORRIENTES_BANCO_PLUS]
AS
SELECT     dbo.CO_CUENTA_CORRIENTE.CO_CC_NUM AS CUENTA, dbo.CO_BANCO.CO_BAN_NOM AS BANCO
FROM         dbo.CO_CUENTA_CORRIENTE INNER JOIN
                      dbo.CO_BANCO ON dbo.CO_CUENTA_CORRIENTE.CO_BAN_COD = dbo.CO_BANCO.CO_BAN_COD
GO
