SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_VENTA_EMPLEADO]
@CO_EMP_RUC CHAR(13),
@CO_NOT_DEB_NUM INT
AS
SELECT * FROM CO_VENTA_EMPLEADO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_NOT_DEB_NUM=@CO_NOT_DEB_NUM
GO
