SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TEMP_ASIENTO]
@CO_EMP_RUC char(13)
--,@CO_TEMP_ASI_COD int
as
DELETE [dbo].[CO_TEMP_ASIENTO]
WHERE CO_EMP_RUC=@CO_EMP_RUC 
--and @CO_TEMP_ASI_COD=CO_TEMP_ASI_COD
GO
