SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_UBICACION_GEOGRAFICA]
@CO_UBI_GEO_COD nvarchar(10)
,@CO_EMP_RUC char(13)
,@CO_UBI_GEO_DIV nvarchar(50)
,@CO_UBI_GEO_NOM nvarchar(50)
AS
UPDATE [dbo].[CO_UBICACION_GEOGRAFICA] SET
[CO_UBI_GEO_DIV]=@CO_UBI_GEO_DIV
,[CO_UBI_GEO_NOM]=@CO_UBI_GEO_NOM
WHERE 
([CO_UBI_GEO_COD]=@CO_UBI_GEO_COD
 AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
