SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_DETALLE_ESTADO_CUENTA]
@CO_EST_CUE_FEC1 DATETIME
,@CO_EST_CUE_FEC2 DATETIME
,@PROF_COD CHAR(10)
,@CO_EST_CUE_OPC CHAR(1)
,@CO_EST_CUE_SAL FLOAT
,@co_emp_ruc char(13)
AS
IF(@CO_EST_CUE_OPC='T')
BEGIN
SELECT *,@CO_EST_CUE_FEC1 AS DESDE,@CO_EST_CUE_FEC2 AS HASTA,@CO_EST_CUE_SAL AS SALDO 
FROM CO_VW_SELECT_ESTADO_CUENTA_DEBITO
WHERE co_emp_ruc=@co_emp_ruc and 
CO_NOT_DEB_FEC>=@CO_EST_CUE_FEC1 AND 
CO_NOT_DEB_FEC<=@CO_EST_CUE_FEC2
END
ELSE IF(@CO_EST_CUE_OPC='E')
BEGIN
SELECT *,@CO_EST_CUE_FEC1 AS DESDE,@CO_EST_CUE_FEC2 AS HASTA,@CO_EST_CUE_SAL AS SALDO 
FROM CO_VW_SELECT_ESTADO_CUENTA_DEBITO
WHERE co_emp_ruc=@co_emp_ruc and 
CO_NOT_DEB_FEC>=@CO_EST_CUE_FEC1 AND 
CO_NOT_DEB_FEC<=@CO_EST_CUE_FEC2 AND
PROF_COD=@PROF_COD
END
GO
