SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_DOCUMENTO_VENTA]
@CO_TIP_DOC_VEN_NUM int
,@CO_TIP_DOC_VEN_NOM nvarchar(100)
,@CO_TIP_DOC_VEN_NUM_FIL INT
,@CO_TIP_DOC_VEN_MOD_NUM BIT
,@CO_TIP_DOC_VEN_FOR_AFE_INV CHAR(1)
,@CO_TIP_DOC_VEN_IMP nvarchar(200)
,@CO_TIP_DOC_VEN_AGR_PRO bit
,@CO_TIP_DOC_VEN_LIS_PRE int
,@CO_TIP_DOC_VEN_MOD_PRE bit
AS
INSERT INTO [dbo].[CO_TIPO_DOCUMENTO_VENTA]
VALUES
(@CO_TIP_DOC_VEN_NUM
,@CO_TIP_DOC_VEN_NOM
,@CO_TIP_DOC_VEN_NUM_FIL
,@CO_TIP_DOC_VEN_MOD_NUM
,@CO_TIP_DOC_VEN_FOR_AFE_INV
,@CO_TIP_DOC_VEN_MOD_PRE
,@CO_TIP_DOC_VEN_IMP
,@CO_TIP_DOC_VEN_AGR_PRO
,@CO_TIP_DOC_VEN_LIS_PRE)
GO
