SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_TIPO_ARTICULO]
@CO_TIP_ART_COD nvarchar(10)
,@CO_EMP_RUC char(13)
,@CO_TIP_ART_NOM nvarchar(100)
AS
UPDATE [dbo].[CO_TIPO_ARTICULO] SET
[CO_TIP_ART_NOM]=@CO_TIP_ART_NOM
WHERE [CO_TIP_ART_COD]=@CO_TIP_ART_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC
GO
