SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_ALMACEN]
(@CO_ALM_COD nvarchar(20)
,@CO_EMP_RUC char(13))
AS
DELETE [dbo].[CO_ALMACEN]
WHERE ([CO_ALM_COD]=@CO_ALM_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
