SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_KARDEX]
@CO_EMP_RUC char(13)
,@CO_KAR_DOC_TIP nvarchar(50)
,@CO_KAR_DOC_COD int
AS
DELETE CO_KARDEX
WHERE CO_KAR_DOC_COD=@CO_KAR_DOC_COD AND
CO_KAR_DOC_TIP=@CO_KAR_DOC_TIP AND
CO_EMP_RUC=@CO_EMP_RUC
GO
