SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Fredy M. Aguirre
-- Create date: 11/12/206
-- Description:	Devuelve los saldos anteriores a una fecha dada
-- =============================================
CREATE PROCEDURE [dbo].[CO_SP_SELECT_SALDOS_ANTERIORES_KARDEX_TOTAL] 

@CO_EMP_RUC char(13),
@CO_ART_COD nvarchar(40),
@FECHA datetime

AS
BEGIN

SELECT (SELECT     SUM(CO_ENT_KAR_CANT) AS SUMA_CANT_ENTRADAS
FROM         CO_ENTRADAS_KARDEX
WHERE     (CO_ART_COD = @CO_ART_COD) AND (CO_EMP_RUC = @CO_EMP_RUC) AND (CO_ENT_KAR_FEC < @FECHA)) - (SELECT     SUM(CO_SAL_KAR_CANT) AS SUMA_CANT_SALIDAS
FROM         CO_SALIDAS_KARDEX
WHERE     (CO_ART_COD = @CO_ART_COD) AND (CO_EMP_RUC = @CO_EMP_RUC) AND (CO_SAL_KAR_FEC < @FECHA)) AS SALDO_CANT, (SELECT     SUM(CO_ENT_KAR_VAL_TOT) AS SUMA_TOTAL_ENTRADAS
FROM         CO_ENTRADAS_KARDEX
WHERE     (CO_ART_COD = @CO_ART_COD) AND (CO_EMP_RUC = @CO_EMP_RUC) AND (CO_ENT_KAR_FEC < @FECHA)) - (SELECT     SUM(CO_SAL_KAR_VAL_TOT) AS SUMA_TOTAL_SALIDAS
FROM         CO_SALIDAS_KARDEX
WHERE     (CO_ART_COD = @CO_ART_COD) AND (CO_EMP_RUC = @CO_EMP_RUC) AND (CO_SAL_KAR_FEC < @FECHA)) AS SALDO_TOTAL

END
GO
