SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ASIENTO_DIARIO]
@CO_EMP_RUC CHAR(13),
@CO_COM_NUM INT,
@CO_TIP_COM_COD INT
AS
SELECT * FROM CO_VW_SELECT_ASIENTO_DIARIO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_COM_NUM=@CO_COM_NUM AND 
CO_TIP_COM_COD=@CO_TIP_COM_COD
order by co_asi_cod
GO
