SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_UPDATE_KARDEX_TOTAL]
@CO_EMP_RUC CHAR(13),
@CO_ART_COD NVARCHAR(40),
@CO_KAR_TOT_DOC INT,
@CO_KAR_TOT_TIP_DOC INT,
@CO_KAR_TOT_EST NVARCHAR(10)
AS
UPDATE CO_KARDEX_TOTAL SET CO_KAR_TOT_EST=@CO_KAR_TOT_EST 
WHERE CO_KAR_TOT_DOC=@CO_KAR_TOT_DOC AND CO_KAR_TOT_TIP_DOC=@CO_KAR_TOT_TIP_DOC AND CO_EMP_RUC=@CO_EMP_RUC AND CO_ART_COD=@CO_ART_COD
GO
