SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_COMPROBANTE_COBRO_ESTADO]
@CO_COM_COB_NUM INT
,@CO_EMP_RUC CHAR(13)
AS
UPDATE CO_COMPROBANTE_COBRO SET
CO_COM_COB_EST=0
WHERE CO_COM_COB_NUM=@CO_COM_COB_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
