SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_INSERT_EXISTENCIA_FINAL_KARDEX] 
	-- Add the parameters for the stored procedure here
	@CO_EMP_RUC char(13),
	@CO_ART_COD nvarchar(40),
	@CO_EXI_FIN_KAR_FEC datetime,
	@CO_EXI_FIN_KAR_DOC int,
	@CO_EXI_FIN_KAR_TIP_DOC int,
	@CO_EXI_FIN_KAR_CANT float,
	@CO_EXI_FIN_KAR_VAL_UNI float,
	@CO_EXI_FIN_KAR_VAL_TOT float
AS
BEGIN

INSERT INTO CO_EXISTENCIA_FINAL_KARDEX
                      (CO_EMP_RUC, CO_ART_COD, CO_EXI_FIN_KAR_FEC, CO_EXI_FIN_KAR_DOC, CO_EXI_FIN_KAR_TIP_DOC, CO_EXI_FIN_KAR_CANT, 
                      CO_EXI_FIN_KAR_VAL_UNI, CO_EXI_FIN_KAR_VAL_TOT)
VALUES     (@CO_EMP_RUC,@CO_ART_COD,@CO_EXI_FIN_KAR_FEC,@CO_EXI_FIN_KAR_DOC,@CO_EXI_FIN_KAR_TIP_DOC,@CO_EXI_FIN_KAR_CANT,@CO_EXI_FIN_KAR_VAL_UNI,@CO_EXI_FIN_KAR_VAL_TOT)
END
GO
