SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_COMPROBANTE_SUSTENTO2]
@CO_TIP_SUS_COD NVARCHAR(5)
AS
SELECT dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_COD, dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_NOM
FROM dbo.CO_CRUCE_SUSTENTO INNER JOIN
dbo.CO_TIPO_COMPROBANTE_COMPRA ON 
dbo.CO_CRUCE_SUSTENTO.CO_TIP_COM_COM_COD = dbo.CO_TIPO_COMPROBANTE_COMPRA.CO_TIP_COM_COM_COD INNER JOIN
dbo.CO_TIPO_SUSTENTO ON dbo.CO_CRUCE_SUSTENTO.CO_TIP_SUS_COD = dbo.CO_TIPO_SUSTENTO.CO_TIP_SUS_COD
WHERE dbo.CO_TIPO_SUSTENTO.CO_TIP_SUS_COD=@CO_TIP_SUS_COD
GO
