SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TEMP_ASIENTO]
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_CUENTA.CO_EMP_RUC, dbo.CO_CUENTA.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, dbo.CO_TEMP_ASIENTO.CO_TEMP_ASI_FEC, 
dbo.CO_TEMP_ASIENTO.CO_TEMP_ASI_DES, dbo.CO_TEMP_ASIENTO.CO_TEMP_ASI_DEB, dbo.CO_TEMP_ASIENTO.CO_TEMP_ASI_HAB, 
dbo.CO_TEMP_ASIENTO.CO_CEN_COS_COD
FROM dbo.CO_CUENTA INNER JOIN
dbo.CO_TEMP_ASIENTO ON dbo.CO_CUENTA.CO_EMP_RUC = dbo.CO_TEMP_ASIENTO.CO_EMP_RUC AND 
dbo.CO_CUENTA.CO_CUE_COD = dbo.CO_TEMP_ASIENTO.CO_CUE_COD
WHERE dbo.CO_CUENTA.CO_EMP_RUC=@CO_EMP_RUC
GO
