SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CORRECCION_HORAS3]
@CO_UBI_COD INT,
@CO_EMP_RUC CHAR(13)
AS
SELECT PROF_COD,EMPLEADO, Horas_Laboradas, Horas_Extras, Horas_Suplementarias,MES,ANIO,CO_EMP_RUC
FROM CO_VW_SELECT_HORAS_VACIAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_UBI_COD=@CO_UBI_COD
GO
