SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_DELETE_CUENTA_CONTABLE]
@CO_EMP_RUC char(13),
@CO_CUE_COD varchar(40)
as
DELETE CO_CUENTA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CUE_COD=@CO_CUE_COD
GO
