SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_SELECT_VERICAR_USUARIO]
@USUA_ALI VARCHAR(15),
@CO_EMP_RUC CHAR(13)
AS
SELECT     COUNT(*)
FROM dbo.CO_GRUPO INNER JOIN
dbo.CO_PERTENECE ON dbo.CO_GRUPO.CO_GRU_COD = dbo.CO_PERTENECE.CO_GRU_COD INNER JOIN
dbo.USUARIO ON dbo.CO_PERTENECE.USUA_COD = dbo.USUARIO.USUA_COD
WHERE UPPER(USUA_ALI)=UPPER(@USUA_ALI) AND dbo.CO_GRUPO.CO_EMP_RUC=@CO_EMP_RUC
GO
