SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[CO_SP_SELECT_PLAN_CUENTAS_PADRE]
@CO_EMP_RUC AS VARCHAR(40),
@CO_CUE_COD_ANT VARCHAR(40)
AS
SELECT CO_CUE_COD,CO_CUE_NOM,CO_CUE_TIP,CO_CUE_COD_ANT FROM CO_CUENTA
WHERE CO_EMP_RUC=@CO_EMP_RUC and CO_CUE_COD_ANT=@CO_CUE_COD_ANT
ORDER BY CO_CUE_COD

GO
