SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PAGO_PROVEEDOR]
@CO_DOC_COM_NUM uniqueidentifier,
@CO_EMP_RUC CHAR(13)
AS
SELECT * FROM CO_PAGO_PROVEEDOR
WHERE CO_DOC_COM_NUM=@CO_DOC_COM_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
