SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_KARDEX_ARTICULO_DOCUMENTO]
@CO_ART_COD NVARCHAR(20),
@CO_KAR_TOT_DOC INT,
@CO_KAR_TOT_TIP_DOC INT
AS
SELECT * FROM dbo.CO_KARDEX_TOTAL
WHERE CO_ART_COD=@CO_ART_COD AND CO_KAR_TOT_DOC=@CO_KAR_TOT_DOC
AND CO_KAR_TOT_TIP_DOC=@CO_KAR_TOT_TIP_DOC
GO
