SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PRESUPUESTO]
@CO_EMP_RUC char(13)
,@CO_ITE_PRE_COD int
,@CO_PRE_ANO int
,@CO_PRE_VAL_ACT float
,@CO_PRE_VAL_NUE float
AS
UPDATE [dbo].[CO_PRESUPUESTO] SET
[CO_PRE_VAL_ACT]=@CO_PRE_VAL_ACT
,[CO_PRE_VAL_NUE]=@CO_PRE_VAL_NUE
WHERE
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_ITE_PRE_COD]=@CO_ITE_PRE_COD
AND [CO_PRE_ANO]=@CO_PRE_ANO)
GO
