SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ASIENTOS_MES_BALANCE_RESULTADOS]
@CO_FEC_MES INT,
@CO_FEC_ANIO INT,
@CO_EMP_RUC CHAR(13),
@CO_CUE_ING NVARCHAR(10),
@CO_CUE_EGR NVARCHAR(10)
AS
DECLARE @INGRESOS AS VARCHAR(12)
DECLARE @EGRESOS AS VARCHAR(12)
SET @INGRESOS=@CO_CUE_ING+'%'
SET @EGRESOS=@CO_CUE_EGR+'%'
SELECT     dbo.CO_CUENTA.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, ROUND(SUM(dbo.CO_ASIENTO.CO_ASI_DEB), 2) AS CO_ASI_DEB, 
ROUND(SUM(dbo.CO_ASIENTO.CO_ASI_HAB), 2) AS CO_ASI_HAB, dbo.CO_CUENTA.CO_CUE_COD_ANT
FROM         dbo.CO_CUENTA INNER JOIN
dbo.CO_ASIENTO ON dbo.CO_CUENTA.CO_EMP_RUC = dbo.CO_ASIENTO.CO_EMP_RUC AND 
dbo.CO_CUENTA.CO_CUE_COD = dbo.CO_ASIENTO.CO_CUE_COD INNER JOIN
dbo.CO_COMPROBANTE ON dbo.CO_ASIENTO.CO_EMP_RUC = dbo.CO_COMPROBANTE.CO_EMP_RUC AND 
dbo.CO_ASIENTO.CO_TIP_COM_COD = dbo.CO_COMPROBANTE.CO_TIP_COM_COD AND 
dbo.CO_ASIENTO.CO_COM_NUM = dbo.CO_COMPROBANTE.CO_COM_NUM
WHERE dbo.CO_CUENTA.CO_EMP_RUC=@CO_EMP_RUC AND 
MONTH(dbo.CO_ASIENTO.CO_ASI_FEC)=@CO_FEC_MES and year(dbo.CO_ASIENTO.CO_ASI_FEC)=@CO_FEC_ANIO
AND (dbo.CO_CUENTA.CO_CUE_COD LIKE @INGRESOS
OR dbo.CO_CUENTA.CO_CUE_COD LIKE @EGRESOS)
GROUP BY dbo.CO_CUENTA.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, dbo.CO_CUENTA.CO_CUE_COD_ANT, dbo.CO_CUENTA.CO_EMP_RUC, 
dbo.CO_COMPROBANTE.CO_COM_EST
HAVING (dbo.CO_COMPROBANTE.CO_COM_EST = 'ACTIVO')
GO
