SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_FAMILIA_ARTICULO]
@CO_TIP_ART_COD nvarchar(10)
,@CO_EMP_RUC char(13)
,@CO_FAM_ART_NOM nvarchar(100)
AS
INSERT INTO [dbo].[CO_FAMILIA_ARTICULO]
([CO_TIP_ART_COD]
,[CO_EMP_RUC]
,[CO_FAM_ART_NOM])
VALUES
(@CO_TIP_ART_COD
,@CO_EMP_RUC
,@CO_FAM_ART_NOM)
GO
