SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_ESTADO_CUENTA_EMPLEADO]
@DAT_FEC_INI DATETIME,
@DAT_FEC_FIN DATETIME,
@CO_EMP_RUC CHAR(13)
AS
SELECT     SUM(dbo.CO_PAGO_CUOTA.CO_PAG_VAL) AS ABONOS, SUM(dbo.CO_PAGO_CUOTA.CO_PAG_VAL_IMP) AS VENTAS, 
                      dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS EMPLEADO, dbo.CO_NOTA_DEBITO.CO_NOT_DEB_NUM, 
                      dbo.CO_EMPRESA.CO_EMP_NOM,dbo.PROFESOR.PROF_COD,@DAT_FEC_INI AS DESDE,@DAT_FEC_FIN AS HASTA
FROM         dbo.CO_PAGO_CUOTA INNER JOIN
                      dbo.CO_NOTA_DEBITO ON dbo.CO_PAGO_CUOTA.CO_EMP_RUC = dbo.CO_NOTA_DEBITO.CO_EMP_RUC AND 
                      dbo.CO_PAGO_CUOTA.CO_NOT_DEB_NUM = dbo.CO_NOTA_DEBITO.CO_NOT_DEB_NUM AND 
                      dbo.CO_PAGO_CUOTA.PROF_COD = dbo.CO_NOTA_DEBITO.PROF_COD INNER JOIN
                      dbo.PROFESOR ON dbo.CO_NOTA_DEBITO.PROF_COD = dbo.PROFESOR.PROF_COD INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_NOTA_DEBITO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
where (dbo.CO_NOTA_DEBITO.CO_NOT_DEB_FEC>=@dat_fec_ini and
dbo.CO_NOTA_DEBITO.CO_NOT_DEB_FEC<=@dat_fec_fin) and dbo.CO_NOTA_DEBITO.CO_EMP_RUC=@CO_EMP_RUC
GROUP BY dbo.PROFESOR.PROF_APE, dbo.PROFESOR.PROF_NOM, dbo.CO_NOTA_DEBITO.CO_NOT_DEB_NUM, dbo.CO_EMPRESA.CO_EMP_NOM,dbo.PROFESOR.PROF_COD
GO
