SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_UPDATE_PERTENECE]
@USUA_COD INT,
@CO_GRU_COD INT
AS
UPDATE CO_PERTENECE SET CO_GRU_COD=@CO_GRU_COD
WHERE USUA_COD=@USUA_COD
GO
