SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC  [dbo].[CO_SP_SELECT_DETALLE_GUIA_REMISION]
@CO_DOC_VEN_GUI_COD uniqueidentifier
as
select *
from CO_DETALLE_GUIA_REMISION
where CO_DOC_VEN_GUI_COD=@CO_DOC_VEN_GUI_COD
GO
