SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_SERVICIO]
@CO_SER_COD varchar(10)
,@CO_TIP_SER_COD int
,@CO_SER_NOM nvarchar(50)
,@CO_SER_PRE float
,@CO_SER_POR_IVA int
,@CO_EMP_RUC CHAR(13)
,@CO_ICE_COD int
,@CO_CUE_COD VARCHAR(40)
AS
UPDATE [dbo].[CO_SERVICIO] SET
[CO_TIP_SER_COD]=@CO_TIP_SER_COD
,[CO_SER_NOM]=@CO_SER_NOM
,[CO_SER_PRE]=@CO_SER_PRE
,[CO_SER_POR_IVA]=@CO_SER_POR_IVA
,CO_ICE_COD=@CO_ICE_COD
,CO_CUE_COD=@CO_CUE_COD
 WHERE CO_SER_COD=@CO_SER_COD AND
CO_EMP_RUC=@CO_EMP_RUC

GO
