SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PAGO_CUOTA_TODOS]
@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
AS
DELETE [dbo].[CO_PAGO_CUOTA]
WHERE 
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_NOT_DEB_NUM]=@CO_NOT_DEB_NUM)
GO
