SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_RETENCION_VENTA]
(@CO_DOC_VEN_ID UNIQUEIDENTIFIER)
AS
SELECT * FROM [dbo].[CO_RETENCION]
WHERE CO_RET_COD IN (SELECT CO_RET_COD FROM CO_RETENCION WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID)
GO
