SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_COMPROBANTE_NUMERO_TIPO]
@CO_EMP_RUC CHAR(13),
@CO_COM_NUM INT,
@CO_TIP_COM_COD INT
AS
SELECT dbo.CO_COMPROBANTE.CO_EMP_RUC, dbo.CO_COMPROBANTE.CO_TIP_COM_COD, dbo.CO_COMPROBANTE.CO_COM_NUM, 
dbo.CO_TIPO_COMPROBANTE.CO_TIP_COM_NOM, dbo.CO_COMPROBANTE.CO_COM_NOM_EMP, dbo.CO_COMPROBANTE.CO_COM_FEC, 
dbo.CO_COMPROBANTE.CO_COM_EST,dbo.CO_COMPROBANTE.CO_COM_RUC_EMP,dbo.CO_COMPROBANTE.CO_COM_CONC,
dbo.CO_COMPROBANTE.CO_RETENCION_ID
FROM dbo.CO_COMPROBANTE INNER JOIN
dbo.CO_TIPO_COMPROBANTE ON dbo.CO_COMPROBANTE.CO_EMP_RUC = dbo.CO_TIPO_COMPROBANTE.CO_EMP_RUC AND 
dbo.CO_COMPROBANTE.CO_TIP_COM_COD = dbo.CO_TIPO_COMPROBANTE.CO_TIP_COM_COD
WHERE dbo.CO_COMPROBANTE.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_COMPROBANTE.CO_COM_NUM=@CO_COM_NUM AND dbo.CO_COMPROBANTE.CO_COM_MAY=0
AND dbo.CO_COMPROBANTE.CO_TIP_COM_COD=@CO_TIP_COM_COD
GO
