SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_RUBRO]
@CO_EMP_RUC char(13),
@CO_TIP_RUB_COD INT
AS
DELETE [dbo].[CO_TIPO_RUBRO]
WHERE 
[CO_EMP_RUC]=@CO_EMP_RUC AND
CO_TIP_RUB_COD=@CO_TIP_RUB_COD
GO
