SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_COMPROBANTE_COMPRA]
@CO_TIP_COM_COM_COD int
,@CO_TIP_COM_COM_NOM nvarchar(150)
,@CO_TIP_COM_COM_FEC_VIG datetime
,@CO_TIP_COM_COM_INV char(1)
AS
INSERT INTO [dbo].[CO_TIPO_COMPROBANTE_COMPRA]
([CO_TIP_COM_COM_COD]
,[CO_TIP_COM_COM_NOM]
,[CO_TIP_COM_COM_FEC_VIG]
,[CO_TIP_COM_COM_INV])
VALUES
(@CO_TIP_COM_COM_COD
,@CO_TIP_COM_COM_NOM
,@CO_TIP_COM_COM_FEC_VIG
,@CO_TIP_COM_COM_INV)
GO
