SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_SALDO_ANTERIOR_DIARIO]
@CO_EMP_RUC CHAR(13),
@CO_MES_NUM INT,
@CO_ANIO_NUM INT
AS
SELECT CO_MES_SAL_ACT,CO_EMP_RUC,CO_CUE_COD FROM CO_MES_SALDO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_MES_NUM=@CO_MES_NUM AND CO_ANIO_NUM=@CO_ANIO_NUM
GO
