SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_BUSQUEDA_NOMBRE_PROFESOR]
@BUSCAR VARCHAR(20)
,@CO_EMP_RUC CHAR(13)
AS
DECLARE @LIKE AS VARCHAR(50)
SET @LIKE='%'+@BUSCAR+'%'
SELECT PROF_COD AS CEDULA,PROF_APE+' '+PROF_NOM AS PROFESOR,PROF_TEL AS TELEFONO,PROF_EMA AS EMAIL
FROM PROFESOR
WHERE PROF_APE+' '+PROF_NOM LIKE @LIKE AND CO_EMP_RUC=@CO_EMP_RUC
GO
