SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TARJETA_CREDITO]
	(@CO_TAR_CRE_COD INT
			,@CO_EMP_RUC char(13))
AS
DELETE [dbo].[CO_TARJETA_CREDITO] 
     WHERE [CO_EMP_RUC]=@CO_EMP_RUC
           AND CO_TAR_CRE_COD=@CO_TAR_CRE_COD
GO
