SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_NUMERO_FACTURA]
@CO_EMP_RUC char(13),
@CO_DOC_VEN_NUM int,
@CO_TIP_DOC_VEN_NUM int

AS
SELECT  CO_EMP_RUC, CO_DOC_VEN_NUM, CO_TIP_DOC_VEN_NUM, CO_DOC_VEN_FEC, CO_DOC_VEN_TOT_PAG
FROM dbo.CO_DOCUMENTO_VENTA
WHERE  (CO_EMP_RUC = @CO_EMP_RUC)and(CO_DOC_VEN_NUM = @CO_DOC_VEN_NUM) AND (CO_TIP_DOC_VEN_NUM = @CO_TIP_DOC_VEN_NUM)
GO
