SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_PAGO_PROVEEDORES_PLUS]
AS
SELECT MAX(CODIGO_PAGO_PROVEEDOR) AS CO_COM_NUM_MAX
FROM dbo.CO_PAGO_PROVEEDORES_PLUS
GO
