SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CONTADOR_UBICACIONARTICULO]
@CO_ART_COD NVARCHAR(50),
@CO_EMP_RUC CHAR(13),
@CO_BOD_COD INT
AS
SELECT COUNT(*) 
FROM [dbo].[CO_UBICACIONARTICULO]
WHERE CO_ART_COD=@CO_ART_COD AND CO_EMP_RUC=@CO_EMP_RUC AND CO_BOD_COD=@CO_BOD_COD
GO
