SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_DETALLE_DOCUMENTO_COMPRA]
@CO_DET_DOC_COM_COD UNIQUEIDENTIFIER
AS
DELETE dbo.CO_DETALLE_DOCUMENTO_COMPRA
WHERE CO_DET_DOC_COM_COD=@CO_DET_DOC_COM_COD
GO
