SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_TRANSACCIONES_BANCO_PLUS]
AS
SELECT     CO_TIP_TRA_COD AS CODIGO, CO_TIP_TRA_NOM AS NOMBRE
FROM       dbo.CO_TIPO_TRANSACCION
GO
