SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_ACTIVO_REASIGNACION]
@CO_ACT_FIJ_COD varchar(10)
,@CO_ACT_REA_FEC datetime
,@CO_ACT_REA_ARE varchar(15)
,@CO_ACT_REA_UBI_NOM VARCHAR(30)
,@CO_ACT_REA_FUN_NOM NCHAR(50)
AS
INSERT INTO [dbo].[CO_ACTIVO_REASIGNACION]
			([CO_ACT_FIJ_COD]
			,[CO_ACT_REA_FEC]
			,[CO_ACT_REA_ARE]
			,[CO_ACT_REA_UBI_NOM]
			,[CO_ACT_REA_FUN_NOM])
     VALUES
			(@CO_ACT_FIJ_COD
			,@CO_ACT_REA_FEC
			,@CO_ACT_REA_ARE
			,@CO_ACT_REA_UBI_NOM
			,@CO_ACT_REA_FUN_NOM)
GO
