SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CUENTA_CORRIENTE]
@CO_CC_NUM VARCHAR(10),
@CO_BAN_COD INT,
@CO_EMP_RUC CHAR(13),
@CO_CUE_COD VARCHAR(40),
@CO_CC_NOM VARCHAR(30),
@CO_CC_USU_ALI VARCHAR(15),
@CO_CC_FEC DATETIME,
@CO_CC_SAL_INI FLOAT,
@CO_CC_NUM_CHE INT
AS
INSERT INTO CO_CUENTA_CORRIENTE VALUES(
@CO_CC_NUM,
@CO_BAN_COD,
@CO_EMP_RUC,
@CO_CUE_COD,
@CO_CC_NOM,
@CO_CC_USU_ALI,
@CO_CC_FEC,
@CO_CC_SAL_INI,
0,
@CO_CC_NUM_CHE)
GO
