SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ASIENTO_CIERRE_MES]
@CO_EMP_RUC CHAR(13),
@CO_ASI_MES INT,
@CO_ASI_ANIO INT
AS
SELECT dbo.CO_ASIENTO.CO_ASI_FEC, dbo.CO_ASIENTO.CO_ASI_DEB, dbo.CO_ASIENTO.CO_ASI_HAB, dbo.CO_CUENTA.CO_CUE_NOM, 
dbo.CO_CUENTA.CO_CUE_COD_ANT, dbo.CO_CUENTA.CO_CUE_COD
FROM dbo.CO_ASIENTO INNER JOIN
dbo.CO_CUENTA ON dbo.CO_ASIENTO.CO_EMP_RUC = dbo.CO_CUENTA.CO_EMP_RUC AND 
dbo.CO_ASIENTO.CO_CUE_COD = dbo.CO_CUENTA.CO_CUE_COD
WHERE dbo.CO_CUENTA.CO_EMP_RUC=@CO_EMP_RUC
AND MONTH(dbo.CO_ASIENTO.CO_ASI_FEC)=@CO_ASI_MES 
AND YEAR(dbo.CO_ASIENTO.CO_ASI_FEC)=@CO_ASI_ANIO
ORDER BY dbo.CO_ASIENTO.CO_COM_NUM
GO
