SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_VERIFICAR_CENTRO_COSTOS]
@CO_CEN_COS_COD VARCHAR(30),
@CO_EMP_RUC CHAR(13)
AS
SELECT COUNT(*) FROM CO_CENTRO_COSTO
WHERE CO_CEN_COS_COD=@CO_CEN_COS_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
