SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CCONTABLE_CCORRIENTE]
@CO_CC_NUM VARCHAR(10),
@CO_EMP_RUC CHAR(13)
AS
SELECT CO_CUE_COD
FROM CO_CUENTA_CORRIENTE
WHERE CO_CC_NUM=@CO_CC_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
