SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PAGO_DOCUMENTO_COMPRA]
@CO_DOC_COM_NUM int
,@CO_DOC_ESTADO_DE_PAGO bit
AS
update [dbo].[CO_DOCUMENTO_COMPRA]set
[CO_DOC_ESTADO_DE_PAGO]=@CO_DOC_ESTADO_DE_PAGO
where
[CO_DOC_COM_NUM]=@CO_DOC_COM_NUM
GO
