SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_COMPROBANTE_ESTADO]
@CO_EMP_RUC char(13)
,@CO_COM_NUM_REF uniqueidentifier
,@CO_COM_EST varchar(10)
AS
UPDATE CO_COMPROBANTE
SET CO_COM_EST=@CO_COM_EST
WHERE @CO_EMP_RUC=CO_EMP_RUC AND
CO_COM_NUM_REF=@CO_COM_NUM_REF

GO
