SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_BALANCE]
@CO_EMP_RUC CHAR(13),
@CO_MES_NUM INT,
@CO_ANIO_NUM INT,
@CO_BAL_OPC BIT
AS

declare @mes int
select top 1 @mes=count(*) from co_mes where CO_MES_NUM=@CO_MES_NUM and CO_ANIO_NUM=@CO_ANIO_NUM and CO_EMP_RUC=@CO_EMP_RUC
if(@mes=1)
begin
	SELECT CO_CUE_COD,CO_CUE_NOM,CO_MES_SAL_ACT,
	CO_MES_SAL_DEB,CO_MES_SAL_HAB,CO_MES_SAL_ANT,CO_EMP_NOM,@CO_MES_NUM AS CO_MES,@CO_ANIO_NUM AS CO_ANIO,CO_CUE_TIP
	FROM CO_VW_SELECT_CUENTAS_SALDOS
	WHERE CO_EMP_RUC=@CO_EMP_RUC and CO_MES_NUM=@CO_MES_NUM and CO_ANIO_NUM=@CO_ANIO_NUM 
	and (CO_MES_SAL_ANT<>0 or CO_MES_SAL_ACT<>0 or CO_MES_SAL_DEB<>0 or CO_MES_SAL_HAB<>0)
	AND CO_CUE_TIP=CASE WHEN @CO_BAL_OPC=0 THEN CO_CUE_TIP ELSE 'Movimiento' END
END
ELSE
BEGIN
	SELECT CO_CUE_COD,CO_CUE_NOM,CO_MES_SAL_ACT,
	CO_MES_SAL_DEB,CO_MES_SAL_HAB,CO_MES_SAL_ANT,CO_EMP_NOM,@CO_MES_NUM AS CO_MES,@CO_ANIO_NUM AS CO_ANIO,CO_CUE_TIP
	FROM CO_VW_SELECT_CUENTAS_SALDOS_TEMP
	WHERE CO_EMP_RUC=@CO_EMP_RUC
	AND CO_CUE_TIP=CASE WHEN @CO_BAL_OPC=0 THEN CO_CUE_TIP ELSE 'Movimiento' END
END






GO
