SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ASIENTO_AUX]
@CO_EMP_RUC char(13)
,@CO_TIP_COM_COD int
,@CO_COM_NUM int
AS
SELECT CO_EMP_RUC,CO_CUE_COD,CO_ASI_COD,
CO_TIP_COM_COD,CO_COM_NUM,CO_ASI_AUX_FEC,CO_ASI_AUX_DES
,CO_ASI_AUX_DEB,CO_ASI_AUX_HAB,CO_ASI_AUX_COD_REF,CO_ASI_AUX_CLI
FROM [dbo].[CO_ASIENTO_AUX] 
WHERE @CO_EMP_RUC=CO_EMP_RUC AND
CO_TIP_COM_COD=@CO_TIP_COM_COD AND
CO_COM_NUM=@CO_COM_NUM
GO
