SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_PROFORMA]
@CO_EMP_RUC CHAR(13)
,@CO_CLI_NOM NVARCHAR(100)
,@CO_PRO_FEC1 DATETIME
,@CO_PRO_FEC2 DATETIME
,@CO_PRO_OPC CHAR(1)
AS
IF(@CO_PRO_OPC='T')
SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_PROFORMA.*, dbo.CO_CLIENTE.CO_CLI_CED
FROM dbo.CO_CLIENTE INNER JOIN
dbo.CO_PROFORMA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_PROFORMA.CO_CLI_COD AND 
dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_PROFORMA.CO_EMP_RUC
WHERE dbo.CO_PROFORMA.CO_EMP_RUC=@CO_EMP_RUC AND
dbo.CO_PROFORMA.CO_PRO_FEC>=@CO_PRO_FEC1 AND dbo.CO_PROFORMA.CO_PRO_FEC<=@CO_PRO_FEC2 AND dbo.CO_PROFORMA.CO_EMP_RUC=@CO_EMP_RUC
AND dbo.CO_PROFORMA.CO_PRO_EST<>'ANULADA' AND dbo.CO_PROFORMA.CO_PRO_EST<>'DESPACHADO'
ELSE IF(@CO_PRO_OPC='C')
begin
DECLARE @LIKE AS VARCHAR(50)
SET @LIKE='%'+@CO_CLI_NOM+'%'
SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_PROFORMA.*, dbo.CO_CLIENTE.CO_CLI_CED
FROM dbo.CO_CLIENTE INNER JOIN
dbo.CO_PROFORMA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_PROFORMA.CO_CLI_COD AND 
dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_PROFORMA.CO_EMP_RUC
WHERE dbo.CO_CLIENTE.CO_CLI_NOM like @LIKE AND dbo.CO_PROFORMA.CO_EMP_RUC=@CO_EMP_RUC AND
dbo.CO_PROFORMA.CO_PRO_FEC>=@CO_PRO_FEC1 AND dbo.CO_PROFORMA.CO_PRO_FEC<=@CO_PRO_FEC2 AND dbo.CO_PROFORMA.CO_EMP_RUC=@CO_EMP_RUC
AND dbo.CO_PROFORMA.CO_PRO_EST<>'ANULADA' AND dbo.CO_PROFORMA.CO_PRO_EST<>'DESPACHADO'
end
ELSE IF(@CO_PRO_OPC='F')
SELECT dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_PROFORMA.*, dbo.CO_CLIENTE.CO_CLI_CED
FROM dbo.CO_CLIENTE INNER JOIN
dbo.CO_PROFORMA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_PROFORMA.CO_CLI_COD AND 
dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_PROFORMA.CO_EMP_RUC 
WHERE dbo.CO_PROFORMA.CO_PRO_FEC>=@CO_PRO_FEC1 AND dbo.CO_PROFORMA.CO_PRO_FEC<=@CO_PRO_FEC2 AND dbo.CO_PROFORMA.CO_EMP_RUC=@CO_EMP_RUC
AND dbo.CO_PROFORMA.CO_PRO_EST<>'ANULADA' AND dbo.CO_PROFORMA.CO_PRO_EST<>'DESPACHADO'
GO
