SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_DETALLE_RETENCION_COMPRA]
@CO_DOC_COM_NUM int
,@CO_DOC_COM_TIP nvarchar(50)
,@CO_EMP_RUC char(13)
,@CO_TIP_RET_COD varchar(10)
,@CO_DET_RET_NUM nvarchar(50)
,@CO_DET_RET_BAS float
,@CO_DET_RET_POR int
,@CO_DET_RET_TOT float
AS
INSERT INTO [dbo].[CO_DETALLE_RETENCION_COMPRA]
([CO_DOC_COM_NUM]
,[CO_DOC_COM_TIP]
,[CO_EMP_RUC]
,[CO_TIP_RET_COD]
,[CO_DET_RET_NUM]
,[CO_DET_RET_BAS]
,[CO_DET_RET_POR]
,[CO_DET_RET_TOT])
VALUES
(@CO_DOC_COM_NUM
,@CO_DOC_COM_TIP
,@CO_EMP_RUC
,@CO_TIP_RET_COD
,@CO_DET_RET_NUM
,@CO_DET_RET_BAS
,@CO_DET_RET_POR
,@CO_DET_RET_TOT)
GO
