SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_BODEGA_ARTICULO]
@CO_BOD_COD INT
,@CO_ART_COD NVARCHAR(20)
AS
DELETE dbo.CO_UBICACIONARTICULO
WHERE CO_BOD_COD=@CO_BOD_COD AND CO_ART_COD=@CO_ART_COD
GO
