SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_COMPROBANTE_CONTABLE_ESTADO]
@CO_EMP_RUC char(13)
,@CO_COM_NUM int
,@CO_TIP_COM_COD varchar(10)
,@CO_COM_EST VARCHAR(15)
AS
UPDATE CO_COMPROBANTE
SET CO_COM_EST=@CO_COM_EST
WHERE @CO_EMP_RUC=CO_EMP_RUC AND
CO_COM_NUM=@CO_COM_NUM AND
CO_TIP_COM_COD=@CO_TIP_COM_COD
GO
