SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PROYECTO_INGRESOS]
@CO_PRO_COD int
,@CO_EMP_RUC char(13)
,@CO_TIP_REC_COD int
,@CO_ING_NOM nvarchar(50)
,@CO_ING_MAN bit
,@CO_ING_CUE nvarchar(50)
,@CO_ING_COD INT
,@CO_PRO_TIP nvarchar
AS
UPDATE [dbo].[CO_PROYECTO_INGRESOS] SET
           [CO_PRO_COD]=@CO_PRO_COD
           ,[CO_TIP_REC_COD]=@CO_TIP_REC_COD
           ,[CO_ING_NOM]=@CO_ING_NOM
           ,[CO_ING_MAN]=@CO_ING_MAN
           ,[CO_ING_CUE]=@CO_ING_CUE
			,CO_PRO_TIP=@CO_PRO_TIP
WHERE
           (CO_ING_COD=@CO_ING_COD
           AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
