SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PARAMETRO_INVENTARIO]
@CO_EMP_RUC char(13)
,@CO_PAR_INV_TIP char(1)
AS
INSERT INTO [dbo].[CO_PARAMETRO_INVENTARIO]
([CO_EMP_RUC]
,[CO_PAR_INV_TIP])
VALUES
(@CO_EMP_RUC
,@CO_PAR_INV_TIP)
GO
