SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_COMPROBANTE]
@CO_EMP_RUC CHAR(13),
@CO_TIP_COM_COD INT,
@CO_COM_NUM INT,
@CO_COM_NOM_EMP VARCHAR(50),
@CO_COM_RUC_EMP CHAR(13),
@CO_COM_CONC VARCHAR(150),
@CO_COM_EST VARCHAR(10),
@CO_COM_FEC DATETIME,
@CO_COM_VAL_LET NVARCHAR(200),
@CO_COM_NUM_CHE NVARCHAR(10),
@CO_RETENCION_ID uniqueidentifier
AS
UPDATE CO_COMPROBANTE SET
CO_COM_NOM_EMP=@CO_COM_NOM_EMP,
CO_COM_RUC_EMP=@CO_COM_RUC_EMP,
CO_COM_CONC=@CO_COM_CONC,
CO_COM_EST=@CO_COM_EST,
CO_COM_FEC=@CO_COM_FEC,
CO_COM_VAL_LET=@CO_COM_VAL_LET,
CO_COM_NUM_CHE=@CO_COM_NUM_CHE
,CO_RETENCION_ID=@CO_RETENCION_ID 
WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
CO_TIP_COM_COD=@CO_TIP_COM_COD AND
CO_COM_NUM=@CO_COM_NUM
GO
