SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_CADUCIDAD]
(@CO_ART_COD nvarchar(40)
,@CO_EMP_RUC char(13)
,@CO_DOC_COM_NUM INT
,@CO_CAD_COD int
,@CO_CAD_FEC_ELA datetime
,@CO_CAD_FEC_FIN datetime
,@CO_CAD_LOT nvarchar(10)
,@CO_CAD_EST BIT)
AS
UPDATE [dbo].[CO_CADUCIDAD] SET
[CO_CAD_FEC_ELA]=@CO_CAD_FEC_ELA
,[CO_CAD_FEC_FIN]=@CO_CAD_FEC_FIN
,[CO_CAD_LOT]=@CO_CAD_LOT
,CO_CAD_EST=@CO_CAD_EST
WHERE 
([CO_ART_COD]=@CO_ART_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_CAD_COD]=@CO_CAD_COD
AND CO_DOC_COM_NUM=@CO_DOC_COM_NUM)
GO
