SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_MOVIMIENTO_NOCONCILIADO]
@CO_CC_NUM VARCHAR(10),
@CO_EMP_RUC CHAR(13)
AS
SELECT *
FROM CO_MOVIENTO_NOCONCILIADO
WHERE CO_CC_NUM=@CO_CC_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
