SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_PROFESOR_CURSO]
@CURS_COD INT,
@PARA_COD INT
as
SELECT DISTINCT dbo.PROFESOR.PROF_COD AS CODIGO, dbo.PROFESOR.PROF_NOM AS PROFESOR
FROM DBO.DICTA INNER JOIN
dbo.PROFESOR ON dbo.DICTA.PROF_COD = dbo.PROFESOR.PROF_COD
WHERE CURS_COD=@CURS_COD AND PARA_COD=@PARA_COD
GO
