SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_RUBRO_ROL]
@CO_RUB_ROL_COD int
,@CO_EMP_RUC char(13)
AS 
DELETE [dbo].[CO_RUBROS_ROL]
WHERE [CO_EMP_RUC]=@CO_EMP_RUC AND CO_RUB_ROL_COD=@CO_RUB_ROL_COD
GO
