SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_NOTA_DEBITO]
@CO_EMP_RUC CHAR(13)
AS
SELECT MAX(CO_NOT_DEB_NUM) AS CO_NOT_DEB_MAX
FROM CO_NOTA_DEBITO
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
