SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PAGOS_DOCUMENTO_VENTA]
@CO_EMP_RUC CHAR(13),
@CO_CLI_COD CHAR(50),
@CO_TIP_DOC_VEN_NUM INT
AS
if(@CO_TIP_DOC_VEN_NUM=1)
BEGIN
	SELECT CO_PAG_DOC_VEN_COD,CO_PAG_DOC_VEN_CON,CO_PAG_DOC_VEN_FEC,CO_DOC_VEN_NUM,CO_PAG_DOC_VEN_VAL,CO_PAG_DOC_VEN_VAL_IMP,
	CO_DOC_VEN_ID
	FROM CO_VW_SELECT_PAGOS_DOCUMENTO_VENTA
	WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PAG_DOC_VEN_EST=0 
	AND CO_CLI_COD=@CO_CLI_COD
	AND CO_TIP_DOC_VEN_NUM IN (20)
	order by CO_DOC_VEN_NUM,CO_PAG_DOC_VEN_FEC
END
ELSE IF(@CO_TIP_DOC_VEN_NUM=2)
BEGIN
	SELECT CO_PAG_DOC_VEN_COD,CO_PAG_DOC_VEN_CON,CO_PAG_DOC_VEN_FEC,CO_DOC_VEN_NUM,CO_PAG_DOC_VEN_VAL,CO_PAG_DOC_VEN_VAL_IMP,
	CO_DOC_VEN_ID
	FROM CO_VW_SELECT_PAGOS_DOCUMENTO_VENTA
	WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PAG_DOC_VEN_EST=0 
	AND CO_CLI_COD=@CO_CLI_COD
	AND CO_TIP_DOC_VEN_NUM NOT IN (20)
	order by CO_DOC_VEN_NUM,CO_PAG_DOC_VEN_FEC
END
ELSE
BEGIN
	SELECT CO_PAG_DOC_VEN_COD,CO_PAG_DOC_VEN_CON,CO_PAG_DOC_VEN_FEC,CO_DOC_VEN_NUM,CO_PAG_DOC_VEN_VAL,CO_PAG_DOC_VEN_VAL_IMP,
	CO_DOC_VEN_ID
	FROM CO_VW_SELECT_PAGOS_DOCUMENTO_VENTA
	WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PAG_DOC_VEN_EST=0 
	AND CO_CLI_COD=@CO_CLI_COD
	order by CO_DOC_VEN_NUM,CO_PAG_DOC_VEN_FEC
END

GO
