SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_DETALLE_ESTADO_CUENTA_CLIENTE]
@CO_EST_CUE_FEC1 DATETIME
,@CO_EST_CUE_FEC2 DATETIME
,@PROF_COD CHAR(10)
,@CO_EST_CUE_OPC CHAR(1)
,@CO_EST_CUE_SAL FLOAT
,@co_emp_ruc char(13)
AS
SELECT * FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO
UNION
SELECT * FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_DEUDA
GO
