SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_MES_LIQUIDADO]
@CO_MES_NUM int
,@CO_ANIO_NUM int
,@CO_EMP_RUC char(13)
,@CO_UBI_COD int
AS
SELECT count(*) AS CONTADOR FROM CO_MES_LIQUIDACION
WHERE CO_MES_LIQ_NUM=@CO_MES_NUM 
AND CO_ANIO_LIQ_NUM=@CO_ANIO_NUM
AND CO_EMP_RUC=@CO_EMP_RUC
AND CO_UBI_COD=@CO_UBI_COD
GO
