SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_UBICACION_AF]
@CO_EMP_RUC char(13)
,@CO_UBI_COD INT
AS
DELETE [dbo].[CO_UBICACION_AF] 

     WHERE
           CO_EMP_RUC=@CO_EMP_RUC
		AND CO_UBI_COD=@CO_UBI_COD
GO
