SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PAGO_PROVEEDOR_ESTADO]
@CO_COM_PAG_NUM UNIQUEIDENTIFIER
,@CO_EMP_RUC CHAR(13)
AS
UPDATE CO_COMPROBANTE_PAGO SET
CO_COM_PAG_EST=0
WHERE CO_COM_PAG_NUM=@CO_COM_PAG_NUM AND CO_EMP_RUC=@CO_EMP_RUC
GO
