SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ARTICULO_CONTADOR]
@CO_EMP_RUC CHAR(13),
@CO_ART_BAR NVARCHAR(20)
AS
SELECT COUNT(*) FROM CO_ARTICULO
WHERE CO_ART_BAR=@CO_ART_BAR AND CO_EMP_RUC=@CO_EMP_RUC
and CO_ART_EST='ACTIVO'
GO
