SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_SALDO_ANTERIOR_CLIENTE]
@CO_EMP_RUC CHAR(13)
,@CO_DOC_COM_FEC_REG DATETIME
,@CO_CLI_COD VARCHAR(20)
,@CO_TIP_CLI_COD VARCHAR(10)
,@USUARIO_ID INT
AS
if((select count(*) from CO_PARAMETRO WHERE PARAMETRO_VALUE=@USUARIO_ID AND PARAMETRO_KEY='USUARIO_VENTAS')=0)
BEGIN
SELECT CO_EMP_NOM,CO_TIP_CLI_COD,CO_CLI_COD,CO_CLI_NOM,
SUM(CO_FACTURAS) AS SALDO_ANTERIOR, CO_TIP_CLI_NOM,
(SELECT SUM(CO_COBROS) 
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO
WHERE CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_EMP_RUC=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC AND 
CO_FEC_DOC<@CO_DOC_COM_FEC_REG AND
CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_CLI_COD=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_CLI_COD
GROUP BY CO_CLI_COD, CO_EMP_RUC) AS VALOR_COBRADO
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE
WHERE CO_FEC_DOC<@CO_DOC_COM_FEC_REG
AND CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC=@CO_EMP_RUC
AND CO_CLI_COD=CASE WHEN @CO_CLI_COD='' THEN CO_CLI_COD ELSE @CO_CLI_COD END
AND CO_TIP_CLI_COD=CASE WHEN @CO_TIP_CLI_COD='' THEN CO_TIP_CLI_COD ELSE @CO_TIP_CLI_COD END
AND CO_TIP_DOC_VEN_NUM<>20
GROUP BY CO_CLI_COD, CO_CLI_NOM,CO_TIP_CLI_COD,CO_TIP_CLI_NOM,CO_EMP_NOM,CO_EMP_RUC
END
ELSE
BEGIN
SELECT CO_EMP_NOM,CO_TIP_CLI_COD,CO_CLI_COD,CO_CLI_NOM,
SUM(CO_FACTURAS) AS SALDO_ANTERIOR, CO_TIP_CLI_NOM,
(SELECT SUM(CO_COBROS) 
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO
WHERE CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_EMP_RUC=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC AND 
CO_FEC_DOC<@CO_DOC_COM_FEC_REG AND
CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO.CO_CLI_COD=CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_CLI_COD
GROUP BY CO_CLI_COD, CO_EMP_RUC) AS VALOR_COBRADO
FROM CO_VW_SELECT_ESTADO_CUENTA_CLIENTE
WHERE CO_FEC_DOC<@CO_DOC_COM_FEC_REG
AND CO_VW_SELECT_ESTADO_CUENTA_CLIENTE.CO_EMP_RUC=@CO_EMP_RUC
AND CO_CLI_COD=CASE WHEN @CO_CLI_COD='' THEN CO_CLI_COD ELSE @CO_CLI_COD END
AND CO_TIP_CLI_COD=CASE WHEN @CO_TIP_CLI_COD='' THEN CO_TIP_CLI_COD ELSE @CO_TIP_CLI_COD END
AND CO_TIP_DOC_VEN_NUM=20
GROUP BY CO_CLI_COD, CO_CLI_NOM,CO_TIP_CLI_COD,CO_TIP_CLI_NOM,CO_EMP_NOM,CO_EMP_RUC
END
GO
