SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create proc [dbo].[CO_SP_SELECT_CUENTA_POR_PAGAR]
@CO_CUE_PAG_FEC_DESDE DATETIME,
@CO_CUE_PAG_FEC_HASTA DATETIME
AS
select * from dbo.CO_CUENTA_POR_PAGAR
where CO_CUE_PAG_FEC>=@CO_CUE_PAG_FEC_DESDE and CO_CUE_PAG_FEC<=@CO_CUE_PAG_FEC_HASTA
GO
