SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PAGO_PROVEEDOR]
@CO_EMP_RUC char(13)
,@CO_DOC_COM_NUM uniqueidentifier
AS
DELETE CO_PAGO_PROVEEDOR
WHERE CO_DOC_COM_NUM=@CO_DOC_COM_NUM AND
CO_EMP_RUC=@CO_EMP_RUC
GO
