SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_MES_LIQUIDACION]
@CO_MES_LIQ_NUM int
,@CO_ANIO_LIQ_NUM int
,@CO_EMP_RUC char(13)
,@CO_UBI_COD int
,@CO_MES_LIQ_EST bit
,@CO_MES_LIQ_USU_ALI nvarchar(13)
AS
INSERT INTO [dbo].[CO_MES_LIQUIDACION]
([CO_MES_LIQ_NUM]
,[CO_ANIO_LIQ_NUM]
,[CO_EMP_RUC]
,[CO_UBI_COD]
,[CO_MES_LIQ_EST]
,[CO_MES_LIQ_USU_ALI])
VALUES
(@CO_MES_LIQ_NUM
,@CO_ANIO_LIQ_NUM
,@CO_EMP_RUC
,@CO_UBI_COD
,@CO_MES_LIQ_EST
,@CO_MES_LIQ_USU_ALI)
GO
