SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PAGO_PROVEEDOR]
@CO_EMP_RUC char(13)
,@CO_DOC_COM_NUM uniqueidentifier
,@CO_PAG_PRO_VAL float
,@CO_PAG_PRO_FEC datetime
,@CO_PAG_PRO_EST bit
,@CO_PAG_PRO_CON nvarchar(50)
,@CO_PAG_PRO_VAL_IMP float
AS
INSERT INTO [dbo].[CO_PAGO_PROVEEDOR]
([CO_EMP_RUC]
,[CO_DOC_COM_NUM]
,[CO_PAG_PRO_VAL]
,[CO_PAG_PRO_FEC]
,[CO_PAG_PRO_EST]
,[CO_PAG_PRO_CON]
,CO_PAG_PRO_VAL_IMP)
VALUES
(@CO_EMP_RUC
,@CO_DOC_COM_NUM
,@CO_PAG_PRO_VAL
,@CO_PAG_PRO_FEC
,@CO_PAG_PRO_EST
,@CO_PAG_PRO_CON
,@CO_PAG_PRO_VAL_IMP)
GO
