SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TABAL_ICE]
@CO_ICE_NOM NVARCHAR(50),
@CO_ICE_POR FLOAT
AS
INSERT INTO [dbo].[CO_TABLA_ICE]
([CO_ICE_NOM]
,[CO_ICE_POR])
VALUES
(@CO_ICE_NOM
,@CO_ICE_POR)
GO
