SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PORCENTAJE_TIPO_RETENCION]
@CO_EMP_RUC CHAR(13),
@CO_TIP_RET_COD VARCHAR(10)
AS
SELECT dbo.CO_TIPO_RETENCION.CO_CUE_COD_COM, dbo.CO_CUENTA.CO_CUE_NOM, dbo.CO_TIPO_RETENCION.CO_TIP_RET_POR, dbo.CO_TIPO_RETENCION.CO_CUE_COD_VEN
FROM dbo.CO_TIPO_RETENCION INNER JOIN
dbo.CO_CUENTA ON dbo.CO_TIPO_RETENCION.CO_EMP_RUC = dbo.CO_CUENTA.CO_EMP_RUC AND 
dbo.CO_TIPO_RETENCION.CO_CUE_COD_COM = dbo.CO_CUENTA.CO_CUE_COD
WHERE dbo.CO_TIPO_RETENCION.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_TIPO_RETENCION.CO_TIP_RET_COD=@CO_TIP_RET_COD

GO
