SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_RUBRO_EMPLEADO]
@PROF_COD char(10)
,@CO_RUB_ROL_COD int
,@CO_EMP_RUC char(13)
,@CO_RUB_EMP_VAL float
AS
INSERT INTO [dbo].[CO_RUBRO_EMPLEADO]
([PROF_COD]
,[CO_RUB_ROL_COD]
,[CO_EMP_RUC]
,[CO_RUB_EMP_VAL])
VALUES
(@PROF_COD
,@CO_RUB_ROL_COD
,@CO_EMP_RUC
,@CO_RUB_EMP_VAL)
GO
