SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CADUCIDAD_ARTICULO]
@CO_ART_COD nvarchar(40)
,@CO_EMP_RUC char(13)
AS
SELECT *
FROM CO_CADUCIDAD
WHERE CO_CAD_EST=1 AND CO_ART_COD=@CO_ART_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
