SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_EXISTENCIAS_DIARIAS]
@CO_EMP_RUC CHAR(13)
,@CO_KAR_TOT_FEC1 DATETIME
,@CO_KAR_TOT_FEC2 DATETIME
,@co_art_cod nvarchar(50)
AS
SELECT * FROM dbo.CO_VW_SELECT_REPORTE_EXISTENCIAS
WHERE CO_KAR_TOT_FEC>=@CO_KAR_TOT_FEC1 AND CO_KAR_TOT_FEC<=@CO_KAR_TOT_FEC2 AND CO_EMP_RUC=@CO_EMP_RUC
and co_art_cod=case @co_art_cod when '' then co_art_cod else @co_art_cod end
order by co_kar_tot_fec
GO
