SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DETALLE_COBRO]
@CO_COM_COB_NUM INT
,@CO_EMP_RUC CHAR(13)
AS
SELECT * FROM CO_DETALLE_COBRO
WHERE CO_COM_COB_NUM=@CO_COM_COB_NUM
AND CO_EMP_RUC=@CO_EMP_RUC
GO
