SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_LIBRO_BANCO_CAJERA_PLUS]
@NUMERO_RESIBO_LIBRO_BANCO nvarchar(50)
AS
SELECT     NUMERO_RESIBO_LIBRO_BANCO, TIPO_TRANSACCION_LIBRO_BANCO, DETALLE_TRANSACCION_LIBRO_BANCO, VALOR_INGRESO_LIBRO_BANCO,
                       VALOR_EGRESO_LIBRO_BANCO, FECHA_TRANSACCION_LIBRO_BANCO, CODIGO_LIBRO_BANCO
FROM         dbo.CO_LIBRO_BANCO
WHERE     (NUMERO_RESIBO_LIBRO_BANCO = @NUMERO_RESIBO_LIBRO_BANCO)
GO
