SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_PAGO_DOCUMENTO_PLUS]
@CODIGO_DOCUMENTO_PAGO int
,@PAGADO_PENDIENTE_FORMA_PAGO nvarchar(9)
AS
UPDATE [dbo].[CO_DOCUMENTO_PAGO_PROVEEDORES]set
[PAGADO_PENDIENTE_FORMA_PAGO]=@PAGADO_PENDIENTE_FORMA_PAGO
WHERE
[CODIGO_DOCUMENTO_PAGO]=@CODIGO_DOCUMENTO_PAGO AND ESTADO_DOCUMENTO_PAGO='ACTIVA'
GO
