SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_DOCUMENTO_RESERVA_OBTENER_PORID]
@CO_DOC_VEN_ID UNIQUEIDENTIFIER
AS
SELECT DR.*, c.CO_CLI_NOM, C.CO_CLI_CED, TI.CO_TIP_IDE_NOM
FROM CO_DOCUMENTO_RESERVA DR inner join CO_CLIENTE C on DR.CO_CLI_COD=c.CO_CLI_COD
inner join CO_TIPO_IDENTIFICACION TI on C.CO_TIP_IDE_COD=TI.CO_TIP_IDE_COD
WHERE CO_DOC_VEN_ID=@CO_DOC_VEN_ID
GO
