SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_RETENCION]
@CO_DOC_COM_ID UNIQUEIDENTIFIER
AS
DELETE FROM CO_DETALLE_RETENCION WHERE CO_RET_COD IN (SELECT CO_RET_COD FROM CO_RETENCION WHERE CO_DOC_COM_ID=@CO_DOC_COM_ID)
DELETE FROM CO_RETENCION WHERE CO_DOC_COM_ID=@CO_DOC_COM_ID
GO
