SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FAMILIA_POR_TIPO]
@CO_TIP_ART_COD NVARCHAR(10),
@CO_EMP_RUC CHAR(13)
AS
SELECT * FROM CO_FAMILIA_ARTICULO
WHERE CO_TIP_ART_COD=@CO_TIP_ART_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
