SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TABLA_PRECIO_ARTICULO]
@ListaDePrecioID INT
,@CO_ART_COD NVARCHAR(20)
AS
DELETE dbo.CO_TABLA_PRECIO
WHERE ListaDePrecioID=@ListaDePrecioID AND CO_ART_COD=@CO_ART_COD
GO
