SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_SALDO_MES]
@CO_EMP_RUC CHAR(13),
@CO_MES_NUM INT,
@CO_ANIO_NUM INT
AS
SELECT *
FROM CO_MES_SALDO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_MES_NUM=@CO_MES_NUM AND CO_ANIO_NUM=@CO_ANIO_NUM

GO
