SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_INGRESO_BODEGA]
@CO_EMP_RUC CHAR(13),
@FECHA1 DATETIME,
@FECHA2 DATETIME
AS
SELECT IngresoID, Numero, Fecha, Estado, Usuario,
		(SELECT CO_BOD_NOM FROM dbo.CO_BODEGA WHERE CO_BOD_COD=dbo.CO_INGRESO.BodegaOrigenID) AS BodegaOrigen,
		(SELECT CO_BOD_NOM FROM dbo.CO_BODEGA WHERE CO_BOD_COD=dbo.CO_INGRESO.BodegaDestinoID) AS BodegaDestino
FROM dbo.CO_INGRESO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND (Fecha BETWEEN @FECHA1 AND @FECHA2)
AND Estado<>'ANULADA'
order by Fecha
GO
