SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_CARTERA_SALDOS]
@CO_EMP_RUC CHAR(13)
,@CO_DOC_VEN_FEC1 DATETIME
,@CO_DOC_VEN_FEC2 DATETIME
,@CO_TIP_CLI_COD NVARCHAR(10)
,@CO_CLI_COD NVARCHAR(50)
,@CO_VEN_CED NCHAR(10)
,@CO_CAR_OPC CHAR(1)
AS
IF @CO_CAR_OPC='T'
SELECT *,@CO_DOC_VEN_FEC1,@CO_DOC_VEN_FEC2 
FROM CO_VW_SELECT_REPORTE_CARTERA_SALDOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND
CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
IF @CO_CAR_OPC='O'
SELECT *,@CO_DOC_VEN_FEC1,@CO_DOC_VEN_FEC2 FROM CO_VW_SELECT_REPORTE_CARTERA_SALDOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_TIP_CLI_COD=@CO_TIP_CLI_COD AND
CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND
CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
IF @CO_CAR_OPC='C'
SELECT *,@CO_DOC_VEN_FEC1,@CO_DOC_VEN_FEC2 FROM CO_VW_SELECT_REPORTE_CARTERA_SALDOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CLI_COD=@CO_CLI_COD AND
CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND
CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
IF @CO_CAR_OPC='V'
SELECT *,@CO_DOC_VEN_FEC1,@CO_DOC_VEN_FEC2 FROM CO_VW_SELECT_REPORTE_CARTERA_SALDOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_VEN_CED=@CO_VEN_CED AND
CO_DOC_VEN_FEC>=@CO_DOC_VEN_FEC1 AND
CO_DOC_VEN_FEC<=@CO_DOC_VEN_FEC2
GO
