SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CARGO_SUELDO]
@CO_CAR_COD INT,
@CO_EMP_RUC CHAR(13)
AS
SELECT CO_CAR_SUE FROM CO_CARGO
WHERE CO_CAR_COD=@CO_CAR_COD
GO
