SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_TIPO_COMPROBANTE_COMPRA]
AS
SELECT [CO_TIP_COM_COM_COD]
      ,[CO_TIP_COM_COM_NOM]
      ,[CO_TIP_COM_COM_FEC_VIG]
	  ,[CO_TIP_COM_COM_INV]
  FROM [dbo].[CO_TIPO_COMPROBANTE_COMPRA]
GO
