SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_INSERT_PERMISO]
@PERM_NOM varchar(80),
@CONT_COD int,
@CO_GRU_COD int,
@USUA_COD INT
as
insert into Permiso values(@PERM_NOM,@CONT_COD,@USUA_COD,@CO_GRU_COD)
GO
