SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_SERVICIOS]
@CO_TIP_SER_COD int
,@CO_EMP_RUC char(13)
AS
DELETE [dbo].[CO_TIPO_SERVICIO]
WHERE 
([CO_EMP_RUC]=@CO_EMP_RUC AND CO_TIP_SER_COD=@CO_TIP_SER_COD)
GO
