SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_COMPROBANTE_RETENCION]
@CO_DOC_COM_ID UNIQUEIDENTIFIER,
@CO_EMP_RUC CHAR(13)
AS
SELECT *
FROM dbo.CO_RETENCION
WHERE CO_EMP_RUC=@CO_EMP_RUC AND 
CO_DOC_COM_ID=@CO_DOC_COM_ID
GO
