SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_REGISTRO_DIARIO]
@CO_EMP_RUC CHAR(13),
@PROF_COD CHAR(10),
@CO_REG_DIA_FEC DATETIME,
@CO_REG_DIA_HOR_SAL NCHAR(5),
@CO_REG_DIA_HOR_EXT FLOAT,
@CO_REG_DIA_HOR_SUP FLOAT,
@CO_REG_DIA_HOR_PER FLOAT,
@CO_REG_DIA_HOR_LAB FLOAT,
@CO_REG_DIA_HOR_CIE BIT
AS
UPDATE CO_REGISTRO_DIARIO SET
CO_REG_DIA_HOR_SAL=@CO_REG_DIA_HOR_SAL,
CO_REG_DIA_HOR_EXT=@CO_REG_DIA_HOR_EXT,
CO_REG_DIA_HOR_SUP=@CO_REG_DIA_HOR_SUP,
CO_REG_DIA_HOR_PER=@CO_REG_DIA_HOR_PER,
CO_REG_DIA_HOR_CIE=@CO_REG_DIA_HOR_CIE,
CO_REG_DIA_HOR_LAB=@CO_REG_DIA_HOR_LAB
FROM CO_REGISTRO_DIARIO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PROF_COD=@PROF_COD AND
Convert(varchar(10),CO_REG_DIA_FEC,103)=Convert(varchar(10),@CO_REG_DIA_FEC,103)
GO
