SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_ARTICULOS]
@CO_EMP_RUC CHAR(13),
@CO_ALM_COD NVARCHAR(20),
@CO_BOD_COD INT,
@CO_FAM_ART_COD INT,
@CO_ART_COM NVARCHAR(100),
@CO_OPCION CHAR(1),
@CO_TAB_PRE_NOM NVARCHAR(50)
AS
IF @CO_OPCION='T'
BEGIN
	WITH S
			as
			(
	SELECT RANK() OVER (PARTITION BY CO_ARTICULO.CO_ART_COD, dbo.CO_KARDEX_TOTAL.CO_BOD_COD ORDER BY dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_FEC DESC) AS 'RowNumber',
	dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_NOM, 
	dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_UNI as CO_KAR_TOT_SAL_VAL_UNI, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_TOT as CO_KAR_TOT_SAL_VAL_TOT, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT as CO_KAR_TOT_SAL_CANT,
	dbo.CO_ARTICULO.CO_ART_COD, dbo.CO_TABLA_PRECIO.CO_TAB_PRE_POR_ART, dbo.CO_TABLA_PRECIO.CO_TAB_PRE, 
	dbo.CO_LISTA_PRECIO.Nombre,dbo.CO_ARTICULO.CO_ART_PRE_COS
	FROM dbo.CO_ARTICULO INNER JOIN
				dbo.CO_EMPRESA ON dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC INNER JOIN
				dbo.CO_TABLA_PRECIO ON dbo.CO_ARTICULO.CO_ART_COD = CO_TABLA_PRECIO.CO_ART_COD INNER JOIN 
				dbo.CO_LISTA_PRECIO ON dbo.CO_TABLA_PRECIO.ListaDePrecioID = dbo.CO_LISTA_PRECIO.ListaDePrecioID INNER JOIN
				dbo.CO_FAMILIA_ARTICULO ON dbo.CO_ARTICULO.CO_FAM_ART_COD = dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_COD INNER JOIN
				 dbo.CO_UBICACIONARTICULO ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_UBICACIONARTICULO.CO_ART_COD AND 
				 dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_UBICACIONARTICULO.CO_EMP_RUC INNER JOIN
				 dbo.CO_BODEGA ON dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_BODEGA.CO_BOD_COD LEFT OUTER JOIN
				 dbo.CO_KARDEX_TOTAL ON dbo.CO_UBICACIONARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
				 dbo.CO_UBICACIONARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC AND 
				 dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_KARDEX_TOTAL.CO_BOD_COD
	WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_LISTA_PRECIO.Nombre=@CO_TAB_PRE_NOM)          
	SELECT * FROM S WHERE RowNumber=1
END
ELSE IF @CO_OPCION='A'
BEGIN
	WITH S
			as
			(
	SELECT RANK() OVER (PARTITION BY CO_ARTICULO.CO_ART_COD, dbo.CO_KARDEX_TOTAL.CO_BOD_COD ORDER BY dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_FEC DESC) AS 'RowNumber',
	dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_NOM, 
	dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_UNI as CO_KAR_TOT_SAL_VAL_UNI, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_TOT as CO_KAR_TOT_SAL_VAL_TOT, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT as CO_KAR_TOT_SAL_CANT,
	dbo.CO_ARTICULO.CO_ART_COD, dbo.CO_TABLA_PRECIO.CO_TAB_PRE_POR_ART, dbo.CO_TABLA_PRECIO.CO_TAB_PRE, 
	dbo.CO_LISTA_PRECIO.Nombre,dbo.CO_ARTICULO.CO_ART_PRE_COS
	FROM dbo.CO_ARTICULO INNER JOIN
				dbo.CO_EMPRESA ON dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC INNER JOIN
				dbo.CO_TABLA_PRECIO ON dbo.CO_ARTICULO.CO_ART_COD = CO_TABLA_PRECIO.CO_ART_COD INNER JOIN 
				dbo.CO_LISTA_PRECIO ON dbo.CO_TABLA_PRECIO.ListaDePrecioID = dbo.CO_LISTA_PRECIO.ListaDePrecioID INNER JOIN
				dbo.CO_FAMILIA_ARTICULO ON dbo.CO_ARTICULO.CO_FAM_ART_COD = dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_COD INNER JOIN
				 dbo.CO_UBICACIONARTICULO ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_UBICACIONARTICULO.CO_ART_COD AND 
				 dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_UBICACIONARTICULO.CO_EMP_RUC INNER JOIN
				 dbo.CO_BODEGA ON dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_BODEGA.CO_BOD_COD LEFT OUTER JOIN
				 dbo.CO_KARDEX_TOTAL ON dbo.CO_UBICACIONARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
				 dbo.CO_UBICACIONARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC AND 
				 dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_KARDEX_TOTAL.CO_BOD_COD
	WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_LISTA_PRECIO.Nombre=@CO_TAB_PRE_NOM AND dbo.CO_BODEGA.CO_ALM_COD=@CO_ALM_COD)          
	SELECT * FROM S WHERE RowNumber=1
END	
ELSE IF @CO_OPCION='B'
BEGIN
	WITH S
			as
			(
	SELECT RANK() OVER (PARTITION BY CO_ARTICULO.CO_ART_COD, dbo.CO_KARDEX_TOTAL.CO_BOD_COD ORDER BY dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_FEC DESC) AS 'RowNumber',
	dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_NOM, 
	dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_UNI as CO_KAR_TOT_SAL_VAL_UNI, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_TOT as CO_KAR_TOT_SAL_VAL_TOT, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT as CO_KAR_TOT_SAL_CANT,
	dbo.CO_ARTICULO.CO_ART_COD, dbo.CO_TABLA_PRECIO.CO_TAB_PRE_POR_ART, dbo.CO_TABLA_PRECIO.CO_TAB_PRE, 
	dbo.CO_LISTA_PRECIO.Nombre,dbo.CO_ARTICULO.CO_ART_PRE_COS
	FROM dbo.CO_ARTICULO INNER JOIN
				dbo.CO_EMPRESA ON dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC INNER JOIN
				dbo.CO_TABLA_PRECIO ON dbo.CO_ARTICULO.CO_ART_COD = CO_TABLA_PRECIO.CO_ART_COD INNER JOIN 
				dbo.CO_LISTA_PRECIO ON dbo.CO_TABLA_PRECIO.ListaDePrecioID = dbo.CO_LISTA_PRECIO.ListaDePrecioID INNER JOIN
				dbo.CO_FAMILIA_ARTICULO ON dbo.CO_ARTICULO.CO_FAM_ART_COD = dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_COD INNER JOIN
				 dbo.CO_UBICACIONARTICULO ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_UBICACIONARTICULO.CO_ART_COD AND 
				 dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_UBICACIONARTICULO.CO_EMP_RUC INNER JOIN
				 dbo.CO_BODEGA ON dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_BODEGA.CO_BOD_COD LEFT OUTER JOIN
				 dbo.CO_KARDEX_TOTAL ON dbo.CO_UBICACIONARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
				 dbo.CO_UBICACIONARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC AND 
				 dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_KARDEX_TOTAL.CO_BOD_COD
	WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_LISTA_PRECIO.Nombre=@CO_TAB_PRE_NOM AND dbo.CO_BODEGA.CO_BOD_COD=@CO_BOD_COD)          
	SELECT * FROM S WHERE RowNumber=1
END
ELSE IF @CO_OPCION='F'
BEGIN
	WITH S
			as
			(
	SELECT RANK() OVER (PARTITION BY CO_ARTICULO.CO_ART_COD, dbo.CO_KARDEX_TOTAL.CO_BOD_COD ORDER BY dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_FEC DESC) AS 'RowNumber',
	dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_NOM, 
	dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_UNI as CO_KAR_TOT_SAL_VAL_UNI, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_VAL_TOT as CO_KAR_TOT_SAL_VAL_TOT, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT as CO_KAR_TOT_SAL_CANT,
	dbo.CO_ARTICULO.CO_ART_COD, dbo.CO_TABLA_PRECIO.CO_TAB_PRE_POR_ART, dbo.CO_TABLA_PRECIO.CO_TAB_PRE, 
	dbo.CO_LISTA_PRECIO.Nombre,dbo.CO_ARTICULO.CO_ART_PRE_COS
	FROM dbo.CO_ARTICULO INNER JOIN
				dbo.CO_EMPRESA ON dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC INNER JOIN
				dbo.CO_TABLA_PRECIO ON dbo.CO_ARTICULO.CO_ART_COD = CO_TABLA_PRECIO.CO_ART_COD INNER JOIN 
				dbo.CO_LISTA_PRECIO ON dbo.CO_TABLA_PRECIO.ListaDePrecioID = dbo.CO_LISTA_PRECIO.ListaDePrecioID INNER JOIN
				dbo.CO_FAMILIA_ARTICULO ON dbo.CO_ARTICULO.CO_FAM_ART_COD = dbo.CO_FAMILIA_ARTICULO.CO_FAM_ART_COD INNER JOIN
				 dbo.CO_UBICACIONARTICULO ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_UBICACIONARTICULO.CO_ART_COD AND 
				 dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_UBICACIONARTICULO.CO_EMP_RUC INNER JOIN
				 dbo.CO_BODEGA ON dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_BODEGA.CO_BOD_COD LEFT OUTER JOIN
				 dbo.CO_KARDEX_TOTAL ON dbo.CO_UBICACIONARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
				 dbo.CO_UBICACIONARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC AND 
				 dbo.CO_UBICACIONARTICULO.CO_BOD_COD = dbo.CO_KARDEX_TOTAL.CO_BOD_COD
	WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_LISTA_PRECIO.Nombre=@CO_TAB_PRE_NOM AND dbo.CO_ARTICULO.CO_FAM_ART_COD=@CO_FAM_ART_COD)          
	SELECT * FROM S WHERE RowNumber=1
END




GO
