SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TABLA_PRECIO]
@ListaDePrecioID int
,@CO_EMP_RUC char(13)
,@CO_ART_COD nvarchar(20)
,@CO_TAB_PRE FLOAT
,@CO_TAB_PRE_POR_ART FLOAT
,@CO_TAB_PRE_MIN float
AS
INSERT INTO [dbo].[CO_TABLA_PRECIO]
(ListaDePrecioID
,CO_EMP_RUC
,CO_ART_COD
,CO_TAB_PRE
,CO_TAB_PRE_POR_ART
,CO_TAB_PRE_MIN)
VALUES
(@ListaDePrecioID
,@CO_EMP_RUC
,@CO_ART_COD
,@CO_TAB_PRE
,@CO_TAB_PRE_POR_ART
,@CO_TAB_PRE_MIN)
GO
