SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_FORMULARIO_102A_EGRESOS]
@CO_EMP_RUC CHAR(13)
,@CO_RET_ANIO INT
AS
SELECT SUM(CO_DOC_COM_TOT_NET) AS GASTOS FROM CO_DOCUMENTO_COMPRA
WHERE CO_EMP_RUC=@CO_EMP_RUC AND YEAR(CO_DOC_COM_FEC_REG)=@CO_RET_ANIO AND CO_DOC_COM_EST='ACTIVA'
GO
