SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_SALDO_ANTERIOR_PROVEEDOR]
@CO_EMP_RUC CHAR(13)
,@CO_DOC_COM_FEC_REG DATETIME
AS
SELECT SUM(CO_FACTURAS) AS SALDO_ANTERIOR, CO_PRO_COD, CO_EMP_RUC,
(SELECT SUM(CO_PAGOS) 
FROM CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR_PAGOS
WHERE CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR_PAGOS.CO_EMP_RUC=CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR.CO_EMP_RUC AND 
CO_FEC_DOC<@CO_DOC_COM_FEC_REG AND
CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR_PAGOS.CO_PRO_COD=CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR.CO_PRO_COD
GROUP BY CO_PRO_COD, CO_EMP_RUC) AS VALOR_PAGADO
FROM CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR
WHERE CO_FEC_DOC<@CO_DOC_COM_FEC_REG
AND CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR.CO_EMP_RUC=@CO_EMP_RUC
GROUP BY CO_PRO_COD, CO_EMP_RUC
GO
