SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_UBICACIONARTICULO_CONTADOR]
@CO_EMP_RUC CHAR(13),
@CO_BOD_COD INT
AS
SELECT COUNT(*) FROM CO_UBICACIONARTICULO
WHERE CO_BOD_COD=@CO_BOD_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
