SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CUENTA_VALIDA]
@CO_CUE_TIP varchar(20),
@CO_EMP_RUC char(13)

AS
SELECT COUNT(*) AS CONTADOR FROM CO_CUENTA
WHERE CO_CUE_TIP=@CO_CUE_TIP AND CO_EMP_RUC=@CO_EMP_RUC
GO
