SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_MES_SALDO]
@CO_CUE_COD VARCHAR(40),
@CO_EMP_RUC CHAR(13),
@CO_MES_NUM INT,
@CO_ANIO_NUM INT
AS
SELECT COUNT(*) FROM CO_MES_SALDO
WHERE CO_CUE_COD=@CO_CUE_COD 
AND CO_EMP_RUC=@CO_EMP_RUC
AND CO_MES_NUM=@CO_MES_NUM
AND CO_ANIO_NUM=@CO_ANIO_NUM
GO
