SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_VENTA_EMPLEADO]
@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_SER_COD nvarchar(10)
AS
DELETE [dbo].[CO_VENTA_EMPLEADO] 
WHERE
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_NOT_DEB_NUM]=@CO_NOT_DEB_NUM
AND [CO_SER_COD]=@CO_SER_COD)
GO
