SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_PAGO_PROFORMA]
@CO_EMP_RUC char(13)
,@CO_PRO_COD int
AS
SELECT * FROM [dbo].[CO_PAGO_PROFORMA]
WHERE
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_PRO_COD]=@CO_PRO_COD)
GO
