SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_UPDATE_INGRESO_BODEGA_ESTADO]
	@IngresoID UNIQUEIDENTIFIER,
	@Estado NVARCHAR(50)
AS
UPDATE dbo.CO_INGRESO SET
          Estado=@Estado
WHERE IngresoID=@IngresoID
GO
