SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_RUBROS_ROL]
@CO_RUB_ROL_FEC1 DATETIME,
@CO_RUB_ROL_FEC2 DATETIME,
@CO_EMP_RUC CHAR(13),
@CO_RUB_ROL_COD INT,
@PROF_COD char(10),
@CO_UBI_COD INT,
@CO_OPCION CHAR(1)
AS
IF(@CO_OPCION='T')
BEGIN
SELECT dbo.CO_EMPRESA.CO_EMP_NOM,dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.PROFESOR.PROF_COD, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS EMPLEADO, SUM(dbo.CO_TRANSACCION.CO_TRA_VAL) AS TRANS_VALOR, 
dbo.CO_RUBROS_ROL.CO_RUB_ROL_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD,@CO_RUB_ROL_FEC1 AS DESDE,@CO_RUB_ROL_FEC2 AS HASTA
FROM dbo.CO_RUBROS_ROL INNER JOIN
dbo.CO_TRANSACCION ON dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD = dbo.CO_TRANSACCION.CO_RUB_ROL_COD AND 
dbo.CO_RUBROS_ROL.CO_EMP_RUC = dbo.CO_TRANSACCION.CO_EMP_RUC INNER JOIN
dbo.PROFESOR ON dbo.CO_TRANSACCION.PROF_COD = dbo.PROFESOR.PROF_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_RUBROS_ROL.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE (dbo.CO_TRANSACCION.CO_TRA_MES>=MONTH(@CO_RUB_ROL_FEC1) AND dbo.CO_TRANSACCION.CO_TRA_ANO>=YEAR(@CO_RUB_ROL_FEC1)) AND
(dbo.CO_TRANSACCION.CO_TRA_MES<=MONTH(@CO_RUB_ROL_FEC2) AND dbo.CO_TRANSACCION.CO_TRA_ANO<=YEAR(@CO_RUB_ROL_FEC2)) AND
dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD=@CO_RUB_ROL_COD
GROUP BY dbo.CO_EMPRESA.CO_EMP_NOM,dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.PROFESOR.PROF_COD, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD
END
ELSE IF(@CO_OPCION='E')
BEGIN
SELECT dbo.CO_EMPRESA.CO_EMP_NOM,dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.PROFESOR.PROF_COD, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS EMPLEADO, SUM(dbo.CO_TRANSACCION.CO_TRA_VAL) AS TRANS_VALOR, 
dbo.CO_RUBROS_ROL.CO_RUB_ROL_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD,@CO_RUB_ROL_FEC1 AS DESDE,@CO_RUB_ROL_FEC2 AS HASTA
FROM dbo.CO_RUBROS_ROL INNER JOIN
dbo.CO_TRANSACCION ON dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD = dbo.CO_TRANSACCION.CO_RUB_ROL_COD AND 
dbo.CO_RUBROS_ROL.CO_EMP_RUC = dbo.CO_TRANSACCION.CO_EMP_RUC INNER JOIN
dbo.PROFESOR ON dbo.CO_TRANSACCION.PROF_COD = dbo.PROFESOR.PROF_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_RUBROS_ROL.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE (dbo.CO_TRANSACCION.CO_TRA_MES>=MONTH(@CO_RUB_ROL_FEC1) AND dbo.CO_TRANSACCION.CO_TRA_ANO>=YEAR(@CO_RUB_ROL_FEC1)) AND
(dbo.CO_TRANSACCION.CO_TRA_MES<=MONTH(@CO_RUB_ROL_FEC2) AND dbo.CO_TRANSACCION.CO_TRA_ANO<=YEAR(@CO_RUB_ROL_FEC2)) AND
dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD=@CO_RUB_ROL_COD AND dbo.PROFESOR.PROF_COD=@PROF_COD
GROUP BY dbo.CO_EMPRESA.CO_EMP_NOM,dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.PROFESOR.PROF_COD, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD
END
ELSE IF(@CO_OPCION='U')
BEGIN
SELECT dbo.CO_EMPRESA.CO_EMP_NOM,dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.PROFESOR.PROF_COD, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS EMPLEADO, SUM(dbo.CO_TRANSACCION.CO_TRA_VAL) AS TRANS_VALOR, 
dbo.CO_RUBROS_ROL.CO_RUB_ROL_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD,@CO_RUB_ROL_FEC1 AS DESDE,@CO_RUB_ROL_FEC2 AS HASTA
FROM dbo.CO_RUBROS_ROL INNER JOIN
dbo.CO_TRANSACCION ON dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD = dbo.CO_TRANSACCION.CO_RUB_ROL_COD AND 
dbo.CO_RUBROS_ROL.CO_EMP_RUC = dbo.CO_TRANSACCION.CO_EMP_RUC INNER JOIN
dbo.PROFESOR ON dbo.CO_TRANSACCION.PROF_COD = dbo.PROFESOR.PROF_COD INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_RUBROS_ROL.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE (dbo.CO_TRANSACCION.CO_TRA_MES>=MONTH(@CO_RUB_ROL_FEC1) AND dbo.CO_TRANSACCION.CO_TRA_ANO>=YEAR(@CO_RUB_ROL_FEC1)) AND
(dbo.CO_TRANSACCION.CO_TRA_MES<=MONTH(@CO_RUB_ROL_FEC2) AND dbo.CO_TRANSACCION.CO_TRA_ANO<=YEAR(@CO_RUB_ROL_FEC2)) AND
dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD=@CO_RUB_ROL_COD AND dbo.PROFESOR.CO_UBI_COD=@CO_UBI_COD
GROUP BY dbo.CO_EMPRESA.CO_EMP_NOM,dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.PROFESOR.PROF_COD, 
dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_NOM, dbo.CO_RUBROS_ROL.CO_RUB_ROL_COD
END
GO
