SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_PROVEEDOR]
@CO_EMP_RUC CHAR(13),
@CO_PRO_NOM NVARCHAR(100),
@CO_TIP_PRO_COD NVARCHAR(10),
@CO_PRO_COD NVARCHAR(13),
@CO_PRO_OPC CHAR(1)
AS
IF @CO_PRO_OPC='N'
BEGIN
DECLARE @LIKE AS VARCHAR(50)
SET @LIKE='%'+@CO_PRO_NOM+'%'
SELECT dbo.CO_PROVEEDOR.* 
FROM CO_PROVEEDOR
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PRO_NOM LIKE @LIKE 
END
ELSE IF @CO_PRO_OPC='T'
SELECT dbo.CO_PROVEEDOR.* 
FROM CO_PROVEEDOR
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_TIP_PRO_COD=@CO_TIP_PRO_COD
ELSE IF @CO_PRO_OPC='C'
SELECT dbo.CO_PROVEEDOR.* 
FROM CO_PROVEEDOR
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PRO_COD=@CO_PRO_COD
ELSE IF @CO_PRO_OPC='E'
SELECT dbo.CO_PROVEEDOR.* 
FROM CO_PROVEEDOR
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_PRO_CED=@CO_PRO_COD
GO
