SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CLIENTE_IDENTIFICACION_CONTADOR]
@CO_EMP_RUC char(13)
,@CO_CLI_CED NVARCHAR(13)
AS
SELECT COUNT(*) FROM [dbo].[CO_CLIENTE] 
WHERE [CO_EMP_RUC]=@CO_EMP_RUC AND CO_CLI_CED=@CO_CLI_CED


GO
