SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[CO_SP_SELECT_DETALLE_CONCEPTO_AIR_COMPRA]
@CO_DOC_COM_ID uniqueidentifier,
@CO_RET_DET_IMP varchar(20)
AS
SELECT DR.CO_TIP_RET_COD_SRI AS codRetAir,DR.CO_RET_POR AS porcentajeAir, [CO_RET_VAL] as valRetAir,
CO_RET_BAS AS baseImpAir
FROM CO_RETENCION R INNER JOIN [dbo].[CO_DETALLE_RETENCION] DR ON R.CO_RET_COD=DR.CO_RET_COD
WHERE co_ret_det_imp=@CO_RET_DET_IMP
and R.CO_DOC_COM_ID=@CO_DOC_COM_ID
GO
