SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CO_SP_SELECT_GRUPO]
@CO_EMP_RUC CHAR(13)
AS
SELECT dbo.CO_GRUPO.CO_GRU_COD, dbo.CO_GRUPO.CO_GRU_NOM, CO_EMP_ESCONTADOR
FROM dbo.CO_GRUPO INNER JOIN
dbo.CO_EMPRESA ON dbo.CO_GRUPO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_EMPRESA.CO_EMP_RUC=@CO_EMP_RUC AND dbo.CO_GRUPO.CO_GRU_NOM!='Tempfzf'
GO
