SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_ACTIVO]
@CO_TIP_ACT_COD int
,@CO_EMP_RUC char(13)
AS
DELETE [dbo].[CO_TIPO_ACTIVO] 
     WHERE 
           CO_TIP_ACT_COD=@CO_TIP_ACT_COD
           AND CO_EMP_RUC=@CO_EMP_RUC
GO
