SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CN_SP_SELECT_PERMISO]
@PERM_NOM VARCHAR(80),
@CONT_COD INT,
@USUA_COD INT
AS
SELECT COUNT(*) FROM CN_VW_SELECT_PERMISO
WHERE PERM_NOM=@PERM_NOM 
AND CONT_COD=@CONT_COD
AND USUA_COD=@USUA_COD
GO
