SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_GENERAL]
@CEDULA CHAR(10)
,@CO_EMP_RUC CHAR(13)
,@NOMBRE VARCHAR(100)
,@TELEFONO VARCHAR(10)
AS
DECLARE @LIKE NVARCHAR(102)
SET @LIKE='%'+@NOMBRE+'%'
SELECT CO_CLI_CED AS CEDULA,CO_CLI_NOM AS NOMBRE,CO_CLI_DIR AS DIRECCION,CO_CLI_TEL AS TELEFONO 
FROM CO_CLIENTE
WHERE CO_EMP_RUC=@CO_EMP_RUC
--AND CO_CLI_NOM LIKE case @LIKE when '' then CO_CLI_NOM else @LIKE end
AND CO_CLI_CED=case @CEDULA when '' then CO_CLI_CED else @CEDULA end
--AND CO_CLI_TEL=case @TELEFONO when '' then CO_CLI_TEL else @TELEFONO end
UNION
SELECT CO_PRO_CED AS CEDULA,CO_PRO_NOM AS NOMBRE,CO_PRO_DIR AS DIRECCION,CO_PRO_TEL1 AS TELEFONO 
FROM CO_PROVEEDOR
WHERE CO_EMP_RUC=@CO_EMP_RUC
--AND CO_PRO_NOM LIKE case @LIKE when '' then CO_PRO_CED else @LIKE end
AND CO_PRO_CED=case @CEDULA when '' then CO_PRO_CED else @CEDULA end
--AND CO_PRO_TEL1=case @TELEFONO when '' then CO_PRO_TEL1 else @TELEFONO end
UNION
SELECT PROF_COD AS CEDULA,PROF_NOM+' '+PROF_APE AS NOMBRE,PROF_DIR AS DIRECCION,PROF_TEL AS TELEFONO 
FROM PROFESOR
WHERE CO_EMP_RUC=@CO_EMP_RUC 
--AND PROF_NOM+' '+PROF_APE LIKE case @LIKE when '' then PROF_NOM+' '+PROF_APE else @LIKE end 
AND PROF_COD=case @CEDULA when '' then PROF_COD else @CEDULA end
--AND PROF_TEL=case @TELEFONO when '' then PROF_TEL else @TELEFONO end
GO
