SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_ACTIVOS_REASIGNACION]
@CO_ACT_FIJ_COD INT
AS
SELECT * FROM CO_ACTIVO_REASIGNACION
WHERE CO_ACT_FIJ_COD=@CO_ACT_FIJ_COD
GO
