SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_VERIFICA_KARDEX]
@CO_KAR_TOT_DOC NVARCHAR(20),
@CO_KAR_TOT_TIP_DOC INT,
@CO_ART_COD NVARCHAR(20)
AS
SELECT * FROM dbo.CO_KARDEX_TOTAL
where CO_KAR_TOT_DOC=@CO_KAR_TOT_DOC AND CO_KAR_TOT_TIP_DOC=@CO_KAR_TOT_TIP_DOC AND CO_ART_COD=@CO_ART_COD
ORDER BY CO_KAR_TOT_FEC DESC
GO
