SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CIERRE_CAJA_GASTOS]
@CO_EMP_RUC CHAR(13),
@CO_DOC_VEN_FEC DATETIME
AS
SELECT DV.CO_DOC_COM_NUM, C.CO_PRO_NOM, DV.CO_DOC_COM_EFE_VAL, DV.CO_DOC_COM_TAR_VAL, 
(SELECT ISNULL(SUM(DR.CO_RET_VAL),0) FROM dbo.CO_RETENCION R INNER JOIN CO_DETALLE_RETENCION DR ON R.CO_RET_COD=DR.CO_RET_COD
						WHERE R.CO_DOC_COM_ID=DV.CO_DOC_COM_ID) AS CO_DOC_VEN_RET_VAL,
DV.CO_DOC_COM_TOT_PAG-
(DV.CO_DOC_COM_EFE_VAL+
DV.CO_DOC_COM_CHE_VAL+
DV.CO_DOC_COM_TAR_VAL+(SELECT ISNULL(SUM(DR.CO_RET_VAL),0) FROM dbo.CO_RETENCION R INNER JOIN CO_DETALLE_RETENCION DR ON R.CO_RET_COD=DR.CO_RET_COD
						WHERE R.CO_DOC_COM_ID=DV.CO_DOC_COM_ID)) AS CO_DOC_VEN_CRE
FROM dbo.CO_DOCUMENTO_COMPRA DV INNER JOIN dbo.CO_PROVEEDOR C ON DV.CO_PRO_COD = C.CO_PRO_COD AND 
DV.CO_EMP_RUC = C.CO_EMP_RUC
WHERE MONTH(CO_DOC_COM_FEC_EMI)=MONTH(@CO_DOC_VEN_FEC) AND DAY(CO_DOC_COM_FEC_EMI)=DAY(@CO_DOC_VEN_FEC) AND YEAR(CO_DOC_COM_FEC_EMI)=YEAR(@CO_DOC_VEN_FEC)
AND DV.CO_EMP_RUC=@CO_EMP_RUC AND CO_DOC_COM_EST='ACTIVA' AND CO_DOC_COM_CHE_VAL=0
order by 1
GO
