SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_UBICACION_GEOGRAFICA]
@CO_UBI_GEO_COD nvarchar(10)
,@CO_EMP_RUC char(13)
AS
DELETE [dbo].[CO_UBICACION_GEOGRAFICA]
WHERE 
([CO_UBI_GEO_COD]=@CO_UBI_GEO_COD
 AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
