SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_ROL_TEMP]
@CO_EMP_RUC CHAR(13),
@CO_MES INT,
@CO_ANIO INT,
@CO_UBI_COD INT
AS
SELECT * FROM CO_VW_SELECT_REPORTE_ROL_TEMP
WHERE CO_MES=@CO_MES AND CO_ANIO=@CO_ANIO AND CO_UBI_COD=@CO_UBI_COD 
AND CO_EMP_RUC=@CO_EMP_RUC
GO
