SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_UBICACION_AF]
@CO_EMP_RUC char(13)
,@CO_UBI_NOM varchar(30)
,@CO_UBI_USU_ALI varchar(15)
,@CO_UBI_DIR nvarchar(100)
,@CO_UBI_TEL nchar(10)
,@CO_UBI_REP nvarchar(100)
,@CO_UBI_REP_CED nchar(10)
AS
INSERT INTO [dbo].[CO_UBICACION_AF]
([CO_EMP_RUC]
,[CO_UBI_NOM]
,[CO_UBI_USU_ALI]
,[CO_UBI_DIR]
,[CO_UBI_TEL]
,[CO_UBI_REP]
,[CO_UBI_REP_CED])
VALUES
(@CO_EMP_RUC
,@CO_UBI_NOM
,@CO_UBI_USU_ALI
,@CO_UBI_DIR
,@CO_UBI_TEL
,@CO_UBI_REP
,@CO_UBI_REP_CED)
GO
