SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CUENTA_CODIGO_ANTERIOR]
@CO_CUE_COD VARCHAR(40),
@CO_EMP_RUC CHAR(13)
AS
SELECT CO_CUE_COD_ANT
FROM CO_CUENTA 
WHERE CO_CUE_COD=@CO_CUE_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
