SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_GUIA_REMISION]
@CO_DOC_VEN_GUI_COD uniqueidentifier
AS
SELECT        dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_CLIENTE.CO_CLI_COD, dbo.CO_CLIENTE.CO_CLI_CIU, dbo.CO_CLIENTE.CO_CLI_DIR, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_NUM, 
                         dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_TIP, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_FEC_INI, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_FEC_TER, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_DES, 
                         dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_NOM_TRA, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_IDE, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_PLACA, dbo.CO_GUIA_REMISION.CO_ESTADO, 
                         dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_FEC_REG, dbo.CO_GUIA_REMISION.CO_EMP_RUC, dbo.CO_GUIA_REMISION.CO_DOC_VEN_ID, dbo.CO_GUIA_REMISION.CO_DOC_VEN_GUI_COD, 
                         dbo.CO_CLIENTE.CO_CLI_NOM
FROM            dbo.CO_GUIA_REMISION INNER JOIN
                         dbo.CO_DOCUMENTO_VENTA ON dbo.CO_GUIA_REMISION.CO_DOC_VEN_ID = dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_ID INNER JOIN
                         dbo.CO_CLIENTE ON dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD = dbo.CO_CLIENTE.CO_CLI_COD AND dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC = dbo.CO_CLIENTE.CO_EMP_RUC
where CO_DOC_VEN_GUI_COD=@CO_DOC_VEN_GUI_COD
GO
