SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_TIPO_RUBRO]
@CO_EMP_RUC char(13)
,@CO_TIP_RUB_NOM nvarchar(50)
,@CO_TIP_RUB_COD_CUE varchar(40)
AS
INSERT INTO [dbo].[CO_TIPO_RUBRO]
([CO_EMP_RUC]
,[CO_TIP_RUB_NOM]
,[CO_TIP_RUB_COD_CUE])
VALUES
(@CO_EMP_RUC
,@CO_TIP_RUB_NOM
,@CO_TIP_RUB_COD_CUE)
GO
