SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_MES_SALDO_TEMP]
@CO_CUE_COD VARCHAR(40),
@CO_EMP_RUC CHAR(13)
AS
SELECT COUNT(*) FROM CO_MES_SALDO_TEMP
WHERE CO_CUE_COD=@CO_CUE_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
