SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_EGRESO_BODEGA_NUMERO]
@CO_EMP_RUC CHAR(13)
AS
SELECT ISNULL(MAX(Numero),0)+1 AS Numero FROM dbo.CO_EGRESO
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
