SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_RUBROS_EMPLEADO]
@PROF_COD char(10)
,@CO_EMP_RUC char(13)
AS
DELETE [dbo].[CO_RUBRO_EMPLEADO]
WHERE PROF_COD=@PROF_COD
AND CO_EMP_RUC=@CO_EMP_RUC
GO
