SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_NUMERO_DOCUMENTO_COMPRA]
@CO_EMP_RUC char(13)
AS
SELECT MAX(CO_DOC_COM_NUM) AS CONTADOR FROM CO_DOCUMENTO_COMPRA
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
