SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PROYECTO]
@CO_PRO_COD int
,@CO_EMP_RUC char(13)
AS
DELETE [dbo].[CO_PROYECTO]
WHERE
([CO_PRO_COD]=@CO_PRO_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC)
GO
