SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_BUSQUEDA_PAGO_CUOTA_FECHA]
@CO_PAG_FEC_INI DATETIME
,@CO_PAG_FEC_FIN DATETIME
,@CO_EMP_RUC CHAR(13)
AS
SELECT * FROM CO_VW_SELECT_BUSCAR_PAGO_CUOTAS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
Convert(varchar(10),CO_COM_COB_FEC,103)>=Convert(varchar(10),@CO_PAG_FEC_INI,103)
AND Convert(varchar(10),CO_COM_COB_FEC,103)<=Convert(varchar(10),@CO_PAG_FEC_FIN,103)
GO
