SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_CORRECCION_HORARIO]
(@CO_COR_HOR_MES int
,@CO_COR_HOR_ANO int
,@PROF_COD char(10)
,@CO_EMP_RUC char(13)
,@CO_COR_HOR_LAB float
,@CO_COR_HOR_EXT float
,@CO_COR_HOR_SUP float)
AS
INSERT INTO [dbo].[CO_CORRECION_HORARIO]
([CO_COR_HOR_MES]
,[CO_COR_HOR_ANO]
,[PROF_COD]
,[CO_EMP_RUC]
,[CO_COR_HOR_LAB]
,[CO_COR_HOR_EXT]
,[CO_COR_HOR_SUP])
VALUES
(@CO_COR_HOR_MES
,@CO_COR_HOR_ANO
,@PROF_COD
,@CO_EMP_RUC
,@CO_COR_HOR_LAB
,@CO_COR_HOR_EXT
,@CO_COR_HOR_SUP)
GO
