SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_BALANCE_GENERAL]
@CO_EMP_RUC CHAR(13),
@CO_MES_NUM INT,
@CO_ANIO_NUM INT,
@ACTIVO VARCHAR(10),
@PASIVO VARCHAR(10),
@PATRIMONIO VARCHAR(10)
AS
declare @mes int
select top 1 @mes=count(*) from co_mes where CO_MES_NUM=@CO_MES_NUM and CO_ANIO_NUM=@CO_ANIO_NUM and CO_EMP_RUC=@CO_EMP_RUC
if(@mes=1)
begin
	SELECT CO_CUE_COD,CO_CUE_NOM,CO_MES_SAL_ACT,CO_EMP_NOM,CO_CUE_NIV,CO_CUE_TIP,CO_EMP_NOM_REP,CO_EMP_NOM_CON,CO_EMP_REG_CON
	,@ACTIVO AS ACTIVOS,@PASIVO AS PASIVOS,@PATRIMONIO AS PATRIMONIO, @CO_MES_NUM as MES, @CO_ANIO_NUM AS ANIO
	FROM CO_VW_SELECT_CUENTAS_SALDOS
	WHERE CO_EMP_RUC=@CO_EMP_RUC and CO_MES_NUM=@CO_MES_NUM and CO_ANIO_NUM=@CO_ANIO_NUM and CO_MES_SAL_ACT<>0
	and (CO_CUE_COD like @ACTIVO+'%' or CO_CUE_COD like @PASIVO+'%' or CO_CUE_COD like @PATRIMONIO+'%')
end
else
begin
	SELECT CO_CUE_COD,CO_CUE_NOM,CO_MES_SAL_ACT,CO_EMP_NOM,CO_CUE_NIV,CO_CUE_TIP,CO_EMP_NOM_REP,CO_EMP_NOM_CON,CO_EMP_REG_CON
	,@ACTIVO AS ACTIVOS,@PASIVO AS PASIVOS,@PATRIMONIO AS PATRIMONIO, @CO_MES_NUM as MES, @CO_ANIO_NUM AS ANIO
	FROM CO_VW_SELECT_CUENTAS_SALDOS_TEMP
	WHERE CO_EMP_RUC=@CO_EMP_RUC --and CO_MES_NUM=@CO_MES_NUM and CO_ANIO_NUM=@CO_ANIO_NUM and CO_MES_SAL_ACT<>0
	and (CO_CUE_COD like @ACTIVO+'%' or CO_CUE_COD like @PASIVO+'%' or CO_CUE_COD like @PATRIMONIO+'%')
end
GO
