SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_REPORTE_TRANSACCIONES_EMPLEADOS]
@CO_EMP_RUC CHAR (13)
,@CO_ROL_CAB_MES INT
,@CO_ROL_CAB_ANO INT
,@CO_UBI_COD INT
,@CO_ROL_CAB_CUE_NUM NVARCHAR(20)
AS
SELECT * 
FROM CO_VW_SELECT_TRANSACCIONES_EMPLEADOS
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_ROL_CAB_MES=@CO_ROL_CAB_MES AND CO_ROL_CAB_ANO=@CO_ROL_CAB_ANO
AND CO_UBI_COD=case @CO_UBI_COD when 0 then CO_UBI_COD else @CO_UBI_COD end
AND CO_ROL_CAB_CUE_NUM=case @CO_ROL_CAB_CUE_NUM when '' then CO_ROL_CAB_CUE_NUM else @CO_ROL_CAB_CUE_NUM end
GO
