SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_TIPO_SUSTENTO]
@CO_TIP_SUS_COD nvarchar(5)
AS
DELETE [dbo].[CO_TIPO_SUSTENTO]
WHERE
[CO_TIP_SUS_COD]=@CO_TIP_SUS_COD
GO
