SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_PAGO_CUOTA]
@CO_FOR_PAG_COD int
,@CO_EMP_RUC char(13)
,@CO_NOT_DEB_NUM int
,@CO_PAG_COD int
AS
DELETE [dbo].[CO_PAGO_CUOTA]
WHERE 
([CO_EMP_RUC]=@CO_EMP_RUC
AND [CO_NOT_DEB_NUM]=@CO_NOT_DEB_NUM 
AND [CO_PAG_COD]=@CO_PAG_COD)
GO
