SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_PAGO_DOCUMENTO_VENTA]
@CO_PAG_DOC_VEN_COD UNIQUEIDENTIFIER
,@CO_DOC_VEN_ID UNIQUEIDENTIFIER
,@CO_PAG_DOC_VEN_VAL float
,@CO_PAG_DOC_VEN_FEC datetime
,@CO_PAG_DOC_VEN_EST bit
,@CO_PAG_DOC_VEN_CON nvarchar(50)
,@CO_PAG_DOC_VEN_VAL_IMP float
AS
INSERT INTO [dbo].[CO_PAGO_DOCUMENTO_VENTA]
([CO_PAG_DOC_VEN_COD]
,[CO_DOC_VEN_ID]
,[CO_PAG_DOC_VEN_VAL]
,[CO_PAG_DOC_VEN_FEC]
,[CO_PAG_DOC_VEN_EST]
,[CO_PAG_DOC_VEN_CON]
,[CO_PAG_DOC_VEN_VAL_IMP])
VALUES
(@CO_PAG_DOC_VEN_COD
,@CO_DOC_VEN_ID
,@CO_PAG_DOC_VEN_VAL
,@CO_PAG_DOC_VEN_FEC
,@CO_PAG_DOC_VEN_EST
,@CO_PAG_DOC_VEN_CON
,@CO_PAG_DOC_VEN_VAL_IMP)
GO
