SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_INSERT_REGISTRO_DIARIO]
(@PROF_COD char(10)
,@CO_EMP_RUC char(13)
,@CO_REG_DIA_FEC datetime
,@CO_REG_DIA_HOR_ING nchar(5)
,@CO_REG_DIA_HOR_SAL nchar(5)
,@CO_REG_DIA_HOR_LAB float
,@CO_REG_DIA_HOR_EXT float
,@CO_REG_DIA_HOR_SUP float
,@CO_REG_DIA_HOR_ATR float)
AS
INSERT INTO [dbo].[CO_REGISTRO_DIARIO]
([PROF_COD]
,[CO_EMP_RUC]
,[CO_REG_DIA_FEC]
,[CO_REG_DIA_HOR_ING]
,[CO_REG_DIA_HOR_SAL]
,[CO_REG_DIA_HOR_LAB]
,[CO_REG_DIA_HOR_EXT]
,[CO_REG_DIA_HOR_SUP]
,[CO_REG_DIA_HOR_ATR]
,[CO_REG_DIA_HOR_CIE])
VALUES
(@PROF_COD
,@CO_EMP_RUC
,@CO_REG_DIA_FEC
,@CO_REG_DIA_HOR_ING
,@CO_REG_DIA_HOR_SAL
,@CO_REG_DIA_HOR_LAB
,@CO_REG_DIA_HOR_EXT
,@CO_REG_DIA_HOR_SUP
,@CO_REG_DIA_HOR_ATR
,0)
GO
