SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_SELECT_CIERRE_CAJA_CHEQUE]
@CO_EMP_RUC CHAR(13),
@CO_DOC_VEN_FEC DATETIME
AS
SELECT DV.CO_DOC_VEN_NUM, C.CO_CLI_NOM, DV.CO_DOC_VEN_CHE_VAL, CO_DOC_VEN_CHE_NUM, [CO_DOC_VEN_CHE_BAN], [CO_DOC_VEN_CHE_FEC]
FROM dbo.CO_DOCUMENTO_VENTA DV INNER JOIN dbo.CO_CLIENTE C ON DV.CO_CLI_COD = C.CO_CLI_COD AND 
DV.CO_EMP_RUC = C.CO_EMP_RUC AND DV.CO_TIP_CLI_COD = C.CO_TIP_CLI_COD
WHERE 
MONTH(CO_DOC_VEN_FEC)=MONTH(@CO_DOC_VEN_FEC) AND DAY(CO_DOC_VEN_FEC)=DAY(@CO_DOC_VEN_FEC) 
AND YEAR(CO_DOC_VEN_FEC)=YEAR(@CO_DOC_VEN_FEC)
AND DV.CO_EMP_RUC=@CO_EMP_RUC AND 
CO_DOC_VEN_EST='ACTIVA' AND CO_DOC_VEN_CHE_VAL>0
GO
