SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[CO_SP_DELETE_CENTRO_COSTOS]
@CO_CEN_COS_COD VARCHAR(10),
@CO_EMP_RUC CHAR(13)
AS
DELETE CO_CENTRO_COSTO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND CO_CEN_COS_COD=@CO_CEN_COS_COD
GO
