SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_UPDATE_DESPACHO_ESTADO]
@Estado VARCHAR(20),
@DespachoID INT
AS
update [PRODUCCION].[DESPACHO] set ESTADO=@Estado
where [PR_DES_COD]=@DespachoID
GO
