SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_INSERT_DETALLE_PROCESO]
@PR_PRO_NUM int
,@CO_EMP_RUC char(13)
,@PR_PRO_COD nvarchar(10)
,@PR_DET_PRO_NOM nvarchar(100)
,@PR_DET_PRO_CAN float
,@PR_DET_PRO_PRE float
,@PR_DET_PRO_CAN_DES float
as
INSERT INTO [PRODUCCION].[DETALLE_PROCESO]
([PR_PRO_NUM]
,[CO_EMP_RUC]
,[PR_PRO_COD]
,[PR_DET_PRO_NOM]
,[PR_DET_PRO_CAN]
,[PR_DET_PRO_PRE]
,[PR_DET_PRO_CAN_DES])
VALUES
(@PR_PRO_NUM
,@CO_EMP_RUC
,@PR_PRO_COD
,@PR_DET_PRO_NOM
,@PR_DET_PRO_CAN
,@PR_DET_PRO_PRE
,@PR_DET_PRO_CAN_DES)

GO
