SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SP_SELECT_KARDEX]
@CO_EMP_RUC CHAR(13),
@CO_KAR_TOT_FEC Datetime,
@PR_PRO_COD nvarchar(10)
AS
SELECT * FROM PRODUCCION.KARDEX
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PR_PRO_COD=@PR_PRO_COD AND
CO_KAR_TOT_FEC<@CO_KAR_TOT_FEC
order by CO_KAR_TOT_FEC desc

GO
