SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_SELECT_REPORTE_PRODUCTO]
@CO_EMP_RUC CHAR(13),
@PR_TIP_REC_COD int
AS
SELECT PRODUCCION.PRODUCTO.PR_PRO_COD, PRODUCCION.PRODUCTO.CO_EMP_RUC, PRODUCCION.PRODUCTO.PR_TIP_REC_COD, 
PRODUCCION.PRODUCTO.PR_PRO_NOM, PRODUCCION.PRODUCTO.PR_PRO_UNI, 
                      0 as PR_PRO_PRE, 
                      0 as PR_PRO_CAN, PRODUCCION.PRODUCTO.PR_PRO_PES, 
                      PRODUCCION.TIPO_RECETA.PR_TIP_REC_NOM
FROM         PRODUCCION.PRODUCTO INNER JOIN
                      PRODUCCION.TIPO_RECETA ON PRODUCCION.PRODUCTO.PR_TIP_REC_COD = PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD
WHERE PRODUCCION.PRODUCTO.CO_EMP_RUC=@CO_EMP_RUC AND
PRODUCCION.PRODUCTO.PR_TIP_REC_COD=CASE @PR_TIP_REC_COD WHEN 0 THEN PRODUCCION.PRODUCTO.PR_TIP_REC_COD ELSE @PR_TIP_REC_COD END



GO
