SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_SELECT_REPORTE_PRODUCCION]
@CO_EMP_RUC CHAR(13)
,@PR_PRO_FEC1 DATETIME
,@PR_PRO_FEC2 DATETIME
,@PR_TIP_REC_COD INT
,@PR_TIP_PRO_COD INT
AS
SELECT * FROM [PRODUCCION].[PR_VW_SELECT_REPORTE_PRODUCCION]
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PR_PRO_FEC>=@PR_PRO_FEC1 AND PR_PRO_FEC<=@PR_PRO_FEC2 AND
PR_TIP_REC_COD=case @PR_TIP_REC_COD when 0 then PR_TIP_REC_COD else @PR_TIP_REC_COD end AND
PR_TIP_PRO_COD=case @PR_TIP_PRO_COD when 0 then PR_TIP_PRO_COD else @PR_TIP_PRO_COD end 

GO
