SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_SELECT_PRODUCTO]
@CO_EMP_RUC CHAR(13),
@PR_PRO_COD NVARCHAR(10)
AS
WITH S
as
(
SELECT RANK() OVER (PARTITION BY PRODUCCION.KARDEX.PR_PRO_COD ORDER BY PRODUCCION.KARDEX.CO_KAR_TOT_COD DESC) AS 'RowNumber',		
				PRODUCCION.PRODUCTO.PR_PRO_COD, PRODUCCION.KARDEX.CO_KAR_TOT_ENT_VAL_UNI,
						PRODUCCION.KARDEX.CO_KAR_TOT_FEC, PRODUCCION.KARDEX.CO_KAR_TOT_EXI_CANT, 
                      PRODUCCION.KARDEX.CO_KAR_TOT_EXI_VAL_UNI, PRODUCCION.KARDEX.CO_KAR_TOT_EXI_VAL_TOT, PRODUCCION.PRODUCTO.PR_PRO_NOM, 
                      PRODUCCION.PRODUCTO.CO_EMP_RUC, PRODUCCION.KARDEX.CO_KAR_TOT_COD, PR_TIP_REC_COD, PR_PRO_UNI, PR_PRO_PES
FROM         PRODUCCION.PRODUCTO LEFT OUTER JOIN
                      PRODUCCION.KARDEX ON PRODUCCION.PRODUCTO.PR_PRO_COD = PRODUCCION.KARDEX.PR_PRO_COD AND 
                      PRODUCCION.PRODUCTO.CO_EMP_RUC = PRODUCCION.KARDEX.CO_EMP_RUC
where PRODUCCION.PRODUCTO.PR_PRO_COD=@PR_PRO_COD AND PRODUCCION.PRODUCTO.CO_EMP_RUC=@CO_EMP_RUC)-- and CO_KAR_TOT_ENT_CANT>0) 


select PR_PRO_COD, PR_PRO_NOM, ISNULL(CO_KAR_TOT_EXI_VAL_UNI,0) as PR_PRO_PRE, ISNULL(CO_KAR_TOT_EXI_CANT,0) as PR_PRO_CAN, PR_TIP_REC_COD, PR_PRO_UNI, PR_PRO_PES
from (
		SELECT RANK() OVER (PARTITION BY PR_PRO_COD ORDER BY CO_KAR_TOT_COD desc) AS 'RowNumber2', PR_PRO_COD, CO_KAR_TOT_EXI_CANT, 
				CO_KAR_TOT_EXI_VAL_UNI, PR_PRO_NOM, PR_TIP_REC_COD, PR_PRO_UNI, PR_PRO_PES
		FROM S
		WHERE RowNumber=1
) as X
where RowNumber2=1
--AS
--SELECT *,
--		(select top 1 CO_KAR_TOT_EXI_CANT from PRODUCCION.KARDEX	
--		 where PRODUCCION.KARDEX.PR_PRO_COD=PRODUCCION.PRODUCTO.PR_PRO_COD
--		 order by CO_KAR_TOT_FEC desc) as PR_PRO_CAN
--FROM PRODUCCION.PRODUCTO
--WHERE CO_EMP_RUC=@CO_EMP_RUC AND
--PR_PRO_COD=@PR_PRO_COD




GO
