SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_UPDATE_ORDEN_TINTURADO_COLOR]
           @CO_EMP_RUC char(13)
           ,@CO_TINTURADO_ID int
           ,@ESTADO varchar(20)
		   ,@PROCESADO BIT
AS
UPDATE [PRODUCCION].[ORDEN_TINTURADO]
           set [ESTADO]=@ESTADO, FECHA_INICIO_PROCESO=GETDATE(), PROCESADO=@PROCESADO
     where CO_TINTURADO_ID=@CO_TINTURADO_ID and CO_EMP_RUC=@CO_EMP_RUC

GO
