SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_UPDATE_PARECIDO]
(@PR_PAR_COD INT
,@PR_PAR_ART_COD nvarchar(15))
AS
UPDATE [PRODUCCION].[PARECIDO] SET 
[PR_PAR_ART_COD]=@PR_PAR_ART_COD
WHERE PR_PAR_COD=@PR_PAR_COD


GO
