SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_INSERT_TIPO_RECETA]
(@PR_TIP_PRO_COD int
,@CO_EMP_RUC char(13)
,@PR_TIP_REC_NOM nvarchar(50))
AS
INSERT INTO [PRODUCCION].[TIPO_RECETA]
([PR_TIP_PRO_COD]
,[CO_EMP_RUC]
,[PR_TIP_REC_NOM])
VALUES
(@PR_TIP_PRO_COD
,@CO_EMP_RUC
,@PR_TIP_REC_NOM)


GO
