SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_INSERT_AGREGADO]
@PR_AGR_MES int
,@PR_TIP_PRO_COD int
,@PR_AGR_ANO int
,@PR_AGR_VAL_MOB float
,@PR_AGR_VAL_PRO float
,@PR_AGR_VAL_COS float
,@PR_AGR_VAL_SUM float
AS
INSERT INTO [PRODUCCION].[AGREGADO]
([PR_AGR_MES]
,[PR_TIP_PRO_COD]
,[PR_AGR_ANO]
,[PR_AGR_VAL_MOB]
,[PR_AGR_VAL_PRO]
,[PR_AGR_VAL_COS]
,[PR_AGR_VAL_SUM])
VALUES
(@PR_AGR_MES
,@PR_TIP_PRO_COD
,@PR_AGR_ANO
,@PR_AGR_VAL_MOB
,@PR_AGR_VAL_PRO
,@PR_AGR_VAL_COS
,@PR_AGR_VAL_SUM)


GO
