SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_BUSQUEDA_PRODUCTO]
@CO_EMP_RUC CHAR(13),
@PR_PRO_COD NVARCHAR(10),
@PR_PRO_NOM NVARCHAR(100)
AS
IF (@PR_PRO_NOM='')
SELECT PR_PRO_COD,PR_PRO_NOM,PR_PRO_PES 
FROM PRODUCCION.PRODUCTO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PR_PRO_COD=case @PR_PRO_COD when '' then PR_PRO_COD else @PR_PRO_COD end  
ELSE 
SELECT PR_PRO_COD,PR_PRO_NOM,PR_PRO_PES 
FROM PRODUCCION.PRODUCTO
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PR_PRO_COD=case @PR_PRO_COD when '' then PR_PRO_COD else @PR_PRO_COD end  AND 
PR_PRO_NOM LIKE '%'+@PR_PRO_NOM+'%'

GO
