SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_DELETE_DETALLE_PROCESO]
@PR_DET_PRO_COD int
as
DELETE [PRODUCCION].[DETALLE_PROCESO]
WHERE [PR_DET_PRO_COD]=@PR_DET_PRO_COD
GO
