SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_DESPACHO_BUSCADOR]
@FECHA_DESPACHO DATETIME
AS
SELECT MAX(PR_DES_COD) FROM PRODUCCION.DESPACHO
WHERE PR_DES_FEC=@FECHA_DESPACHO
AND ESTADO='ACTIVO'
AND TIPO='INGRESO_BODEGA'


GO
