SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_DELETE_DETALLE_PROCESO_REGLA]
@PR_DET_PRO_REG_COD int
AS
DELETE [PRODUCCION].[DETALLE_PROCESO_REGLA]
WHERE PR_DET_PRO_REG_COD=@PR_DET_PRO_REG_COD
GO
