SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create PROC [PRODUCCION].[PR_DELETE_PRODUCTO]
		(@PR_PRO_COD nvarchar(10)
           ,@CO_EMP_RUC char(13))
AS
DELETE  [PRODUCCION].PRODUCTO
WHERE  [PR_PRO_COD]=@PR_PRO_COD
           AND [CO_EMP_RUC]=@CO_EMP_RUC
GO
