SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[CO_PROFORMA_DETALLE_PENDIENTE]
AS
select DP.*, [CO_DET_PRO_CAN]-[CANTIDAD_PROCESADA] AS CANTIDAD_PENDIENTE, C.CO_CLI_NOM, P.CO_PRO_FEC
 FROM [dbo].[CO_DETALLE_PROFORMA] DP INNER JOIN CO_PROFORMA P ON P.CO_PRO_COD=DP.CO_PRO_COD
 INNER JOIN CO_CLIENTE C ON C.CO_CLI_COD=P.CO_CLI_COD 
WHERE DP.ESTADO='PENDIENTE'
and (select count(*) from CO_DOCUMENTO_VENTA where CO_PROFORMA_ID=P.CO_PRO_COD)>0
AND P.CO_PRO_EST<>'ANULADA'
AND DATEDIFF(day, ISNULL((select MAX(CO_DOC_VEN_FEC) from CO_DOCUMENTO_VENTA where CO_PROFORMA_ID=P.CO_PRO_COD),GETDATE()),GETDATE())>0
GO
