SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_ORDEN_TINTURADO_COLORES]
AS
select distinct GAMA_COLOR FROM [PRODUCCION].[ORDEN_TINTURADO]
WHERE ESTADO='PENDIENTE'
GO
