SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_INSERT_TIPO_PROCESO]
@PR_TIP_PRO_NOM nvarchar(50),
@CO_EMP_RUC CHAR(13),
@PR_TIP_PRO_DES BIT
AS
INSERT INTO [PRODUCCION].[TIPO_PROCESO]
([PR_TIP_PRO_NOM],
CO_EMP_RUC,
PR_TIP_PRO_DES)
VALUES
(@PR_TIP_PRO_NOM,
@CO_EMP_RUC,
@PR_TIP_PRO_DES)


GO
