SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_BUSQUEDA_DESPACHO]
@PR_DES_COD int
,@PR_DES_FEC DATETIME
,@PR_DES_OPC INT
,@TIPO VARCHAR(20)
AS
IF(@PR_DES_OPC=1)
SELECT PRODUCCION.DESPACHO.*
FROM PRODUCCION.DESPACHO 
WHERE PRODUCCION.DESPACHO.PR_DES_COD=case @PR_DES_COD when 0 then PRODUCCION.DESPACHO.PR_DES_COD else @PR_DES_COD end
AND TIPO=@TIPO AND ESTADO='ACTIVO'
ELSE
SELECT PRODUCCION.DESPACHO.*
FROM PRODUCCION.DESPACHO
WHERE PRODUCCION.DESPACHO.PR_DES_FEC=@PR_DES_FEC
AND TIPO=@TIPO AND ESTADO='ACTIVO'




GO
