SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_ORDEN_TINTURADO]
@TIPO_COLOR varchar(10)
as
SELECT * FROM [PRODUCCION].[ORDEN_TINTURADO]
WHERE [ESTADO]<>'PROCESADO'
AND GAMA_COLOR like @TIPO_COLOR+'%'
GO
