SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_DELETE_TIPO_RECETA]
(@PR_TIP_REC_COD int
,@CO_EMP_RUC char(13))
AS
DELETE [PRODUCCION].[TIPO_RECETA]
WHERE 
[PR_TIP_REC_COD]=@PR_TIP_REC_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC


GO
