SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create proc [PRODUCCION].[PR_SELECT_DATOS_PRODUCTO]
@CO_EMP_RUC CHAR(13),
@PR_PRO_COD NVARCHAR(10)
AS
select * from PRODUCCION.PRODUCTO
where PRODUCCION.PRODUCTO.PR_PRO_COD=@PR_PRO_COD AND PRODUCCION.PRODUCTO.CO_EMP_RUC=@CO_EMP_RUC
GO
