SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_PARECIDO_ARTICULO]
@PR_PAR_ART_COD NVARCHAR(15)
,@CO_EMP_RUC CHAR(13)
AS
SELECT PRODUCCION.PRODUCTO.PR_PRO_COD, PRODUCCION.PRODUCTO.CO_EMP_RUC, PRODUCCION.PARECIDO.PR_PAR_ART_COD, 
		isnull((select top 1 CO_KAR_TOT_ENT_VAL_UNI from PRODUCCION.KARDEX	
		 where PRODUCCION.KARDEX.PR_PRO_COD=PRODUCCION.PRODUCTO.PR_PRO_COD and CO_KAR_TOT_ENT_CANT>0
		 order by CO_KAR_TOT_FEC desc, PR_PRO_COD desc),0) as PR_PRO_PRE, dbo.CO_ARTICULO.CO_ART_PES
FROM PRODUCCION.PRODUCTO INNER JOIN
PRODUCCION.PARECIDO ON PRODUCCION.PRODUCTO.PR_PRO_COD = PRODUCCION.PARECIDO.PR_PRO_COD AND 
PRODUCCION.PRODUCTO.CO_EMP_RUC = PRODUCCION.PARECIDO.CO_EMP_RUC INNER JOIN
dbo.CO_ARTICULO ON PRODUCCION.PARECIDO.PR_PAR_ART_COD = dbo.CO_ARTICULO.CO_ART_COD
WHERE PRODUCCION.PARECIDO.PR_PAR_ART_COD=@PR_PAR_ART_COD AND PRODUCCION.PRODUCTO.CO_EMP_RUC=@CO_EMP_RUC


GO
