SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_ARTICULO_NOMBRE]
@CO_ART_COD NVARCHAR(20),
@CO_EMP_RUC CHAR(13)
AS
SELECT CO_ART_NOM, 0 as CO_ART_EXI_ACT, 0 as CO_ART_COS_PROM, CO_ART_PRE_COS FROM dbo.CO_ARTICULO
WHERE CO_ART_COD=@CO_ART_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
