SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_PRODUCTO_TIPO_RECETA]
@PR_TIP_REC_COD INT,
@CO_EMP_RUC CHAR(13)
AS
SELECT PR_PRO_COD,PR_PRO_NOM
FROM [PRODUCCION].[PRODUCTO]
WHERE PR_TIP_REC_COD=@PR_TIP_REC_COD AND CO_EMP_RUC=@CO_EMP_RUC
GO
