SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_PROCESO_CONTADOR]
@CO_EMP_RUC CHAR(13)
AS
SELECT MAX(PR_PRO_NUM) FROM PRODUCCION.PROCESO
WHERE CO_EMP_RUC=@CO_EMP_RUC
GO
