SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_INSERT_PARECIDO]
(@PR_PRO_COD nvarchar(10)
,@CO_EMP_RUC char(13)
,@PR_PAR_ART_COD nvarchar(20))
AS
INSERT INTO [PRODUCCION].[PARECIDO]
([PR_PRO_COD]
,[CO_EMP_RUC]
,[PR_PAR_ART_COD])
VALUES
(@PR_PRO_COD
,@CO_EMP_RUC
,@PR_PAR_ART_COD)

GO
