SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create PROC [PRODUCCION].[PR_SP_SELECT_KARDEX_FILA]
@CO_EMP_RUC CHAR(13),
@PR_PRO_COD NVARCHAR(40),
@CO_KAR_TOT_DOC INT
AS
SELECT * FROM PRODUCCION.KARDEX
WHERE CO_EMP_RUC=@CO_EMP_RUC AND
PR_PRO_COD=@PR_PRO_COD AND
CO_KAR_TOT_DOC=@CO_KAR_TOT_DOC

GO
