SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_UPDATE_DETALLE_REGLA]
(@PR_DET_REG_COD int
,@PR_REG_COD int
,@CO_ART_COD nvarchar(10)
,@PR_DET_REG_POR float
,@PR_DET_REG_TIP nchar(1))
AS
UPDATE [PRODUCCION].[DETALLE_REGLA] SET
[CO_ART_COD]=@CO_ART_COD
,[PR_DET_REG_POR]=@PR_DET_REG_POR
,[PR_DET_REG_TIP]=@PR_DET_REG_TIP
WHERE PR_DET_REG_COD=@PR_DET_REG_COD



GO
