SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_BUSQUEDA_PROCESO]
@PR_PRO_NUM int
,@PR_PRO_FEC DATETIME
,@PR_PRO_OPC INT
,@PR_PRO_COD NVARCHAR(10)
AS
IF(@PR_PRO_OPC=1)
SELECT DISTINCT PRODUCCION.PROCESO.PR_PRO_NUM, PRODUCCION.PROCESO.CO_EMP_RUC, PRODUCCION.PROCESO.PR_TIP_REC_COD, 
PRODUCCION.PROCESO.PR_PRO_FEC, PRODUCCION.PROCESO.PR_PRO_EST, PRODUCCION.PROCESO.PR_PRO_VAL_AGR, 
PRODUCCION.TIPO_RECETA.PR_TIP_REC_NOM
FROM PRODUCCION.PROCESO INNER JOIN
PRODUCCION.TIPO_RECETA ON PRODUCCION.PROCESO.PR_TIP_REC_COD = PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD INNER JOIN
PRODUCCION.DETALLE_PROCESO ON PRODUCCION.PROCESO.PR_PRO_NUM = PRODUCCION.DETALLE_PROCESO.PR_PRO_NUM
WHERE PRODUCCION.PROCESO.PR_PRO_NUM=case @PR_PRO_NUM when 0 then PRODUCCION.PROCESO.PR_PRO_NUM else @PR_PRO_NUM end AND
PRODUCCION.PROCESO.PR_PRO_EST=1
ELSE IF (@PR_PRO_OPC=2)
SELECT DISTINCT PRODUCCION.PROCESO.PR_PRO_NUM, PRODUCCION.PROCESO.CO_EMP_RUC, PRODUCCION.PROCESO.PR_TIP_REC_COD, 
PRODUCCION.PROCESO.PR_PRO_FEC, PRODUCCION.PROCESO.PR_PRO_EST, PRODUCCION.PROCESO.PR_PRO_VAL_AGR, 
PRODUCCION.TIPO_RECETA.PR_TIP_REC_NOM
FROM PRODUCCION.PROCESO INNER JOIN
PRODUCCION.TIPO_RECETA ON PRODUCCION.PROCESO.PR_TIP_REC_COD = PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD INNER JOIN
PRODUCCION.DETALLE_PROCESO ON PRODUCCION.PROCESO.PR_PRO_NUM = PRODUCCION.DETALLE_PROCESO.PR_PRO_NUM
WHERE PRODUCCION.PROCESO.PR_PRO_FEC=@PR_PRO_FEC
AND PRODUCCION.PROCESO.PR_PRO_EST=1
ELSE
SELECT DISTINCT PRODUCCION.PROCESO.PR_PRO_NUM, PRODUCCION.PROCESO.CO_EMP_RUC, PRODUCCION.PROCESO.PR_TIP_REC_COD, 
PRODUCCION.PROCESO.PR_PRO_FEC, PRODUCCION.PROCESO.PR_PRO_EST, PRODUCCION.PROCESO.PR_PRO_VAL_AGR, 
PRODUCCION.TIPO_RECETA.PR_TIP_REC_NOM
FROM PRODUCCION.PROCESO INNER JOIN
PRODUCCION.TIPO_RECETA ON PRODUCCION.PROCESO.PR_TIP_REC_COD = PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD INNER JOIN
PRODUCCION.DETALLE_PROCESO ON PRODUCCION.PROCESO.PR_PRO_NUM = PRODUCCION.DETALLE_PROCESO.PR_PRO_NUM
WHERE PRODUCCION.DETALLE_PROCESO.PR_PRO_COD=case @PR_PRO_COD when '' then PRODUCCION.DETALLE_PROCESO.PR_PRO_COD else @PR_PRO_COD end AND
PRODUCCION.PROCESO.PR_PRO_EST=1

GO
