SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_SELECT_AGREGADO]
@PR_AGR_MES INT
,@PR_AGR_ANO INT
,@PR_TIP_PRO_COD int
AS
SELECT * FROM [PRODUCCION].[AGREGADO]
WHERE
[PR_AGR_MES]=@PR_AGR_MES AND
[PR_AGR_ANO]=@PR_AGR_ANO AND
[PR_TIP_PRO_COD]=@PR_TIP_PRO_COD


GO
