SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE PROC [PRODUCCION].[PR_UPDATE_DETALLE_DESPACHO]
@PR_DET_DES_COD INT
,@PR_PRO_COD nvarchar(10)
,@CO_ART_COD nvarchar(10)
,@CO_ART_UNI int
,@CO_ART_PRE float
,@PR_DET_DES_CAN float
,@CO_ART_NOM nvarchar(80)
AS
UPDATE [PRODUCCION].[DETALLE_DESPACHO] SET
PR_PRO_COD=@PR_PRO_COD
,CO_ART_COD=@CO_ART_COD
,[CO_ART_UNI]=@CO_ART_UNI
,[CO_ART_PRE]=@CO_ART_PRE
,[PR_DET_DES_CAN]=@PR_DET_DES_CAN
,CO_ART_NOM=@CO_ART_NOM
WHERE PR_DET_DES_COD=@PR_DET_DES_COD




GO
