SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_SELECT_REGLAS_PRODUCCION]
@PR_TIP_REC_COD INT
AS
SELECT PRODUCCION.DETALLE_REGLA.CO_ART_COD, PRODUCCION.DETALLE_REGLA.PR_DET_REG_POR, 
PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD,PRODUCCION.DETALLE_REGLA.PR_DET_REG_TIP
FROM PRODUCCION.TIPO_RECETA INNER JOIN
PRODUCCION.REGLA ON PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD = PRODUCCION.REGLA.PR_TIP_REC_COD INNER JOIN
PRODUCCION.DETALLE_REGLA ON PRODUCCION.REGLA.PR_REG_COD = PRODUCCION.DETALLE_REGLA.PR_REG_COD
WHERE PRODUCCION.REGLA.PR_TIP_REC_COD=@PR_TIP_REC_COD

GO
