SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_INSERT_DETALLE_REGLA]
(@PR_REG_COD int
,@CO_ART_COD nvarchar(10)
,@PR_DET_REG_POR float
,@PR_DET_REG_TIP nchar(1))
AS
INSERT INTO [PRODUCCION].[DETALLE_REGLA]
([PR_REG_COD]
,[CO_ART_COD]
,[PR_DET_REG_POR]
,[PR_DET_REG_TIP])
VALUES
(@PR_REG_COD
,@CO_ART_COD
,@PR_DET_REG_POR
,@PR_DET_REG_TIP)
GO
