SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[CO_SP_UPDATE_DETALLE_PROFORMA_FACTURAR]
@CO_DET_PRO_COD INT,
@CANTIDAD_FACTURAR FLOAT
AS
UPDATE [dbo].[CO_DETALLE_PROFORMA] SET [CANTIDAD_FACTURAR]=@CANTIDAD_FACTURAR
WHERE CO_DET_PRO_COD=@CO_DET_PRO_COD
GO
