SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_DELETE_ORDEN_TINTURADO]
@CO_TINTURADO_ID INT
AS
DELETE [PRODUCCION].[ORDEN_TINTURADO] WHERE CO_TINTURADO_ID=@CO_TINTURADO_ID
GO
