SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[UPDATE_DETALLE_DESPACHO_DESPERDICIO]
@PR_DET_DES_COD INT,
@PR_DET_PRO_REC_CAN_DES FLOAT
AS
UPDATE [PRODUCCION].[DETALLE_DESPACHO] SET [PR_DET_PRO_REC_CAN_DES]=@PR_DET_PRO_REC_CAN_DES
WHERE [PR_DET_DES_COD]=@PR_DET_DES_COD
GO
