SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_INSERT_DETALLE_PROCESO_REGLA]
@PR_PRO_NUM int
,@CO_EMP_RUC char(13)
,@PR_PRO_COD nvarchar(10)
,@PR_DET_PRO_REG_CAN float
,@PR_DET_PRO_REG_CAN_DES float
,@PR_DET_PRO_REG_TIP nchar(1)
,@PR_DET_PRO_REG_POR FLOAT
AS
INSERT INTO [PRODUCCION].[DETALLE_PROCESO_REGLA]
([PR_PRO_NUM]
,[CO_EMP_RUC]
,[PR_PRO_COD]
,[PR_DET_PRO_REG_CAN]
,[PR_DET_PRO_REG_CAN_DES]
,[PR_DET_PRO_REG_TIP]
,[PR_DET_PRO_REG_POR])
VALUES
(@PR_PRO_NUM
,@CO_EMP_RUC
,@PR_PRO_COD
,@PR_DET_PRO_REG_CAN
,@PR_DET_PRO_REG_CAN_DES
,@PR_DET_PRO_REG_TIP
,@PR_DET_PRO_REG_POR)

GO
