SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_SELECT_AGREGADO_MES_ANTERIOR]
@PR_AGR_MES INT
,@PR_AGR_ANO INT
,@PR_TIP_REC_COD INT
AS
SELECT PRODUCCION.AGREGADO.PR_AGR_COD, PRODUCCION.AGREGADO.PR_TIP_PRO_COD, PRODUCCION.AGREGADO.PR_AGR_MES, 
PRODUCCION.AGREGADO.PR_AGR_ANO, PRODUCCION.AGREGADO.PR_AGR_VAL_MOB, PRODUCCION.AGREGADO.PR_AGR_VAL_PRO, 
PRODUCCION.AGREGADO.PR_AGR_VAL_COS,PRODUCCION.AGREGADO.PR_AGR_VAL_SUM
FROM PRODUCCION.AGREGADO INNER JOIN
PRODUCCION.TIPO_PROCESO ON PRODUCCION.AGREGADO.PR_TIP_PRO_COD = PRODUCCION.TIPO_PROCESO.PR_TIP_PRO_COD INNER JOIN
PRODUCCION.TIPO_RECETA ON PRODUCCION.TIPO_PROCESO.PR_TIP_PRO_COD = PRODUCCION.TIPO_RECETA.PR_TIP_PRO_COD
WHERE PRODUCCION.AGREGADO.PR_AGR_MES=@PR_AGR_MES AND PRODUCCION.AGREGADO.PR_AGR_ANO=@PR_AGR_ANO
AND PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD = @PR_TIP_REC_COD




GO
