SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_UPDATE_ANULAR_PENDIENTES]
@CO_PRO_COD INT
AS
update CO_DETALLE_PROFORMA set estado='ANULADO' where CO_PRO_COD=@CO_PRO_COD and estado='PENDIENTE'
GO
