SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_UPDATE_TIPO_RECETA]
(@PR_TIP_REC_COD int
,@PR_TIP_PRO_COD int
,@CO_EMP_RUC char(13)
,@PR_TIP_REC_NOM nvarchar(50))
AS
UPDATE [PRODUCCION].[TIPO_RECETA] SET 
[PR_TIP_REC_NOM]=@PR_TIP_REC_NOM
,[PR_TIP_PRO_COD]=@PR_TIP_PRO_COD
WHERE 
[PR_TIP_REC_COD]=@PR_TIP_REC_COD
AND [CO_EMP_RUC]=@CO_EMP_RUC


GO
