SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[CO_SP_UPDATE_DETALLE_PROFORMA_ANULAR]
@CO_PRO_COD INT
,@CO_ART_COD VARCHAR(50)
AS
UPDATE [dbo].[CO_DETALLE_PROFORMA] SET ESTADO='ANULADO'
WHERE [CO_PRO_COD]=@CO_PRO_COD AND CO_DET_PRO_ART_COD=@CO_ART_COD

DECLARE @CONTADOR_PROCESADOS INT 
DECLARE @CONTADOR_PENDIENTES INT

SELECT @CONTADOR_PROCESADOS=COUNT(*) FROM [dbo].[CO_DETALLE_PROFORMA] WHERE [CO_PRO_COD]=@CO_PRO_COD AND (ESTADO='PROCESADO' OR ESTADO='ANULADO')
SELECT @CONTADOR_PENDIENTES=COUNT(*) FROM [dbo].[CO_DETALLE_PROFORMA] WHERE [CO_PRO_COD]=@CO_PRO_COD

IF @CONTADOR_PROCESADOS=@CONTADOR_PENDIENTES
BEGIN
UPDATE [dbo].[CO_PROFORMA] SET CO_PRO_EST='PROCESADO'
WHERE [CO_PRO_COD]=@CO_PRO_COD
END


GO
