SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_UPDATE_DETALLE_PROCESO_DESPERDICIO]
@PR_DET_PRO_COD int
,@PR_PRO_NUM int
,@CO_EMP_RUC char(13)
,@PR_DET_PRO_CAN_DES float
AS
UPDATE [PRODUCCION].[DETALLE_PROCESO] SET
[PR_DET_PRO_CAN_DES]=@PR_DET_PRO_CAN_DES
WHERE PR_DET_PRO_COD=@PR_DET_PRO_COD AND
[PR_PRO_NUM]=@PR_PRO_NUM AND [CO_EMP_RUC]=@CO_EMP_RUC


GO
