SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_INSERT_DETALLE_DESPACHO]
@PR_DES_COD int
,@PR_PRO_COD nvarchar(10)
,@CO_ART_COD nvarchar(20)
,@CO_ART_UNI int
,@CO_ART_PRE float
,@PR_DET_DES_CAN float
,@CO_ART_NOM nvarchar(80)
,@ESTADO VARCHAR(20)
AS
INSERT INTO [PRODUCCION].[DETALLE_DESPACHO]
([PR_DES_COD]
,[PR_PRO_COD]
,[CO_ART_COD]
,[CO_ART_UNI]
,[CO_ART_PRE]
,[PR_DET_DES_CAN]
,CO_ART_NOM
,ESTADO)
VALUES
(@PR_DES_COD
,@PR_PRO_COD
,@CO_ART_COD
,@CO_ART_UNI
,@CO_ART_PRE
,@PR_DET_DES_CAN
,@CO_ART_NOM
,@ESTADO)
GO
