SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_UPDATE_REGLA]
@PR_REG_COD int
,@PR_TIP_REC_COD int
,@PR_REG_NOM nvarchar(50)
AS
UPDATE [PRODUCCION].[REGLA] SET
[PR_TIP_REC_COD]=@PR_TIP_REC_COD
,[PR_REG_NOM]=@PR_REG_NOM
WHERE
[PR_REG_COD]=@PR_REG_COD

GO
