SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [PRODUCCION].[PR_UPDATE_TIPO_PROCESO]
@PR_TIP_PRO_COD INT,
@PR_TIP_PRO_NOM nvarchar(50),
@CO_EMP_RUC CHAR(13),
@PR_TIP_PRO_DES BIT
AS
UPDATE [PRODUCCION].[TIPO_PROCESO] SET
[PR_TIP_PRO_NOM]=@PR_TIP_PRO_NOM,
[PR_TIP_PRO_DES]=@PR_TIP_PRO_DES
WHERE
[PR_TIP_PRO_COD]=@PR_TIP_PRO_COD
AND CO_EMP_RUC=@CO_EMP_RUC


GO
