SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_DELETE_TIPO_PROCESO]
@PR_TIP_PRO_COD INT
,@CO_EMP_RUC CHAR(13)
AS
DELETE [PRODUCCION].[TIPO_PROCESO] 
WHERE
[PR_TIP_PRO_COD]=@PR_TIP_PRO_COD AND
CO_EMP_RUC=@CO_EMP_RUC

GO
