SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_REPORTE_DESPERDICIOS]
@PR_PRO_FEC1 DATETIME
,@PR_PRO_FEC2 DATETIME
,@CO_EMP_RUC CHAR(13)
,@PR_TIP_REC_COD INT
AS
SELECT PRODUCCION.PROCESO.PR_PRO_NUM, PRODUCCION.TIPO_RECETA.PR_TIP_REC_NOM, PRODUCCION.DETALLE_PROCESO_REGLA.PR_PRO_COD, 
PRODUCCION.DETALLE_PROCESO_REGLA.PR_DET_PRO_REG_CAN_DES AS DESPERDICIO, 
PRODUCCION.DETALLE_PROCESO_REGLA.PR_DET_PRO_REG_CAN AS CANTIDAD
FROM PRODUCCION.PROCESO INNER JOIN
PRODUCCION.DETALLE_PROCESO_REGLA ON 
PRODUCCION.PROCESO.PR_PRO_NUM = PRODUCCION.DETALLE_PROCESO_REGLA.PR_PRO_NUM INNER JOIN
PRODUCCION.TIPO_RECETA ON PRODUCCION.PROCESO.PR_TIP_REC_COD = PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD
WHERE PRODUCCION.PROCESO.CO_EMP_RUC=@CO_EMP_RUC AND PRODUCCION.PROCESO.PR_PRO_EST=1 and
PRODUCCION.PROCESO.PR_PRO_FEC>=@PR_PRO_FEC1 AND PRODUCCION.PROCESO.PR_PRO_FEC<=@PR_PRO_FEC2 AND
PRODUCCION.PROCESO.PR_TIP_REC_COD=case @PR_TIP_REC_COD when 0 then PRODUCCION.PROCESO.PR_TIP_REC_COD else @PR_TIP_REC_COD end 
union
SELECT PRODUCCION.PROCESO.PR_PRO_NUM, PRODUCCION.TIPO_RECETA.PR_TIP_REC_NOM, PRODUCCION.DETALLE_PROCESO.PR_PRO_COD, 
PRODUCCION.DETALLE_PROCESO.PR_DET_PRO_CAN_DES AS DESPERDICIO,
PRODUCCION.DETALLE_PROCESO.PR_DET_PRO_CAN AS CANTIDAD
FROM PRODUCCION.PROCESO INNER JOIN
PRODUCCION.DETALLE_PROCESO_REGLA ON 
PRODUCCION.PROCESO.PR_PRO_NUM = PRODUCCION.DETALLE_PROCESO_REGLA.PR_PRO_NUM INNER JOIN
PRODUCCION.TIPO_RECETA ON PRODUCCION.PROCESO.PR_TIP_REC_COD = PRODUCCION.TIPO_RECETA.PR_TIP_REC_COD INNER JOIN
PRODUCCION.DETALLE_PROCESO ON PRODUCCION.PROCESO.PR_PRO_NUM = PRODUCCION.DETALLE_PROCESO.PR_PRO_NUM
WHERE PRODUCCION.PROCESO.CO_EMP_RUC=@CO_EMP_RUC AND PRODUCCION.PROCESO.PR_PRO_EST=1 and
PRODUCCION.PROCESO.PR_PRO_FEC>=@PR_PRO_FEC1 AND PRODUCCION.PROCESO.PR_PRO_FEC<=@PR_PRO_FEC2 AND
PRODUCCION.PROCESO.PR_TIP_REC_COD=case @PR_TIP_REC_COD when 0 then PRODUCCION.PROCESO.PR_TIP_REC_COD else @PR_TIP_REC_COD end 

GO
