SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_UPDATE_ORDEN_TINTURADO_PROCESADO]
           @CO_TINTURADO_ID INT
		   ,@CANTIDAD_KG float
		   ,@CANTIDAD_PROCESADO float
		   ,@ESTADO varchar(20)
AS
UPDATE [PRODUCCION].[ORDEN_TINTURADO]
           set [ESTADO]=@ESTADO, FECHA_FIN_PROCESO=GETDATE(),
		   CANTIDAD_KG=@CANTIDAD_KG, CANTIDAD_PROCESADO=@CANTIDAD_PROCESADO
     where CO_TINTURADO_ID=@CO_TINTURADO_ID
GO
