SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_UPDATE_DETALLE_PROCESO_REGLA]
@PR_DET_PRO_REG_COD int
,@PR_PRO_NUM int
,@CO_EMP_RUC char(13)
,@PR_PRO_COD nvarchar(10)
,@PR_DET_PRO_REG_CAN float
,@PR_DET_PRO_REG_CAN_DES float
,@PR_DET_PRO_REG_TIP nchar(1)
,@PR_DET_PRO_REG_POR FLOAT
AS
UPDATE [PRODUCCION].[DETALLE_PROCESO_REGLA] SET
[PR_PRO_NUM]=@PR_PRO_NUM
,[CO_EMP_RUC]=@CO_EMP_RUC
,[PR_PRO_COD]=@PR_PRO_COD
,[PR_DET_PRO_REG_CAN]=@PR_DET_PRO_REG_CAN
,[PR_DET_PRO_REG_CAN_DES]=@PR_DET_PRO_REG_CAN_DES
,[PR_DET_PRO_REG_TIP]=@PR_DET_PRO_REG_TIP
,[PR_DET_PRO_REG_POR]=@PR_DET_PRO_REG_POR
WHERE PR_DET_PRO_REG_COD=@PR_DET_PRO_REG_COD
GO
