SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_DELETE_DETALLE_DESPACHO]
@PR_DET_DES_COD INT
AS
DELETE [PRODUCCION].[DETALLE_DESPACHO] 
WHERE
PR_DET_DES_COD=@PR_DET_DES_COD
GO
