SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_SELECT_REPORTE_KARDEX]
@CO_EMP_RUC CHAR(13)
,@CO_KAR_TOT_FEC1 DATETIME
,@CO_KAR_TOT_FEC2 DATETIME
,@PR_PRO_COD NVARCHAR(10)
AS
SELECT * FROM PRODUCCION.PR_REPORTE_KARDEX
WHERE CO_EMP_RUC=@CO_EMP_RUC 
AND CO_KAR_TOT_FEC>=@CO_KAR_TOT_FEC1 AND CO_KAR_TOT_FEC<=@CO_KAR_TOT_FEC2
AND PR_PRO_COD=CASE @PR_PRO_COD WHEN '' THEN PR_PRO_COD ELSE @PR_PRO_COD END
ORDER BY CO_KAR_TOT_COD
GO
