SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [PRODUCCION].[PR_SELECT_REPORTE_EXISTENCIA_FECHA]
@CO_KAR_TOT_FEC DATETIME
,@CO_EMP_RUC CHAR(13)
AS

WITH S
as
(
SELECT RANK() OVER (PARTITION BY PRODUCCION.KARDEX.PR_PRO_COD ORDER BY PRODUCCION.KARDEX.CO_KAR_TOT_FEC DESC) AS 'RowNumber',
 
PRODUCCION.PRODUCTO.PR_PRO_COD, 
PRODUCCION.KARDEX.CO_KAR_TOT_FEC, PRODUCCION.KARDEX.CO_KAR_TOT_EXI_CANT, 
                      PRODUCCION.KARDEX.CO_KAR_TOT_EXI_VAL_UNI, PRODUCCION.KARDEX.CO_KAR_TOT_EXI_VAL_TOT, PRODUCCION.PRODUCTO.PR_PRO_NOM, 
                      PRODUCCION.PRODUCTO.CO_EMP_RUC, PRODUCCION.KARDEX.CO_KAR_TOT_COD
FROM         PRODUCCION.PRODUCTO INNER JOIN
                      PRODUCCION.KARDEX ON PRODUCCION.PRODUCTO.PR_PRO_COD = PRODUCCION.KARDEX.PR_PRO_COD AND 
                      PRODUCCION.PRODUCTO.CO_EMP_RUC = PRODUCCION.KARDEX.CO_EMP_RUC
where convert(datetime, CO_KAR_TOT_FEC,103)<=convert(datetime,@CO_KAR_TOT_FEC,103) and PRODUCCION.PRODUCTO.CO_EMP_RUC=@CO_EMP_RUC) 


select PR_PRO_COD, CO_KAR_TOT_EXI_CANT, CO_KAR_TOT_EXI_VAL_UNI, PR_PRO_NOM,
(case when len(PR_PRO_COD)<=5 then 1
	   when len(PR_PRO_COD)=6 then 2
	   when len(PR_PRO_COD)=7 then 3
	   when len(PR_PRO_COD)=8 then 4
	   when len(PR_PRO_COD)=9 then 5 
	   when len(PR_PRO_COD)=10 then 6 else 7 end) as PRO_ORDEN
from (
SELECT RANK() OVER (PARTITION BY PR_PRO_COD ORDER BY CO_KAR_TOT_COD desc) AS 'RowNumber2', PR_PRO_COD, CO_KAR_TOT_EXI_CANT, 
CO_KAR_TOT_EXI_VAL_UNI, PR_PRO_NOM  
FROM S
WHERE RowNumber=1
) as X
where RowNumber2=1
order by PRO_ORDEN, PR_PRO_COD


GO
