SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE PROC [PRODUCCION].[PR_SELECT_DETALLE_REGLA_CONTADOR]
@PR_REG_COD INT,
@CO_ART_COD NVARCHAR(20)
AS
SELECT * FROM [PRODUCCION].DETALLE_REGLA 
WHERE PR_REG_COD=@PR_REG_COD AND CO_ART_COD=@CO_ART_COD



GO
