SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [PRODUCCION].[PR_UPDATE_AGREGADO]
@PR_AGR_MES int
,@PR_AGR_ANO int
,@PR_TIP_PRO_COD INT
,@PR_AGR_VAL_MOB float
,@PR_AGR_VAL_PRO float
,@PR_AGR_VAL_COS float
,@PR_AGR_VAL_SUM float
AS
UPDATE [PRODUCCION].[AGREGADO] SET
[PR_AGR_VAL_MOB]=@PR_AGR_VAL_MOB
,[PR_AGR_VAL_PRO]=@PR_AGR_VAL_PRO
,[PR_AGR_VAL_COS]=@PR_AGR_VAL_COS
,[PR_AGR_VAL_SUM]=@PR_AGR_VAL_SUM
WHERE
[PR_AGR_MES]=@PR_AGR_MES AND
[PR_AGR_ANO]=@PR_AGR_ANO AND
[PR_TIP_PRO_COD]=@PR_TIP_PRO_COD


GO
