SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create proc [PRODUCCION].[PR_UPDATE_KARDEX_INPUT]
@CO_KAR_TOT_COD numeric(18,0),
@CO_EMP_RUC char(13),
@PR_PRO_COD nvarchar(10),
@CO_KAR_TOT_EXI_CANT float,
@CO_KAR_TOT_EXI_VAL_UNI float,
@CO_KAR_TOT_EXI_VAL_TOT float
as
update PRODUCCION.KARDEX set
CO_KAR_TOT_EXI_CANT=@CO_KAR_TOT_EXI_CANT,
CO_KAR_TOT_EXI_VAL_UNI=@CO_KAR_TOT_EXI_VAL_UNI,
CO_KAR_TOT_EXI_VAL_TOT=@CO_KAR_TOT_EXI_VAL_TOT
where CO_KAR_TOT_COD=@CO_KAR_TOT_COD
and CO_EMP_RUC=@CO_EMP_RUC
and PR_PRO_COD=@PR_PRO_COD

GO
