SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CO_VW_SELECT_REPORTE_EXISTENCIAS]
AS
SELECT     dbo.CO_ARTICULO.CO_ART_COD, dbo.CO_ARTICULO.CO_ART_NOM, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_FEC, 
                      dbo.CO_TIPO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NOM, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_ENT_CANT, 
                      dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_SAL_CANT, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EXI_CANT, dbo.CO_ARTICULO.CO_ART_BAR, 
                      dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_DET, 
                      dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EST
FROM         dbo.CO_ARTICULO INNER JOIN
                      dbo.CO_KARDEX_TOTAL ON dbo.CO_ARTICULO.CO_ART_COD = dbo.CO_KARDEX_TOTAL.CO_ART_COD AND 
                      dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_KARDEX_TOTAL.CO_EMP_RUC INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_ARTICULO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC LEFT OUTER JOIN
                      dbo.CO_TIPO_DOCUMENTO_VENTA ON 
                      dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_TIP_DOC = dbo.CO_TIPO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM
WHERE     (dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EST = N'Activo') OR
                      (dbo.CO_KARDEX_TOTAL.CO_KAR_TOT_EST = N'')

GO
