SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CO_VW_SELECT_REPORTE_COBRO_CLIENTES]
AS
SELECT     dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_CLIENTE.CO_CLI_NOM, 
                      dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_NUM, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_FEC, 
                      dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CON, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_VAL, 
                      dbo.CO_DETALLE_COBRO_CLIENTE.CO_DET_COB_CLI_CON, dbo.CO_DETALLE_COBRO_CLIENTE.CO_DET_COB_CLI_VAL,
					  dbo.CO_COBRO_CLIENTE.CO_COM_COD_CLI_ID
FROM         dbo.CO_CLIENTE INNER JOIN
                      dbo.CO_COBRO_CLIENTE ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_COBRO_CLIENTE.CO_CLI_COD AND 
                      dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_COBRO_CLIENTE.CO_EMP_RUC AND 
                      dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_COBRO_CLIENTE.CO_TIP_CLI_COD INNER JOIN
                      dbo.CO_DETALLE_COBRO_CLIENTE ON 
                      dbo.CO_COBRO_CLIENTE.CO_COM_COD_CLI_ID = dbo.CO_DETALLE_COBRO_CLIENTE.CO_COM_COD_CLI_ID inner join
                      dbo.CO_EMPRESA ON dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
GO
