SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CO_VW_SELECT_DOCUMENTO_VENTA_SALDOS]
AS
SELECT     dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_VENDEDOR.CO_VEN_NOM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM, 
                      dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_PAGO_DOCUMENTO_VENTA.CO_PAG_DOC_VEN_VAL, 
                      dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_TOT_PAG, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC, 
                      dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC
FROM         dbo.CO_DOCUMENTO_VENTA INNER JOIN
                      dbo.CO_PAGO_DOCUMENTO_VENTA ON dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_ID = dbo.CO_PAGO_DOCUMENTO_VENTA.CO_DOC_VEN_ID INNER JOIN
                      dbo.CO_VENDEDOR ON dbo.CO_DOCUMENTO_VENTA.CO_VEN_CED = dbo.CO_VENDEDOR.CO_VEN_CED AND 
                      dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC = dbo.CO_VENDEDOR.CO_EMP_RUC INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_VENDEDOR.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC



GO
