SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[CO_VW_SELECT_REPORTES_RETENCIONES]
AS
SELECT        dbo.CO_RETENCION.CO_RET_BEN_NOM, dbo.CO_RETENCION.CO_RET_BEN_NUM_RUC, dbo.CO_RETENCION.CO_RET_NUM_REF, dbo.CO_DETALLE_RETENCION.CO_RET_BAS, dbo.CO_DETALLE_RETENCION.CO_RET_VAL, 
                         dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_DIR, dbo.CO_DETALLE_RETENCION.CO_TIP_RET_COD_SRI as CO_TIP_RET_COD, dbo.CO_DETALLE_RETENCION.CO_TIP_RET_NOM, dbo.CO_DETALLE_RETENCION.CO_RET_POR, 
                         dbo.CO_RETENCION.CO_DOC_COM_ID, dbo.CO_RETENCION.CO_DOC_VEN_ID, dbo.CO_RETENCION.CO_RET_BEN_FEC_EMI, dbo.CO_RETENCION.CO_EMP_RUC, dbo.CO_RETENCION.CO_RET_EMI, 
                         dbo.CO_RETENCION.CO_ESTADO AS CO_RET_DET_EST, dbo.CO_RETENCION.CO_RET_TIP
FROM            dbo.CO_EMPRESA INNER JOIN
                         dbo.CO_RETENCION ON dbo.CO_EMPRESA.CO_EMP_RUC = dbo.CO_RETENCION.CO_EMP_RUC
						 INNER JOIN dbo.CO_DETALLE_RETENCION ON dbo.CO_RETENCION.CO_RET_COD=dbo.CO_DETALLE_RETENCION.CO_RET_COD
WHERE        (dbo.CO_RETENCION.CO_ESTADO = 1)


GO
