SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create VIEW [dbo].[CO_VW_SELECT_REPORTE_MOVIMIENTOS_FINAL]
AS
SELECT * FROM dbo.CO_VW_SELECT_REPORTE_MOVIMIENTOS_ENTRADAS
UNION
SELECT * FROM dbo.CO_VW_SELECT_REPORTE_MOVIMIENTOS_SALIDAS
UNION
SELECT * FROM dbo.CO_VW_SELECT_REPORTE_MOVIMIENTOS_SALIDAS_CORRECCIONES
GO
