SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CO_VW_SELECT_BUSCAR_COBRO_CLIENTE]
AS
SELECT        dbo.CO_CLIENTE.CO_CLI_COD, dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_NUM, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_FEC, 
                         dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_VAL, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CON, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_COM, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_EST, 
                         dbo.CO_COBRO_CLIENTE.CO_EMP_RUC, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_FOR_COB, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_EFE, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_EFE_VAL, 
                         dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CHE, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CHE_VAL, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CHE_NUM, 
                         dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CHE_BAN, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_TAR, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_TAR_VAL, 
                         dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_TAR_NUM, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_TAR_VAU, dbo.CO_COBRO_CLIENTE.CO_COM_COD_CLI_ID, 
                         dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_CHE_FEC, dbo.CO_COBRO_CLIENTE.CO_COM_COB_TRA, dbo.CO_COBRO_CLIENTE.CO_COM_COB_TRA_VAL, 
                         dbo.CO_COBRO_CLIENTE.CO_COM_COB_TRA_DOC_NUM
FROM            dbo.CO_COBRO_CLIENTE INNER JOIN
                         dbo.CO_CLIENTE ON dbo.CO_COBRO_CLIENTE.CO_CLI_COD = dbo.CO_CLIENTE.CO_CLI_COD AND dbo.CO_COBRO_CLIENTE.CO_EMP_RUC = dbo.CO_CLIENTE.CO_EMP_RUC AND 
                         dbo.CO_COBRO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_CLIENTE.CO_TIP_CLI_COD

GO
