SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[CO_VW_SELECT_REPORTE_MOVIMIENTOS_SALIDAS]
AS
SELECT     dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC, 
                      dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_ART_COD, 
                      (CASE WHEN dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM = 4 THEN dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_CAN ELSE
                       dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_CAN * - 1 END) AS CO_DET_DOC_VEN_CAN, 
                      'Documento de venta Tipo:' + CAST(dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM AS varchar(2)) 
                      + ' No.: ' + CAST(dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM AS varchar(250)) AS Detalle, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_EST, 
                      dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM,0 as Saldo
FROM         dbo.CO_DOCUMENTO_VENTA INNER JOIN
                      dbo.CO_DETALLE_DOCUMENTO_VENTA ON dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_ID = dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DOC_VEN_ID
GO
