SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[CO_VW_SELECT_LISTADO_DOCUMENTOS_VENTA]
AS
SELECT     dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM, 
                      dbo.CO_DOCUMENTO_VENTA.CO_VEN_CED, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC, 
                      dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_ART_COD, dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_ART_NOM, 
                      dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_CAN, dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_PRE, 
                      dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_DES, dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_TOT, 
                      dbo.CO_CLIENTE.CO_TIP_CLI_COD, dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_CLIENTE.CO_CLI_COD, dbo.CO_EMPRESA.CO_EMP_RUC, 
                      dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_EMPRESA.CO_EMP_CIU, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FOR_PAG, 
                      0 AS CO_ALM_COD, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_TOT_NET, 
                      dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_POR_DES, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_DES, 
                      dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_POR_IVA, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_IVA, 
                      dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_TOT_PAG, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_EST
FROM         dbo.CO_DETALLE_DOCUMENTO_VENTA INNER JOIN
                      dbo.CO_DOCUMENTO_VENTA ON dbo.CO_DETALLE_DOCUMENTO_VENTA.CO_DOC_VEN_ID = dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_ID INNER JOIN
                      dbo.CO_CLIENTE ON dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD = dbo.CO_CLIENTE.CO_CLI_COD AND 
                      dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC = dbo.CO_CLIENTE.CO_EMP_RUC AND 
                      dbo.CO_DOCUMENTO_VENTA.CO_TIP_CLI_COD = dbo.CO_CLIENTE.CO_TIP_CLI_COD INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
GO
