SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[CO_VW_SELECT_CUENTAS_SALDOS_TEMP]
AS
SELECT     dbo.CO_MES_SALDO_TEMP.CO_EMP_RUC, dbo.CO_MES_SALDO_TEMP.CO_CUE_COD, dbo.CO_CUENTA.CO_CUE_NOM, 
                      dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_ACT, dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_DEB, dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_HAB, 
                      dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_ANT, dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_CUENTA.CO_CUE_TIP, 0 as CO_CUE_NIV, 
                      dbo.CO_EMPRESA.CO_EMP_NOM_REP, dbo.CO_EMPRESA.CO_EMP_NOM_CON, dbo.CO_EMPRESA.CO_EMP_REG_CON
FROM         dbo.CO_CUENTA INNER JOIN
                      dbo.CO_MES_SALDO_TEMP ON dbo.CO_CUENTA.CO_EMP_RUC = dbo.CO_MES_SALDO_TEMP.CO_EMP_RUC AND 
                      dbo.CO_CUENTA.CO_CUE_COD = dbo.CO_MES_SALDO_TEMP.CO_CUE_COD INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_CUENTA.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_ACT<>0 OR dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_DEB<>0 OR dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_HAB<>0 OR
                      dbo.CO_MES_SALDO_TEMP.CO_MES_SAL_ANT<>0

GO
