SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[CO_VW_SELECT_REPORTE_MOVIMIENTOS_SALIDAS_CORRECCIONES]
AS
SELECT     CO_EMP_RUC, CO_KAR_TOT_FEC, CO_ART_COD, CO_KAR_TOT_SAL_CANT*-1 AS CO_KAR_TOT_SAL_CANT, CO_KAR_TOT_DET, CO_KAR_TOT_EST, 
			CO_KAR_TOT_DOC, CO_KAR_TOT_TIP_DOC, CO_KAR_TOT_EXI_CANT
FROM         dbo.CO_KARDEX_TOTAL
WHERE     (CO_KAR_TOT_SAL_CANT > 0) AND CO_KAR_TOT_DOC='0' AND CO_KAR_TOT_TIP_DOC=0
GO
