SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[CO_VW_SELECT_ESTADO_CUENTA_PROVEEDOR_PAGOS]
AS
SELECT     dbo.CO_DETALLE_COMPROBANTE_PAGO.CO_DOC_COM_NUM, dbo.CO_DETALLE_COMPROBANTE_PAGO.CO_DET_PAG_PRO_CON, 
                      0 AS CO_FACTURAS, dbo.CO_DETALLE_COMPROBANTE_PAGO.CO_DET_PAG_PRO_VAL AS CO_PAGOS, 
                      dbo.CO_COMPROBANTE_PAGO.CO_COM_PAG_FEC AS CO_FEC_DOC, dbo.CO_COMPROBANTE_PAGO.CO_PRO_COD, 
                      dbo.CO_PROVEEDOR.CO_PRO_CUE, dbo.CO_PROVEEDOR.CO_PRO_NOM, dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_EMPRESA.CO_EMP_NOM, 
                      dbo.CO_PROVEEDOR.CO_TIP_PRO_COD, dbo.CO_TIPO_PROVEEDOR.CO_TIP_PRO_NOM,
					  CO_COM_PAG_VAL
FROM         dbo.CO_DETALLE_COMPROBANTE_PAGO INNER JOIN
                      dbo.CO_COMPROBANTE_PAGO ON 
                      dbo.CO_DETALLE_COMPROBANTE_PAGO.CO_COM_PAG_NUM = dbo.CO_COMPROBANTE_PAGO.CO_COM_PAG_NUM AND 
                      dbo.CO_DETALLE_COMPROBANTE_PAGO.CO_EMP_RUC = dbo.CO_COMPROBANTE_PAGO.CO_EMP_RUC INNER JOIN
                      dbo.CO_PROVEEDOR ON dbo.CO_COMPROBANTE_PAGO.CO_PRO_COD = dbo.CO_PROVEEDOR.CO_PRO_COD INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_COMPROBANTE_PAGO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC INNER JOIN
                      dbo.CO_TIPO_PROVEEDOR ON dbo.CO_PROVEEDOR.CO_TIP_PRO_COD = dbo.CO_TIPO_PROVEEDOR.CO_TIP_PRO_COD AND 
                      dbo.CO_PROVEEDOR.CO_EMP_RUC = dbo.CO_TIPO_PROVEEDOR.CO_EMP_RUC AND 
                      dbo.CO_EMPRESA.CO_EMP_RUC = dbo.CO_TIPO_PROVEEDOR.CO_EMP_RUC
WHERE     (dbo.CO_COMPROBANTE_PAGO.CO_COM_PAG_EST = 1)



GO
