SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[CO_VW_SELECT_DETALLE_DOCUMENTO_VENTA_RESUMIDO]
AS
select *,
(SELECT TOP 1 CO_ICE_COD_PORC_SRI FROM dbo.CO_TABLA_ICE WHERE CO_ICE_COD IN (SELECT CO_ICE_COD FROM CO_ARTICULO WHERE CO_ART_COD=CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_ART_COD)) AS CO_ICE_COD_PORC_SRI,
(SELECT TOP 1 CO_ICE_POR FROM dbo.CO_TABLA_ICE WHERE CO_ICE_COD IN (SELECT CO_ICE_COD FROM CO_ARTICULO WHERE CO_ART_COD=CO_DETALLE_DOCUMENTO_VENTA.CO_DET_DOC_VEN_ART_COD)) AS CO_ICE_POR
from CO_DETALLE_DOCUMENTO_VENTA
GO
