SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

/* View*/
CREATE VIEW [dbo].[CO_VW_SELECT_ESTADO_CUENTA_CLIENTE]
AS
SELECT        dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM, dbo.CO_PAGO_DOCUMENTO_VENTA.CO_PAG_DOC_VEN_CON, 
                         dbo.CO_PAGO_DOCUMENTO_VENTA.CO_PAG_DOC_VEN_VAL_IMP AS CO_FACTURAS, 0 AS CO_COBROS, dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC AS CO_FEC_DOC, dbo.CO_CLIENTE.CO_CLI_COD, 
                         dbo.CO_CLIENTE.CO_CLI_CUE_CON, dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_EMPRESA.CO_EMP_NOM, dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_COD, 
                         dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_NOM
FROM            dbo.CO_DOCUMENTO_VENTA INNER JOIN
                         dbo.CO_PAGO_DOCUMENTO_VENTA ON dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_ID = dbo.CO_PAGO_DOCUMENTO_VENTA.CO_DOC_VEN_ID INNER JOIN
                         dbo.CO_CLIENTE ON dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD = dbo.CO_CLIENTE.CO_CLI_COD INNER JOIN
                         dbo.CO_TIPO_CLIENTE ON dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_COD INNER JOIN
                         dbo.CO_EMPRESA ON dbo.CO_TIPO_CLIENTE.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
WHERE        (dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_EST = N'ACTIVA')

GO
