SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[CO_VW_SELECT_REPORTE_MOVIMIENTOS_ENTRADAS]
AS
SELECT     CO_EMP_RUC, CO_KAR_TOT_FEC, CO_ART_COD, CO_KAR_TOT_ENT_CANT, CO_KAR_TOT_DET, CO_KAR_TOT_EST, CO_KAR_TOT_DOC, 
                      CO_KAR_TOT_TIP_DOC, CO_KAR_TOT_EXI_CANT
FROM         dbo.CO_KARDEX_TOTAL
WHERE     (CO_KAR_TOT_ENT_CANT > 0)
GO
