SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- View

CREATE VIEW [dbo].[CO_VW_SELECT_ESTADO_CUENTA_CLIENTE_COBRO]
AS
SELECT     dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM, 
                      dbo.CO_DETALLE_COBRO_CLIENTE.CO_DET_COB_CLI_CON, 0 AS CO_FACTURAS, SUM(dbo.CO_DETALLE_COBRO_CLIENTE.CO_DET_COB_CLI_VAL) 
                      AS CO_COBROS, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_FEC AS CO_FEC_DOC, dbo.CO_COBRO_CLIENTE.CO_CLI_COD, 
                      dbo.CO_CLIENTE.CO_CLI_CUE_CON, dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_EMPRESA.CO_EMP_RUC, dbo.CO_EMPRESA.CO_EMP_NOM, 
                      dbo.CO_CLIENTE.CO_TIP_CLI_COD, dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_NOM
FROM         dbo.CO_CLIENTE INNER JOIN
                      dbo.CO_COBRO_CLIENTE ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_COBRO_CLIENTE.CO_CLI_COD AND 
                      dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_COBRO_CLIENTE.CO_EMP_RUC AND 
                      dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_COBRO_CLIENTE.CO_TIP_CLI_COD INNER JOIN
                      dbo.CO_DETALLE_COBRO_CLIENTE ON  dbo.CO_COBRO_CLIENTE.CO_COM_COD_CLI_ID = dbo.CO_DETALLE_COBRO_CLIENTE.CO_COM_COD_CLI_ID
                      INNER JOIN
                      dbo.CO_TIPO_CLIENTE ON dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_COD AND 
                      dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_TIPO_CLIENTE.CO_EMP_RUC INNER JOIN
                      dbo.CO_EMPRESA ON dbo.CO_TIPO_CLIENTE.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC INNER JOIN 
					  dbo.CO_DOCUMENTO_VENTA ON dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_ID=dbo.CO_DETALLE_COBRO_CLIENTE.CO_DOC_VEN_ID
					  AND dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM<>20
GROUP BY dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_NUM, dbo.CO_DOCUMENTO_VENTA.CO_TIP_DOC_VEN_NUM,
                      dbo.CO_DETALLE_COBRO_CLIENTE.CO_DET_COB_CLI_CON, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_FEC, 
                      dbo.CO_COBRO_CLIENTE.CO_CLI_COD, dbo.CO_CLIENTE.CO_CLI_CUE_CON, dbo.CO_CLIENTE.CO_CLI_NOM, dbo.CO_CLIENTE.CO_TIP_CLI_COD, 
                      dbo.CO_TIPO_CLIENTE.CO_TIP_CLI_NOM, dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_EST, dbo.CO_EMPRESA.CO_EMP_RUC, 
                      dbo.CO_EMPRESA.CO_EMP_NOM
HAVING      (dbo.CO_COBRO_CLIENTE.CO_COM_COB_CLI_EST = 'ACTIVA') 




GO
