SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [PRODUCCION].[PR_VW_SELECT_REPORTE_INGRESOS]
AS
SELECT        PRODUCCION.DESPACHO.PR_DES_FEC, PRODUCCION.DESPACHO.ESTADO, PRODUCCION.DESPACHO.NUMERO_INGRESO, PRODUCCION.DESPACHO.TIPO, PRODUCCION.DESPACHO.PR_DES_COD, 
                         PRODUCCION.DETALLE_DESPACHO.PR_PRO_COD, PRODUCCION.DETALLE_DESPACHO.PR_DET_DES_CAN, PRODUCCION.DETALLE_DESPACHO.PR_DET_PRO_REC_CAN_DES, 
                         PRODUCCION.DETALLE_DESPACHO.CO_ART_COD
FROM            PRODUCCION.DESPACHO INNER JOIN
                         PRODUCCION.DETALLE_DESPACHO ON PRODUCCION.DESPACHO.PR_DES_COD = PRODUCCION.DETALLE_DESPACHO.PR_DES_COD
GO
