SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[co_fn_ventas_cliente](@dat_fec_ini datetime,@dat_fec_fin datetime,@str_emp_ruc char(13))
RETURNS TABLE
AS
RETURN 
(
    SELECT dbo.CO_CLIENTE.CO_CLI_COD AS CO_CLI_COD_VENTAS, dbo.CO_CLIENTE.CO_CLI_NOM AS V_CLIENTE, 
	SUM(dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_TOT_PAG) AS VENTAS
	FROM dbo.CO_CLIENTE INNER JOIN
    dbo.CO_DOCUMENTO_VENTA ON dbo.CO_CLIENTE.CO_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_CLI_COD AND 
    dbo.CO_CLIENTE.CO_EMP_RUC = dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC AND 
    dbo.CO_CLIENTE.CO_TIP_CLI_COD = dbo.CO_DOCUMENTO_VENTA.CO_TIP_CLI_COD
	where (convert(nvarchar(10),dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC,103)>=convert(nvarchar(10),@dat_fec_ini,103) and
	convert(nvarchar(10),dbo.CO_DOCUMENTO_VENTA.CO_DOC_VEN_FEC,103)<=convert(nvarchar(10),@dat_fec_fin,103)) 
	and dbo.CO_DOCUMENTO_VENTA.CO_EMP_RUC=@str_emp_ruc
	GROUP BY dbo.CO_CLIENTE.CO_CLI_COD, dbo.CO_CLIENTE.CO_CLI_NOM
);
GO
