SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[co_fn_abonos_empleado](@dat_fec_ini datetime,@dat_fec_fin datetime,@str_emp_ruc char(13))
RETURNS TABLE
AS
RETURN 
(
    SELECT dbo.PROFESOR.PROF_COD as CO_PROF_COD_ABONOS, dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM AS A_EMPLEADO, 
    SUM(dbo.CO_COMPROBANTE_COBRO.CO_COM_COB_VAL) AS ABONOS,dbo.CO_EMPRESA.CO_EMP_NOM AS A_EMPRESA
	FROM dbo.PROFESOR INNER JOIN
	dbo.CO_COMPROBANTE_COBRO ON dbo.PROFESOR.PROF_COD = dbo.CO_COMPROBANTE_COBRO.PROF_COD INNER JOIN
    dbo.CO_EMPRESA ON dbo.CO_COMPROBANTE_COBRO.CO_EMP_RUC = dbo.CO_EMPRESA.CO_EMP_RUC
	where (convert(nvarchar(10),dbo.CO_COMPROBANTE_COBRO.CO_COM_COB_FEC,103)>=convert(nvarchar(10),@dat_fec_ini,103) and
	convert(nvarchar(10),dbo.CO_COMPROBANTE_COBRO.CO_COM_COB_FEC,103)<=convert(nvarchar(10),@dat_fec_fin,103)) and dbo.CO_COMPROBANTE_COBRO.CO_EMP_RUC=@str_emp_ruc
	GROUP BY dbo.PROFESOR.PROF_APE + ' ' + dbo.PROFESOR.PROF_NOM, dbo.PROFESOR.PROF_COD,dbo.CO_EMPRESA.CO_EMP_NOM
);
GO
