CREATE TABLE [dbo].[CO_TRANSACCION]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_COD] [int] NOT NULL,
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TRA_MES] [int] NOT NULL,
[CO_TRA_ANO] [int] NOT NULL,
[CO_TRA_VAL] [float] NULL,
[CO_TRA_USU_ALI] [varchar] (13) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TRANSACCION] ADD CONSTRAINT [PK_NO_TRANSACCION] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_RUB_ROL_COD], [PROF_COD], [CO_TRA_MES], [CO_TRA_ANO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TRANSACCION] ADD CONSTRAINT [FK_CO_TRANSACCION_CO_RUBROS_ROL] FOREIGN KEY ([CO_RUB_ROL_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_RUBROS_ROL] ([CO_RUB_ROL_COD], [CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_TRANSACCION] ADD CONSTRAINT [FK_CO_TRANSACCION_PROFESOR] FOREIGN KEY ([PROF_COD]) REFERENCES [dbo].[PROFESOR] ([PROF_COD])
GO
