CREATE TABLE [dbo].[CO_DOCUMENTO_ELECTRONICO]
(
[CO_DOCUMENTO_ELECTRONICO_ID] [uniqueidentifier] NOT NULL,
[CO_DOCUMENTO_ID] [uniqueidentifier] NOT NULL,
[CO_FECHA_AUTORIZA_FACT_ELECTRONICA] [datetime] NULL,
[CO_XML_FACTURA_ELECTRONICA] [varbinary] (max) NULL,
[CO_RIDE_FACTURA_ELECTRONICA] [varbinary] (max) NULL,
[CO_OBSERVA_FACT_ELECTRONICA] [varchar] (1000) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CLAVE_ACCESO_FACT_ELECTRONICA] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CODIGO_BARRAS_FACT_ELECTRONICA] [varbinary] (max) NULL,
[CO_ESTADO_FACTURA_ELECTRONICA] [int] NULL,
[CO_FECHA_REGISTRO] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DOCUMENTO_ELECTRONICO] ADD CONSTRAINT [PK_CO_DOCUMENTO_ELECTRONICO] PRIMARY KEY CLUSTERED ([CO_DOCUMENTO_ELECTRONICO_ID]) ON [PRIMARY]
GO
