CREATE TABLE [dbo].[CO_COMPROBANTE_COBRO]
(
[CO_COM_COB_NUM] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_FEC] [datetime] NULL,
[CO_COM_COB_CON] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_VAL] [float] NULL,
[CO_COM_COB_EST] [bit] NULL,
[CO_COM_COB_COM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_USU_ALI] [nvarchar] (14) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_FOR_COB] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_EFE] [bit] NULL,
[CO_COM_COB_EFE_VAL] [float] NULL,
[CO_COM_COB_CHE] [bit] NULL,
[CO_COM_COB_CHE_VAL] [float] NULL,
[CO_COM_COB_CHE_NUM] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CHE_BAN] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_ROL] [bit] NULL,
[CO_COM_COB_ROL_VAL] [float] NULL,
[CO_COM_COB_ROL_DOC_NUM] [int] NULL,
[CO_COM_NUM] [int] NOT NULL,
[CO_TIP_COM_COD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COMPROBANTE_COBRO] ADD CONSTRAINT [PK_CO_COMPROBANTE_COBRO] PRIMARY KEY CLUSTERED ([CO_COM_COB_NUM], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COMPROBANTE_COBRO] ADD CONSTRAINT [FK_CO_COMPROBANTE_COBRO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_COMPROBANTE_COBRO] ADD CONSTRAINT [FK_CO_COMPROBANTE_COBRO_PROFESOR] FOREIGN KEY ([PROF_COD]) REFERENCES [dbo].[PROFESOR] ([PROF_COD])
GO
