CREATE TABLE [dbo].[CO_CLASIFICADOR]
(
[CO_CLASIFICADOR_ID] [uniqueidentifier] NOT NULL,
[CO_TIPO_CLASIFICADOR_ID] [uniqueidentifier] NOT NULL,
[NOMBRE] [varchar] (250) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ADICIONAL1] [varchar] (200) COLLATE Modern_Spanish_CI_AS NULL,
[ESTADO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CLASIFICADOR] ADD CONSTRAINT [PK_CO_CLASIFICADOR] PRIMARY KEY CLUSTERED ([CO_CLASIFICADOR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CLASIFICADOR] ADD CONSTRAINT [FK_CO_CLASIFICADOR_CO_TIPO_CLASIFICADOR] FOREIGN KEY ([CO_TIPO_CLASIFICADOR_ID]) REFERENCES [dbo].[CO_TIPO_CLASIFICADOR] ([CO_TIPO_CLASIFICADOR_ID])
GO
