CREATE TABLE [dbo].[CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE]
(
[CO_CUE_PAG_DET_CHE_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_CUE_PAG_COD] [int] NOT NULL,
[CO_CC_NUM] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_PAG_DET_CHE_NUM] [int] NOT NULL,
[CO_CUE_PAG_DET_CHE_VAL] [float] NOT NULL,
[CO_CUE_PAG_DET_CHE_FEC] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE] ADD CONSTRAINT [PK_CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE] PRIMARY KEY CLUSTERED ([CO_CUE_PAG_DET_CHE_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE] ADD CONSTRAINT [FK_CO_CUENTA_POR_PAGAR_DETALLE_CHEQUE_CO_CUENTA_POR_PAGAR] FOREIGN KEY ([CO_CUE_PAG_COD]) REFERENCES [dbo].[CO_CUENTA_POR_PAGAR] ([CO_CUE_PAG_COD])
GO
