CREATE TABLE [dbo].[CO_EGRESO_DETALLE]
(
[DetalleEgresoID] [uniqueidentifier] NOT NULL,
[EgresoID] [uniqueidentifier] NOT NULL,
[CO_ART_COD] [uniqueidentifier] NOT NULL,
[CO_ART_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[Costo] [float] NOT NULL,
[Cantidad] [float] NOT NULL,
[Total] [float] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_EGRESO_DETALLE] ADD CONSTRAINT [PK_CO_EGRESO_DETALLE] PRIMARY KEY CLUSTERED ([DetalleEgresoID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_EGRESO_DETALLE] ADD CONSTRAINT [FK_CO_EGRESO_DETALLE_CO_ARTICULO] FOREIGN KEY ([CO_ART_COD]) REFERENCES [dbo].[CO_ARTICULO] ([CO_ART_COD])
GO
ALTER TABLE [dbo].[CO_EGRESO_DETALLE] ADD CONSTRAINT [FK_CO_EGRESO_DETALLE_CO_EGRESO] FOREIGN KEY ([EgresoID]) REFERENCES [dbo].[CO_EGRESO] ([EgresoID])
GO
