CREATE TABLE [dbo].[CO_CONCEPTO_AIR]
(
[CO_CON_AIR_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CON_AIR_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CON_AIR_POR] [float] NULL,
[CO_CON_AIR_CUE_COM] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CON_AIR_CUE_VEN] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CON_AIR_COD_SRI] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CONCEPTO_AIR] ADD CONSTRAINT [PK_CO_CONCEPTO_AIR] PRIMARY KEY CLUSTERED ([CO_CON_AIR_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CONCEPTO_AIR] ADD CONSTRAINT [FK_CO_CONCEPTO_AIR_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
