CREATE TABLE [dbo].[CO_EXISTENCIA_FINAL_KARDEX]
(
[CO_EXI_FIN_KAR_COD] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ART_COD] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_EXI_FIN_KAR_FEC] [datetime] NULL,
[CO_EXI_FIN_KAR_DOC] [int] NULL,
[CO_EXI_FIN_KAR_TIP_DOC] [int] NULL,
[CO_EXI_FIN_KAR_CANT] [int] NULL,
[CO_EXI_FIN_KAR_VAL_UNI] [float] NULL,
[CO_EXI_FIN_KAR_VAL_TOT] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_EXISTENCIA_FINAL_KARDEX] ADD CONSTRAINT [PK_CO_EXISTENCIA_FINAL_KARDEX] PRIMARY KEY CLUSTERED ([CO_EXI_FIN_KAR_COD], [CO_EMP_RUC], [CO_ART_COD]) ON [PRIMARY]
GO
