CREATE TABLE [dbo].[CO_TIPO_IDENTIFICACION]
(
[CO_TIP_IDE_COD] [uniqueidentifier] NOT NULL,
[CO_TIP_IDE_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_IDE_COD_SRI] [varchar] (5) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_IDENTIFICACION] ADD CONSTRAINT [PK_CO_TIPO_IDENTIFICACION_1] PRIMARY KEY CLUSTERED ([CO_TIP_IDE_COD]) ON [PRIMARY]
GO
