CREATE TABLE [dbo].[CO_FAMILIA_ARTICULO]
(
[CO_FAM_ART_COD] [uniqueidentifier] NOT NULL,
[CO_TIP_ART_COD] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_FAM_ART_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_FAMILIA_ARTICULO] ADD CONSTRAINT [PK_CO_FAMILIA_ARTICULO] PRIMARY KEY CLUSTERED ([CO_FAM_ART_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_FAMILIA_ARTICULO] ADD CONSTRAINT [FK_CO_FAMILIA_ARTICULO_CO_TIPO_ARTICULO1] FOREIGN KEY ([CO_TIP_ART_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_TIPO_ARTICULO] ([CO_TIP_ART_COD], [CO_EMP_RUC]) ON UPDATE CASCADE
GO
