CREATE TABLE [dbo].[CO_DOCUMENTO_PAGO_PROVEEDORES]
(
[CODIGO_DOCUMENTO_PAGO] [int] NOT NULL,
[CO_PRO_COD] [uniqueidentifier] NULL,
[CO_EMP_RUC] [nchar] (13) COLLATE Modern_Spanish_CI_AS NULL,
[FECHA_DOCUMENTO_PAGO] [datetime] NULL,
[VALOR_TOTAL_DOCUMENTO_PAGO] [decimal] (18, 2) NULL,
[ESTADO_DOCUMENTO_PAGO] [nvarchar] (9) COLLATE Modern_Spanish_CI_AS NULL,
[PAGADO_PENDIENTE_FORMA_PAGO] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[USUARIO_NOMBRE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DOCUMENTO_PAGO_PROVEEDORES] ADD CONSTRAINT [PK_CO_DOCUMENTO_PAGO_PROVEEDORES] PRIMARY KEY CLUSTERED ([CODIGO_DOCUMENTO_PAGO]) ON [PRIMARY]
GO
