CREATE TABLE [dbo].[CO_TIPO_RECURSO]
(
[CO_TIP_REC_COD] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_REC_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_RECURSO] ADD CONSTRAINT [PK_CO_TIPO_RECURSO] PRIMARY KEY CLUSTERED ([CO_TIP_REC_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_RECURSO] ADD CONSTRAINT [FK_CO_TIPO_RECURSO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
