CREATE TABLE [dbo].[CO_TIPO_ACTIVO]
(
[CO_TIP_ACT_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CUE_COD] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_ACT_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD_DEP] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_ACT_POR] [float] NOT NULL,
[CO_TIP_ACT_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_ACT_TIE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_ACTIVO] ADD CONSTRAINT [PK_CO_TIPO_ACTIVO] PRIMARY KEY CLUSTERED ([CO_TIP_ACT_COD]) ON [PRIMARY]
GO
