CREATE TABLE [dbo].[CO_PROYECTO_INGRESOS]
(
[CO_PRO_COD] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_REC_COD] [int] NOT NULL,
[CO_ING_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_PRO_TIP] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ING_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ING_MAN] [bit] NULL,
[CO_ING_CUE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PROYECTO_INGRESOS] ADD CONSTRAINT [PK_CO_PROYECTO_INGRESOS] PRIMARY KEY CLUSTERED ([CO_PRO_COD], [CO_EMP_RUC], [CO_TIP_REC_COD], [CO_ING_COD], [CO_PRO_TIP]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PROYECTO_INGRESOS] ADD CONSTRAINT [FK_CO_PROYECTO_INGRESOS_CO_PROYECTO] FOREIGN KEY ([CO_PRO_COD], [CO_EMP_RUC], [CO_PRO_TIP]) REFERENCES [dbo].[CO_PROYECTO] ([CO_PRO_COD], [CO_EMP_RUC], [CO_PRO_TIP])
GO
ALTER TABLE [dbo].[CO_PROYECTO_INGRESOS] ADD CONSTRAINT [FK_CO_PROYECTO_INGRESOS_CO_TIPO_RECURSO] FOREIGN KEY ([CO_TIP_REC_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_TIPO_RECURSO] ([CO_TIP_REC_COD], [CO_EMP_RUC])
GO
