CREATE TABLE [dbo].[CO_ACTIVO_FIJO]
(
[CO_ACT_FIJ_COD] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_COD] [int] NOT NULL,
[CO_TIP_ACT_COD] [int] NOT NULL,
[CO_BAN_COD] [int] NULL,
[CO_ACT_FIJ_NOM] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ACT_FIJ_SER] [char] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_FIJ_FEC_COM] [datetime] NOT NULL,
[CO_ACT_FIJ_NUM_FAC] [varchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_FIJ_NUM_CHE] [varchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_FIJ_NOM_PRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_FIJ_ARE] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_FIJ_DEP] [bit] NOT NULL,
[CO_ACT_FIJ_VAL_ADQ] [float] NOT NULL,
[CO_ACT_FIJ_DEP_ACU] [float] NULL,
[CO_ACT_FIJ_VAL_ACT] [float] NULL,
[CO_ACT_FIJ_FEC_INI] [datetime] NOT NULL,
[CO_ACT_FIJ_FEC_FIN] [datetime] NOT NULL,
[CO_ACT_FIJ_EST] [bit] NOT NULL,
[CO_ACT_FIJ_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ACT_FIJ_FUN_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_FIJ_CAN] [int] NULL,
[CO_ACT_FIJ_COD_PRO] [nchar] (13) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ACTIVO_FIJO] ADD CONSTRAINT [PK_CO_ACTIVO_FIJO_1] PRIMARY KEY CLUSTERED ([CO_ACT_FIJ_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ACTIVO_FIJO] ADD CONSTRAINT [FK_CO_ACTIV_COMPRA_CO_BANCO] FOREIGN KEY ([CO_BAN_COD]) REFERENCES [dbo].[CO_BANCO] ([CO_BAN_COD])
GO
ALTER TABLE [dbo].[CO_ACTIVO_FIJO] ADD CONSTRAINT [FK_CO_ACTIVO_FIJO_CO_TIPO_ACTIVO] FOREIGN KEY ([CO_TIP_ACT_COD]) REFERENCES [dbo].[CO_TIPO_ACTIVO] ([CO_TIP_ACT_COD])
GO
ALTER TABLE [dbo].[CO_ACTIVO_FIJO] ADD CONSTRAINT [FK_CO_ACTIVO_FIJO_CO_UBICACION_AF1] FOREIGN KEY ([CO_EMP_RUC], [CO_UBI_COD]) REFERENCES [dbo].[CO_UBICACION_AF] ([CO_EMP_RUC], [CO_UBI_COD])
GO
