CREATE TABLE [dbo].[CO_RUBROS_ROL]
(
[CO_RUB_ROL_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_NOM] [nvarchar] (60) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_TIP] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_VAL] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_REN] [bit] NOT NULL,
[CO_RUB_USU_ALI] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_FOR] [nvarchar] (200) COLLATE Modern_Spanish_CI_AS NULL,
[CO_RUB_ROL_IES] [bit] NULL,
[CO_TIP_RUB_COD] [int] NOT NULL,
[CO_RUB_ROL_AFE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_RUBROS_ROL] ADD CONSTRAINT [PK_CO_RUBROS_ROL] PRIMARY KEY CLUSTERED ([CO_RUB_ROL_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_RUBROS_ROL] ADD CONSTRAINT [FK_CO_RUBROS_ROL_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_RUBROS_ROL] ADD CONSTRAINT [FK_CO_RUBROS_ROL_CO_TIPO_RUBRO] FOREIGN KEY ([CO_TIP_RUB_COD]) REFERENCES [dbo].[CO_TIPO_RUBRO] ([CO_TIP_RUB_COD])
GO
