CREATE TABLE [dbo].[CO_PERTENECE]
(
[USUA_COD] [uniqueidentifier] NOT NULL,
[CO_GRU_COD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PERTENECE] ADD CONSTRAINT [PK_CO_PERTENECE] PRIMARY KEY CLUSTERED ([USUA_COD], [CO_GRU_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PERTENECE] ADD CONSTRAINT [FK_CO_PERTENECE_CO_GRUPO] FOREIGN KEY ([CO_GRU_COD]) REFERENCES [dbo].[CO_GRUPO] ([CO_GRU_COD])
GO
ALTER TABLE [dbo].[CO_PERTENECE] ADD CONSTRAINT [FK_CO_PERTENECE_USUARIO] FOREIGN KEY ([USUA_COD]) REFERENCES [dbo].[CO_USUARIO] ([USUA_COD])
GO
