CREATE TABLE [dbo].[CO_DETALLE_COBRO_CLIENTE]
(
[CO_DET_COB_CLI_COD] [uniqueidentifier] NOT NULL,
[CO_COM_COD_CLI_ID] [uniqueidentifier] NOT NULL,
[CO_DOC_VEN_ID] [uniqueidentifier] NOT NULL,
[CO_DET_COB_CLI_CON] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_COB_CLI_VAL] [float] NULL,
[CO_DET_COB_CLI_FEC] [datetime] NULL,
[CO_PAG_DOC_VEN_COD] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_COBRO_CLIENTE] ADD CONSTRAINT [PK_CO_DETALLE_COBRO_CLIENTE_1] PRIMARY KEY CLUSTERED ([CO_DET_COB_CLI_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_COBRO_CLIENTE] ADD CONSTRAINT [FK_CO_DETALLE_COBRO_CLIENTE_CO_COBRO_CLIENTE] FOREIGN KEY ([CO_COM_COD_CLI_ID]) REFERENCES [dbo].[CO_COBRO_CLIENTE] ([CO_COM_COD_CLI_ID])
GO
ALTER TABLE [dbo].[CO_DETALLE_COBRO_CLIENTE] ADD CONSTRAINT [FK_CO_DETALLE_COBRO_CLIENTE_CO_DOCUMENTO_VENTA] FOREIGN KEY ([CO_DOC_VEN_ID]) REFERENCES [dbo].[CO_DOCUMENTO_VENTA] ([CO_DOC_VEN_ID])
GO
