CREATE TABLE [dbo].[CO_CUENTA_POR_PAGAR_DETALLE]
(
[CO_CUE_PAG_DET_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_DOC_COM_NUM] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_PAG_COD] [int] NOT NULL,
[CO_CUE_PAG_DET_VAL] [float] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CUENTA_POR_PAGAR_DETALLE] ADD CONSTRAINT [PK_CO_CUENTA_POR_PAGAR_DETALLE] PRIMARY KEY CLUSTERED ([CO_CUE_PAG_DET_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CUENTA_POR_PAGAR_DETALLE] ADD CONSTRAINT [FK_CO_CUENTA_POR_PAGAR_DETALLE_CO_CUENTA_POR_PAGAR] FOREIGN KEY ([CO_CUE_PAG_COD]) REFERENCES [dbo].[CO_CUENTA_POR_PAGAR] ([CO_CUE_PAG_COD])
GO
