CREATE TABLE [dbo].[CO_UBICACION_GEOGRAFICA]
(
[CO_UBI_GEO_COD] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_GEO_DIV] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_GEO_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_UBICACION_GEOGRAFICA] ADD CONSTRAINT [PK_CO_UBICACION_GEOGRAFICA] PRIMARY KEY CLUSTERED ([CO_UBI_GEO_COD]) ON [PRIMARY]
GO
