CREATE TABLE [dbo].[CO_TIPO_COMPROBANTE]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_COM_COD] [int] NOT NULL,
[CO_TIP_COM_NOM] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_COM_INI] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_COMPROBANTE] ADD CONSTRAINT [PK_CO_TIPO_COMPROBANTE] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_TIP_COM_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_COMPROBANTE] ADD CONSTRAINT [FK_CO_TIPO__POSEE_CO_EMPRE] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
