CREATE TABLE [dbo].[CO_TABLA_PRECIO]
(
[ListaDePrecioID] [uniqueidentifier] NOT NULL,
[CO_ART_COD] [uniqueidentifier] NOT NULL,
[CO_TAB_PRE] [float] NOT NULL,
[CO_TAB_PRE_POR_ART] [float] NOT NULL,
[CO_TAB_PRE_MIN] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TABLA_PRECIO] ADD CONSTRAINT [PK_CO_TABLA_PRECIO] PRIMARY KEY CLUSTERED ([ListaDePrecioID], [CO_ART_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TABLA_PRECIO] ADD CONSTRAINT [FK_CO_TABLA_PRECIO_CO_ARTICULO] FOREIGN KEY ([CO_ART_COD]) REFERENCES [dbo].[CO_ARTICULO] ([CO_ART_COD])
GO
ALTER TABLE [dbo].[CO_TABLA_PRECIO] ADD CONSTRAINT [FK_CO_TABLA_PRECIO_CO_LISTA_PRECIO] FOREIGN KEY ([ListaDePrecioID]) REFERENCES [dbo].[CO_LISTA_PRECIO] ([ListaDePrecioID])
GO
