CREATE TABLE [dbo].[CO_COMPROBANTE_PAGO]
(
[CO_COM_PAG_NUM] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_PRO_COD] [uniqueidentifier] NULL,
[CO_COM_PAG_CON] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_PAG_FEC] [datetime] NULL,
[CO_COM_PAG_EST] [bit] NOT NULL,
[CO_COM_PAG_USU_ALI] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_PAG_EFE] [bit] NULL,
[CO_COM_PAG_EFE_VAL] [float] NULL,
[CO_COM_PAG_CHE] [bit] NULL,
[CO_COM_PAG_CHE_VAL] [float] NULL,
[CO_COM_PAG_VAL] [float] NULL,
[CO_COM_PAG_TRA] [bit] NULL,
[CO_COM_PAG_TRA_VAL] [float] NULL,
[CO_COM_PAG_TRA_DOC_NUM] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_PAG_TAR] [bit] NULL,
[CO_COM_PAG_TAR_VAL] [float] NULL,
[CO_COM_PAG_TAR_NUM] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_PAG_TAR_VAU] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_PAG_TAR_NOM] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COMPROBANTE_PAGO] ADD CONSTRAINT [PK_CO_COMPROBANTE_PAGO_1] PRIMARY KEY CLUSTERED ([CO_COM_PAG_NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COMPROBANTE_PAGO] ADD CONSTRAINT [FK_CO_COMPROBANTE_PAGO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_COMPROBANTE_PAGO] ADD CONSTRAINT [FK_CO_COMPROBANTE_PAGO_CO_PROVEEDOR] FOREIGN KEY ([CO_PRO_COD]) REFERENCES [dbo].[CO_PROVEEDOR] ([CO_PRO_COD])
GO
