CREATE TABLE [dbo].[CO_DETALLE_DOCUMENTO_COMPRA]
(
[CO_DET_DOC_COM_COD] [uniqueidentifier] NOT NULL,
[CO_DOC_COM_ID] [uniqueidentifier] NOT NULL,
[CO_DET_DOC_COM_ART_COD] [nvarchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_DET_DOC_COM_ART_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_DOC_COM_CAN] [float] NULL,
[CO_DET_DOC_COM_PRE] [float] NULL,
[CO_DET_DOC_COM_DES] [float] NULL,
[CO_DET_DOC_COM_VAL_ICE] [float] NULL,
[CO_DET_DOC_COM_IVA] [float] NULL,
[CO_DET_DOC_COM_TOT] [float] NULL,
[CO_DET_DOC_COM_TIP_ART] [bit] NULL,
[CO_DET_DOC_COM_POR_ICE] [float] NULL,
[CO_DET_DOC_COM_POR_IVA] [float] NULL,
[CO_DET_DOC_COM_ART_BAR] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CORRE_INV_DET_COM] [bit] NULL,
[CO_BOD_COD] [int] NULL,
[CO_BOD_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CANTIDAD_EMPAQUE] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_DOCUMENTO_COMPRA] ADD CONSTRAINT [PK_CO_DETALLE_DOCUMENTO_COMPRA] PRIMARY KEY CLUSTERED ([CO_DET_DOC_COM_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_DOCUMENTO_COMPRA] ADD CONSTRAINT [FK_CO_DETALLE_DOCUMENTO_COMPRA_CO_DOCUMENTO_COMPRA] FOREIGN KEY ([CO_DOC_COM_ID]) REFERENCES [dbo].[CO_DOCUMENTO_COMPRA] ([CO_DOC_COM_ID])
GO
