CREATE TABLE [dbo].[CO_TIPO_PROVEEDOR]
(
[CO_TIP_PRO_COD] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_PRO_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_PRO_CUE_CON] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_PROVEEDOR] ADD CONSTRAINT [PK_CO_TIPO_PROVEEDOR] PRIMARY KEY CLUSTERED ([CO_TIP_PRO_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_PROVEEDOR] ADD CONSTRAINT [FK_CO_TIPO_PROVEEDOR_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
