CREATE TABLE [dbo].[CO_ALMACEN]
(
[CO_ALM_COD] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ALM_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ALMACEN] ADD CONSTRAINT [PK_CO_ALMACEN_1] PRIMARY KEY CLUSTERED ([CO_ALM_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ALMACEN] ADD CONSTRAINT [FK_CO_ALMACEN_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
