CREATE TABLE [dbo].[CO_KARDEX_TOTAL]
(
[CO_KAR_TOT_COD] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ART_COD] [uniqueidentifier] NOT NULL,
[CO_BOD_COD] [uniqueidentifier] NOT NULL,
[CO_KAR_TOT_FEC] [datetime] NOT NULL,
[CO_KAR_TOT_DOC] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_KAR_TOT_TIP_DOC] [int] NULL,
[CO_KAR_TOT_ENT_CANT] [float] NULL,
[CO_KAR_TOT_ENT_VAL_UNI] [float] NULL,
[CO_KAR_TOT_ENT_VAL_TOT] [float] NULL,
[CO_KAR_TOT_SAL_CANT] [float] NULL,
[CO_KAR_TOT_SAL_VAL_UNI] [float] NULL,
[CO_KAR_TOT_SAL_VAL_TOT] [float] NULL,
[CO_KAR_TOT_EXI_CANT] [float] NULL,
[CO_KAR_TOT_EXI_VAL_UNI] [float] NULL,
[CO_KAR_TOT_EXI_VAL_TOT] [float] NULL,
[CO_KAR_TOT_EST] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_KAR_TOT_DET] [nvarchar] (70) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_KARDEX_TOTAL] ADD CONSTRAINT [PK_CO_KARDEX_TOTAL] PRIMARY KEY CLUSTERED ([CO_KAR_TOT_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_KARDEX_TOTAL] ADD CONSTRAINT [FK_CO_KARDEX_TOTAL_CO_UBICACIONARTICULO] FOREIGN KEY ([CO_ART_COD], [CO_BOD_COD]) REFERENCES [dbo].[CO_UBICACIONARTICULO] ([CO_ART_COD], [CO_BOD_COD])
GO
