CREATE TABLE [dbo].[CO_GUIA_REMISION]
(
[CO_DOC_VEN_GUI_COD] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_DOC_VEN_ID] [uniqueidentifier] NOT NULL,
[CO_DOC_VEN_GUI_NUM] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DOC_VEN_GUI_FEC_INI] [datetime] NULL,
[CO_DOC_VEN_GUI_FEC_TER] [datetime] NULL,
[CO_DOC_VEN_GUI_DES] [varchar] (300) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DOC_VEN_GUI_TIP] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DOC_VEN_GUI_NOM_TRA] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DOC_VEN_GUI_IDE] [nvarchar] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DOC_VEN_GUI_PLACA] [varchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ESTADO] [int] NOT NULL,
[CO_DOC_VEN_GUI_FEC_REG] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_GUIA_REMISION] ADD CONSTRAINT [PK_CO_GUIA_REMISION] PRIMARY KEY CLUSTERED ([CO_DOC_VEN_GUI_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_GUIA_REMISION] ADD CONSTRAINT [FK_CO_GUIA_REMISION_CO_DOCUMENTO_VENTA] FOREIGN KEY ([CO_DOC_VEN_ID]) REFERENCES [dbo].[CO_DOCUMENTO_VENTA] ([CO_DOC_VEN_ID])
GO
ALTER TABLE [dbo].[CO_GUIA_REMISION] ADD CONSTRAINT [FK_CO_GUIA_REMISION_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
