CREATE TABLE [dbo].[CO_RUBRO_EMPLEADO]
(
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_COD] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_EMP_VAL] [float] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_RUBRO_EMPLEADO] ADD CONSTRAINT [PK_CO_RUBRO_EMPLEADO] PRIMARY KEY CLUSTERED ([PROF_COD], [CO_RUB_ROL_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_RUBRO_EMPLEADO] ADD CONSTRAINT [FK_CO_RUBRO_EMPLEADO_CO_RUBROS_ROL] FOREIGN KEY ([CO_RUB_ROL_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_RUBROS_ROL] ([CO_RUB_ROL_COD], [CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_RUBRO_EMPLEADO] ADD CONSTRAINT [FK_CO_RUBRO_EMPLEADO_PROFESOR] FOREIGN KEY ([PROF_COD]) REFERENCES [dbo].[PROFESOR] ([PROF_COD])
GO
