CREATE TABLE [dbo].[CO_MES_SALDO]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_MES_NUM] [int] NOT NULL,
[CO_ANIO_NUM] [int] NOT NULL,
[CO_MES_SAL_ACT] [float] NOT NULL,
[CO_MES_SAL_DEB] [float] NOT NULL,
[CO_MES_SAL_HAB] [float] NOT NULL,
[CO_MES_SAL_ANT] [float] NOT NULL,
[CO_CUE_COD_ANT] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MES_SALDO] ADD CONSTRAINT [PK_CO_MES_SALDO] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_CUE_COD], [CO_MES_NUM], [CO_ANIO_NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MES_SALDO] ADD CONSTRAINT [FK_CO_MES_SALDO_CO_MES] FOREIGN KEY ([CO_MES_NUM], [CO_ANIO_NUM], [CO_EMP_RUC]) REFERENCES [dbo].[CO_MES] ([CO_MES_NUM], [CO_ANIO_NUM], [CO_EMP_RUC])
GO
