CREATE TABLE [dbo].[CO_NOTIFICACIONES_STOCK]
(
[CO_NOT_STO_COD] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[CO_ART_COD] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_NOT_STO_COD] [numeric] (18, 0) NULL,
[USUA_COD] [uniqueidentifier] NULL,
[CO_NOT_STO_DET] [nvarchar] (200) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_NOT_STO_FEC] [datetime] NULL,
[CO_NOT_STO_ATE] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_NOTIFICACIONES_STOCK] ADD CONSTRAINT [PK_CO_NOTIFICACIONES_STOCK] PRIMARY KEY CLUSTERED ([CO_NOT_STO_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_NOTIFICACIONES_STOCK] ADD CONSTRAINT [FK_CO_NOTIF_GENERA_USUARIO] FOREIGN KEY ([USUA_COD]) REFERENCES [dbo].[CO_USUARIO] ([USUA_COD])
GO
ALTER TABLE [dbo].[CO_NOTIFICACIONES_STOCK] ADD CONSTRAINT [FK_CO_NOTIF_TIENE_CO_TIPO_] FOREIGN KEY ([CO_TIP_NOT_STO_COD]) REFERENCES [dbo].[CO_TIPO_NOTIFICACIONES_STOCK] ([CO_TIP_NOT_STO_COD])
GO
