CREATE TABLE [dbo].[CO_CUENTA_CORRIENTE]
(
[CO_CC_NUM] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_BAN_COD] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CC_NOM] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CC_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CC_FEC] [datetime] NOT NULL,
[CO_CC_SAL_INI] [float] NULL,
[CO_CC_SAL_LIB] [float] NULL,
[CO_CC_NUM_CHE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CUENTA_CORRIENTE] ADD CONSTRAINT [PK_CO_CUENTA_CORRIENTE] PRIMARY KEY CLUSTERED ([CO_CC_NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CUENTA_CORRIENTE] ADD CONSTRAINT [FK_CO_CUENT_REALIZA_CO_BANCO] FOREIGN KEY ([CO_BAN_COD]) REFERENCES [dbo].[CO_BANCO] ([CO_BAN_COD])
GO
