CREATE TABLE [dbo].[CO_ESTANDAR_ITEM]
(
[CO_ITE_EST_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_ITE_EST_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ITE_EST_DES] [nvarchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ITE_EST_CUE] [bit] NOT NULL,
[CO_ITE_EST_CUE_CON] [nvarchar] (200) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ITE_EST_TIP] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ITE_EST_COD_PAD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ESTANDAR_ITEM] ADD CONSTRAINT [PK_CO_ITEM_ESTANDAR] PRIMARY KEY CLUSTERED ([CO_ITE_EST_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ESTANDAR_ITEM] ADD CONSTRAINT [FK_CO_ESTANDAR_ITEM_CO_ESTANDAR_ITEM] FOREIGN KEY ([CO_ITE_EST_COD_PAD]) REFERENCES [dbo].[CO_ESTANDAR_ITEM] ([CO_ITE_EST_COD])
GO
