CREATE TABLE [dbo].[CO_DETALLE_PROFORMA]
(
[CO_DET_PRO_COD] [uniqueidentifier] NOT NULL,
[CO_PRO_COD] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_DET_PRO_ART_COD] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_PRO_ART_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_PRO_CAN] [int] NULL,
[CO_DET_PRO_PRE] [float] NULL,
[CO_DET_PRO_DES] [float] NULL,
[CO_DET_PRO_TOT] [float] NULL,
[CO_DET_PRO_TIP_ART] [bit] NULL,
[CO_DET_PRO_IVA] [float] NULL,
[CO_DET_PRO_CAN_EXI] [int] NULL,
[CO_DET_PRO_TIP_PRE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_PRO_ART_BAR] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CANTIDAD_PROCESADA] [float] NULL,
[ESTADO] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CANTIDAD_FACTURAR] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_PROFORMA] ADD CONSTRAINT [PK_CO_DETALLE_PROFORMA] PRIMARY KEY CLUSTERED ([CO_DET_PRO_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_PROFORMA] ADD CONSTRAINT [FK_CO_DETALLE_PROFORMA_CO_PROFORMA] FOREIGN KEY ([CO_PRO_COD]) REFERENCES [dbo].[CO_PROFORMA] ([CO_PRO_COD])
GO
