CREATE TABLE [dbo].[CO_UBICACIONARTICULO]
(
[CO_ART_COD] [uniqueidentifier] NOT NULL,
[CO_BOD_COD] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_UBICACIONARTICULO] ADD CONSTRAINT [PK_CO_UBICACIONARTICULO] PRIMARY KEY CLUSTERED ([CO_ART_COD], [CO_BOD_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_UBICACIONARTICULO] ADD CONSTRAINT [FK_CO_UBICACIONARTICULO_CO_ARTICULO] FOREIGN KEY ([CO_ART_COD]) REFERENCES [dbo].[CO_ARTICULO] ([CO_ART_COD])
GO
ALTER TABLE [dbo].[CO_UBICACIONARTICULO] ADD CONSTRAINT [FK_CO_UBICACIONARTICULO_CO_BODEGA] FOREIGN KEY ([CO_BOD_COD]) REFERENCES [dbo].[CO_BODEGA] ([CO_BOD_COD])
GO
