CREATE TABLE [dbo].[CO_PEDIDO]
(
[CO_PED_COD] [numeric] (18, 0) NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_PRO_COD] [uniqueidentifier] NULL,
[USUA_COD] [uniqueidentifier] NULL,
[CO_PED_DET] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PED_FEC] [datetime] NULL,
[CO_PED_AUT] [nvarchar] (25) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PED_EST] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PEDIDO] ADD CONSTRAINT [PK_CO_PEDIDO] PRIMARY KEY CLUSTERED ([CO_PED_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PEDIDO] ADD CONSTRAINT [FK_CO_PEDID_REALIZA_CO_EMPRE] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_PEDIDO] ADD CONSTRAINT [FK_CO_PEDID_RECIBE_CO_PROVE] FOREIGN KEY ([CO_PRO_COD]) REFERENCES [dbo].[CO_PROVEEDOR] ([CO_PRO_COD])
GO
ALTER TABLE [dbo].[CO_PEDIDO] ADD CONSTRAINT [FK_CO_PEDID_RLSH_1_USUARIO] FOREIGN KEY ([USUA_COD]) REFERENCES [dbo].[CO_USUARIO] ([USUA_COD])
GO
