CREATE TABLE [dbo].[CO_CADUCIDAD]
(
[CO_ART_COD] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DOC_COM_NUM] [int] NULL,
[CO_CAD_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_CAD_FEC_ELA] [datetime] NULL,
[CO_CAD_FEC_FIN] [datetime] NULL,
[CO_CAD_LOT] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CAD_EST] [bit] NULL,
[CO_CAD_CAN] [int] NULL,
[CO_CAD_LOC] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CADUCIDAD] ADD CONSTRAINT [PK_CO_CADUCIDAD] PRIMARY KEY CLUSTERED ([CO_CAD_COD]) ON [PRIMARY]
GO
