CREATE TABLE [dbo].[CO_DETALLE_GUIA_REMISION]
(
[CO_DET_GUI_REM_COD] [uniqueidentifier] NOT NULL,
[CO_DOC_VEN_GUI_COD] [uniqueidentifier] NOT NULL,
[CO_DET_GUI_REM_CAN] [int] NULL,
[CO_DET_GUI_REM_DES] [nvarchar] (500) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_GUIA_REMISION] ADD CONSTRAINT [PK_CO_DETALLE_GUIA_REMISION] PRIMARY KEY CLUSTERED ([CO_DET_GUI_REM_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_GUIA_REMISION] ADD CONSTRAINT [FK_CO_DETALLE_GUIA_REMISION_CO_DETALLE_GUIA_REMISION] FOREIGN KEY ([CO_DOC_VEN_GUI_COD]) REFERENCES [dbo].[CO_GUIA_REMISION] ([CO_DOC_VEN_GUI_COD])
GO
