CREATE TABLE [dbo].[CO_CENTRO_COSTO]
(
[CO_CEN_COS_COD] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CEN_COS_DES] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CENTRO_COSTO] ADD CONSTRAINT [PK_CO_CENTRO_COSTO] PRIMARY KEY CLUSTERED ([CO_CEN_COS_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CENTRO_COSTO] ADD CONSTRAINT [FK_CO_CENTRO_COSTO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
