CREATE TABLE [dbo].[CO_PAGO_DOCUMENTO_VENTA]
(
[CO_PAG_DOC_VEN_COD] [uniqueidentifier] NOT NULL,
[CO_DOC_VEN_ID] [uniqueidentifier] NOT NULL,
[CO_PAG_DOC_VEN_VAL] [float] NOT NULL,
[CO_PAG_DOC_VEN_FEC] [datetime] NOT NULL,
[CO_PAG_DOC_VEN_EST] [bit] NULL,
[CO_PAG_DOC_VEN_CON] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAG_DOC_VEN_VAL_IMP] [float] NULL,
[NUMERO_TEMP] [int] NULL,
[TIPO_TEMP] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PAGO_DOCUMENTO_VENTA] ADD CONSTRAINT [PK_CO_PAGO_DOCUMENTO_VENTA] PRIMARY KEY CLUSTERED ([CO_PAG_DOC_VEN_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PAGO_DOCUMENTO_VENTA] ADD CONSTRAINT [FK_CO_PAGO_DOCUMENTO_VENTA_CO_DOCUMENTO_VENTA] FOREIGN KEY ([CO_DOC_VEN_ID]) REFERENCES [dbo].[CO_DOCUMENTO_VENTA] ([CO_DOC_VEN_ID])
GO
