CREATE TABLE [dbo].[CO_PERMISO]
(
[PERM_COD] [uniqueidentifier] NOT NULL,
[CO_MENU_ID] [uniqueidentifier] NOT NULL,
[USUA_COD] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PERMISO] ADD CONSTRAINT [PK_PERMISO] PRIMARY KEY CLUSTERED ([PERM_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PERMISO] ADD CONSTRAINT [FK_CO_PERMISO_CO_MENU] FOREIGN KEY ([CO_MENU_ID]) REFERENCES [dbo].[CO_MENU] ([CO_MENU_ID])
GO
ALTER TABLE [dbo].[CO_PERMISO] ADD CONSTRAINT [FK_CO_PERMISO_CO_USUARIO] FOREIGN KEY ([USUA_COD]) REFERENCES [dbo].[CO_USUARIO] ([USUA_COD])
GO
