CREATE TABLE [dbo].[CO_COBRO_CLIENTE]
(
[CO_COM_COD_CLI_ID] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CLI_COD] [uniqueidentifier] NULL,
[CO_COM_COB_CLI_NUM] [int] NOT NULL,
[CO_COM_COB_CLI_FEC] [datetime] NULL,
[CO_COM_COB_CLI_CON] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_VAL] [float] NULL,
[CO_COM_COB_CLI_EST] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_COM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_USU_ALI] [nvarchar] (14) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_FOR_COB] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_EFE] [bit] NULL,
[CO_COM_COB_CLI_EFE_VAL] [float] NULL,
[CO_COM_COB_CLI_CHE] [bit] NULL,
[CO_COM_COB_CLI_CHE_VAL] [float] NULL,
[CO_COM_COB_CLI_CHE_NUM] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_CHE_BAN] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_TAR] [bit] NULL,
[CO_COM_COB_CLI_TAR_VAL] [float] NULL,
[CO_COM_COB_CLI_TAR_NUM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_TAR_VAU] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_COB_CLI_CHE_FEC] [datetime] NULL,
[CO_COM_COB_TRA] [bit] NULL,
[CO_COM_COB_TRA_VAL] [float] NULL,
[CO_COM_COB_TRA_DOC_NUM] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COBRO_CLIENTE] ADD CONSTRAINT [PK_CO_COBRO_CLIENTE_1] PRIMARY KEY CLUSTERED ([CO_COM_COD_CLI_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COBRO_CLIENTE] ADD CONSTRAINT [FK_CO_COBRO_CLIENTE_CO_CLIENTE] FOREIGN KEY ([CO_CLI_COD]) REFERENCES [dbo].[CO_CLIENTE] ([CO_CLI_COD])
GO
