CREATE TABLE [dbo].[CO_PARAMETRO_NOMINA]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_PAR_NOM_NOT_DEB_TIP_COM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_NOT_DEB_TIP_COM_COD] [int] NULL,
[CO_PAR_NOM_NOT_DEB_MOD_FEC] [bit] NULL,
[CO_PAR_NOM_NOT_DEB_MOD_NUM] [bit] NULL,
[CO_PAR_NOM_REG_HOR_ING] [nchar] (5) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_REG_HOR_SAL] [nchar] (5) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_REG_MIN_DES] [nchar] (5) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_REG_TIE_LUN] [nchar] (5) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_ROL_RUB_SUE] [int] NULL,
[CO_PAR_NOM_NOT_DEB_CUE_DEB] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_NOT_DEB_CUE_HAB_EFE] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_ROL_TIP_COM_COD] [int] NULL,
[CO_PAR_NOM_ROL_CUE_HAB_EFE] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_ROL_CUE_SUE_PAG] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAR_NOM_NOT_DEB_ASI_AUT] [bit] NULL,
[CO_PAR_NOM_ROL_ASI_AUT] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PARAMETRO_NOMINA] ADD CONSTRAINT [PK_CO_PARAMETRO_NOMINA] PRIMARY KEY CLUSTERED ([CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PARAMETRO_NOMINA] ADD CONSTRAINT [FK_CO_PARAMETRO_NOMINA_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
