CREATE TABLE [dbo].[CO_PROYECTO]
(
[CO_PRO_COD] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_PRO_NOM] [nvarchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PRO_DES] [nvarchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PRO_TIP] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PROYECTO] ADD CONSTRAINT [PK_CO_PROYECTO] PRIMARY KEY CLUSTERED ([CO_PRO_COD], [CO_EMP_RUC], [CO_PRO_TIP]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PROYECTO] ADD CONSTRAINT [FK_CO_PROYECTO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
