CREATE TABLE [dbo].[CO_PAGO_PROVEEDORES_PLUS]
(
[CODIGO_PAGO_PROVEEDOR] [int] NOT NULL,
[CODIGO_DOCUMENTO_PAGO] [int] NULL,
[FORMA_PAGO_PROVEEDOR] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[NUMERO_PAGO_PROVEEDOR] [nvarchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CC_NUM] [varchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[VALOR_PAGO_PROVEEDOR] [decimal] (18, 2) NULL,
[FECHA_PAGO_PROVEEDOR] [datetime] NULL,
[ESTADO_PAGO_PROVEEDOR] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[USUARIO_NOMBRE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PRO_COD] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[VALOR_PAGADO_EN_NUMEROS] [nvarchar] (max) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PAGO_PROVEEDORES_PLUS] ADD CONSTRAINT [PK_CO_PAGO_PROVEEDORES_PLUS] PRIMARY KEY CLUSTERED ([CODIGO_PAGO_PROVEEDOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PAGO_PROVEEDORES_PLUS] ADD CONSTRAINT [FK_CO_PAGO_PROVEEDORES_PLUS_CO_DOCUMENTO_PAGO_PROVEEDORES] FOREIGN KEY ([CODIGO_DOCUMENTO_PAGO]) REFERENCES [dbo].[CO_DOCUMENTO_PAGO_PROVEEDORES] ([CODIGO_DOCUMENTO_PAGO])
GO
