CREATE TABLE [dbo].[CO_ROL_TEMP]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_COD] [int] NOT NULL,
[CO_RUB_ROL_VAL] [float] NULL,
[CO_MES] [int] NULL,
[CO_ANIO] [int] NULL,
[CO_RUB_ROL_TIP] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ROL_TEMP] ADD CONSTRAINT [PK_CO_ROL_TEMP] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [PROF_COD], [CO_RUB_ROL_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ROL_TEMP] ADD CONSTRAINT [FK_CO_ROL_TEMP_CO_RUBROS_ROL] FOREIGN KEY ([CO_RUB_ROL_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_RUBROS_ROL] ([CO_RUB_ROL_COD], [CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_ROL_TEMP] ADD CONSTRAINT [FK_CO_ROL_TEMP_PROFESOR] FOREIGN KEY ([PROF_COD]) REFERENCES [dbo].[PROFESOR] ([PROF_COD])
GO
