CREATE TABLE [dbo].[CO_MES]
(
[CO_MES_NUM] [int] NOT NULL,
[CO_ANIO_NUM] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_MES_EST] [bit] NOT NULL,
[CO_MES_USU_ALI] [varchar] (13) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MES] ADD CONSTRAINT [PK_CO_MES] PRIMARY KEY CLUSTERED ([CO_MES_NUM], [CO_ANIO_NUM], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MES] ADD CONSTRAINT [FK_CO_MES_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
