CREATE TABLE [dbo].[CO_NOTA_DEBITO]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_NOT_DEB_NUM] [int] NOT NULL,
[CO_NOT_DEB_FEC] [datetime] NOT NULL,
[CO_NOT_DEB_EST] [bit] NOT NULL,
[CO_NOT_DEB_CON] [nvarchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_NOT_DEB_COM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_NOT_DEB_USU_ALI] [nvarchar] (14) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_NOT_DEB_SUB] [float] NULL,
[CO_NOT_DEB_DES] [float] NULL,
[CO_NOT_DEB_TOT] [float] NULL,
[CO_COM_NUM] [int] NOT NULL,
[CO_TIP_COM_COD] [int] NOT NULL,
[CO_NOT_DEB_FOR_PAG] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_NOT_DEB_EFE] [bit] NULL,
[CO_NOT_DEB_EFE_VAL] [float] NULL,
[CO_NOT_DEB_CHE] [bit] NULL,
[CO_NOT_DEB_CHE_VAL] [float] NULL,
[CO_NOT_DEB_CHE_NUM] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_NOT_DEB_CUE_NUM] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_NOT_DEB_NUM_PAG] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_NOTA_DEBITO] ADD CONSTRAINT [PK_CO_NOTA_DEBITO] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_NOT_DEB_NUM], [PROF_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_NOTA_DEBITO] ADD CONSTRAINT [FK_CO_NOTA_DEBITO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_NOTA_DEBITO] ADD CONSTRAINT [FK_CO_NOTA_DEBITO_PROFESOR] FOREIGN KEY ([PROF_COD]) REFERENCES [dbo].[PROFESOR] ([PROF_COD])
GO
