CREATE TABLE [dbo].[CO_TIPO_RETENCION]
(
[CO_TIP_RET_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD_COM] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_RET_NOM] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_RET_POR] [float] NOT NULL,
[CO_TIP_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD_VEN] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_RET_COD_SRI] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_RETENCION] ADD CONSTRAINT [PK_CO_TIPO_RETENCION] PRIMARY KEY CLUSTERED ([CO_TIP_RET_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
