CREATE TABLE [dbo].[CO_TIPO_DOCUMENTO_VENTA]
(
[CO_TIP_DOC_VEN_NUM] [int] NOT NULL IDENTITY(1, 1),
[CO_TIP_DOC_VEN_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_DOC_VEN_NUM_FIL] [int] NULL,
[CO_TIP_DOC_VEN_MOD_NUM] [bit] NOT NULL,
[CO_TIP_DOC_VEN_FOR_AFE_INV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_DOC_VEN_MOD_PRE] [bit] NOT NULL,
[CO_TIP_DOC_VEN_IMP] [nvarchar] (200) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_DOC_VEN_AGR_PRO] [bit] NOT NULL,
[CO_TIP_DOC_VEN_LIS_PRE] [int] NULL,
[CO_TIP_DOC_VEN_COD_SRI] [varchar] (5) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_DOCUMENTO_VENTA] ADD CONSTRAINT [PK_CO_TIPO_DOCUMENTO_VENTA] PRIMARY KEY CLUSTERED ([CO_TIP_DOC_VEN_NUM]) ON [PRIMARY]
GO
