CREATE TABLE [dbo].[CO_SERVICIO]
(
[CO_SER_COD] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_SER_COD] [int] NULL,
[CO_SER_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_SER_PRE] [float] NULL,
[CO_SER_POR_IVA] [int] NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ICE_COD] [int] NULL,
[CO_CUE_COD] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ESTADO] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_SERVICIO] ADD CONSTRAINT [PK_CO_SERVICIO] PRIMARY KEY CLUSTERED ([CO_SER_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_SERVICIO] ADD CONSTRAINT [FK_CO_SERVICIO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CO_SERVICIO] ADD CONSTRAINT [FK_CO_SERVICIO_CO_TABLA_ICE] FOREIGN KEY ([CO_ICE_COD]) REFERENCES [dbo].[CO_TABLA_ICE] ([CO_ICE_COD])
GO
ALTER TABLE [dbo].[CO_SERVICIO] ADD CONSTRAINT [FK_CO_SERVICIO_CO_TIPO_SERVICIO] FOREIGN KEY ([CO_TIP_SER_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_TIPO_SERVICIO] ([CO_TIP_SER_COD], [CO_EMP_RUC])
GO
