CREATE TABLE [dbo].[CO_CRUCE_SUSTENTO]
(
[CO_TIP_SUS_COD] [uniqueidentifier] NOT NULL,
[CO_TIP_COM_COM_COD] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CRUCE_SUSTENTO_RUC] [bit] NULL,
[CO_CRUCE_SUSTENTO_CI] [bit] NULL,
[CO_CRUCE_SUSTENTO_PASAPORTE] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CRUCE_SUSTENTO] ADD CONSTRAINT [PK_CO_CRUCE_SUSTENTO] PRIMARY KEY CLUSTERED ([CO_TIP_SUS_COD], [CO_TIP_COM_COM_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CRUCE_SUSTENTO] ADD CONSTRAINT [FK_CO_CRUCE_SUSTENTO_CO_TIPO_COMPROBANTE_COMPRA1] FOREIGN KEY ([CO_TIP_COM_COM_COD]) REFERENCES [dbo].[CO_TIPO_COMPROBANTE_COMPRA] ([CO_TIP_COM_COM_COD]) ON DELETE CASCADE
GO
