CREATE TABLE [dbo].[CO_DETALLE_DOCUMENTO_RESERVA]
(
[CO_DET_DOC_VEN_COD] [uniqueidentifier] NOT NULL,
[CO_DOC_VEN_ID] [uniqueidentifier] NOT NULL,
[CO_DET_DOC_VEN_ART_COD] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_DOC_VEN_ART_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_DOC_VEN_CAN] [float] NULL,
[CO_DET_DOC_VEN_PRE] [float] NULL,
[CO_DET_DOC_VEN_DES] [float] NULL,
[CO_DET_DOC_VEN_VAL_ICE] [float] NULL,
[CO_DET_DOC_VEN_IVA] [float] NULL,
[CO_DET_DOC_VEN_TOT] [float] NULL,
[CO_DET_DOC_VEN_TIP_ART] [bit] NULL,
[CO_DET_DOC_VEN_POR_ICE] [float] NULL,
[CO_DET_DOC_VEN_POR_IVA] [float] NULL,
[CO_DET_DOC_VEN_TIP_PRE] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_DOC_VEN_ART_BAR] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_DOC_VEN_ART_PRE_COS] [float] NULL,
[CO_ART_EXI_ACT] [float] NULL,
[CO_BOD_COD] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_DOCUMENTO_RESERVA] ADD CONSTRAINT [PK_DETALLE_DOCUMENTO_RESERVA] PRIMARY KEY CLUSTERED ([CO_DET_DOC_VEN_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_DOCUMENTO_RESERVA] ADD CONSTRAINT [FK_CO_DETALLE_DOCUMENTO_RESERVA_CO_DOCUMENTO_RESERVA] FOREIGN KEY ([CO_DOC_VEN_ID]) REFERENCES [dbo].[CO_DOCUMENTO_RESERVA] ([CO_DOC_VEN_ID])
GO
