CREATE TABLE [dbo].[CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES]
(
[CODIGO_DETALLE_DOCUMENTO_PAGO] [int] NOT NULL,
[CODIGO_DOCUMENTO_PAGO] [int] NULL,
[CO_DOC_COM_NUM] [int] NULL,
[VALOR_FACTURA_COMPRA] [decimal] (18, 2) NULL,
[NUMERO_FACTURA_COMPRA] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PRO_COD] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES] ADD CONSTRAINT [PK_CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES] PRIMARY KEY CLUSTERED ([CODIGO_DETALLE_DOCUMENTO_PAGO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES] ADD CONSTRAINT [FK_CO_DETALLE_DOCUMENTO_PAGO_PROVEEDORES_CO_DOCUMENTO_PAGO_PROVEEDORES] FOREIGN KEY ([CODIGO_DOCUMENTO_PAGO]) REFERENCES [dbo].[CO_DOCUMENTO_PAGO_PROVEEDORES] ([CODIGO_DOCUMENTO_PAGO])
GO
