CREATE TABLE [dbo].[CO_TARJETA_CREDITO]
(
[CO_TAR_CRE_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TAR_CRE_NOM] [nvarchar] (250) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TAR_CRE_CUE] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TARJETA_CREDITO] ADD CONSTRAINT [PK_CO_TARJETA_CREDITO] PRIMARY KEY CLUSTERED ([CO_TAR_CRE_COD]) ON [PRIMARY]
GO
