CREATE TABLE [dbo].[CO_MES_LIQUIDACION]
(
[CO_MES_LIQ_NUM] [int] NOT NULL,
[CO_ANIO_LIQ_NUM] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_COD] [int] NOT NULL,
[CO_MES_LIQ_EST] [bit] NULL,
[CO_MES_LIQ_USU_ALI] [nvarchar] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_MES_LIQ_CON_EST] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MES_LIQUIDACION] ADD CONSTRAINT [PK_CO_MES_LIQUIDACION] PRIMARY KEY CLUSTERED ([CO_MES_LIQ_NUM], [CO_ANIO_LIQ_NUM], [CO_EMP_RUC], [CO_UBI_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MES_LIQUIDACION] ADD CONSTRAINT [FK_CO_MES_LIQUIDACION_CO_UBICACION_AF] FOREIGN KEY ([CO_EMP_RUC], [CO_UBI_COD]) REFERENCES [dbo].[CO_UBICACION_AF] ([CO_EMP_RUC], [CO_UBI_COD])
GO
