CREATE TABLE [dbo].[CO_AUDITORIO_CORRECCIONES]
(
[CO_AUD_COR_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_AUD_COR_ART_COD] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_AUD_COR_SIG] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_AUD_COR_CAN] [float] NOT NULL,
[CO_AUD_COR_USU] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_AUD_COR_FEC] [datetime] NOT NULL
) ON [PRIMARY]
GO
