CREATE TABLE [dbo].[CO_MENU]
(
[CO_MENU_ID] [uniqueidentifier] NOT NULL,
[CO_MENU_PADRE_ID] [uniqueidentifier] NULL,
[NOMBRE] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DISPONIBLE] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MENU] ADD CONSTRAINT [PK_CO_MENU] PRIMARY KEY CLUSTERED ([CO_MENU_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_MENU] ADD CONSTRAINT [FK_CO_MENU_CO_MENU] FOREIGN KEY ([CO_MENU_PADRE_ID]) REFERENCES [dbo].[CO_MENU] ([CO_MENU_ID])
GO
