CREATE TABLE [dbo].[CO_TIPO_SERVICIO]
(
[CO_TIP_SER_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_SER_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_SER_CTA_VEN] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_SER_CTA_COM] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_SER_CTA_IMP] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_SER_CTA_PRO] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_SERVICIO] ADD CONSTRAINT [PK_CO_TIPO_SERVICIO] PRIMARY KEY CLUSTERED ([CO_TIP_SER_COD], [CO_EMP_RUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_SERVICIO] ADD CONSTRAINT [FK_CO_TIPO_SERVICIO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
