CREATE TABLE [dbo].[CO_COMPROBANTE]
(
[CO_COM_NUM] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_COM_COD] [int] NOT NULL,
[CO_COM_NOM_EMP] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_RUC_EMP] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_FEC] [datetime] NOT NULL,
[CO_COM_EST] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_COM_CONC] [varchar] (1500) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_COM_MAY] [bit] NULL,
[CO_COM_VAL_LET] [nvarchar] (200) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_NUM_CHE] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_COM_NUM_REF] [uniqueidentifier] NULL,
[CO_RETENCION_ID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COMPROBANTE] ADD CONSTRAINT [PK_CO_COMPROBANTE] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_TIP_COM_COD], [CO_COM_NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_COMPROBANTE] ADD CONSTRAINT [FK_CO_COMPR_TRABAJA_CO_TIPO_] FOREIGN KEY ([CO_EMP_RUC], [CO_TIP_COM_COD]) REFERENCES [dbo].[CO_TIPO_COMPROBANTE] ([CO_EMP_RUC], [CO_TIP_COM_COD])
GO
