CREATE TABLE [dbo].[CO_PARAMETRO]
(
[PARAMETRO_ID] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PARAMETRO_KEY] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PARAMETRO_VALUE] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[VALUE1] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[VALUE2] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PARAMETRO] ADD CONSTRAINT [PK_CO_PARAMETRO] PRIMARY KEY CLUSTERED ([PARAMETRO_ID]) ON [PRIMARY]
GO
