CREATE TABLE [dbo].[CO_CARGO]
(
[CO_CAR_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CAR_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CAR_SUE] [float] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CARGO] ADD CONSTRAINT [PK_CO_CARGO] PRIMARY KEY CLUSTERED ([CO_CAR_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CARGO] ADD CONSTRAINT [FK_CO_CARGO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
