CREATE TABLE [dbo].[CO_PAGO_CUOTA]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_NOT_DEB_NUM] [int] NULL,
[CO_PAG_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_PAG_VAL] [float] NULL,
[CO_PAG_FEC] [datetime] NULL,
[CO_PAG_EST] [bit] NULL,
[CO_PAG_CON] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_PAG_VAL_IMP] [float] NULL,
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_RUB_ROL_COD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PAGO_CUOTA] ADD CONSTRAINT [PK_CO_PAGO_CUOTA] PRIMARY KEY CLUSTERED ([CO_PAG_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_PAGO_CUOTA] ADD CONSTRAINT [FK_CO_PAGO_CUOTA_CO_NOTA_DEBITO] FOREIGN KEY ([CO_EMP_RUC], [CO_NOT_DEB_NUM], [PROF_COD]) REFERENCES [dbo].[CO_NOTA_DEBITO] ([CO_EMP_RUC], [CO_NOT_DEB_NUM], [PROF_COD])
GO
