CREATE TABLE [dbo].[CO_DETALLE_COBRO]
(
[CO_COM_COB_NUM] [int] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_DET_COB_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_NOT_DEB_NUM] [int] NULL,
[CO_DET_COB_TIP] [nchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_COB_CON] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_DET_COB_VAL] [float] NULL,
[CO_DET_COB_FEC] [datetime] NULL,
[CO_PAG_COD] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_COBRO] ADD CONSTRAINT [PK_CO_DETALLE_COBRO] PRIMARY KEY CLUSTERED ([CO_COM_COB_NUM], [CO_EMP_RUC], [CO_DET_COB_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_DETALLE_COBRO] ADD CONSTRAINT [FK_CO_DETALLE_COBRO_CO_COMPROBANTE_COBRO] FOREIGN KEY ([CO_COM_COB_NUM], [CO_EMP_RUC]) REFERENCES [dbo].[CO_COMPROBANTE_COBRO] ([CO_COM_COB_NUM], [CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_DETALLE_COBRO] ADD CONSTRAINT [FK_CO_DETALLE_COBRO_CO_PAGO_CUOTA] FOREIGN KEY ([CO_PAG_COD]) REFERENCES [dbo].[CO_PAGO_CUOTA] ([CO_PAG_COD])
GO
