CREATE TABLE [dbo].[CO_ACTIVO_REASIGNACION]
(
[CO_ACT_REA_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_ACT_FIJ_COD] [int] NULL,
[CO_ACT_REA_FEC] [datetime] NOT NULL,
[CO_ACT_REA_ARE] [varchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_REA_UBI_NOM] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ACT_REA_FUN_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ACTIVO_REASIGNACION] ADD CONSTRAINT [PK_CO_ACTIVO_REASIGNACION] PRIMARY KEY CLUSTERED ([CO_ACT_REA_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ACTIVO_REASIGNACION] ADD CONSTRAINT [FK_CO_ACTIVO_REASIGNACION_CO_ACTIVO_FIJO] FOREIGN KEY ([CO_ACT_FIJ_COD]) REFERENCES [dbo].[CO_ACTIVO_FIJO] ([CO_ACT_FIJ_COD])
GO
