CREATE TABLE [dbo].[CO_TIPO_RUBRO]
(
[CO_TIP_RUB_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_RUB_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_RUB_COD_CUE] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_RUBRO] ADD CONSTRAINT [PK_CO_TIPO_RUBRO] PRIMARY KEY CLUSTERED ([CO_TIP_RUB_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_RUBRO] ADD CONSTRAINT [FK_CO_TIPO_RUBRO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
