CREATE TABLE [dbo].[CO_ASIENTO]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ASI_COD] [int] NOT NULL,
[CO_TIP_COM_COD] [int] NOT NULL,
[CO_COM_NUM] [int] NOT NULL,
[CO_ASI_FEC] [datetime] NOT NULL,
[CO_ASI_DES] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ASI_DEB] [float] NOT NULL,
[CO_ASI_HAB] [float] NOT NULL,
[CO_ASI_TIP] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ASI_COD_ALI] [int] NULL,
[CO_CEN_COS_COD] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ASIENTO] ADD CONSTRAINT [PK_CO_ASIENTO] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_CUE_COD], [CO_ASI_COD], [CO_TIP_COM_COD], [CO_COM_NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ASIENTO] ADD CONSTRAINT [FK_CO_ASIENTO_CO_COMPROBANTE1] FOREIGN KEY ([CO_EMP_RUC], [CO_TIP_COM_COD], [CO_COM_NUM]) REFERENCES [dbo].[CO_COMPROBANTE] ([CO_EMP_RUC], [CO_TIP_COM_COD], [CO_COM_NUM])
GO
ALTER TABLE [dbo].[CO_ASIENTO] ADD CONSTRAINT [FK_CO_ASIENTO_CO_CUENTA] FOREIGN KEY ([CO_CUE_COD], [CO_EMP_RUC]) REFERENCES [dbo].[CO_CUENTA] ([CO_CUE_COD], [CO_EMP_RUC]) ON UPDATE CASCADE
GO
