CREATE TABLE [dbo].[CO_BANCO]
(
[CO_BAN_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_BAN_NOM] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_BAN_DEC] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_BANCO] ADD CONSTRAINT [PK_CO_BANCO] PRIMARY KEY CLUSTERED ([CO_BAN_COD]) ON [PRIMARY]
GO
