CREATE TABLE [dbo].[CO_CABECERA_ROL]
(
[PROF_COD] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ROL_CAB_FEC_PAG] [datetime] NOT NULL,
[CO_ROL_CAB_VAL_LET] [nvarchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ROL_CAB_VAL] [float] NOT NULL,
[CO_ROL_CAB_TIP] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ROL_CAB_CHE] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ROL_CAB_CUE_NUM] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ROL_CAB_MES] [int] NOT NULL,
[CO_ROL_CAB_ANO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CABECERA_ROL] ADD CONSTRAINT [PK_CO_CABECERA_ROL_1] PRIMARY KEY CLUSTERED ([PROF_COD], [CO_EMP_RUC], [CO_ROL_CAB_MES], [CO_ROL_CAB_ANO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_CABECERA_ROL] ADD CONSTRAINT [FK_CO_CABECERA_ROL_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_CABECERA_ROL] ADD CONSTRAINT [FK_CO_CABECERA_ROL_PROFESOR] FOREIGN KEY ([PROF_COD]) REFERENCES [dbo].[PROFESOR] ([PROF_COD])
GO
