CREATE TABLE [dbo].[CO_TIPO_CLIENTE]
(
[CO_TIP_CLI_COD] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_TIP_CLI_NOM] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_TIP_CLI_CUE] [nvarchar] (40) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_CLIENTE] ADD CONSTRAINT [PK_CO_TIPO_CLIENTE_1] PRIMARY KEY CLUSTERED ([CO_TIP_CLI_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TIPO_CLIENTE] ADD CONSTRAINT [FK_CO_TIPO_CLIENTE_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
