CREATE TABLE [dbo].[CO_UBICACION_AF]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_UBI_NOM] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_UBI_DIR] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_UBI_TEL] [nchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[CO_UBI_REP] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_UBI_REP_CED] [nchar] (10) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_UBICACION_AF] ADD CONSTRAINT [PK_CO_UBICACION_AF] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_UBI_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_UBICACION_AF] ADD CONSTRAINT [FK_CO_UBICA_ABARCA_CO_EMPRE] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC]) ON UPDATE CASCADE
GO
