CREATE TABLE [dbo].[CO_ASIENTO_AUX]
(
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CUE_COD] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ASI_COD] [int] NOT NULL,
[CO_ASI_AUX_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_TIP_COM_COD] [int] NOT NULL,
[CO_COM_NUM] [int] NOT NULL,
[CO_ASI_AUX_FEC] [datetime] NOT NULL,
[CO_ASI_AUX_DES] [nvarchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ASI_AUX_DEB] [float] NOT NULL,
[CO_ASI_AUX_HAB] [float] NOT NULL,
[CO_ASI_AUX_COD_REF] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ASI_AUX_CLI] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ASIENTO_AUX] ADD CONSTRAINT [PK_CO_ASIENTO_AUX] PRIMARY KEY CLUSTERED ([CO_EMP_RUC], [CO_CUE_COD], [CO_ASI_COD], [CO_ASI_AUX_COD], [CO_TIP_COM_COD], [CO_COM_NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ASIENTO_AUX] ADD CONSTRAINT [FK_CO_ASIENTO_AUX_CO_ASIENTO] FOREIGN KEY ([CO_EMP_RUC], [CO_CUE_COD], [CO_ASI_COD], [CO_TIP_COM_COD], [CO_COM_NUM]) REFERENCES [dbo].[CO_ASIENTO] ([CO_EMP_RUC], [CO_CUE_COD], [CO_ASI_COD], [CO_TIP_COM_COD], [CO_COM_NUM])
GO
