CREATE TABLE [dbo].[CO_ARTICULO]
(
[CO_ART_COD] [uniqueidentifier] NOT NULL,
[CO_EMP_RUC] [char] (13) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_CLA_FAM_ART_COD] [uniqueidentifier] NULL,
[CO_ART_NOM] [nvarchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ART_COD_FAB] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CLA_ART_MAR] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ART_COL] [nvarchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ART_EXI_MIN] [int] NULL,
[CO_ART_EXI_MAX] [int] NULL,
[CO_ART_UNI] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ART_POR_IVA] [float] NULL,
[CO_CLA_ART_TIP] [nvarchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ART_USU_ALI] [varchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[CO_ICE_COD] [int] NULL,
[CO_ART_PRE_COS] [float] NULL,
[CO_ART_PES] [float] NULL,
[CO_ART_BAR] [nvarchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CO_CLA_TIP_ART_COD] [nvarchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[DESCRIPCION] [varchar] (500) COLLATE Modern_Spanish_CI_AS NULL,
[UNIDAD_X_EMPAQUE] [int] NULL,
[PRESENTACION] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[CODIGO_BARRAS] [varbinary] (max) NULL,
[CO_ART_EST] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ARTICULO] ADD CONSTRAINT [PK_CO_ARTICULO_1] PRIMARY KEY CLUSTERED ([CO_ART_COD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_ARTICULO] ADD CONSTRAINT [FK_CO_ARTICULO_CO_EMPRESA] FOREIGN KEY ([CO_EMP_RUC]) REFERENCES [dbo].[CO_EMPRESA] ([CO_EMP_RUC])
GO
ALTER TABLE [dbo].[CO_ARTICULO] ADD CONSTRAINT [FK_CO_ARTICULO_CO_FAMILIA_ARTICULO] FOREIGN KEY ([CO_CLA_FAM_ART_COD]) REFERENCES [dbo].[CO_FAMILIA_ARTICULO] ([CO_FAM_ART_COD]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CO_ARTICULO] ADD CONSTRAINT [FK_CO_ARTICULO_CO_TABLA_ICE] FOREIGN KEY ([CO_ICE_COD]) REFERENCES [dbo].[CO_TABLA_ICE] ([CO_ICE_COD])
GO
