CREATE TABLE [dbo].[CO_TABLA_ICE]
(
[CO_ICE_COD] [int] NOT NULL IDENTITY(1, 1),
[CO_ICE_NOM] [nvarchar] (500) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CO_ICE_POR] [float] NOT NULL,
[CO_ICE_COD_PORC_SRI] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO_TABLA_ICE] ADD CONSTRAINT [PK_CO_TABLA_ICE] PRIMARY KEY CLUSTERED ([CO_ICE_COD]) ON [PRIMARY]
GO
