//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_ALMACEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_ALMACEN()
        {
            this.CO_BODEGA = new HashSet<CO_BODEGA>();
        }
    
        public System.Guid CO_ALM_COD { get; set; }
        public string CO_EMP_RUC { get; set; }
        public string CO_ALM_NOM { get; set; }
    
        public virtual CO_EMPRESA CO_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_BODEGA> CO_BODEGA { get; set; }
    }
}
