//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_ARTICULO()
        {
            this.CO_EGRESO_DETALLE = new HashSet<CO_EGRESO_DETALLE>();
            this.CO_INGRESO_DETALLE = new HashSet<CO_INGRESO_DETALLE>();
            this.CO_TABLA_PRECIO = new HashSet<CO_TABLA_PRECIO>();
            this.CO_BODEGA = new HashSet<CO_BODEGA>();
        }
    
        public System.Guid CO_ART_COD { get; set; }
        public string CO_EMP_RUC { get; set; }
        public Nullable<System.Guid> CO_CLA_FAM_ART_COD { get; set; }
        public string CO_ART_NOM { get; set; }
        public string CO_ART_COD_FAB { get; set; }
        public string CO_CLA_ART_MAR { get; set; }
        public string CO_ART_COL { get; set; }
        public Nullable<int> CO_ART_EXI_MIN { get; set; }
        public Nullable<int> CO_ART_EXI_MAX { get; set; }
        public string CO_ART_UNI { get; set; }
        public Nullable<double> CO_ART_POR_IVA { get; set; }
        public string CO_CLA_ART_TIP { get; set; }
        public string CO_ART_USU_ALI { get; set; }
        public Nullable<int> CO_ICE_COD { get; set; }
        public Nullable<double> CO_ART_PRE_COS { get; set; }
        public Nullable<double> CO_ART_PES { get; set; }
        public string CO_ART_BAR { get; set; }
        public string CO_CLA_TIP_ART_COD { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> UNIDAD_X_EMPAQUE { get; set; }
        public string PRESENTACION { get; set; }
        public byte[] CODIGO_BARRAS { get; set; }
        public string CO_ART_EST { get; set; }
    
        public virtual CO_EMPRESA CO_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_EGRESO_DETALLE> CO_EGRESO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_INGRESO_DETALLE> CO_INGRESO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_TABLA_PRECIO> CO_TABLA_PRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_BODEGA> CO_BODEGA { get; set; }
    }
}
