//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_BODEGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_BODEGA()
        {
            this.CO_ARTICULO = new HashSet<CO_ARTICULO>();
        }
    
        public System.Guid CO_BOD_COD { get; set; }
        public System.Guid CO_ALM_COD { get; set; }
        public string CO_EMP_RUC { get; set; }
        public string CO_BOD_NOM { get; set; }
        public int CO_ESTADO { get; set; }
    
        public virtual CO_ALMACEN CO_ALMACEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_ARTICULO> CO_ARTICULO { get; set; }
    }
}
