//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_DETALLE_PROFORMA
    {
        public System.Guid CO_DET_PRO_COD { get; set; }
        public System.Guid CO_PRO_COD { get; set; }
        public string CO_EMP_RUC { get; set; }
        public string CO_DET_PRO_ART_COD { get; set; }
        public string CO_DET_PRO_ART_NOM { get; set; }
        public Nullable<int> CO_DET_PRO_CAN { get; set; }
        public Nullable<double> CO_DET_PRO_PRE { get; set; }
        public Nullable<double> CO_DET_PRO_DES { get; set; }
        public Nullable<double> CO_DET_PRO_TOT { get; set; }
        public Nullable<bool> CO_DET_PRO_TIP_ART { get; set; }
        public Nullable<double> CO_DET_PRO_IVA { get; set; }
        public Nullable<int> CO_DET_PRO_CAN_EXI { get; set; }
        public string CO_DET_PRO_TIP_PRE { get; set; }
        public string CO_DET_PRO_ART_BAR { get; set; }
        public Nullable<double> CANTIDAD_PROCESADA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<double> CANTIDAD_FACTURAR { get; set; }
    }
}
