//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_DOCUMENTO_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_DOCUMENTO_COMPRA()
        {
            this.CO_DETALLE_DOCUMENTO_COMPRA = new HashSet<CO_DETALLE_DOCUMENTO_COMPRA>();
        }
    
        public System.Guid CO_DOC_COM_ID { get; set; }
        public string CO_EMP_RUC { get; set; }
        public System.Guid AlmacenID { get; set; }
        public System.Guid CO_PRO_COD { get; set; }
        public System.Guid CO_CLA_SUS_COD { get; set; }
        public string CO_CLA_COM_COM_COD { get; set; }
        public int CO_DOC_COM_NUM { get; set; }
        public Nullable<System.DateTime> CO_DOC_COM_FEC_CAD { get; set; }
        public string CO_DOC_COM_ETA { get; set; }
        public string CO_DOC_COM_PUN_EMI { get; set; }
        public string CO_DOC_COM_SEC { get; set; }
        public string CO_DOC_COM_DET { get; set; }
        public string CO_DOC_COM_NUM_AUT { get; set; }
        public Nullable<System.DateTime> CO_DOC_COM_FEC_EMI { get; set; }
        public Nullable<System.DateTime> CO_DOC_COM_FEC_REG { get; set; }
        public string CO_DOC_COM_EST { get; set; }
        public Nullable<double> CO_DOC_COM_TOT_NET { get; set; }
        public Nullable<double> CO_DOC_COM_POR_DES { get; set; }
        public Nullable<double> CO_DOC_COM_DES { get; set; }
        public Nullable<int> CO_DOC_COM_POR_IVA { get; set; }
        public Nullable<double> CO_DOC_COM_IVA { get; set; }
        public Nullable<double> CO_DOC_COM_TOT_PAG { get; set; }
        public string CO_DOC_COM_FOR_PAG { get; set; }
        public Nullable<bool> CO_DOC_COM_EFE { get; set; }
        public Nullable<double> CO_DOC_COM_EFE_VAL { get; set; }
        public Nullable<bool> CO_DOC_COM_CHE { get; set; }
        public Nullable<double> CO_DOC_COM_CHE_VAL { get; set; }
        public string CO_DOC_COM_CHE_NUM { get; set; }
        public string CO_DOC_COM_CHE_NUM_CUE { get; set; }
        public Nullable<int> CO_DOC_COM_NUM_PAG { get; set; }
        public string CO_DOC_COM_USU_ALI { get; set; }
        public string CO_DOC_COM_TOT_LET { get; set; }
        public Nullable<double> CO_DOC_COM_VAL_ICE { get; set; }
        public Nullable<double> CO_DOC_COM_VAL_IVA0 { get; set; }
        public Nullable<bool> CO_DOC_COM_CORRE_INV { get; set; }
        public Nullable<System.DateTime> CO_DOC_COM_FEC_PAGO { get; set; }
        public Nullable<int> CO_DOC_COM_DIAS_PLA { get; set; }
        public Nullable<bool> CO_DOC_ESTADO_DE_PAGO { get; set; }
        public Nullable<bool> CO_DOC_COM_TAR { get; set; }
        public Nullable<double> CO_DOC_COM_TAR_VAL { get; set; }
        public string CO_DOC_COM_TAR_NUM { get; set; }
        public string CO_DOC_COM_TAR_VAU { get; set; }
        public Nullable<System.DateTime> CO_DOC_COM_CHE_FEC { get; set; }
        public Nullable<bool> CO_DOC_COM_TRA { get; set; }
        public Nullable<double> CO_DOC_COM_TRA_VAL { get; set; }
        public string CO_DOC_COM_TRA_DOC_NUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DETALLE_DOCUMENTO_COMPRA> CO_DETALLE_DOCUMENTO_COMPRA { get; set; }
    }
}
