//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_DETALLE_DOCUMENTO_VENTA
    {
        public System.Guid CO_DET_DOC_VEN_COD { get; set; }
        public System.Guid CO_DOC_VEN_ID { get; set; }
        public string CO_DET_DOC_VEN_ART_COD { get; set; }
        public string CO_DET_DOC_VEN_ART_NOM { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_CAN { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_PRE { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_DES { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_VAL_ICE { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_IVA { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_TOT { get; set; }
        public Nullable<bool> CO_DET_DOC_VEN_TIP_ART { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_POR_ICE { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_POR_IVA { get; set; }
        public string CO_DET_DOC_VEN_TIP_PRE { get; set; }
        public string CO_DET_DOC_VEN_ART_BAR { get; set; }
        public Nullable<double> CO_DET_DOC_VEN_ART_PRE_COS { get; set; }
        public Nullable<double> CO_ART_EXI_ACT { get; set; }
        public Nullable<int> CO_BOD_COD { get; set; }
        public Nullable<double> CO_CANTIDAD_EMPAQUE { get; set; }
    
        public virtual CO_DOCUMENTO_VENTA CO_DOCUMENTO_VENTA { get; set; }
    }
}
