//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_DETALLE_GUIA_REMISION
    {
        public System.Guid CO_DET_GUI_REM_COD { get; set; }
        public System.Guid CO_DOC_VEN_GUI_COD { get; set; }
        public Nullable<int> CO_DET_GUI_REM_CAN { get; set; }
        public string CO_DET_GUI_REM_DES { get; set; }
    
        public virtual CO_GUIA_REMISION CO_GUIA_REMISION { get; set; }
    }
}
