//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_EMPRESA()
        {
            this.CO_ALMACEN = new HashSet<CO_ALMACEN>();
            this.CO_ARTICULO = new HashSet<CO_ARTICULO>();
            this.CO_GRUPO = new HashSet<CO_GRUPO>();
            this.CO_GUIA_REMISION = new HashSet<CO_GUIA_REMISION>();
            this.CO_LISTA_PRECIO = new HashSet<CO_LISTA_PRECIO>();
        }
    
        public string CO_EMP_RUC { get; set; }
        public string CO_EMP_NOM { get; set; }
        public string CO_EMP_NOM_REP { get; set; }
        public string CO_EMP_NOM_CON { get; set; }
        public string CO_EMP_REG_CON { get; set; }
        public string CO_EMP_DIR { get; set; }
        public System.Guid CO_CLA_CIU { get; set; }
        public string CO_EMP_TEL { get; set; }
        public string CO_EMP_FAX { get; set; }
        public string CO_CLA_TIP_IDE { get; set; }
        public string CO_EMP_REP_IDE { get; set; }
        public string CO_EMP_RUC_CON { get; set; }
        public string CO_EMP_MAI { get; set; }
        public string CO_EMP_RAZ_SOC { get; set; }
        public Nullable<bool> CO_CONTRIBUYENTE_ESPECIAL { get; set; }
        public string CO_CONTRIBUYENTE_NUMERO { get; set; }
        public Nullable<bool> CO_OBLIGADO_CONTABILIDAD { get; set; }
        public byte[] CO_EMPRESA_LOGO { get; set; }
        public string CO_EMPRESA_LOGO_FILE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_ALMACEN> CO_ALMACEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_ARTICULO> CO_ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_GRUPO> CO_GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_GUIA_REMISION> CO_GUIA_REMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_LISTA_PRECIO> CO_LISTA_PRECIO { get; set; }
    }
}
