//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_EGRESO_DETALLE
    {
        public System.Guid DetalleEgresoID { get; set; }
        public System.Guid EgresoID { get; set; }
        public System.Guid CO_ART_COD { get; set; }
        public string CO_ART_NOM { get; set; }
        public double Costo { get; set; }
        public double Cantidad { get; set; }
        public double Total { get; set; }
    
        public virtual CO_ARTICULO CO_ARTICULO { get; set; }
        public virtual CO_EGRESO CO_EGRESO { get; set; }
    }
}
