//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_GRUPO
    {
        public int CO_GRU_COD { get; set; }
        public string CO_GRU_NOM { get; set; }
        public string CO_EMP_RUC { get; set; }
        public bool CO_EMP_ESCONTADOR { get; set; }
    
        public virtual CO_EMPRESA CO_EMPRESA { get; set; }
    }
}
