//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_INGRESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_INGRESO()
        {
            this.CO_INGRESO_DETALLE = new HashSet<CO_INGRESO_DETALLE>();
        }
    
        public System.Guid IngresoID { get; set; }
        public string CO_EMP_RUC { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Numero { get; set; }
        public int BodegaOrigenID { get; set; }
        public int BodegaDestinoID { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Transferencia { get; set; }
        public Nullable<int> AlmacenID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_INGRESO_DETALLE> CO_INGRESO_DETALLE { get; set; }
    }
}
