//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_LISTA_PRECIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_LISTA_PRECIO()
        {
            this.CO_TABLA_PRECIO = new HashSet<CO_TABLA_PRECIO>();
        }
    
        public System.Guid ListaDePrecioID { get; set; }
        public string CO_EMP_RUC { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Rentabilidad { get; set; }
    
        public virtual CO_EMPRESA CO_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_TABLA_PRECIO> CO_TABLA_PRECIO { get; set; }
    }
}
