//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_MENU()
        {
            this.CO_MENU1 = new HashSet<CO_MENU>();
        }
    
        public System.Guid CO_MENU_ID { get; set; }
        public Nullable<System.Guid> CO_MENU_PADRE_ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<bool> DISPONIBLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_MENU> CO_MENU1 { get; set; }
        public virtual CO_MENU CO_MENU2 { get; set; }
    }
}
