//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNet.Core.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterNet_WebEntities : DbContext
    {
        public MasterNet_WebEntities()
            : base("name=MasterNet_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CO_ALMACEN> CO_ALMACEN { get; set; }
        public virtual DbSet<CO_ARTICULO> CO_ARTICULO { get; set; }
        public virtual DbSet<CO_BODEGA> CO_BODEGA { get; set; }
        public virtual DbSet<CO_DETALLE_DOCUMENTO_COMPRA> CO_DETALLE_DOCUMENTO_COMPRA { get; set; }
        public virtual DbSet<CO_DETALLE_DOCUMENTO_VENTA> CO_DETALLE_DOCUMENTO_VENTA { get; set; }
        public virtual DbSet<CO_DETALLE_GUIA_REMISION> CO_DETALLE_GUIA_REMISION { get; set; }
        public virtual DbSet<CO_DETALLE_PROFORMA> CO_DETALLE_PROFORMA { get; set; }
        public virtual DbSet<CO_DETALLE_RETENCION> CO_DETALLE_RETENCION { get; set; }
        public virtual DbSet<CO_DOCUMENTO_COMPRA> CO_DOCUMENTO_COMPRA { get; set; }
        public virtual DbSet<CO_DOCUMENTO_VENTA> CO_DOCUMENTO_VENTA { get; set; }
        public virtual DbSet<CO_EGRESO> CO_EGRESO { get; set; }
        public virtual DbSet<CO_EGRESO_DETALLE> CO_EGRESO_DETALLE { get; set; }
        public virtual DbSet<CO_EMPRESA> CO_EMPRESA { get; set; }
        public virtual DbSet<CO_GRUPO> CO_GRUPO { get; set; }
        public virtual DbSet<CO_GUIA_REMISION> CO_GUIA_REMISION { get; set; }
        public virtual DbSet<CO_INGRESO> CO_INGRESO { get; set; }
        public virtual DbSet<CO_INGRESO_DETALLE> CO_INGRESO_DETALLE { get; set; }
        public virtual DbSet<CO_MENU> CO_MENU { get; set; }
        public virtual DbSet<CO_LISTA_PRECIO> CO_LISTA_PRECIO { get; set; }
        public virtual DbSet<CO_TABLA_PRECIO> CO_TABLA_PRECIO { get; set; }
    }
}
